Makefile

Signed-off-by: edgex <jpwhite_mn@yahoo.com>

Fixes #10, added docker creation for core services

---

core/clients/coredataclients/coredata-clients.go

Signed-off-by: Drasko DRASKOVIC <drasko.draskovic@gmail.com>

Fix package import

---

README.md

Signed-off-by: Drasko DRASKOVIC <drasko.draskovic@gmail.com>

Add information about ZMQ

---

Makefile
core/clients/metadataclients/metadata-clients.go
core/data/clients/database-client.go
core/data/messaging/eventpublisher.go
core/domain/models/event.go

Also fixing the issues reported.

Adding go vet to test makefile target

---

.gitignore

glide command will create a `glide.lock` we should filter it from the project source code, enviroment :  
OS: Mac os x 10.13.2
IDE: GoLand
package tool : homebrew and so on...

add a new item into .gitignore file to filter glide.lock

---

support/scheduler-client/Attribution.txt
support/scheduler-client/README.md
support/scheduler-client/client.go
support/scheduler-client/client_test.go

[issue-43] implement a support-scheduler-client

---

Makefile
bin/edgex-docker-launch.sh
bin/edgex-launch.sh
cmd/support-logging/main.go
docker/Dockerfile.support-logging

Adding:
- docker
- Makefile microservice compilation
- Added to launch scripts

support-logging improvements

---

core/command/device.go

update the PUT GET block to use the correct path
Signed-off-by: bullapse <spencerbull2554@gmail.com>

fix URL command GET PUT path

---

core/clients/commandclients/command-clients.go
core/clients/coredataclients/coredata-clients.go

Helpful in facilitating increased unit test coverage.

Created interface for remaining core service clients

---

bin/edgex-launch.sh
support/logging/mongo.go

Signed-off-by: chencho <smunoz@cavium.com>

Duplicated support-logging

---

docker/Dockerfile.core-data
docker/Dockerfile.export-distro

Update mirror for alpine 3.7 image

---

support/scheduler-client/README.md
support/scheduler-client/client.go
support/scheduler-client/client_test.go

based on #86 , please see the change declaratives.  cc @drasko please review this PR, thanks!

#86 [support][schedule-client] improve and refactor scheduler client

---

core/metadata/mongoOps.go

Seems to be my PR day :)
Hope this one is the good one, related with #122 and #123 

Fixed error when updating an addressable in core-metadata

---

cmd/core-data/res/configuration-docker.toml

Signed-off-by: Edward Scott <ed@iotechsys.com>

Fix typo in Zeromq URL for core-metadata docker toml

---

export/client/registration.go
export/distro/client.go
export/registration.go
export/registration_test.go

Modify registration.Validate to also return an error with the reason when a
registration is considered invalid.
Also added tests to Validate

Also return an error to registration.Validate

---

core/metadata/rest_addressable.go

https://github.com/edgexfoundry/edgex-go/issues/147

Name can't be empty when adding addressable (Issue #147)

---

cmd/support-logging/res/configuration-docker.toml

Configuration-docker.toml has wrong Consul host name

---

Makefile

Adding latest tag to the docker images. Adding 'docker-' to the name of the images. Formatting docker build commands for legibility
Signed-off-by: Jesus Valenzuela <chuyval@gmail.com>

Modifying makefile

---

cmd/export-client/main.go
export/client/clients/database-client.go
export/client/clients/memory-database.go
export/client/clients/mongo-client.go
export/client/init.go
export/client/init_test.go

Add CloseSession method to export client db interface

---

core/clients/types/err-not-found.go
core/data/validate_test.go

#212 Add license info for some test files in Core service

---

cmd/core-command/Attribution.txt
cmd/core-data/Attribution.txt
cmd/core-metadata/Attribution.txt

#204 Core services do not have an attribution file

---

support/consul-client/consul.go
support/domain/domain.go
support/logging-client/logger.go
support/logging-client/mock-logger.go
support/notifications-client/client.go
support/notifications-client/client_config.go
support/scheduler-client/client_config.go

#216 Drop attribution lines from support service files

---

export/client/clients/database-client.go
export/client/clients/memory-database.go
export/client/clients/mongo-client.go

#218 Drop attribution lines from export service files

---

core/clients/coredataclients/valuedescriptor_test.go

#183 Refactor core data clients value descriptor test from integration testing to unit testing

---

core/metadata/rest_device.go

CheckForDevices() was returning 404 for found device

---

core/command/raml/core-command.raml

Updated RAML per issue #211

---

core/clients/metadataclients/device_test.go

#235 Change device_test from integration test to unit test

---

core/clients/metadata/device.go
core/clients/metadata/device_service.go
core/clients/metadata/device_service_test.go
core/clients/metadata/device_test.go
core/data/init.go

Consul service lookup for metadata device_service

---

core/data/clients/influx-client.go
core/data/clients/mongo-client.go

Improved performance when scrub old event in core-data

---

core/clients/command/command.go
core/clients/metadata/addressable.go
core/clients/metadata/device_profile.go

Reinstate Deleted Clients -- Command, Device Profile, Addressable

---

README.md

#280 Integrate go report card service to give a check and add a badges for the project(part 1)

---

cmd/support-logging/res/configuration-docker.toml

Verifying that this will fix the Consul hostname resolution errors within Docker.

Changing Consul hostname to match current image

---

cmd/support-logging/res/configuration-docker.toml

Reverts edgexfoundry/edgex-go#288

Revert "Changing Consul hostname to match current image"

---

core/data/clients/MongoEvent.go
core/data/clients/influx-client.go
core/data/clients/memory-database_test.go
core/domain/models/event.go

#283 Remove Unused Schedule Property from domain/models/event.go

---

export/distro/iotcore.go
export/distro/registrations.go

This pull request resolves #101.
Signed-off-by: Aleksandar Novakovic <anovakovic01@gmail.com>

EF-101 - Add Google IoT Core export connector

---

export/client/Attribution.txt
export/distro/Attribution.txt

cc @drasko and @janko-isidorovic

#120 Export services (client and distro) do not have an attribution file

---

cmd/core-command/res/configuration-docker.toml
cmd/core-command/res/configuration.toml

#300 Incorrect ReadLimit Key in Core-Command Configuration TOML

---

docker/Dockerfile.support-logging

Add bash to support-logging container image

---

snap/snapcraft.yaml

Bump snap version to 0.6.0 for california

---

core/command/init.go

Fixed initialization in command client

---

core/clients/command/command.go
core/clients/coredata/event.go
core/clients/coredata/reading.go
core/clients/coredata/value_descriptor.go
core/clients/metadata/addressable.go
core/clients/metadata/command.go
core/clients/metadata/device.go
core/clients/metadata/device_profile.go
core/clients/metadata/device_service.go
core/clients/types/endpoint.go
core/command/restDevice.go

Added methods in device profile client

---

snap/bin/start-config-seed.sh
snap/bin/start-edgex.sh
snap/snapcraft.yaml

This PR updates the snap to build and run the core-config-seed-go.

[snap] Switch to core-config-seed-go

---

snap/bin/start-config-seed.sh
snap/bin/start-edgex.sh
snap/snapcraft.yaml

This PR updates the snap to build and run the core-config-seed-go.

Snap cali update config seed

---

cmd/support-logging/main.go

Updated support-logging to include log of port it started on.

---

core/clients/types/endpoint.go

#384 
Bringing over fix from PR #383 into California for inclusion in 0.6.1 release.

Busy wait fix in monitor. Sleep instead.

---

snap/bin/start-config-seed.sh
snap/bin/start-consul.sh
snap/bin/start-edgex.sh
snap/bin/stop-edgex.sh

This commit cleans up warnings produced by shellcheck when run against the snap start & stop scripts.

Snap script cleanup

---

export/client/raml/export-client.raml

corrected export-client API definition for in-existent registration

---

internal/support/logging/server.go

Set correct content-type for JSON on GET methods

---

internal/support/logging/models/log_entry.go
internal/support/logging/mongo.go
pkg/models/log_entry.go

Addressed the following issues:
#372 
#373 

Fix: logLevel field name in JSON, criteria in Mongo

---

cmd/core-metadata/main.go
internal/core/metadata/const.go
internal/core/metadata/init.go
internal/core/metadata/rest_addressable.go
internal/core/metadata/rest_command.go
internal/core/metadata/rest_device.go
internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/rest_devicereport.go
internal/core/metadata/rest_deviceservice.go
internal/core/metadata/rest_provisionwatcher.go
internal/core/metadata/rest_scheduleevent.go

#416 
Submitting as a pattern proposal for solving the above issue. I have an open question in my mind as to whether or not some of this code can make its way into a common internal/pkg implementation, but that refactoring will come later as I see the effect on subsequent services.

Core-metadata -- Handle bootstrap dependency timing

---

export/distro/influxdb.go

Add err to log messages and fix a typo in influxdb part of export distro
to make debugging easier for influxdb connection issues
Signed-off-by: David Chang <david@iotechsys.com>

Add err to log messages and fix a typo

---

cmd/core-command/main.go
internal/core/command/const.go
internal/core/command/device.go
internal/core/command/init.go
internal/core/command/restDevice.go

Core-command -- Handle bootstrap dependency timing

---

api/raml/support-logging.raml
internal/support/logging/file.go
internal/support/logging/mongo.go
internal/support/logging/persistence_test.go
internal/support/logging/server.go
internal/support/logging/server_test.go
internal/support/logging/types.go

#410 
This is my first strike at the problem. I removed a lot of error messages that don't seem possible since there doesn't appear to be error handling for those execution paths, would we rather add error handling for those?

Attempting to make RAML and code for support-logging agree

---

cmd/support-logging/main.go
internal/support/logging/const.go
internal/support/logging/file.go
internal/support/logging/init.go
internal/support/logging/mongo.go
internal/support/logging/server.go
internal/support/logging/server_test.go
internal/support/logging/types.go

Support-logging: Handle bootstrap dependency timing

---

api/raml/core-command.raml
internal/core/command/device.go

Updated core-command so that 503->500

---

api/raml/core-data.raml
internal/core/data/event.go
internal/core/data/reading.go
internal/core/data/valuedescriptor.go

HTTP 503 -> 500 in core-data service

---

Makefile

Use long sha to reduce chance of collision

---

docs/api/Ch-APICoreData.rst

Update link to core-data.raml file to point to the correct location

Update link to core-data.raml file

---

cmd/export-distro/main.go
cmd/export-distro/res/configuration-docker.toml
cmd/export-distro/res/configuration.toml
core/clients/coredata/event.go
core/clients/coredata/event_test.go
export/distro/const.go
export/distro/http.go
export/distro/init.go
export/distro/iotcore.go
export/distro/mqtt.go
export/distro/registrations.go
export/distro/registrations_test.go
export/distro/types.go
export/distro/xmpp.go

This is porting https://github.com/edgexfoundry/edgex-go/pull/421 from master into california.
Done some local testing, marking pushed works fine if enabled.

If enabled, mark pushed time after an event is sent in export distro (port from master)

---

api/raml/core-command.raml
internal/core/command/device.go
pkg/clients/metadata/command.go
pkg/clients/metadata/device.go
pkg/clients/types/errors.go

Issue #412: HTTP 403 -> 400 in core-command

Update error handling in core-command

---

api/raml/core-metadata.raml
internal/core/metadata/rest_addressable.go
internal/core/metadata/rest_command.go
internal/core/metadata/rest_device.go
internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/rest_devicereport.go
internal/core/metadata/rest_deviceservice.go
internal/core/metadata/rest_provisionwatcher.go
internal/core/metadata/rest_scheduleevent.go

Update return codes in metadata

---

cmd/support-notifications/main.go
internal/core/data/errors/types.go
internal/core/data/event.go
internal/core/data/reading.go
internal/core/data/validate.go
internal/core/data/validate_test.go
internal/pkg/db/test/db_metadata.go
internal/support/logging/types.go
internal/support/notifications/const.go
internal/support/notifications/init.go
internal/support/notifications/notification.go
internal/support/notifications/subscription.go
internal/support/notifications/transmission.go
pkg/clients/coredata/event_test.go
pkg/clients/coredata/reading_test.go
pkg/clients/coredata/value_descriptor_test.go
pkg/clients/metadata/command_test.go
pkg/clients/metadata/device_service_test.go
pkg/clients/metadata/device_test.go
pkg/clients/types/errors.go
pkg/models/severity_test.go
pkg/models/subscription.go

Fixed all gofmt, ineffassign and misspell issues detected by the [report card](https://goreportcard.com/report/github.com/edgexfoundry/edgex-go).
Related with #501

Fixed gofmt, ineffassign and misspell issues

---

Makefile
bin/edgex-launch.sh
cmd/sys-mgmt-agent/Attribution.txt
cmd/sys-mgmt-agent/main.go
cmd/sys-mgmt-agent/res/configuration-docker.toml
cmd/sys-mgmt-agent/res/configuration.toml
cmd/sys-mgmt-agent/toml_test.go
docker/Dockerfile.sys-mgmt-agent
internal/system/agent/const.go
internal/system/agent/init.go
internal/system/agent/router.go
internal/system/agent/services.go
internal/system/agent/services_test.go
internal/system/agent/utils.go

First of all, this PR is **tagged and associated with** [Issue #497](https://github.com/edgexfoundry/edgex-go/issues/497)
`This PR essentially has two major parts:`
1. Bringing the new System Management Agent functionality into master
2. The refactoring done to split business logic from routing / INFRA concerns. 
- Details regarding the former can be [found here](https://wiki.edgexfoundry.org/display/FA/Phase+1%2C+System+Management+Delhi+Release)
- And details regarding the latter can be [found here](https://github.com/edgexfoundry/edgex-go/issues/457).

Sys management agent

---

snap/bin/stop-edgex.sh
snap/snapcraft.yaml

There's likely some sort of race condition going on here, but in the meantime this should fix the bug.

snap/bin/stop-edgex.sh: remove the kong_env file too

---

export/client/registration.go

This PR fix #512.
Maybe it's not the best way to fix the issue, but I don't know any best way without touching Registration structure.

Enable parameter wasn't updated in registration export-client

---

.gitignore
internal/core/metadata/rest_addressable.go
internal/core/metadata/rest_deviceprofile.go

Fix #527 
Also added a notification when a device profile is updated.

Removed some unused notify device service

---

docs/Dockerfile.build
docs/general/conf.py

Add Google Analytics to generated documentation

---

internal/core/metadata/rest_deviceservice.go
pkg/models/addressable.go
pkg/models/addressable_test.go

Do not attempt callback if no URL provided

---

pkg/clients/metadata/addressable.go

Device-sdk can update or remove addressable by client lib.
https://github.com/edgexfoundry/edgex-go/issues/566

Implement update and remove function for matadata's addressable client

---

internal/export/distro/registrations.go

Remaining changes by gofmt.
Fixes #569

Remove export distro trace.

---

internal/export/distro/encryption.go
internal/export/distro/encryption_test.go
internal/export/distro/filter.go
internal/export/distro/filter_test.go
internal/export/distro/format.go
internal/export/distro/format_test.go
internal/export/distro/httpsender.go
internal/export/distro/httpsender_test.go
internal/export/distro/influxdb.go
internal/export/distro/iotcore.go
internal/export/distro/mqtt.go
internal/export/distro/registrations.go
internal/export/distro/registrations_test.go
internal/export/distro/server.go
internal/export/distro/types.go
internal/export/distro/xmpp.go
internal/export/distro/xmpp_test.go
internal/export/distro/zeromq.go

Renamed some function to make them privates
Fixes #579

Moving export interfaces back to distro.

---

cmd/export-distro/main.go
cmd/export-distro/res/configuration-docker.toml
cmd/export-distro/res/configuration.toml
internal/export/distro/client.go
internal/export/distro/client_test.go
internal/export/distro/init.go
internal/export/distro/iotcore.go
internal/export/distro/registrations.go
internal/export/distro/zeromq.go

Retry Service Dependencies on Startup -- ExportDistro

---

snap/bin/security-start.sh
snap/bin/start-edgex.sh
snap/bin/stop-edgex.sh
snap/snapcraft.yaml

This is a forward port to master of the following PR's to cali:
* https://github.com/edgexfoundry/edgex-go/pull/582 (resolves #478 for master)
* https://github.com/edgexfoundry/edgex-go/pull/516 (resolves #515 for master)
* https://github.com/edgexfoundry/edgex-go/pull/510 (resolves #509 for master)
* https://github.com/edgexfoundry/edgex-go/pull/508 (resolves #496 for master)

Forward-porting california snap changes to master

---

snap/snapcraft.yaml

snapcraft.yaml: include COPYRIGHT for openresty

---

internal/export/distro/init.go
internal/export/distro/server.go
internal/export/distro/server_test.go
pkg/clients/constants.go
pkg/clients/coredata/event_test.go
pkg/clients/metadata/addressable.go
pkg/clients/metadata/addressable_test.go
pkg/clients/metadata/schedule_test.go
pkg/clients/metadata/scheduleevent_test.go
pkg/clients/scheduler/client.go
pkg/clients/scheduler/client_test.go

Fix #602 and #322 
Added get addressable by ID in addressable client with related tests.
Also unified URL usage in several files.

Added get addressable by ID in addressable client

---

internal/core/metadata/init.go

core-metadata should use LoadFromFileV2

---

internal/core/command/init.go
internal/core/data/init.go
internal/core/metadata/init.go
internal/export/client/init.go

#618 
Propogated fix to other V2 services thus far

BUG: Consul values overridden at service start

---

cmd/config-seed/res/properties/edgex-support-rulesengine/application.properties
cmd/config-seed/res/properties/edgex-support-rulesengine;docker/application.properties

add property for Java rules engine to address issue #575

---

cmd/export-distro/res/configuration.toml
cmd/export-distro/res/docker/configuration.toml
internal/export/distro/config.go
internal/export/distro/registrations.go
internal/export/distro/zeromq.go

Fixes #575 - export distro sends event data to rules engine via JSON

---

README.md

Per #607, this updates non-Docker install instructions.  
Signed-off-by: Andre Srinivasan <andre@redislabs.com>

Updated non-Docker install instructions and MacOS clarifications

---

.gitignore
Makefile
bin/edgex-docker-launch.sh
bin/edgex-launch.sh
cmd/support-scheduler/Attribution.txt
cmd/support-scheduler/main.go
cmd/support-scheduler/res/configuration.toml
cmd/support-scheduler/res/docker/configuration.toml
cmd/support-scheduler/toml_test.go
docker/Dockerfile.config-seed
docker/Dockerfile.support-scheduler
internal/constants.go
internal/pkg/config/types.go
internal/seed/config/populate.go
internal/support/scheduler/README.md
internal/support/scheduler/config.go
internal/support/scheduler/const.go
internal/support/scheduler/init.go
internal/support/scheduler/router.go
internal/support/scheduler/schedule.go
internal/support/scheduler/schedulecontext.go
internal/support/scheduler/schedulercontext_test.go

#57 Support Scheduler in Go
Initial Go version port of the java Scheduler Service.
Features:  Scheduler, SchedulerContext, and Router
Includes:  V2 Configuration changes as per the current EdgeX design pattern
Bootstrap, Retry design pattern
TODO: 
- Further enhancement of the Support Scheduler to include additional tests
- Examine the use of the core-metadata as an option for our Event.Addressable needs

Support Scheduler Go initial service creation

---

snap/Dockerfile.amd64.build
snap/build.sh
snap/entrypoint.sh

Fixes #646 
Accompanying ci-management PR that adds the relevant docker cleanup macro: https://github.com/edgexfoundry/ci-management/pull/226

Fix snap release jobs

---

snap/hooks/install
snap/local/bin/start-edgex.sh

Use new go support-notifications in the snap

---

snap/Dockerfile.amd64.build
snap/build.sh
snap/entrypoint.sh

Backport of #652 for california.

Fix for snap release jobs in california

---

api/raml/core-command.raml
cmd/sys-mgmt-agent/res/configuration.toml
internal/core/command/const.go
internal/core/command/rest.go
internal/system/agent/const.go
internal/system/agent/init.go
internal/system/agent/mocks/MSMClient.go
internal/system/agent/msmClient.go
internal/system/agent/msm_client.go
internal/system/agent/response_structs.go
internal/system/agent/router.go
internal/system/agent/services.go
internal/system/agent/services_test.go
internal/system/agent/utils.go
pkg/clients/command/mgmt.go
pkg/clients/notifications/client.go

- This PR contains the work done under the purview of: [Issue Number 654](https://github.com/edgexfoundry/edgex-go/issues/654)
- The essence of this work is to have the EdgeX Micro Service Management (MSM) API be applied to the CoreCommand service.
- Details can be found here: [Issue Number 654](https://github.com/edgexfoundry/edgex-go/issues/654)

Spread the (MSM) API to the CoreCommand service.

---

api/raml/support-scheduler.raml
api/raml/system-agent.raml
docs/Dockerfile.build
docs/api/Ch-APIReference.rst
docs/api/Ch-APISupportingServicesLogging.rst
docs/api/Ch-APISupportingServicesScheduling.rst
docs/api/Ch-APISystemManagement.rst
docs/build.sh
docs/entrypoint.sh
docs/support/logging/Ch-Logging.rst
docs/support/notifications/Ch-AlertsNotifications.rst

initial RAML and documentation for Scheduler and System Management Agent

---

snap/entrypoint.sh

snap/entrypoint.sh: include manifest in the snap

---

snap/Dockerfile.armhf.build
snap/README.md
snap/snapcraft.yaml

Fixes some of issue #670 (notably doesn't add documentation about how to use the snap with services, as that isn't done yet).

Update snap documentation

---

internal/core/command/rest.go
internal/core/data/router.go
internal/core/data/utils.go
internal/core/metadata/router.go
internal/export/client/server.go
internal/export/distro/server.go
internal/support/logging/server.go
internal/support/notifications/router.go
internal/support/scheduler/router.go

- Update (i.e. implement in) the router of each EdgeX service the metrics handler.
- Work per this Issue is taking place on the following branch: [Construction site](https://github.com/akramtexas/edgex-go/tree/update_router_each_in_services).

Add the metrics handler to the router of each EdgeX service.

---

docs/api/Ch-APIExportServicesClientRegistration.rst

Docs -- Update ExportClient RAML link

---

internal/core/data/valuedescriptor.go

Now value descriptor description can be updated

---

snap/snapcraft.yaml

snapcraft.yaml: update device-virtual and rulesengine to delhi branch

---

internal/core/metadata/rest_scheduleevent.go

LogLevel = WARN when ScheduleEvent associates not found

---

internal/core/metadata/rest_scheduleevent.go

LogLevel = WARN when ScheduleEvent associates not found (Master)

---

internal/seed/config/populate.go

#715 
Sample output
`WARN: 2018/11/07 15:42:44 open /Users/tconn/go/src/github.com/edgexfoundry/edgex-go/cmd/support-scheduler/res/configuration.toml: no such file or directory`

config-seed startup log WARN if expected directory missing

---

docker/Dockerfile.config-seed
docker/Dockerfile.core-command
docker/Dockerfile.core-data
docker/Dockerfile.core-metadata
docker/Dockerfile.export-client
docker/Dockerfile.export-distro
docker/Dockerfile.support-logging
docker/Dockerfile.support-notifications
docker/Dockerfile.support-scheduler
docker/Dockerfile.sys-mgmt-agent

#764 
If interested, I have attached container size comparisons between Delhi and this proposed change on the issue referenced above.
_Please do not approve until I've had a chance to review with @JPWKU_ 

Updated dockerfile base image to golang:1.11.2-alpine3.7

---

api/raml/system-agent.raml
internal/system/agent/executor/docker.go
internal/system/agent/executor/os.go
internal/system/agent/interfaces/ExecutorClient.go
internal/system/agent/router.go
internal/system/agent/services.go
pkg/models/sma_operation.go

#782 
- Added custom unmarshaling from JSON to assign default values for nullable properties
- Removed the params property altogether since it wasn't used anywhere. It was just increased surface area wherein bugs can be found.

SMA Addressed panic for missing params property

---

api/raml/system-agent.raml
internal/system/agent/executor/docker.go
internal/system/agent/executor/os.go
internal/system/agent/interfaces/ExecutorClient.go
internal/system/agent/router.go
internal/system/agent/services.go
pkg/models/sma_operation.go

- This PR addresses (**on the master branch**) the following issue: [Issue #782](https://github.com/edgexfoundry/edgex-go/issues/782), which was (separately) addressed (_on the delhi branch_) via [PR #783](https://github.com/edgexfoundry/edgex-go/pull/783).
- For further details (rather than repeating them here), please refer to [PR #782](https://github.com/edgexfoundry/edgex-go/pull/782) 👍

Address SMA panic for missing params property.

---

snap/entrypoint.sh

snap/entrypoint.sh: enable silent reports, push metadata

---

bin/edgex-docker-launch.sh

Update make run_docker to use 0.7.0 Delhi images

---

docs/export/distro/Ch-Distribution.rst
docs/general/Ch-Intro.rst
docs/getting-started/Ch-GettingStartedDevelopers.rst
docs/getting-started/Ch-GettingStartedGoDevelopers.rst
docs/getting-started/Ch-GettingStartedHybrid.rst
docs/getting-started/Ch-GettingStartedJavaDevelopers.rst
docs/getting-started/Ch-GettingStartedUsers.rst
docs/support/notifications/Ch-AlertsNotifications.rst

Signed-off-by: Jim White <james_white2@dell.com>

updating docs - getting started guides, some service documents

---

bin/edgex-docker-launch.sh

Re: #663.
I found having a mix of Docker based microservices and local microservices useful while developing.

Issue 663 - Docker Launch Overrides

---

README.md
internal/core/command/README.md
internal/core/data/README.md
internal/core/metadata/README.md
internal/export/client/README.md
internal/export/distro/README.md
internal/support/logging/README.md
internal/support/scheduler/README.md

Replace RocketChat links with new Slack links in README files

---

bin/edgex-docker-launch.sh

Re: #663 
Merge script into Delhi

Merge Issue #663 into Delhi

---

glide.yaml
internal/core/data/init.go
internal/core/metadata/init.go
internal/export/client/init.go
internal/pkg/db/db.go
internal/pkg/db/redis/README.md
internal/pkg/db/redis/client.go
internal/pkg/db/redis/client_test.go
internal/pkg/db/redis/data.go
internal/pkg/db/redis/device.go
internal/pkg/db/redis/device_profile.go
internal/pkg/db/redis/device_service.go
internal/pkg/db/redis/event.go
internal/pkg/db/redis/export.go
internal/pkg/db/redis/metadata.go
internal/pkg/db/redis/object.go
internal/pkg/db/redis/provision_watcher.go
internal/pkg/db/redis/queries.go
internal/pkg/db/redis/schedule_event.go
internal/pkg/db/redis/scripts.go
internal/pkg/db/redis/util.go

Re issue #380 
This PR includes
- the code written by @itamarhaber to integrate Redis into Core Data, Core Metadata, and Export Client.
- hooks in all the respective init.go to support the TOML based configs
- tested with as much of the data from the blackbox testing as possible
- tested with virtual device
- remaining tests were performed with data generated by the Go tests

Issue 380 Initial Redis Integration

---

internal/core/data/event.go

FIX: event ids blank when exported

---

cmd/support-scheduler/res/docker/configuration.toml

Cherry-picked #875, but for Delhi

Fixed invalid path in default schedule event (Delhi)

---

cmd/support-scheduler/res/docker/configuration.toml

Fixed invalid path in default schedule event

---

cmd/core-data/main.go
glide.yaml
internal/core/command/init.go
internal/core/data/init.go
internal/export/client/init.go
internal/export/client/server_test.go
internal/export/distro/init.go
internal/support/logging/criteria.go
internal/support/logging/criteria_test.go
internal/support/logging/models/log_entry.go
internal/support/logging/persistence_test.go
internal/support/logging/types.go
internal/support/scheduler/init.go
pkg/clients/logging/logger.go
pkg/clients/logging/mock-logger.go
pkg/models/log_entry.go

Issue #739.
Current logging statements are compatible. The logging client implementation requires minor rework.
Support-logging was left as-is since it's a siloed service.

Update logging to use GoKit key/value logger.

---

internal/system/agent/init.go
internal/system/agent/services.go

Use a map of general clients initialized in a loop instead of discrete variables.

---

internal/export/client/init.go
internal/pkg/startup/endpoint.go

#622 
Duplicate of PR #898 but for `master` branch.

FIX: Client monitor update in milliseconds, not seconds (master)

---

docs/getting-started/Ch-GettingStartedUsers.rst

Update Getting Started - Users to specify 0.7.1 as the latest release

---

internal/core/metadata/interfaces/db.go
internal/core/metadata/rest_command.go
internal/core/metadata/rest_deviceprofile.go
internal/pkg/db/memory/client.go
internal/pkg/db/memory/metadata.go
internal/pkg/db/mongo/metadata.go
internal/pkg/db/mongo/models/action.go
internal/pkg/db/mongo/models/command.go
internal/pkg/db/mongo/models/get.go
internal/pkg/db/mongo/models/put.go
internal/pkg/db/mongo/models/response.go
internal/pkg/db/test/db_metadata.go
pkg/models/command.go
pkg/models/commandresponse.go
pkg/models/get.go
pkg/models/put.go
pkg/models/response.go

Issue 882 - core-metadata Command: Eliminate Mongo Types from Models

---

internal/system/agent/executor/snap.go
internal/system/agent/init.go
snap/hooks/install
snap/snapcraft.yaml

This PR is essentially a duplicate of #750 and #744 but for master (and thus Edinburgh) instead of Delhi.

Add SMA to snap + enable stopping services in snap using SMA (for master)

---

internal/core/metadata/rest_deviceprofile.go

#842
Check for empty yaml file at /deviceprofile/uploadfile of
core metadata api

#842 Check for empty yaml file at /deviceprofile/uploadfile

---

internal/core/metadata/rest_device.go
internal/core/metadata/rest_deviceservice.go
internal/pkg/db/mongo/device.go
internal/pkg/db/mongo/device_service.go
internal/pkg/db/mongo/schedule_event.go

Corrects issues with addressable changes to eliminate Mongo types from models preventing core-metadata.devicereport and core-metadata.devicereport_err_4xx blackbox tests from running successfully.
Dependent upon #954 

Issue 881 - corrects issues with addressable changes

---

internal/core/metadata/interfaces/db.go
internal/core/metadata/interfaces/mocks/DBClient.go
internal/core/metadata/rest_device.go
internal/core/metadata/rest_devicereport.go
internal/core/metadata/rest_scheduleevent.go
internal/pkg/db/memory/metadata.go
internal/pkg/db/mongo/metadata.go
internal/pkg/db/mongo/models/devicereport.go
internal/pkg/db/test/db_metadata.go
pkg/models/devicereport.go

Modified GetAllDeviceReports signature.
Modified GetDeviceReportByDeviceName signature.
Modified GetDeviceReportByName signature.
Modified GetDeviceReportById signature.
Modified GetDeviceReportsByScheduleEventName signature.
Eliminated Mongo types from DeviceReport model.
#879

Issue 879 - core-metadata DeviceReports: Eliminate Mongo Types from Models

---

glide.yaml

Updated Gorilla MUX to v1.6.2

---

internal/core/metadata/interfaces/db.go
internal/core/metadata/interfaces/mocks/DBClient.go
internal/core/metadata/rest_command.go
internal/core/metadata/rest_deviceprofile.go
internal/pkg/db/mongo/metadata.go
internal/pkg/db/test/db_metadata.go

* Removed redundant assignments.
* Converted GetCommandById().
* Converted GetCommandByName().
* Converted GetAllCommands().
Issue #956

Issue 956 - core-metadata Command: update query methods

---

internal/core/data/init.go
internal/core/data/interfaces/db.go
internal/core/metadata/init.go
internal/core/metadata/interfaces/db.go
internal/export/client/init.go
internal/export/db.go
internal/pkg/db/mongo/client.go
internal/pkg/db/mongo/client_test.go
internal/pkg/db/mongo/data.go
internal/pkg/db/mongo/export.go
internal/pkg/db/mongo/notifications.go
internal/pkg/db/test/db_data.go
internal/pkg/db/test/db_export.go
internal/pkg/db/test/db_metadata.go
internal/support/notifications/init.go
internal/support/notifications/interfaces/db.go

#976 
Planning to address issues raised in #977 in separate PR.

Removed receiver pointers from MongoClient

---

pkg/clients/logging/logger.go

Added service name to logging output

---

LICENSE

Revised copyright line in LICENSE file

---

internal/constants.go
internal/core/command/init.go
internal/core/data/init.go
internal/core/metadata/init.go
internal/export/client/init.go
internal/export/distro/init.go
internal/seed/config/populate.go
internal/support/logging/init.go
internal/support/notifications/init.go
internal/support/scheduler/init.go

Updated config stem.

---

cmd/core-data/res/configuration.toml
cmd/core-data/res/docker/configuration.toml
internal/constants.go
internal/core/data/config.go
internal/core/data/device.go
internal/core/data/event.go
internal/core/data/event_test.go
internal/core/data/init.go
internal/core/data/reading.go
internal/core/data/router.go

Updated core data to use writable config.

---

internal/pkg/db/mongo/data.go
internal/pkg/db/mongo/models/event.go
internal/pkg/db/mongo/models/reading.go

Separated responsibilities -- updated Mongo model to represent data as it exists in Mongo (including DBRefs) and conversion (ToContract/FromContract) to be responsible for transform to/from DBRefs.
#998

Issue 998 - Refactor core-data events

---

cmd/support-scheduler/res/configuration.toml
cmd/support-scheduler/res/docker/configuration.toml
internal/support/scheduler/config.go
internal/support/scheduler/init.go

Updated support-scheduler to use writable config.

---

cmd/export-distro/res/configuration.toml
cmd/export-distro/res/docker/configuration.toml
internal/export/distro/config.go
internal/export/distro/init.go
internal/export/distro/registrations.go

Updated export-distro to use writable config

---

cmd/support-notifications/res/configuration.toml
cmd/support-notifications/res/docker/configuration.toml
internal/support/notifications/config.go
internal/support/notifications/init.go
internal/support/notifications/sending_service.go

Updated support-notifications to use writable config.

---

cmd/support-logging/res/configuration.toml
cmd/support-logging/res/docker/configuration.toml
internal/support/logging/config.go
internal/support/logging/init.go

Updated support-logging to use writable config.

---

pkg/clients/logging/logger.go

#1025 Fixes a race condition in pkg/clients/logging/logger.go

#1025 Synchronize access to EdgeXLogger.levelLoggers map

---

internal/export/distro/registrations.go

Events should not be exported to disabled clients

---

cmd/config-seed/main.go
cmd/core-command/main.go
cmd/core-data/main.go
cmd/core-metadata/main.go
cmd/export-client/main.go
cmd/export-distro/main.go
cmd/support-logging/main.go
cmd/support-notifications/main.go
cmd/support-scheduler/main.go
cmd/sys-mgmt-agent/main.go

Updated return codes in all mains to call exit instead of return.

---

glide.yaml

Fix Influx DB Dependency in Delhi Branch

---

README.md

Updated readme to make Docker instructions more clear.

---

docs/support/logging/Ch-Logging.rst

#1082 
Also refined some content around the existing configuration settings for support-logging service.

Added docs content for logging keys

---

snap/snapcraft.yaml

Upgrade go to 1.11.2, vault to 1.0.2

---

internal/pkg/db/mongo/models/deviceprofile.go
pkg/models/propertyvalue.go
pkg/models/propertyvalue_test.go

Removed field word, lsb, and signed from PropertyValue

---

snap/hooks/configure
snap/hooks/install
snap/snapcraft.yaml

Duplicate of #894 but for master (Edinburgh)
Closes #958

Add new device services for master

---

cmd/config-seed/Dockerfile
cmd/core-command/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/export-client/Dockerfile
cmd/export-distro/Dockerfile
cmd/support-logging/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile

Copying Attribution.txt files into Docker images

---

.gitignore
Makefile
cmd/sys-mgmt-agent/Dockerfile
cmd/sys-mgmt-agent/main.go
cmd/sys-mgmt-agent/res/configuration.toml
cmd/sys-mgmt-agent/res/docker/configuration.toml
cmd/sys-mgmt-executor/main.go
internal/system/agent/execution_engine.go
internal/system/agent/init.go

- The work done in this PR is per [Issue #1118](https://github.com/edgexfoundry/edgex-go/issues/1118).
Signed-off-by: Akram Ahmad <sftwr2020@gmail.com>

Add the SMA Docker executor code to edgex-go.

---

README.md

Revised README for Go 1.11.x

---

go.mod
internal/core/data/device_test.go
internal/pkg/db/mongo/models/device.go
internal/pkg/db/test/db_metadata.go

#1171 
For history on why this was added, please refer to https://github.com/edgexfoundry/device-sdk-go/pull/199

Persist Device With New ProtocolProperties Type

---

go.mod
internal/core/data/router.go

Added 501 return codes for CBOR data to Event router

---

internal/core/data/router.go

Added missing error case to ValueDescriptor router

---

internal/system/agent/router.go
internal/system/agent/services.go

Addressed SMA operation error handling issues

---

internal/pkg/startup/bootstrap_test.go

Fixed race condition in bootstrap test.

---

internal/pkg/telemetry/telemetry.go
internal/pkg/telemetry/telemetry_test.go

Fixed race condition in telemetry test.

---

go.mod
internal/pkg/db/mongo/models/deviceprofile.go

Added MediaType to Mongo PropertyValue type

---

docs/configuration/Ch-Configuration.rst

Revised Configuration documentation

---

cmd/sys-mgmt-agent/Dockerfile

Pinned to specific docker-compose version in SMA

---

cmd/core-command/main.go
cmd/core-data/main.go
cmd/core-metadata/main.go
cmd/export-client/main.go
cmd/export-distro/main.go
cmd/support-logging/main.go
cmd/support-notifications/main.go
cmd/support-scheduler/main.go
cmd/sys-mgmt-agent/main.go
internal/core/command/init.go
internal/core/data/init.go
internal/core/metadata/init.go
internal/export/client/init.go
internal/export/distro/init.go
internal/support/logging/init.go
internal/support/notifications/init.go
internal/support/scheduler/init.go
internal/system/agent/init.go

Added OS agnostic interrupts.

---

internal/support/scheduler/interval.go

Fixed issue while trying to remove an Interval still in use

---

go.mod
internal/core/command/init.go
internal/core/data/init.go
internal/core/metadata/init.go
internal/export/client/init.go
internal/export/distro/init.go
internal/pkg/startup/endpoint.go
internal/seed/config/init.go
internal/seed/config/populate.go
internal/support/logging/init.go
internal/support/notifications/init.go
internal/support/scheduler/init.go
internal/system/agent/init.go

The PR addresses issue #1206 
Update for import and namespace changes.

Updates for latest go-mod-registry

---

internal/pkg/db/mongo/data.go
internal/pkg/db/test/db_data.go

Issue #1175 
To test, run the Mongo driver tests.

Fixed sort order for Readings in Mongo driver.

---

snap/snapcraft.yaml

snapcraft.yaml: remove configuration-driver.toml file for

---

docs/api/Ch-APICoreCommand.rst

Corrected doc link to core-command RAML

---

go.mod
internal/core/metadata/rest_command.go
internal/core/metadata/rest_deviceprofile.go
internal/pkg/db/mongo/metadata.go
internal/pkg/db/mongo/models/deviceprofile.go
internal/pkg/db/redis/device_profile.go
internal/pkg/db/redis/metadata.go
internal/pkg/db/redis/provision_watcher.go
internal/pkg/db/test/db_metadata.go

Integrate DeviceProfile Resources / Commands Name Change

---

internal/pkg/correlation/middleware.go

Updated correlation ID logging to be at the TRACE level.

---

internal/pkg/db/db.go
internal/pkg/db/redis/README.md
internal/pkg/db/redis/client_test.go
internal/pkg/db/redis/export.go
internal/pkg/db/redis/metadata.go
internal/pkg/db/redis/notifications.go
internal/pkg/db/redis/queries.go
internal/pkg/db/redis/scheduler.go
internal/pkg/db/redis/util.go
internal/pkg/db/test/db_metadata.go
internal/pkg/db/test/db_notifications.go
internal/support/notifications/init.go

#862 
IOTech deserves all the kudos. I just merged.
Signed-off-by: Andre Srinivasan <andre@redislabs.com>

PR for Issue 862 - Add Redis Support for Notification Service

---

internal/support/notifications/sending_service.go

Support-Notifications - add the lack of ID at the persistTransmission func

---

api/raml/core-command.raml
go.mod
internal/core/command/rest.go
internal/core/command/restDevice.go
internal/pkg/db/mongo/models/interval.go
internal/pkg/db/redis/models/interval.go
internal/pkg/db/redis/scheduler.go
internal/support/scheduler/interval.go
internal/support/scheduler/interval_test.go
internal/support/scheduler/loader.go

#1244.
Requires changes from https://github.com/edgexfoundry/go-mod-core-contracts/pull/73

Updated PUT endpoint for devices in core command.

---

Makefile
cmd/config-seed/Dockerfile
snap/snapcraft.yaml

Removed obsolete "prepare" target from Makefile

---

api/raml/core-command.raml
internal/core/command/const.go
internal/core/command/device.go
internal/core/command/rest.go
internal/core/command/restDevice.go

/device/name/{name}/command/{commandname}
Issue: https://github.com/edgexfoundry/edgex-go/issues/1223

Add GET and PUT core-command endpoints by Device and Command Names:

---

go.mod

#1292 
Consumption of new core-contracts to pick up this bug fix.

Bug Fix -- Reading Value Mis-Assigned During Unmarshal

---

docs/getting-started/Ch-GettingStartedGoDevelopers.rst

Signed-off-by: Malini Bhandaru <mbhandaru@vmware.com>

format fix

---

internal/pkg/db/mongo/models/device.go
internal/pkg/db/redis/device.go

Issue: https://github.com/edgexfoundry/edgex-go/issues/1271

Add ProfileName to Device Persistence Models

---

internal/pkg/db/mongo/models/device.go

remove unused device.addressable prop from Mongo

---

api/raml/support-notifications.raml
go.mod

- Also updated go.mod to integrate recent contract changes
#1317

Update Transmission Status Enum in Notifications RAML

---

go.mod
internal/pkg/db/mongo/data.go
internal/pkg/db/redis/data.go

Updated redis and mongo providers to fill in Device ID from event

---

internal/core/command/restDevice.go

fix update of command.OperatingStatus

---

api/raml/core-command.raml
api/raml/core-metadata.raml
internal/core/command/device.go
internal/core/command/rest.go
internal/core/command/restDevice.go
internal/core/metadata/rest_command.go
internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/router.go
internal/pkg/db/test/db_metadata.go

The raml files also updated
Issue: https://github.com/edgexfoundry/edgex-go/issues/1346

Remove Legacy Endpoints from Core-Command and Core-Metadata

---

cmd/sys-mgmt-executor/main.go

* Remove newlines at start and end of usage message
* Remove unnecessary variables when running docker commands
* Remove duplicated logging messages and instead wrap errors and return
* Return error as second return value when checking status of container
after an operation
* Fix error where start operation result wasn't being checked because
fallthrough wasn't being used
* Get status of docker container directly using json formatted docker
inspect command and decoding the output
Fixes #1129 
To test, I used the docker-compose file from developer-scripts for delhi: https://github.com/edgexfoundry/developer-scripts/blob/master/compose-files/docker-compose-delhi-0.7.1.yml.
The following things should be tested:
- `docker-compose -f docker-compose-delhi-0.7.1.yml up -d`
- `sys-mgmt-executor …

cmd/sys-mgmt-executor/main.go: use json output, misc cleanups

---

api/raml/support-notifications.raml
internal/pkg/db/mongo/notifications.go
internal/pkg/db/redis/notifications.go
internal/support/notifications/interfaces/db.go
internal/support/notifications/rest_subscription.go
internal/support/notifications/router.go

Updated notifications subscription APIs

---

api/raml/support-notifications.raml
internal/pkg/db/mongo/notifications.go
internal/pkg/db/redis/README.md
internal/pkg/db/redis/notifications.go
internal/support/notifications/interfaces/db.go
internal/support/notifications/rest_transmission.go
internal/support/notifications/router.go

Fix #1335 
Add API for querying limited transmissions with specified slug and created date range

Add API for querying transmissions by slug

---

cmd/sys-mgmt-agent/Dockerfile

Fix [#1371](https://github.com/edgexfoundry/edgex-go/issues/1371)
- Fix three minor issues (with SMA docker container).

Fix three minor issues (with SMA docker container).

---

Makefile
README.md
bin/edgex-docker-launch.sh
internal/pkg/db/redis/CONFIGURATION.md

For issue #1263 
Documentation cleanup and tweak to Makefile to take advantage of new Redis/Mongo switch when using Docker.

PR for Issue 1263: Update Redis configuration information

---

docs/getting-started/Ch-GettingStartedSDK-C.rst
docs/getting-started/configuration.toml
docs/getting-started/random-generator-device.yaml

This accounts for changes in version names and numbers, device profiles, device locations (protocol properties), device service scheduling (automatic events) and the 'template' example supplied in the SDK.
Addresses #1198

Update C SDK documentation for Edinburgh

---

cmd/core-data/res/configuration.toml
internal/core/data/init.go

Updated configuration toml and keys used to obtain database secrets

Minor tweaks to work with SecrectClient updates

---

go.mod
internal/core/data/init.go
internal/core/metadata/config.go
internal/core/metadata/init.go
internal/export/client/config.go
internal/export/client/init.go
internal/support/logging/config.go
internal/support/logging/init.go
internal/support/notifications/config.go
internal/support/notifications/init.go
internal/support/scheduler/config.go
internal/support/scheduler/init.go

Also incorporated changes from recent API changes and feedback from Trevor.

Restructured code to use retry logic in all services.

---

snap/hooks/install
snap/local/runtime-helpers/bin/kong-daemon.sh
snap/snapcraft.yaml

Backport of #1398 to Edinburgh

snap/many: update kong to 1.0.3 (edinburgh)

---

internal/support/notifications/rest_notification.go

Remove unnecessary encoding on error path

---

internal/support/notifications/rest_notification.go
internal/support/notifications/rest_subscription.go
internal/support/notifications/rest_transmission.go

Remove unnecessary switch cases in REST API handlers

---

cmd/core-command/res/docker/configuration.toml
cmd/core-metadata/res/docker/configuration.toml
cmd/export-distro/res/docker/configuration.toml
cmd/support-notifications/res/docker/configuration.toml
cmd/support-scheduler/res/docker/configuration.toml
cmd/sys-mgmt-agent/res/docker/configuration.toml

Fixes #1415 for Edinburgh.
This PR is for Edinburgh as #1416 was for master.

Updated Docker configuration to log to support-logging.

---

internal/support/notifications/cleanup.go

Refactored cleanup handler in notifications

---

.gitignore

Fix #1454
Signed-off-by: Mike Johanson <michael.johanson@intel.com>

add *.dll and debug to .gitignore

---

internal/system/agent/const.go
internal/system/agent/router.go

Use constants in System Agent API

---

internal/core/command/init.go
internal/core/data/init.go
internal/core/metadata/init.go
internal/export/client/init.go
internal/export/distro/init.go
internal/pkg/config/environment.go
internal/pkg/config/environment_test.go
internal/seed/config/environment.go
internal/seed/config/environment_test.go
internal/seed/config/init.go
internal/seed/config/populate.go
internal/support/logging/init.go
internal/support/notifications/init.go
internal/support/scheduler/init.go
internal/system/agent/init.go

Override Configuration Using Environment Variables

---

internal/support/scheduler/interval.go
internal/support/scheduler/router.go
internal/support/scheduler/schedulecontext.go

Updated scheduler to properly use runOnce intervals for Edinburgh.

---

internal/support/scheduler/interval.go
internal/support/scheduler/router.go
internal/support/scheduler/schedulecontext.go

Updated scheduler to properly use runOnce intervals.

---

internal/support/notifications/sending_service.go

Issue Numbers: #1382 #1469
Assume that the mail server doesn't support Auth
Signed-off-by: Amit Kumar Chaudhary <a.rudder.free@gmail.com>

If password is empty, do not assume Plain Auth

---

go.mod

Verified locally. Will update after changes are made to https://github.com/edgexfoundry/go-mod-registry/pull/19

Updated Consul to 1.5.2.

---

go.mod

Fix (SendMessage race condition) Update go-mod-messaging to latest with SendMessage race condition fix.

---

docs/api/Ch-APISupportingServicesScheduling.rst
internal/support/scheduler/schedule.go

Fix #1497
Fixed issue with Scheduler POST and PUT HTTP Verbs not supplying JSON body when creating interval actions.
Fixed scheduler rst documentation around the use of interval and interval actions.

Edinburgh - PUT or POST interval action not work

---

internal/support/scheduler/schedule.go

Fix #1497
Added code to enable parameters to be included as body for POST and PUT
httpMethods.
Updated Scheduler.RST documentation to reflect the changes in types from Schedule, ScheduleEvent to Interval, IntervalAction. 

PUT or POST interval action not work

---

Makefile

add docker- to sys-mgmt-agent-go target

---

bin/edgex-docker-launch.sh

Correct paths to Edinburgh 1.0.1 for make run_docker

---

README.md

Update the Docker compose link in README

---

internal/support/notifications/operators/notification/db.go
internal/support/notifications/operators/notification/get.go
internal/support/notifications/operators/notification/get_test.go
internal/support/notifications/operators/notification/mocks/NotificationLoader.go
internal/support/notifications/rest_notification.go
internal/support/notifications/rest_notification_test.go
internal/support/notifications/router.go

Apply Operator Pattern - Notification Get By Sender

---

internal/support/notifications/operators/notification/db.go
internal/support/notifications/operators/notification/get.go
internal/support/notifications/operators/notification/get_test.go
internal/support/notifications/operators/notification/mocks/NotificationLoader.go
internal/support/notifications/rest_notification.go
internal/support/notifications/rest_notification_test.go
internal/support/notifications/router.go

Apply Operator Pattern - Notification Get By StartEnd

---

internal/support/notifications/operators/notification/db.go
internal/support/notifications/operators/notification/get.go
internal/support/notifications/operators/notification/get_test.go
internal/support/notifications/operators/notification/mocks/NotificationLoader.go
internal/support/notifications/rest_notification.go
internal/support/notifications/rest_notification_test.go
internal/support/notifications/router.go

Apply Operator Pattern - Notification Get By Start

---

internal/support/notifications/operators/notification/db.go
internal/support/notifications/operators/notification/get.go
internal/support/notifications/operators/notification/get_test.go
internal/support/notifications/operators/notification/mocks/NotificationLoader.go
internal/support/notifications/rest_notification.go
internal/support/notifications/rest_notification_test.go
internal/support/notifications/router.go

Apply Operator Pattern - Notification Get By End

---

internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/rest_deviceprofile_test.go

Fix #1639 
Reused the operator and centralized logic from #1626

Added unit tests for restAddDeviceProfile

---

internal/core/metadata/operators/device_profile/value_descriptor.go
internal/core/metadata/operators/device_profile/value_descriptor_test.go
internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/rest_deviceprofile_test.go

Fix #1603
Add missing validation checks for DeviceProfile's Update and Add APIs
which allowed the system to enter an undesirable state due to orphaned
ValueDescriptors.
Add validation check for DeviceProfile non-unique name during Add before
creating the associated ValueDescriptors.
Add validation check to ensure the DeviceProfile is not in use by a
Device before performing the update.
Add necessary tests to cover the newly added logic.

Add missing validation for DeviceProfile APIs

---

cmd/config-seed/res/properties/go.mod

Fix #1680
This file was added during the transition of our repos to modules. See
issue for more details. Modules have been adopted everywhere in our
project now, so we can remove this file.

Removal of config-seed/res/properties/go.mod

---

internal/core/metadata/operators/device_service/db.go
internal/core/metadata/operators/device_service/get.go
internal/core/metadata/operators/device_service/get_test.go
internal/core/metadata/operators/device_service/mocks/DeviceServiceLoader.go
internal/core/metadata/operators/device_service/mocks/DeviceServiceUpdater.go
internal/core/metadata/operators/device_service/update_test.go
internal/core/metadata/rest_addressable_test.go
internal/core/metadata/rest_deviceservice.go
internal/core/metadata/rest_deviceservice_test.go

Added operator, unit test and REST test for GetDeviceServiceById

---

api/raml/core-command.raml
api/raml/core-data.raml
api/raml/core-metadata.raml
api/raml/export-client.raml
api/raml/support-logging.raml
api/raml/support-notifications.raml
api/raml/support-scheduler.raml
api/raml/system-agent.raml

Standardize RAML Headers

---

internal/core/metadata/operators/device_service/get.go
internal/core/metadata/operators/device_service/get_test.go
internal/core/metadata/rest_deviceservice.go
internal/core/metadata/rest_deviceservice_test.go

Added operator, unit and REST tests for DeviceServiceGetById

---

internal/support/scheduler/interval.go
internal/support/scheduler/operators/interval/db.go
internal/support/scheduler/operators/interval/delete.go
internal/support/scheduler/operators/interval/delete_test.go
internal/support/scheduler/operators/interval/mocks/IntervalDeleter.go
internal/support/scheduler/rest_interval.go
internal/support/scheduler/rest_interval_test.go
internal/support/scheduler/router.go

Apply Operator Pattern - Scrub Intervals

---

internal/support/notifications/operators/notification/db.go
internal/support/notifications/operators/notification/get.go
internal/support/notifications/operators/notification/get_test.go
internal/support/notifications/operators/notification/mocks/NotificationLoader.go
internal/support/notifications/rest_notification.go
internal/support/notifications/rest_notification_test.go
internal/support/notifications/router.go

Apply Operator Pattern - Notification Get Newest

---

cmd/core-command/main.go
cmd/core-metadata/main.go
cmd/export-client/main.go
cmd/export-distro/main.go
cmd/support-notifications/main.go
cmd/support-scheduler/main.go
cmd/sys-mgmt-agent/main.go
go.mod
internal/core/command/rest.go
internal/export/client/memory_db.go
internal/export/client/router.go
internal/export/client/router_test.go
internal/export/distro/registrations.go
internal/export/distro/router.go
internal/export/distro/router_test.go

Fix #1702
These services were accidentally skipped.

Timeout bug, PR #2

---

internal/support/notifications/operators/subscription/db.go
internal/support/notifications/operators/subscription/get.go
internal/support/notifications/operators/subscription/get_test.go
internal/support/notifications/operators/subscription/mocks/SubscriptionLoader.go
internal/support/notifications/rest_notification_test.go
internal/support/notifications/rest_subscription.go
internal/support/notifications/rest_subscription_test.go
internal/support/notifications/router.go

Apply Operator Pattern - SubscriptionsByCategories

---

.gitignore
cmd/security-secretstore-setup/main.go
internal/security/secretstore/certs.go
internal/security/secretstore/certs_test.go
internal/security/secretstore/constants.go
internal/security/secretstore/init.go
internal/security/secretstore/requester.go
internal/security/secretstore/testdata/test-resp-init.json

closes #1675
Load cert pair from filesystem into vault

load kong cert pair from filesystem to vault

---

internal/pkg/db/redis/metadata.go

Change current implementations to obtain a DeviceReport by different criteria. Add a single function with all common functionality to reduce code duplication.
Closes Issue #1746 
Signed-off-by: Ivan Marquez <js.ivan.marquez@gmail.com>

Redis client refactor to reduce code duplication

---

internal/security/secretstore/certs.go

Fixes #1675  again.
When addressing code review feedback I made a couple of changes that didn't work with the semantics of the rest of the code (there was a case in certs.go:retrieve() where an error was logged and not returned--I "fixed" it to return an error.  This change causes this function to return an error and has the caller handle it appropriately.)
I also remembered why I was checking for any status code in the 2xx range in a function and changed the code to accommodate 204's.
1. Inside `cmd/security-secretstore-setup/res/configuration.toml`, edit the `[SecretStore]` section for the following fields:
```
server = "localhost"
scheme = "http"
cafilepath = "/Users/jdharms/workspace/edgex-go/cmd/security-secretstore-setup/EdgeXFoundryCA.pem"
certfilepath = …
```

Fix issues around checking for existence of cert in secretstore

---

go.mod

Add min support version go 1.12 to go.mod

---

cmd/export-distro/main.go
internal/export/distro/config.go
internal/export/distro/init.go
internal/export/distro/registrations.go

Converts export-distro to use the common bootstrap package.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/1804

Convert export-distro to use common bootstrap package

---

internal/security/secretstoreclient/vault.go

Removes delegate function from secretstoreclient processResponse utility method
Addresses post-commit feedback for #1848.
Fixes potential bug where /auth/token/tidy JSON response would not be
processed because it returns http.StatusAccepted (tidy not currently called).

Remove delegate function from secretstoreclient processResponse

---

internal/pkg/db/mongo/models/command.go

Fix: https://github.com/edgexfoundry/edgex-go/issues/1871

Fix assign command put resources

---

internal/support/scheduler/utils.go

Fixes#1845 - Address issue in the scheduler schedulerContext code.
- Was not handling old format correctly for execution in the scheduler_context
- Fixes Black Box Tests and work correctly.
- Will introduce a few more Scheduler Black Box Tests which exercise the Interval Frequency

Scheduler IntervalAction returns (413) expected 200

---

cmd/security-secrets-setup/main.go
internal/security/setup/init.go
internal/security/setup/option/cache_test.go
internal/security/setup/option/generate_test.go
internal/security/setup/option/import_test.go

Signed-off-by: Enobong Udoko <enobong.n.udoko@intel.com>

add --confdir switch to security-secrets-setup

---

cmd/support-notifications/res/configuration.toml
cmd/support-notifications/res/docker/configuration.toml

feat(configuration) : Change default for Smtp.Password to be empty

---

internal/system/executor/README.md

Create a README for System Management Executor Implementation.

---

internal/core/command/config.go
internal/core/data/config.go
internal/core/metadata/config.go
internal/export/client/config.go
internal/export/distro/config.go
internal/pkg/bootstrap/interfaces/configuration.go
internal/support/logging/config.go
internal/support/notifications/config.go
internal/support/scheduler/config.go
internal/system/agent/config/config.go

Fixes: https://github.com/edgexfoundry/edgex-go/issues/1894

Config settings from Registry no longer properly copied into Services' configuration struct

---

internal/core/data/router.go

Fixes: https://github.com/edgexfoundry/edgex-go/issues/1907

Error-handling pattern in core-data REST Handlers missing returns

---

internal/pkg/telemetry/telemetry.go
internal/pkg/telemetry/telemetry_test.go

Partial clean up (telemetry code).
https://github.com/edgexfoundry/edgex-go/issues/1811

Remove code obsoleted by common bootstrap package

---

cmd/security-secrets-setup/README.md

Add instructions to run security-secrets-setup various subcommands in stand-alone executable
Fix typo as found in issue #1815

Update security-secrets-setup README.md

---

api/raml/core-command.raml
api/raml/core-data.raml
api/raml/core-metadata.raml
api/raml/export-client.raml
api/raml/support-notifications.raml
api/raml/support-scheduler.raml

Remove BSON from Service RAML Docs

---

internal/security/secretstore/password.go

Followup from https://github.com/edgexfoundry/edgex-go/pull/1916
Merged before I could address all feedback

no issue--Address error message feedback from Ian Johnson in security-secretstore-setup

---

snap/snapcraft.yaml

version part override-pull cds to root so git rev provides the required data to set the version

Add git rev to snap version

---

go.mod
internal/core/metadata/rest_deviceprofile_test.go

Fix #1966
Corrected a couple DeviceProfile tests also

Consumed Go-Mod-Core-Contracts v0.1.31

---

README.md
SECURITY.md
cmd/security-proxy-setup/README.md
cmd/security-secrets-setup/README.md
cmd/security-secretstore-setup/README.md
cmd/security-secretstore-setup/main.go

Add multiple README files for security services and update README for EdgeX-Go to include information of security services.

update README files for security components

---

internal/pkg/bootstrap/handlers/secret/secret.go

Updated to instantiate secretstore only when EDGEX_SECURITY_SECRET_STORE
is not false.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/1986
Fixes: https://github.com/edgexfoundry/developer-scripts/issues/157

Secret Bootstrap instantiates secretstore regardless of EDGEX_SECURITY_SECRET_STORE value

---

cmd/security-secrets-setup/README.md

fix  #1994
Signed-off-by: Enobong Udoko <enobong.n.udoko@intel.com>

update description of subcommands in security-secrets-setup README

---

internal/security/proxy/requestor.go

Add the missing code for the requestor to load CA certificate on HTTP TLS transport layer setup
This PR should resolve the issue #1984 

Fix issue #1984: EdgeX Proxy Setup failed to retrieve CA certificate

---

internal/system/agent/container/config.go

Fixes: https://github.com/edgexfoundry/edgex-go/issues/2043

Correct comments in internal/system/agent/container/config.go

---

cmd/security-secrets-setup/main.go

Fix how security-secrets-setup says it succeeded when it also says it fails.

---

cmd/security-secrets-setup/main.go

Fix (on master branch, too) how security-secrets-setup misleadingly says it succeeded.

---

cmd/support-notifications/main.go
internal/support/notifications/cleanup.go
internal/support/notifications/distribution_coordinator.go
internal/support/notifications/escalating_service.go
internal/support/notifications/init.go
internal/support/notifications/normal_distribution.go
internal/support/notifications/rest_notification.go
internal/support/notifications/rest_notification_test.go
internal/support/notifications/rest_subscription.go
internal/support/notifications/rest_subscription_test.go
internal/support/notifications/rest_transmission.go
internal/support/notifications/router.go
internal/support/notifications/sending_service.go
internal/support/notifications/utils.go

Fixes: https://github.com/edgexfoundry/edgex-go/issues/2060

notifications: refactor to remove LoggingClient global variable

---

cmd/support-notifications/main.go
internal/support/notifications/cleanup.go
internal/support/notifications/distribution_coordinator.go
internal/support/notifications/escalating_service.go
internal/support/notifications/init.go
internal/support/notifications/normal_distribution.go
internal/support/notifications/rest_notification.go
internal/support/notifications/rest_notification_test.go
internal/support/notifications/rest_subscription.go
internal/support/notifications/rest_subscription_test.go
internal/support/notifications/rest_transmission.go
internal/support/notifications/router.go
internal/support/notifications/sending_service.go

Fixes: #2061 
Signed-off-by: Michael Estrin m.estrin@dell.com

notifications: refactor to remove dbClient global variable

---

cmd/support-notifications/main.go
cmd/support-notifications/toml_test.go
internal/support/notifications/config/config.go
internal/support/notifications/container/config.go
internal/support/notifications/distribution_coordinator.go
internal/support/notifications/escalating_service.go
internal/support/notifications/normal_distribution.go
internal/support/notifications/rest_notification.go
internal/support/notifications/rest_notification_test.go
internal/support/notifications/rest_subscription_test.go
internal/support/notifications/router.go
internal/support/notifications/sending_service.go
internal/support/notifications/utils.go

Fixes: #2062
Signed-off-by: Michael Estrin m.estrin@dell.com

notifications: refactor to remove Configuration global variable

---

bin/edgex-launch.sh
cmd/core-command/res/configuration.toml
cmd/core-data/res/configuration.toml
cmd/core-metadata/res/configuration.toml
cmd/export-client/res/configuration.toml
cmd/security-proxy-setup/res/configuration.toml
cmd/support-logging/res/configuration.toml
cmd/support-notifications/res/configuration.toml
cmd/support-scheduler/res/configuration.toml

Duplicate of #2052 for Geneva/master.

many/configuration.toml: set default security key values, fix proxy SNIs (master)

---

internal/core/command/device.go
internal/core/command/device_test.go
internal/core/command/init.go
internal/core/command/restDevice.go
internal/core/command/router.go

Command: refactor to remove dbClient global variable

---

internal/core/command/containers/device.go
internal/core/command/device.go
internal/core/command/device_test.go
internal/core/command/init.go
internal/core/command/restDevice.go
internal/core/command/router.go
internal/core/metadata/containers/device.go

Command: refactor to remove mdc global variable

---

internal/pkg/db/mongo/models/device.go

/pkg/db/mongo/models/device.go's ToContract() method assigned
some values to the named contract.Device in the return value.
This value was overwritten at the end of the method causing these
assignments to be discarded.
This change removes all named return values from the file and
adjusts the methods accordingly.
fixes: #2034

fix: #2034 fixes bug around named return values (fuji)

---

internal/pkg/db/mongo/models/device.go

This is a duplicate of #2083 (which targets the fuji branch)
/pkg/db/mongo/models/device.go's ToContract() method assigned
some values to the named contract.Device in the return value.
This value was overwritten at the end of the method causing these
assignments to be discarded.
This change removes all named return values from the file and
adjusts the methods accordingly.
fixes: #2034

fix: #2034 fixes bug around named return values (master)

---

SECURITY.md

to address #2105. There is no code change. Just document related changes.

Update SECURITY.md for Fuji release due to recent change of docker-compose file

---

cmd/security-proxy-setup/Dockerfile
cmd/security-secretstore-setup/Dockerfile

Forward-port of https://github.com/edgexfoundry/edgex-go/pull/2075 to master/geneva

security-{proxy,secretstore}-setup/Dockerfile: use alpine to get curl (master)

---

cmd/config-seed/Dockerfile

Fixes #2108 in master. See #2111 for discussion and verification steps.

(master) Fixed bug with using Redis for core-command in Docker.

---

internal/pkg/db/redis/data.go
internal/pkg/db/redis/event.go
internal/pkg/db/redis/queries.go

#2076 in master.
Please see #2094 for verification steps and discussion on design.
Signed-off-by: Brandon Forster brandonforster@gmail.com

(master) Delete event func for Redis misses the deletion of pushed and device collection

---

cmd/security-secretstore-setup/main.go
internal/security/proxy/init.go
internal/security/secretstore/config.go
internal/security/secretstore/init.go

Fixes: https://github.com/edgexfoundry/edgex-go/issues/1806

Convert security-secretstore-setup to use common bootstrap package

---

cmd/security-secretstore-setup/main.go
internal/security/secretstore/certs.go
internal/security/secretstore/certs_test.go
internal/security/secretstore/config/config.go
internal/security/secretstore/container/config.go
internal/security/secretstore/init.go
internal/security/secretstore/password.go
internal/security/secretstore/password_test.go
internal/security/secretstore/requester.go

Fixes: https://github.com/edgexfoundry/edgex-go/issues/2128
Dependency on (includes work from) #2129. That PR must be reviewed and merged prior to this one.

security-secretstore-setup: refactor to remove Configuration global variable

---

internal/core/metadata/init.go
internal/core/metadata/rest_addressable.go
internal/core/metadata/rest_addressable_test.go
internal/core/metadata/rest_command.go
internal/core/metadata/rest_command_test.go
internal/core/metadata/rest_device.go
internal/core/metadata/rest_device_test.go
internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/rest_deviceprofile_test.go
internal/core/metadata/rest_devicereport.go
internal/core/metadata/rest_deviceservice.go
internal/core/metadata/rest_deviceservice_test.go
internal/core/metadata/rest_provisionwatcher.go
internal/core/metadata/router.go

Refactor Metadata-related code to remove dbClient global variable.

---

snap/snapcraft.yaml

Duplicate of https://github.com/edgexfoundry/edgex-go/pull/2102 but for master.

snapcraft.yaml: add security-proxy-setup-cmd (for master)

---

cmd/core-command/res/configuration.toml
cmd/core-command/res/docker/configuration.toml
cmd/core-data/res/configuration.toml
cmd/core-data/res/docker/configuration.toml
cmd/core-metadata/res/configuration.toml
cmd/core-metadata/res/docker/configuration.toml
cmd/export-client/res/configuration.toml
cmd/export-client/res/docker/configuration.toml
cmd/support-logging/res/configuration.toml
cmd/support-logging/res/docker/configuration.toml
cmd/support-notifications/res/configuration.toml
cmd/support-notifications/res/docker/configuration.toml
cmd/support-scheduler/res/configuration.toml
cmd/support-scheduler/res/docker/configuration.toml
go.mod

Duplicate of #2098 but for master/Geneva

many/configuration.toml: use time.Duration string for RetryWaitPeriod

---

cmd/support-scheduler/main.go
internal/pkg/bootstrap/configuration/file.go
internal/pkg/bootstrap/configuration/registry.go
internal/support/logging/init.go
internal/support/scheduler/init.go
internal/support/scheduler/interval.go
internal/support/scheduler/interval_action.go
internal/support/scheduler/interval_test.go
internal/support/scheduler/loader.go
internal/support/scheduler/rest_interval.go
internal/support/scheduler/rest_interval_test.go
internal/support/scheduler/rest_intervalaction.go
internal/support/scheduler/rest_intervalaction_test.go
internal/support/scheduler/router.go
internal/support/scheduler/schedule.go
internal/support/scheduler/schedulecontext.go
internal/support/scheduler/schedulercontext_test.go
internal/support/scheduler/utils.go

Scheduler: Remove LoggingClient global variable

---

internal/core/metadata/init.go
internal/core/metadata/rest_addressable.go
internal/core/metadata/rest_addressable_test.go
internal/core/metadata/rest_command.go
internal/core/metadata/rest_command_test.go
internal/core/metadata/rest_device.go
internal/core/metadata/rest_device_test.go
internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/rest_deviceprofile_test.go
internal/core/metadata/rest_devicereport.go
internal/core/metadata/rest_deviceservice.go
internal/core/metadata/rest_deviceservice_test.go
internal/core/metadata/rest_provisionwatcher.go
internal/core/metadata/router.go

Refactor metadata to remove the httpErrorHandler global variable.

---

internal/support/scheduler/init.go
internal/support/scheduler/schedule.go

Fixes #2038.
To verify, run the unit tests and the blackbox tests.

Scheduler: Remove ticker global variable

---

internal/core/metadata/container/notifications.go
internal/core/metadata/init.go
internal/core/metadata/rest_device.go
internal/core/metadata/rest_deviceservice.go
internal/core/metadata/router.go

Refactor metadata to remove the nc (i.e. NotificationsClient) global variable.

---

cmd/support-scheduler/main.go
cmd/support-scheduler/toml_test.go
internal/support/scheduler/config/config.go
internal/support/scheduler/container/config.go
internal/support/scheduler/init.go
internal/support/scheduler/interval_test.go
internal/support/scheduler/loader.go
internal/support/scheduler/rest_interval.go
internal/support/scheduler/rest_interval_test.go
internal/support/scheduler/rest_intervalaction.go
internal/support/scheduler/rest_intervalaction_test.go
internal/support/scheduler/router.go
internal/support/scheduler/schedule.go

Fixes #2039.
To verify, run the unit and black box tests.

Scheduler: Remove Configuration global variable

---

internal/pkg/db/redis/queries.go

Changes from #2192 cherry-picked onto `master`.
Fixes #2187 in `master`.

master: Fix event deleting func with redis DB.

---

internal/support/logging/container/logger.go
internal/support/logging/init.go
internal/support/logging/router.go
internal/support/logging/router_test.go

Dependency on #2199 (PR #2201)
Fixes: #2070

support-logging: refactor to remove dbClient global variable

---

cmd/core-metadata/main.go
cmd/core-metadata/toml_test.go
internal/core/metadata/config/config.go
internal/core/metadata/container/config.go
internal/core/metadata/init.go
internal/core/metadata/operators/addressable/get.go
internal/core/metadata/rest_addressable.go
internal/core/metadata/rest_addressable_test.go
internal/core/metadata/rest_command.go
internal/core/metadata/rest_command_test.go
internal/core/metadata/rest_device.go
internal/core/metadata/rest_device_test.go
internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/rest_deviceprofile_test.go
internal/core/metadata/rest_devicereport.go
internal/core/metadata/rest_deviceservice.go
internal/core/metadata/rest_deviceservice_test.go
internal/core/metadata/rest_provisionwatcher.go
internal/core/metadata/router.go

Refactor Metadata to remove Configuration global variable.

---

cmd/support-logging/main.go
internal/support/logging/container/config.go
internal/support/logging/init.go
internal/support/logging/router.go
internal/support/logging/router_test.go

Dependency on #2070 (PR #2204)
Fixes: #2071

support-logging: refactor to remove Configuration global variable

---

internal/system/agent/executor/operation.go

Implemented concurrent calls to external executor to execute
operations. 
Fixes: https://github.com/edgexfoundry/edgex-go/issues/2009

Execute System Management Operations Asynchronously

---

snap/local/runtime-helpers/bin/kong-stop.sh
snap/snapcraft.yaml

These came out of my work on other things and aren't necessary so to make those other things more review-able, splitting these out to a separate PR.
Fixes https://github.com/edgexfoundry/edgex-go/issues/2046

snap: miscellaneous snapcraft.yaml cleanups

---

cmd/security-proxy-setup/README.md

Corrected compose link in security-proxy-setup README

---

internal/security/fileprovider/provider.go

This is a followup to a previous code review to clean up
the logic to explicitly Close() a file being written that
contains the authentication token to the secret store.
Deferred Close()s are removed and replaced with
explicit closes before leaving the function and an error-
reporting Close() at the end of each loop iteration.
Fixes #2248

Explicit Close() when security-file-token provider writes tokens

---

cmd/core-command/main.go
cmd/core-data/main.go
cmd/core-metadata/main.go
cmd/security-file-token-provider/main.go
cmd/security-proxy-setup/main.go
cmd/security-secrets-setup/main.go
cmd/security-secretstore-setup/main.go
cmd/support-logging/main.go
cmd/support-notifications/main.go
cmd/support-scheduler/main.go
cmd/sys-mgmt-agent/main.go
go.mod
internal/core/command/init.go
internal/core/command/router.go
internal/core/data/init.go
internal/core/data/router.go
internal/core/metadata/init.go
internal/core/metadata/router.go
internal/security/fileprovider/init.go
internal/security/proxy/init.go
internal/security/secrets/init.go
internal/security/secretstore/init.go
internal/support/logging/init.go
internal/support/logging/router.go
internal/support/notifications/init.go
internal/support/notifications/router.go
internal/support/scheduler/init.go
internal/support/scheduler/router.go
internal/system/agent/init.go
internal/system/agent/router.go

Fixes: https://github.com/edgexfoundry/edgex-go/issues/2263

Move LoadRestRoutes into service-specific bootstrap handler

---

go.mod
internal/core/command/main.go
internal/core/data/main.go
internal/core/metadata/main.go
internal/support/logging/main.go
internal/support/notifications/main.go
internal/support/scheduler/main.go
internal/system/agent/main.go

Fixes: https://github.com/edgexfoundry/edgex-go/issues/2301

Update to latest (v.0.0.10) go-mod-bootstrap

---

SECURITY.md

update method of creating Kong token by overwriting the entrypoint in SECURITY.md; 
fix https://github.com/edgexfoundry/edgex-go/issues/2267
Signed-off-by: Tingyu Zeng <Tingyu.Zeng@rsa.com>

Update method of creating Kong token in SECURITY.md

---

.gitignore
SECURITY.md
cmd/security-secretstore-setup/README.md

Fixes #2278 
Signed-off-by: Andre Srinivasan <andre@redislabs.com>

Cleanup Markdown

---

internal/core/metadata/rest_addressable_test.go
internal/core/metadata/rest_deviceprofile_test.go
internal/core/metadata/rest_deviceservice_test.go

Create a unit test for Update Device Service LastReported by ID.

---

go.mod
internal/core/command/main.go
internal/core/data/main.go
internal/core/metadata/main.go
internal/security/fileprovider/main.go
internal/security/proxy/main.go
internal/security/secrets/main.go
internal/security/secretstore/main.go
internal/support/logging/main.go
internal/support/notifications/main.go
internal/support/scheduler/main.go
internal/system/agent/main.go

Fixes: https://github.com/edgexfoundry/edgex-go/issues/2350
Issue Number: https://github.com/edgexfoundry/edgex-go/issues/2350

Update go-mod-bootstrap to v0.0.18

---

snap/snapcraft.yaml

Issue Number:
https://github.com/edgexfoundry/edgex-go/issues/2368
This fix restores SMA start/stop/restart operations when deployed via the snap.
Please see associated issue for testing defails.

snapcraft.yaml: fix sys-mgmt-agent executor

---

README.md
bin/edgex-docker-launch.sh
cmd/core-command/res/configuration.toml
cmd/core-command/res/docker/configuration.toml
cmd/core-data/res/configuration.toml
cmd/core-data/res/docker/configuration.toml
cmd/core-metadata/res/configuration.toml
cmd/core-metadata/res/docker/configuration.toml
cmd/support-logging/res/configuration.toml
cmd/support-logging/res/docker/configuration.toml
cmd/support-notifications/res/configuration.toml
cmd/support-notifications/res/docker/configuration.toml
cmd/support-scheduler/res/configuration.toml
cmd/support-scheduler/res/docker/configuration.toml

Fixes #2283
Tested with blackbox testing.

Make Redis default for non-secure EdgeX

---

internal/system/agent/router.go
internal/system/agent/services.go

Fixes: https://github.com/edgexfoundry/edgex-go/issues/2345
Issue Number: https://github.com/edgexfoundry/edgex-go/issues/2345

getHealth() always returns a nil error

---

api/openapi/v1/support-scheduler.yaml

Review V1 Swagger (support-scheduler) for completeness.

---

api/openapi/v1/system-agent.yaml

Review V1 Swagger for completeness (System Agent).

---

api/openapi/v1/support-logging.yaml

Review V1 Swagger (support-logging) for completeness.

---

api/openapi/v1/core-command.yaml

Review V1 Swagger (core-command) for completeness.

---

go.mod

URLClients never successfully resolve and the black box tests are broken.
Issue Number: Fixes #2399

Update core-contracts version to fix bug in URLClient

---

snap/hooks/configure
snap/hooks/install
snap/hooks/pre-refresh
snap/local/parts/drop-user/Makefile
snap/local/parts/drop-user/drop.c
snap/local/runtime-helpers/bin/gosu-snap_daemon.sh
snap/snapcraft.yaml

This PR includes a number of commits which update the snap packaging for Geneva. Some of these are bug fixes recently made to the fuji branch, some address updating configuration files for new Geneva behavior (e.g. security-secretstore-setup's new token provider for per-service vault tokens), and some are general cleanup of the snap packaging.

Snap updates geneva

---

api/openapi/v1/support-notifications.yaml

Review V1 Swagger (support-notifications) for completeness.

---

internal/core/metadata/rest_provisionwatcher.go

Issue Number: Fixes #2409
To verify, run the unit and black box tests.

Provision Watcher REST API Audit: Creation Endpoint

---

api/openapi/v1/core-data.yaml

Review V1 Swagger (Core Data) for completeness.

---

api/openapi/v1/core-command.yaml
api/openapi/v1/core-data.yaml
api/openapi/v1/core-metadata.yaml
api/openapi/v1/support-logging.yaml
api/openapi/v1/support-notifications.yaml
api/openapi/v1/support-scheduler.yaml
api/openapi/v1/system-agent.yaml

Change v1 api version to 1.2.0

---

api/openapi/v1/core-metadata.yaml

Fix #2361 
- Please note that this `PR` contains a _large_ number of updates (the Swagger `YAML` consisted of approximately 2500 lines).
- As before (and as with similar updates to other Swagger docs previously), I ran the `YAML` through a validator to ensure that it conforms to being well-formed.

Review V1 Swagger (Core Metadata) for completeness.

---

go.mod

Upgrade go-mod-boostrap to a version that adds a wait
loop when security is enabled to ensure that the
secret store token is valid before the service is started.
This is a more robust solution than init-blocking code
and ensures that both first-boot and restart scenarios
are handled equally well.
This change fixes race conditions in:
core-command,
core-data,
core-metadata,
edgex-support-scheduler,
edgex-support-notifications,
edgex-support-logging
The above-listed microservices will start and fail immediately due to inability to connect to the secret store due to an invalid or missing token. Many of these containers derive from scratch …

fix[core,security]: Update go-mod-bootstrap to fix race

---

snap/README.md

This PR simply updates the snap/README.md file to use the new snapcraft.io/docs site per issue #1971 
- [x ] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
Issue Number: #1971 
**NA**
No

snap: update doc links in README.md

---

internal/pkg/db/mongo/models/addressable.go
internal/pkg/db/mongo/models/deviceservice.go

Currently, addressables in device service could fail to update if the update request JSON only provides a name and not an ID. This has been fixed.
Issue Number: Fixes #2484
If the update request object does not have an ID, the driver now performs a lookup by name and uses the result of that to generate the contract ID instead of creating a new one.

Added lookup by name for updated objects in core data in Mongo driver

---

cmd/security-secretstore-setup/res-file-token-provider/configuration.toml

Fixes: #2498
Issue Number: #2498

security: fix non-empty token-provider Logging.File

---

go.mod

environment overrides can't be uppercase.
Issue Number: #2504 
Now environment overrides can be uppercase.

feature(environment): Allow uppercase environment overrides

---

.gitignore
Makefile
SECURITY.md
cmd/core-command/res/configuration.toml
cmd/core-data/res/configuration.toml
cmd/core-metadata/res/configuration.toml
cmd/security-file-token-provider/res/token-config.json
cmd/security-secrets-setup/README.md
cmd/security-secretstore-read/Attribution.txt
cmd/security-secretstore-read/README.md
cmd/security-secretstore-read/main.go
cmd/security-secretstore-read/res/configuration.toml
cmd/security-secretstore-setup/Dockerfile
cmd/security-secretstore-setup/README.md
cmd/security-secretstore-setup/entrypoint.sh
cmd/support-logging/res/configuration.toml
cmd/support-notifications/res/configuration.toml
cmd/support-scheduler/res/configuration.toml
internal/pkg/bootstrap/handlers/database/database.go
internal/security/secretread/config.go
internal/security/secretread/constants.go
internal/security/secretread/credentials.go
internal/security/secretread/init.go
internal/security/secretread/types.go
internal/security/secretstore/init.go

Redis can only be used without authentication
Issue Number: #2449 
Redis can be used with authentication
This is tightly coupled to 
[developer-scripts PR#248](https://github.com/edgexfoundry/developer-scripts/pull/248)
[go-mod-bootstrap PR#68](https://github.com/edgexfoundry/go-mod-bootstrap/pull/68)

Add secure redis

---

internal/core/metadata/rest_provisionwatcher.go

Fails newly added blackbox test when run in Mongo mode
Issue Number: Fixes #2484
Passes blackbox test when run in Mongo mode

#2484: Added check for bad ID on getProvisionWatcherById

---

README.md

Fixes #2528
Signed-off-by: André Srinivasan <andre@redislabs.com>
Corrects type-o in READM.md
Issue Number:
#2528 
Type-o corrected

Correct compose file reference

---

cmd/security-file-token-provider/res/token-config.json

No token generated for application-service shared DB credentials 
Issue Number:  #2530
Token now generated for application-service shared DB credentials

fix: Add generation of application-service vault token for shared DB credentials

---

go.mod

Bring in fix for this issue https://github.com/edgexfoundry/go-mod-bootstrap/issues/72
Issue Number: #2335
Overrides done get un-done during bootstrap

fix: Update to use go-mod-bootstrap to fix issue with override un-done.

---

api/openapi/v1/core-metadata.yaml

The Swagger representation of Device is not in sync with the model that is used in go-mod-core-contracts
Issue Number: #2532 
The swagger matches the Device data structure
To verify these changes copy the YAML from this PR into the Swagger editor at https://editor.swagger.io/ and verify the `POST /v1/device` request body structure matches the device structure in go-mod-core-contracts
N\A

Update V1 Metadata Device Swagger Schema

---

snap/README.md
snap/hooks/configure
snap/hooks/install
snap/local/build-helpers/bin/go-build-helper.sh
snap/local/patches/0001-Makefile-rm-golangci-lint-tool.patch
snap/local/runtime-helpers/bin/kong-launch.sh
snap/local/runtime-helpers/bin/redis-launch.sh
snap/local/runtime-helpers/bin/security-secretstore-setup-launch.sh
snap/local/runtime-helpers/bin/support-rulesengine-wrapper.sh
snap/snapcraft.yaml

This PR includes multiple changes to the snap packaging for Geneva including:
* update Consul, postgreSQL, and Vault to the latest versions used for Geneva
* enable secure postgreSQL (issue #1943)
* enable secure Redis
* disable sys-mgmt-agent by default (see issue #2486)
* include new device-virtual binary device profile
* add Kuiper support
* update release tags for non-edgex-go EdgeX services (e.g. device-virtual, support-rulesengine, ...)
* fix configure hook logic to allow the database provider to be switched between mongo and redis (needed due to the removal of core-config-seed)
* update the snap README file
**Note** - testing Kuiper just requires using 'snap set' to activate …

Snap geneva updates

---

api/openapi/v1/support-notifications.yaml

PR Checklist
Missing OpenAPI documentation for `GET Notification By ID`
Issue Number: #2540 
Add missing OpenAPI documentation for `GET Notification By ID`
Verify these changes with https://editor.swagger.io

Add missing GET Notification API

---

.github/PULL_REQUEST_TEMPLATE.md

Invoking `make test` is not a documented requirement
Issue Number: #2500 
Added checkbox for invoking `make test`

improvement: Include reference to Conventional Commits spec and invoking `make test` in requirements

---

snap/hooks/configure
snap/local/runtime-helpers/bin/support-rulesengine-wrapper.sh
snap/snapcraft.yaml

* updates app-service-config source-tag to v1.1.0
* updates device-virtual source-tag to v1.2.0
* replace app-service-config `--registry` option with `-cp http://localhost:8500 `per @lenny-intel's comment
* fixed the legacy rules-engine which was failing on startup due to a JRE problem
* update the snap **grade** to **stable** (from **devel**), which allows the snap to be published to stable channels in the Snap store

snap: final geneva release items

---

internal/security/secrets/directory/directory.go

fix: Missing fmt.Sprintf() in debug logging statement

---

internal/support/scheduler/operators/interval/delete.go
internal/support/scheduler/operators/interval/delete_test.go
internal/support/scheduler/rest_interval.go
internal/support/scheduler/rest_interval_test.go
internal/support/scheduler/router.go

Fix #2520 
Removing a scheduler interval when a interval action still using it would crash the scheduler

Fix bug for removal-of-scheduler-interval causing the scheduler to crash.

---

api/openapi/v1/core-command.yaml
api/openapi/v1/core-data.yaml
api/openapi/v1/core-metadata.yaml
api/openapi/v1/support-logging.yaml
api/openapi/v1/support-notifications.yaml
api/openapi/v1/support-scheduler.yaml
api/openapi/v1/system-agent.yaml

Update OAS API version to 1.2.1

---

snap/hooks/configure
snap/local/patches/0001-Makefile-rm-golangci-lint-tool.patch
snap/snapcraft.yaml

Issue Number: #2581 
NA
In addition to the fix for issue #2581, this commit also updates the versions of consul, kuiper, and vault to the latest maintenance releases.

snap updates for 1.2.1

---

internal/core/metadata/operators/device/update.go

- [x ] Bugfix
Issue Number: #2556 
- [x ] No

Fix bug of failed to empty device autoEvents.

---

Makefile

This [script](https://github.com/edgexfoundry/ci-management/blob/master/shell/edgexfoundry-go-docker-push.sh) is responsible for retagging docker images for edgex-go. It attempts to retag the image adding the nexus3 url. If we pre-tag with the nexus url, it causes the docker tag to become malformed. This PR removed the nexus tags causing the docker push to fail.
Broken builds can be seen here: 
https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/edgex-go/job/master/97/console
https://jenkins.edgexfoundry.org/view/EdgeX%20Foundry%20Project/job/edgexfoundry/job/edgex-go/job/master/98/console
Issue …

build: revert explicit nexus tagging due to build failures

---

Dockerfile.build
Jenkinsfile
Makefile
cmd/core-command/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/security-proxy-setup/Dockerfile
cmd/security-secrets-setup/Dockerfile
cmd/security-secretstore-setup/Dockerfile
cmd/support-logging/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile
cmd/sys-mgmt-agent/Dockerfile

The DevOps team has been working on a new Jenkins pipeline for edgex-go to bring it more inline with the other Go based EdgeX projects. This PR changes/introduces a few new things into the build pipeline.
- Update cmd/**/Dockerfile's to have a parametrized `FROM` to allow the Jenkins pipeline to create a shared cache layer to build from, thus allow for faster docker builds.
- Add new Dockerfile.build to act as the `BUILDER_BASE` other images.
- Standardize to the `/edgex-go` WORKDIR in Dockerfile's
- Add new `GOTESTFLAGS` in Makefile to allow race condition testing to be turned off during pipeline to avoid race condition failures in the alpine based golang image (fixed in Go 1.15 https://github.com/golang/go/issues/14481)
- Update `Jenkinsfile` to use the new `edgeXBuildGoParallel` global …

build: updates for new Jenkins pipeline.

---

api/openapi/v2/core-data.yaml

Issue Number:
https://github.com/edgexfoundry/edgex-go/issues/2630

doc: Update Core Data v2 API Response Examples

---

internal/security/secretstore/tokenprovider_linux_test.go

Unit test fails in apline builder
Fixes #2640
Issue Number: #2640
Fix allows system path to be searched for touch tool

fix: Fix path dependency in tokenprovider_linux_test.go

---

openapi/v2/core-data.yaml
openapi/v2/core-metadata.yaml

Fix #2626 
Issue Number: #2626 
Modify API doc to reflect the changes of PR edgexfoundry/go-mod-core-contracts#253.

doc: Modify V2 Swagger for Core-MedataData DTO and Model

---

openapi/v1/core-metadata.yaml

Add service and profile in device schema of v1 core-metadata yaml file

---

openapi/v2/core-data.yaml

Update AddEventRequest and Reading DTO models in swagger file.
Fix https://github.com/edgexfoundry/edgex-go/issues/2652
Signed-off-by: Lindsey Cheng <beckysocute@gmail.com>
Issue Number: https://github.com/edgexfoundry/edgex-go/issues/2652

doc: Update V2 API core data swagger file

---

cmd/core-command/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/support-logging/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile
cmd/sys-mgmt-agent/Dockerfile

Signed-off-by: Koppolu <venkata.subbareddy.koppolu@intel.com>
Issue Number:
https://github.com/edgexfoundry/edgex-go/issues/2643
None

refactor: update dockerfiles to appropriately use ENTRYPOINT and CMD

---

Jenkinsfile

Enable inline snap builds

---

go.mod
internal/mocks/DeviceClient.go

Tests are failing due to recent changes to Device Client in go-mod-core-contracts.
Issue Number: #2678
Device Client Mock updated for signature changes on a few functions
No

fix: Fix failing unit tests caused by changes to Device Client in go-mod-core-contracts

---

openapi/v1/core-data.yaml
openapi/v2/core-data.yaml

Swagger not updated for recently add Tags property on Event
Issue Number: #2667
V1 & V2 Swagger now updated for recently add Tags property on Event
No

feat: Add Tags property to Event in V1 & V2 swagger.

---

snap/snapcraft.yaml

Disable the app-service-config (used for kuiper integration)
version check when run from the snap, as we ensure that the
version of app-service-config included in this snap is compatible
with the core services.
- [NA] `make test` has completed successfully
This change disables the version check made by app-service-config (used for kuiper integration) when run from within the main edgexfoundry snap. Without this, when running the development release of edgex, if kuiper is enabled (e.g. 'sudo snap set …

fix(snap): disable asc version check

---

go.mod
internal/core/data/v2/application/event.go
internal/core/data/v2/application/event_test.go
internal/core/data/v2/controller/http/const_test.go
internal/core/data/v2/controller/http/event.go
internal/core/data/v2/controller/http/event_test.go
internal/core/data/v2/infrastructure/interfaces/db.go
internal/core/data/v2/infrastructure/interfaces/mocks/DBClient.go
internal/core/data/v2/router.go
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/const.go
internal/pkg/v2/infrastructure/redis/dbcommands.go
internal/pkg/v2/infrastructure/redis/event.go

Issue Number: Fix https://github.com/edgexfoundry/edgex-go/issues/2670
Implement Get Event by Id V2 API with unit test

feat(core-data): implement Get Event by Id V2 API

---

openapi/v1/core-data.yaml

Update ID to id in core-data v1 API url

---

go.mod
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/dbcommands.go
internal/pkg/v2/infrastructure/redis/event.go
internal/pkg/v2/infrastructure/redis/queries.go
internal/pkg/v2/infrastructure/redis/reading.go

Issue Number: Fix https://github.com/edgexfoundry/edgex-go/issues/2719
Fix the bugs in GetEventById V2 API:
- store Event and Reading with the collection prefix
- query Readings when getting Event

fix(data):Correct GetEventById V2 implementation

---

snap/snapcraft.yaml

Update to the latest stable version of consul.
Issue Number:
No
Blackbox tests run in non-secure mode, and no failures.

fix(snap): update consul to 1.8.4

---

internal/pkg/v2/infrastructure/redis/event.go

Add Event without checking whether the id exists.
Issue Number: Fix https://github.com/edgexfoundry/edgex-go/issues/2723
Add a check in the infrastructure layer to check whether the Event Id
exists.  If it exists, the API should return 409 conflict.

fix(data):Event post returns 409 if id exists

---

snap/snapcraft.yaml

we unnecessarily use a snapcraft passthrough feature
Issue Number:
we don't use passthrough for system-usernames, meaning that snapcraft will validate the input for us, to ensure that it is spelled correctly and has the right scope, etc.

fix (snap): mv system-usernames out of passthrough

---

internal/core/data/v2/router.go
internal/core/metadata/v2/router.go
internal/pkg/v2/controller/http/common.go
version.go

Issue Number: Fix https://github.com/edgexfoundry/edgex-go/issues/2721
Create the controller for common V2 API, including ping, metrics,
version, and config.
Add the API to the core-data and core-metadata router.

feat(v2 all):Implement common V2 API

---

internal/core/data/v2/controller/http/event.go
internal/core/metadata/v2/controller/http/deviceprofile.go

Issue Number: Fix https://github.com/edgexfoundry/edgex-go/issues/2747
Add correlation id when writing error or debug logs.

feat(V2): Add correlation id into log

---

openapi/v2/core-data.yaml
openapi/v2/core-metadata.yaml

fix(docs): Add examples to core-metadata v2 APIs

---

internal/core/data/v2/controller/http/event.go
internal/core/metadata/v2/controller/http/deviceprofile.go
internal/core/metadata/v2/controller/http/deviceservice.go

Fix https://github.com/edgexfoundry/edgex-go/issues/2769
V2 add request JSON parsing isn't handeled correctly.  Make them return
the response format meet the swagger definition.

fix(metadata): correct V2 parsing err response

---

openapi/v2/core-data.yaml

Fix https://github.com/edgexfoundry/edgex-go/issues/2727
Issue Number:
#2727 and part of #2740
1. update examples as requested
2. change delete response code from 204 to 200 and return baseResponse body
3. correct the timestamp example for ping api

docs(data): Update examples in V2 API Swagger file

---

openapi/v2/core-command.yaml
openapi/v2/core-data.yaml
openapi/v2/core-metadata.yaml
openapi/v2/support-logging.yaml
openapi/v2/support-notifications.yaml
openapi/v2/support-scheduler.yaml
openapi/v2/system-agent.yaml

Fix: https://github.com/edgexfoundry/edgex-go/issues/2740
#2740 
1. Add 400 and 500 response code to POST
2. Change config, version, ping, metrics from POST to GET
3. Add 423 response code to DELETE deviceprofile and deviceservice in core-metadata

docs(all): Update response codes in V2 Swagger files

---

internal/core/metadata/v2/application/deviceservice.go
internal/core/metadata/v2/controller/http/deviceservice.go
internal/core/metadata/v2/controller/http/deviceservice_test.go
internal/core/metadata/v2/infrastructure/interfaces/db.go
internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go
internal/core/metadata/v2/io/deviceservice.go
internal/core/metadata/v2/router.go
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/device_service.go
internal/pkg/v2/infrastructure/redis/queries.go

Fix #2783
Implement Core Metadata PATCH /deviceservice V2 API according to the API doc

feat(metadata): Implement Metadata PATCH /deviceservice V2 API

---

internal/core/data/v2/controller/http/event.go
internal/core/data/v2/io/event.go
internal/core/metadata/v2/application/device.go
internal/core/metadata/v2/controller/http/const_test.go
internal/core/metadata/v2/controller/http/device.go
internal/core/metadata/v2/controller/http/device_test.go
internal/core/metadata/v2/controller/http/deviceprofile.go
internal/core/metadata/v2/controller/http/deviceservice.go
internal/core/metadata/v2/infrastructure/interfaces/db.go
internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go
internal/core/metadata/v2/io/device.go
internal/core/metadata/v2/io/deviceprofile.go
internal/core/metadata/v2/io/deviceservice.go
internal/core/metadata/v2/router.go
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/device.go
internal/pkg/v2/infrastructure/redis/device_profile.go
internal/pkg/v2/infrastructure/redis/device_service.go

Fix #2788
Implement Core Metadata POST /device V2 API according to the API doc

feat(metadata): Implement Metadata POST /device V2 API

---

internal/core/data/v2/application/event.go
internal/core/data/v2/application/event_test.go
internal/core/data/v2/controller/http/event.go
internal/core/data/v2/controller/http/event_test.go
internal/core/data/v2/infrastructure/interfaces/db.go
internal/core/data/v2/infrastructure/interfaces/mocks/DBClient.go
internal/core/data/v2/router.go
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/device.go
internal/pkg/v2/infrastructure/redis/device_profile.go
internal/pkg/v2/infrastructure/redis/device_service.go
internal/pkg/v2/infrastructure/redis/event.go
internal/pkg/v2/infrastructure/redis/reading.go

Fix https://github.com/edgexfoundry/edgex-go/issues/2809
Implement the API defined in https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/default/get_event_count_device__deviceName_

feat(data): Impl Event Count by Device V2 API

---

internal/core/data/event.go
internal/core/data/v2/application/event.go

core-data wrote log in Info level when receiving each event.
Fix https://github.com/edgexfoundry/edgex-go/issues/2828
It would spam the logs, so the log level should be debug.

fix(data): Modify the log level of event

---

internal/core/data/v2/application/event.go
internal/core/metadata/v2/application/device.go
internal/core/metadata/v2/application/deviceprofile.go
internal/core/metadata/v2/application/deviceservice.go
internal/core/metadata/v2/controller/http/device.go
internal/core/metadata/v2/controller/http/device_test.go
internal/core/metadata/v2/controller/http/deviceprofile.go
internal/core/metadata/v2/controller/http/deviceprofile_test.go
internal/core/metadata/v2/controller/http/deviceservice.go
internal/core/metadata/v2/controller/http/deviceservice_test.go
internal/core/metadata/v2/infrastructure/interfaces/db.go
internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go
internal/core/metadata/v2/router.go
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/device.go
internal/pkg/v2/infrastructure/redis/queries.go

Fix #2812
Implement Metadata DELETE /device/id{id} and /device/name{name} V2 API according to the API doc
The DB implementation is base on the PR https://github.com/edgexfoundry/edgex-go/pull/2811

feat(metadata): Implement Metadata device deletion V2 API

---

internal/core/metadata/v2/application/device.go
internal/core/metadata/v2/controller/http/device.go
internal/core/metadata/v2/controller/http/device_test.go
internal/core/metadata/v2/infrastructure/interfaces/db.go
internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go
internal/core/metadata/v2/router.go
internal/pkg/v2/infrastructure/redis/client.go

Fix #2817
Implement Metadata device exists checking V2 API according to the API doc
- /device/check/id/{id}
- /device/check/id/{name}

feat(metadata): Implement device exists checking V2 API

---

internal/core/data/v2/application/event.go
internal/core/data/v2/application/event_test.go
internal/core/data/v2/controller/http/event.go
internal/core/data/v2/controller/http/event_test.go
internal/core/data/v2/infrastructure/interfaces/db.go
internal/core/data/v2/infrastructure/interfaces/mocks/DBClient.go
internal/core/data/v2/router.go
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/event.go

#2834 
Per https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/default/delete_event_id__id_,
implement the V2 API for DELETE /event/id/{id}

feat(data): Implement Core Data DELETE /event/id/{id} V2 API

---

internal/core/metadata/v2/application/device.go
internal/core/metadata/v2/application/deviceservice.go
internal/core/metadata/v2/controller/http/device.go
internal/core/metadata/v2/controller/http/device_test.go
internal/core/metadata/v2/controller/http/deviceservice_test.go
internal/core/metadata/v2/infrastructure/interfaces/db.go
internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go
internal/core/metadata/v2/io/device.go
internal/core/metadata/v2/router.go
internal/pkg/v2/infrastructure/redis/client.go

Fix #2820
Implement Metadata PATCH /device V2 API according to the API doc
The DB implementation is based on:
Get device by name - https://github.com/edgexfoundry/edgex-go/pull/2811
Delete device - https://github.com/edgexfoundry/edgex-go/pull/2813

feat(metadata): Implement PATCH /device V2 API

---

internal/core/metadata/v2/application/device.go
internal/core/metadata/v2/controller/http/device.go
internal/core/metadata/v2/controller/http/device_test.go
internal/core/metadata/v2/infrastructure/interfaces/db.go
internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go
internal/core/metadata/v2/router.go
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/device.go
internal/pkg/v2/infrastructure/redis/device_profile.go
internal/pkg/v2/infrastructure/redis/device_service.go
internal/pkg/v2/infrastructure/redis/event.go
internal/pkg/v2/infrastructure/redis/reading.go

Fix #2814
Implement Metadata GET /device/all V2 API according to the API doc

feat(metadata): Implement Metadata GET /device/all V2 API

---

Makefile

Some security services have wrong Docker image names
All service Docker image names match that built by the CI pipelines

fix: Build docker images with proper names

---

go.mod
internal/core/data/v2/controller/http/const_test.go
internal/core/data/v2/controller/http/event_test.go
internal/core/metadata/v2/application/deviceprofile.go
internal/core/metadata/v2/controller/http/deviceprofile.go
internal/core/metadata/v2/controller/http/deviceprofile_test.go
internal/core/metadata/v2/infrastructure/interfaces/db.go
internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go
internal/core/metadata/v2/router.go
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/device_profile.go
openapi/v2/core-data.yaml
openapi/v2/core-metadata.yaml

Fix #2909 
Implement GET /deviceprofile/model/{model} V2 API according to the doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.x#/default/get_deviceprofile_model__model_

feat(metadata): Implement GET /deviceprofile/model/{model} V2 API

---

internal/core/data/v2/application/event_test.go
internal/core/data/v2/controller/http/const_test.go
internal/core/data/v2/controller/http/event_test.go
internal/pkg/v2/infrastructure/redis/event.go

fix #2948 
Per https://github.com/edgexfoundry/go-mod-core-contracts/pull/398, we should remove pushed field completely from Event related implementation.

feat(data): remove pushed field completely from V2 Event related implementation

---

go.mod
internal/core/metadata/v2/controller/http/device_test.go
internal/core/metadata/v2/controller/http/deviceservice_test.go

Fix #2950
Upgrade go-mod-core-contracts version to v0.1.128 and fix test fail

feat: Upgrade go-mod-core-contracts version to v0.1.128

---

snap/local/patches/0001-optimize-build-for-pipeline-CI-check.patch
snap/local/runtime-helpers/config/security-secret-store/vault-config.hcl.in
snap/snapcraft.yaml

remove the dependency of consul  from vault
- [X ] No

build(snap): Snap remove vault depend consul

---

Dockerfile.build
cmd/core-command/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/security-bootstrap-redis/Dockerfile
cmd/security-proxy-setup/Dockerfile
cmd/security-secretstore-setup/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile
cmd/sys-mgmt-agent/Dockerfile

ci: standardize dockerfiles

---

internal/security/config/command/flags_common.go
snap/local/patches/0001-optimize-build-for-pipeline-CI-check.patch
snap/snapcraft.yaml

Used previous verion of go-mod-bootstrap that had backward compatibility code which supported pascal case env overrides and -r/--registry that accepted a URL. 
go-mo-bootstrap has been update to remove backwards compatibility code which requires a few changes to common flags usage and changing env overrides in snap to be upper case.

refactor: Adjust for removal of backward compatibility code

---

README.md

current link is not accessible
update to correct link

docs:  fix wrong link of api walk through page

---

cmd/security-secretstore-setup/entrypoint.sh

Command "chown" follows symlinks.
#3017 
Command "chown" does NOT follow symlinks.
N/A

fix: update chown options

---

internal/core/metadata/v2/application/provisionwatcher.go
internal/core/metadata/v2/controller/http/provisionwatcher.go
internal/core/metadata/v2/controller/http/provisionwatcher_test.go
internal/core/metadata/v2/infrastructure/interfaces/db.go
internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go
internal/core/metadata/v2/router.go
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/provisionwatcher.go

- /provisionwatcher/name/{name}
Implement DELETE /provisionwatcher/name/{name} V2 API

feat(meta): implement DELETE ProvisionWatcher v2 API

---

openapi/v2/core-data.yaml

fix #3041 
1. Add 409 response for AddEvent
2. Remove MultiSimpleReadingsResponse
3. Update Event/BaseReading schema
4. Update Example with correct fields

feat(data): Update Swagger doc to sync DTO schema with go-mod-core-contracts

---

internal/core/metadata/v2/application/provisionwatcher.go
internal/core/metadata/v2/controller/http/provisionwatcher_test.go
internal/core/metadata/v2/infrastructure/interfaces/db.go
internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/provisionwatcher.go

Refactor update operation to DBClient because deleting and adding to update a record only used for RedisDB.

refactor(meta): Refactor provision watcher update operation to DBClient

---

internal/pkg/v2/infrastructure/redis/device_profile.go

Refactor update operation to execute the RedisDB commands in same transaction.

refactor(meta): Refactor device profile update operation

---

openapi/v2/support-notifications.yaml

Update Swagger doc to meet V2 design requirements.
Details:
- Added missing V2 DTOs.
- Replaced the `slug` of Subscription with `name`.
- Added a new severity level: `MINOR`
- Added a new property `resendLimit` to Subscription, AddSubscriptionRequest, and UpdateSubscriptionRequest object.
- Added a new property `resendInterval` to Subscription, AddSubscriptionRequest, and UpdateSubscriptionRequest object.
- Replaced the `receiver` of Transmission object  with `subscriptionName`.
- Removed the /batch path.
- Removed the …

docs(notifications): Update Swagger doc

---

internal/core/metadata/v2/application/deviceprofile.go
internal/core/metadata/v2/application/notify.go
internal/core/metadata/v2/controller/http/deviceprofile_test.go

Close #3077
Add notify function to invoke Device Service callback for DeviceProfile change

feat(meta): Invoke Device Service callback for DeviceProfile change

---

go.mod
snap/local/patches/0001-optimize-build-for-pipeline-CI-check.patch

Hanoi branch doesn't have ZMQ bug fix via go-mod-messaging
Hanoi branch now has ZMQ bug fix via go-mod-messaging v0.1.30

fix: Hanoi - Upgrade to go-mod-messaging with ZMQ fix for Hanoi

---

go.mod
internal/core/command/init.go
internal/core/command/v2/application/command.go
internal/core/command/v2/controller/http/command.go
internal/core/command/v2/controller/http/command_test.go
internal/core/command/v2/router.go
openapi/v2/core-command.yaml

fix #3035 
Per https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-command/2.x#/default/get_device_name__name_, implement Command GET /device/name/{name} V2 API
Signed-off-by: Jude Hung <jude@iotechsys.com>

feat(command): Implement Command GET /device/name/{name} V2 API

---

openapi/v2/core-metadata.yaml

Fix #3093 
1. Update schema for ping, version, metrics, and config APIs.
2. Update operatingState value.
3. Remove response code 423 from /provisionwatcher/name/{name} delete method.

fix(meta): Update core-metadata API file

---

internal/core/metadata/operators/device_service/update.go
internal/core/metadata/operators/device_service/update_test.go
internal/core/metadata/rest_deviceservice.go
internal/core/metadata/rest_deviceservice_test.go
internal/core/metadata/router.go

Add callback for deviceService AdminState Update API to notify the service should update the AdminState
These changes are picked up from the main branch.

feat(meta): DS AdminState PUT API add service callback for Hanoi

---

go.mod
internal/core/metadata/v2/controller/http/const_test.go
internal/core/metadata/v2/controller/http/deviceprofile_test.go
openapi/v2/core-metadata.yaml

Close #3119
Rename ProfileResource to DeviceCommand for V2 API

feat(meta): Rename ProfileResource to DeviceCommand for V2 API

---

go.mod

Fix #3117
To fix the #3117, made the changes at go-mod-core-contract.

build: Upgrade go-mod-core-contract lib

---

internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/subscription.go
internal/support/notifications/v2/application/subscription.go
internal/support/notifications/v2/controller/http/subscription.go
internal/support/notifications/v2/controller/http/subscription_test.go
internal/support/notifications/v2/infrastructure/interfaces/db.go
internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/notifications/v2/router.go

Per https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_subscription_category__category_, implementd GET /subscription/category/{category} V2 API.
Close #3122

feat(notifications): Implement GET /subscription/category/{category} V2 API

---

go.mod
internal/core/command/init.go
internal/core/command/v2/application/command.go
internal/core/command/v2/controller/http/command.go
internal/core/command/v2/controller/http/command_test.go
internal/core/command/v2/router.go
internal/pkg/v2/utils/http.go
openapi/v2/core-command.yaml

fix #3064
Implement Command GET /device/name/{name}/{command} V2 API

feat(command):  Implement Command GET /device/name/{name}/{command} V2 API

---

internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/subscription.go
internal/support/notifications/v2/application/subscription.go
internal/support/notifications/v2/controller/http/subscription.go
internal/support/notifications/v2/controller/http/subscription_test.go
internal/support/notifications/v2/infrastructure/interfaces/db.go
internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/notifications/v2/router.go

Per https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_subscription_label__label_, implemented GET /subscription/label/{label} V2 API.
Close #3126

feat(notifications): Implement GET /subscription/label/{label} V2 API

---

openapi/v2/core-command.yaml
openapi/v2/core-data.yaml
openapi/v2/core-metadata.yaml
openapi/v2/support-notifications.yaml
openapi/v2/support-scheduler.yaml
openapi/v2/system-agent.yaml

1. add apiVersion to all request objects
2. update core-metadata DELETE status code from 423 to 409
3. update coreCommands from put to set
4. update config, version, metrics, and ping schemas and examples

docs(all): add apiVersion to all request objects and update DELETE status code

---

go.mod
internal/core/command/v2/application/command.go
internal/core/command/v2/controller/http/command_test.go
internal/core/metadata/v2/controller/http/device_test.go
internal/core/metadata/v2/controller/http/deviceprofile_test.go
internal/core/metadata/v2/controller/http/deviceservice_test.go

Close #3131
- Upgrade go-mod-core-contract lib to v2.0.0-dev.29
- Rename Put Command to Set Command

refactor(meta): Rename Put Command to Set Command

---

go.mod
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/subscription.go
internal/support/notifications/v2/application/subscription.go
internal/support/notifications/v2/controller/http/subscription.go
internal/support/notifications/v2/controller/http/subscription_test.go
internal/support/notifications/v2/infrastructure/interfaces/db.go
internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/notifications/v2/io/subscription.go
internal/support/notifications/v2/router.go

Per https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/patch_subscription, implement PATCH /subscription V2 API.
Close #3143

feat(notifications): Implement PATCH /subscription V2 API

---

go.mod
internal/core/command/v2/application/command.go
internal/core/command/v2/controller/http/command.go
internal/core/command/v2/controller/http/command_test.go
internal/core/command/v2/router.go
openapi/v2/core-command.yaml

fix #3152 
Per https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-command/2.x#/default/get_device_all, implement GET /device/all V2 API.

feat(command): Implement GET /device/all V2 API

---

internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/interval.go
internal/support/scheduler/v2/application/interval.go
internal/support/scheduler/v2/controller/http/interval.go
internal/support/scheduler/v2/controller/http/interval_test.go
internal/support/scheduler/v2/infrastructure/interfaces/db.go
internal/support/scheduler/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/scheduler/v2/router.go
openapi/v2/support-scheduler.yaml

Close #3173
Implement the V2 API according to the swagger doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-scheduler/2.x#/default/get_interval_name__name_

feat(scheduler): Implement GET /interval/name/{name} V2 API

---

internal/core/command/v2/application/command.go
internal/core/command/v2/controller/http/command.go
internal/core/command/v2/controller/http/command_test.go
internal/core/command/v2/router.go
internal/pkg/v2/utils/http.go

fix #3176 
Per
https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-command/2.x#/default/put_device_name__name___command_
implement PUT /device/name/{deviceName}/{command} V2 API.

feat(command): Implement PUT /device/name/{deviceName}/{command} V2 API

---

Attribution.txt
go.mod

Signed-off-by: Jim White <jpwhite_mn@yahoo.com>
Update 
#3163 

fix(all): update attribution to include libs for consul 1.8.1

---

cmd/security-secretstore-setup/README.md
internal/security/proxy/testdata/configuration.toml
snap/snapcraft.yaml

The following still refer to `SecretService` which has ben changed to `SecretStore` for Secret Store Setup & Proxy Setup
- Snap env overrides
- Secret Store Setup README
- Proxy Setup testdata config
The following now refer to new `SecretStore` for Secret Store Setup & Proxy Setup
- Snap env overrides
- Secret Store Setup README
- Proxy Setup testdata config
Previous PR contained the breaking change

refactor: Update remaining SecretService references to be SecretStore

---

go.mod
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/notification.go
internal/support/notifications/v2/application/notification.go
internal/support/notifications/v2/controller/http/notification.go
internal/support/notifications/v2/controller/http/notification_test.go
internal/support/notifications/v2/controller/http/subscription_test.go
internal/support/notifications/v2/infrastructure/interfaces/db.go
internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/notifications/v2/io/notification.go
internal/support/notifications/v2/router.go

Per https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/post_notification, implemented POST /notification V2 API.
Close #3174 
This PR depends on https://github.com/edgexfoundry/go-mod-core-contracts/pull/513
Note that the part about sending notifications will be added by another PR.

feat(notifications): Implement POST /notification V2 API

---

internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/interval.go
internal/support/scheduler/v2/application/interval.go
internal/support/scheduler/v2/controller/http/interval.go
internal/support/scheduler/v2/controller/http/interval_test.go
internal/support/scheduler/v2/infrastructure/interfaces/db.go
internal/support/scheduler/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/scheduler/v2/router.go

Close #3197
Implement the V2 API according to the swagger doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-scheduler/2.x#/default/delete_interval_name__name_

feat(scheduler): Implement DELETE /interval V2 API

---

internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/notification.go
internal/support/notifications/v2/application/notification.go
internal/support/notifications/v2/controller/http/notification.go
internal/support/notifications/v2/controller/http/notification_test.go
internal/support/notifications/v2/infrastructure/interfaces/db.go
internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/notifications/v2/router.go

Per [https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_notification_category__category_](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_notification_category__category_), implemented GET /notification/category/{category} V2 API.
Close #3211

feat(notifications): Implement GET /notification/category/{category} V2 API

---

go.mod
internal/core/command/v2/controller/http/command_test.go
internal/core/data/v2/application/event.go
internal/core/data/v2/application/event_test.go
internal/core/data/v2/controller/http/const_test.go
internal/core/data/v2/controller/http/event.go
internal/core/data/v2/controller/http/event_test.go
internal/core/data/v2/router.go
internal/core/metadata/v2/controller/http/device_test.go
internal/core/metadata/v2/controller/http/provisionwatcher_test.go
openapi/v2/core-data.yaml

Close #3213
Upgrade the go-mod-core-contracts lib

build: Upgrade the go-mod-core-contracts lib

---

internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/device_service.go
internal/pkg/v2/infrastructure/redis/interval.go
internal/support/scheduler/v2/application/interval.go
internal/support/scheduler/v2/controller/http/interval.go
internal/support/scheduler/v2/controller/http/interval_test.go
internal/support/scheduler/v2/infrastructure/interfaces/db.go
internal/support/scheduler/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/scheduler/v2/router.go

Close #3200
Implement the V2 API according to the swagger doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-scheduler/2.x#/default/patch_interval

feat(scheduler): Implement PATCH /interval V2 API

---

internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/notification.go
internal/support/notifications/v2/application/notification.go
internal/support/notifications/v2/controller/http/notification.go
internal/support/notifications/v2/controller/http/notification_test.go
internal/support/notifications/v2/infrastructure/interfaces/db.go
internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/notifications/v2/router.go

Per [https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_notification_label__label_](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_notification_label__label_), implemented GET /notification/label/{label} V2 API.
Close #3216

feat(notifications): Implement GET /notification/label/{label} V2 API

---

go.mod
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/notification.go
internal/support/notifications/v2/application/notification.go
internal/support/notifications/v2/controller/http/notification.go
internal/support/notifications/v2/controller/http/notification_test.go
internal/support/notifications/v2/infrastructure/interfaces/db.go
internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/notifications/v2/router.go
openapi/v2/support-notifications.yaml

Per [https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_notification_id__id_](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_notification_id__id_), implemented GET /notification/id/{id} V2 API.
Close #3207

feat(notifications): Implement GET /notification/id/{id} V2 API

---

Attribution.txt
go.mod
internal/core/data/v2/application/event.go
internal/core/data/v2/application/event_test.go
internal/core/data/v2/controller/http/event.go
internal/core/data/v2/controller/http/event_test.go
internal/core/data/v2/io/event.go
internal/core/data/v2/io/event_test.go

fix #2894 
Add implementation for decoding CBOR-encoded AddEventRequest

feat(data): Add CBOR support for V2 API

---

go.mod
internal/core/command/v2/application/command.go
internal/core/command/v2/application/command_test.go
internal/core/command/v2/controller/http/command_test.go
internal/core/metadata/v2/controller/http/deviceprofile_test.go
openapi/v2/core-metadata.yaml

Close #3248
- Update CoreCommand to use re-designed profile
- update swagger file

feat(command): Update CoreCommand to use re-designed profile

---

go.mod
internal/core/metadata/v2/controller/http/device_test.go
internal/core/metadata/v2/controller/http/deviceprofile_test.go
internal/core/metadata/v2/controller/http/deviceservice_test.go
internal/core/metadata/v2/controller/http/provisionwatcher_test.go
internal/support/notifications/v2/controller/http/subscription_test.go
internal/support/scheduler/v2/controller/http/interval_test.go
openapi/v2/core-metadata.yaml
openapi/v2/support-scheduler.yaml

Close #3261
Upgrade go-mod-core-contracts lib to apply the changes

build: Upgrade go-mod-core-contracts lib

---

internal/core/metadata/v2/application/notify.go

Close #3253
Callback for device and provision watcher deletion to be done by name

fix: Invoke DS deletion Callback by name

---

go.mod
internal/core/data/v2/controller/http/event_test.go
internal/core/metadata/v2/controller/http/device_test.go
internal/core/metadata/v2/controller/http/deviceservice_test.go
internal/core/metadata/v2/controller/http/provisionwatcher_test.go
internal/support/notifications/v2/controller/http/subscription_test.go
internal/support/scheduler/v2/controller/http/interval_test.go
openapi/v2/core-data.yaml
openapi/v2/core-metadata.yaml
openapi/v2/support-scheduler.yaml

Close #3264 #3259
Upgrade go-mod-core-contracts lib and modify API doc

build: Upgrade go-mod-core-contracts lib to v2.0.0-dev.51 

---

internal/support/notifications/v2/router.go
internal/support/scheduler/v2/router.go

Close #3277
Add missing middleware function to support-scheduler and support-notification router

feat: Add missing middleware func to router

---

go.mod
internal/support/notifications/v2/controller/http/subscription_test.go
openapi/v2/support-notifications.yaml

- Upgraded go-mod-core-contracts lib from v2.0.0-dev.51 to v2.0.0-dev.54
- Updated unit tests according to Subscription DTO and model changes.
- Updated support-notifications V2 API doc to reflect Subscription DTO and model changes.
Close #3265

build: Upgrade go-mod-core-contracts lib to v2.0.0-dev.54

---

go.mod
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/intervalaction.go
internal/support/scheduler/v2/application/intervalaction.go
internal/support/scheduler/v2/controller/http/intervalaction.go
internal/support/scheduler/v2/controller/http/intervalaction_test.go
internal/support/scheduler/v2/infrastructure/interfaces/db.go
internal/support/scheduler/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/scheduler/v2/router.go
openapi/v2/support-scheduler.yaml

Close #3289
Implement the API according to the doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-scheduler/2.x#/default/get_intervalaction_all

feat(scheduler): Implement GET /intervalaction/all V2 API

---

internal/security/bootstrapper/command/setupacl/command.go
internal/security/bootstrapper/command/setupacl/command_test.go

Implement the capability to add registry ACL roles on the fly via environment variable.
Changes on `security-bootstrapper`'s setupRegistryACL sub-command:
- Add logic to read and parse the environment variable `ADD_REGISTRY_ACL_ROLES` for adding additional registry roles on the fly
- Add validation logic on the comma-separated list of service key names as role names
- Add logic to make a unique list of role names combining both ones from configuration and from env. var.
- Refactor logic to re-set up when running in 2nd time or later
Closes: #3280
**If your build fails** due to your commit message not …

feat(security): Implementation for adding registry roles on the fly

---

go.mod
openapi/v2/support-notifications.yaml

Fix #3294
- Upgrade the core-contracts lib to solve the issue
- Update support-notifications API doc

feat: Update API doc and Upgrade core-contracts lib to v2.0.0-dev.57

---

internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/intervalaction.go
internal/support/scheduler/v2/application/intervalaction.go
internal/support/scheduler/v2/controller/http/intervalaction.go
internal/support/scheduler/v2/controller/http/intervalaction_test.go
internal/support/scheduler/v2/infrastructure/interfaces/db.go
internal/support/scheduler/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/scheduler/v2/router.go

Close #3304
Implement the API according to the doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-scheduler/2.x#/default/get_intervalaction_name__name_

feat(scheduler): Implement GET /intervalaction/name/{name} V2 API

---

internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/intervalaction.go
internal/support/notifications/v2/controller/http/subscription.go
internal/support/notifications/v2/controller/http/subscription_test.go
internal/support/scheduler/v2/application/intervalaction.go
internal/support/scheduler/v2/controller/http/interval_test.go
internal/support/scheduler/v2/controller/http/intervalaction.go
internal/support/scheduler/v2/controller/http/intervalaction_test.go
internal/support/scheduler/v2/infrastructure/interfaces/db.go
internal/support/scheduler/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/scheduler/v2/router.go
openapi/v2/support-notifications.yaml
openapi/v2/support-scheduler.yaml

Close #3309
Implement the API according to the doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-scheduler/2.x#/default/delete_intervalaction_name__name_

feat(scheduler): Implement DELETE /intervalaction/name/{name} V2 API

---

internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/intervalaction.go
internal/support/scheduler/v2/application/intervalaction.go
internal/support/scheduler/v2/controller/http/interval_test.go
internal/support/scheduler/v2/controller/http/intervalaction.go
internal/support/scheduler/v2/controller/http/intervalaction_test.go
internal/support/scheduler/v2/infrastructure/interfaces/db.go
internal/support/scheduler/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/scheduler/v2/router.go

Close #3321
Implement the API according to the doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-scheduler/2.x#/default/patch_interval

feat(scheduler): Implement Patch /intervalaction V2 API

---

internal/pkg/v2/bootstrap/handlers/database.go

Close #3323
Add the missing RedisDB Password for v2 security mode

feat: Add RedisDB Password for v2 security mode

---

internal/pkg/v2/infrastructure/redis/event.go

Close #3351
Add the sourceName to event model before storing to DB

feat(data): Add the missing event's sourceName at persistent layer

---

internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/notification.go
internal/support/notifications/v2/application/notification.go
internal/support/notifications/v2/controller/http/notification.go
internal/support/notifications/v2/controller/http/notification_test.go
internal/support/notifications/v2/infrastructure/interfaces/db.go
internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/notifications/v2/router.go

Close #3360
Implement V2 API according to the doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/delete_notification_id__id_

feat(notifications): Implement DELETE /notification/id/{id} API

---

openapi/v2/support-notifications.yaml

Renamed `TRXESCALATED` to `ESCALATED`
Fix #3376

docs(notifications): Update Swagger V2 doc to rename `TRXESCALATED`

---

internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/notification.go
internal/pkg/v2/infrastructure/redis/queries.go
internal/support/notifications/v2/application/notification.go
internal/support/notifications/v2/controller/http/notification.go
internal/support/notifications/v2/controller/http/notification_test.go
internal/support/notifications/v2/infrastructure/interfaces/db.go
internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/notifications/v2/router.go

Close #3378
Implement Notification Get /notification/subscription/name/{name} V2 API , https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_notification_subscription_name__name_

feat(notifications): Implement query by subscriptionName

---

go.mod
internal/core/command/v2/application/command.go
internal/core/command/v2/controller/http/command.go
internal/core/command/v2/controller/http/command_test.go
internal/core/metadata/v2/controller/http/deviceprofile_test.go

Close #3345
- Check whether the ds-pushevent and ds-returnevent parameters is valid
- Return empty content when ds-returnevent is set to no

fix(command): fix Get Command Request Response Errors

---

internal/core/command/v2/controller/http/command.go
internal/core/data/v2/controller/http/event.go
internal/core/data/v2/controller/http/reading.go
internal/core/metadata/v2/controller/http/device.go
internal/core/metadata/v2/controller/http/deviceprofile.go
internal/core/metadata/v2/controller/http/deviceresource.go
internal/core/metadata/v2/controller/http/deviceservice.go
internal/core/metadata/v2/controller/http/provisionwatcher.go
internal/pkg/v2/utils/http.go
internal/support/notifications/v2/controller/http/notification.go
internal/support/notifications/v2/controller/http/subscription.go
internal/support/scheduler/v2/controller/http/interval.go
internal/support/scheduler/v2/controller/http/intervalaction.go

Close: #3399
Refactor the duplicated code snippets of the controller error handling.

refactor: Refactor controller error handling

---

internal/system/agent/init.go
internal/system/agent/router.go
internal/system/agent/v2/router.go
openapi/v2/system-agent.yaml

feat(sma): add v2 common API

---

Dockerfile.build
README.md
cmd/core-command/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/security-bootstrapper/Dockerfile
cmd/security-proxy-setup/Dockerfile
cmd/security-secretstore-setup/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile
cmd/sys-mgmt-agent/Dockerfile
go.mod

update go.mod, Dockerfile.build, Dockerfile, README.md
Signed-off-by: Jim White <jpwhite_mn@yahoo.com>
upgrade to Go 1.16

build: upgrade Go lang to 1.16

---

cmd/support-scheduler/res/configuration.toml
go.mod
internal/core/metadata/v2/controller/http/device_test.go
internal/core/metadata/v2/controller/http/provisionwatcher_test.go
internal/support/scheduler/config/config.go
internal/support/scheduler/loader.go
internal/support/scheduler/v2/application/interval.go
internal/support/scheduler/v2/application/scheduler/executor.go
internal/support/scheduler/v2/application/scheduler/executor_test.go
internal/support/scheduler/v2/application/scheduler/queue_test.go
internal/support/scheduler/v2/controller/http/interval_test.go

refactor: rename Frquency to Interval in AutoEvent and Scheduler

---

cmd/core-data/res/configuration.toml
go.mod
internal/core/data/init.go
internal/core/data/main.go
internal/core/data/messaging/messaging.go
internal/core/data/v2/application/subscriber.go

Close: #2936
- Add subscribing logic to bootstrapping MessageBus client
- Implement Event received via MessageBus

feat(data): Implement events subscribing from message bus

---

go.mod
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/transmission.go
internal/support/notifications/v2/application/transmission.go
internal/support/notifications/v2/controller/http/transmission.go
internal/support/notifications/v2/controller/http/transmission_test.go
internal/support/notifications/v2/infrastructure/interfaces/db.go
internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/notifications/v2/router.go
openapi/v2/support-notifications.yaml

Close: #3482
Implement V2 GET /transmission/status/{status} API according to the doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_transmission_status__status_

feat(notifications): Implement V2 GET /transmission/status/{status} API

---

internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/transmission.go
internal/support/notifications/v2/application/transmission.go
internal/support/notifications/v2/controller/http/transmission.go
internal/support/notifications/v2/controller/http/transmission_test.go
internal/support/notifications/v2/infrastructure/interfaces/db.go
internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go
internal/support/notifications/v2/router.go

Close: #3489
Implement V2 Get /transmission/subscription/name/{name} API according to the doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_transmission_subscription_name__name_

feat(notifications): Implement query transmissions V2 API

---

cmd/core-command/res/configuration.toml
cmd/core-data/res/configuration.toml
cmd/core-metadata/res/configuration.toml
cmd/support-notifications/res/configuration.toml
cmd/support-scheduler/res/configuration.toml
cmd/sys-mgmt-agent/res/configuration.toml
go.mod
internal/core/command/v2/controller/http/command_test.go
internal/support/scheduler/schedule.go
internal/system/agent/init.go

Using old version of ServiceInfo struct from go-mod-bootstrap
Using new version of ServiceInfo struct from go-mod-bootstrap
BREAKING CHANGE: Core/Support/SysMgmt Service configuration has changed.

refactor: Update Service configurations for changes to common Service configuration struct

---

internal/core/data/v2/application/subscriber.go

Close: #3503
CoreData should check whether the event is valid when receive the event from the message bus.

feat(data): message topic should contain the event's deviceName

---

internal/support/notifications/v2/application/distributioncoordinator.go
internal/support/scheduler/v2/application/scheduler/manager.go
openapi/v2/core-metadata.yaml
openapi/v2/support-scheduler.yaml

Close: #3375
- skip the notification transmission when the subscription is locked
- skip the scheduler job execution when the interval action is locked

feat: Enable the check of adminState for notifications and scheduler

---

openapi/v2/core-command.yaml
openapi/v2/core-data.yaml
openapi/v2/core-metadata.yaml
openapi/v2/support-notifications.yaml
openapi/v2/support-scheduler.yaml

Close: #2690
Using the enum keyword to specify possible values of the model property.

docs: Update swagger doc

---

go.mod
internal/core/metadata/controller/http/deviceprofile_test.go

Close: #3595
Update to Core Contracts lib to v2.0.0-dev.103

build: Update Core Contracts lib to v2.0.0-dev.103

---

go.mod

Using pre-release go-mods
Using released go-mods

build: Update to released go-mods

---

openapi/v2/core-command.yaml
openapi/v2/core-data.yaml
openapi/v2/core-metadata.yaml
openapi/v2/support-notifications.yaml
openapi/v2/support-scheduler.yaml
openapi/v2/system-agent.yaml

V2 Swagger is published with version of 2.x
V2 Swagger is now published with version of 2.0

refactor: Change V2 Swagger to be published as 2.0

---

openapi/v2/core-command.yaml
openapi/v2/core-data.yaml
openapi/v2/core-metadata.yaml
openapi/v2/support-notifications.yaml
openapi/v2/support-scheduler.yaml
openapi/v2/system-agent.yaml

fix: Change V2 Swagger API version to 2.0.0

---

openapi/v2/core-metadata.yaml

docs(metadata): Update provisionwatcher v2 Swagger doc

---

openapi/v2/support-notifications.yaml

docs(notifications): Update notifications V2 Swagger doc

---

.hadolint.yml
Makefile
cmd/sys-mgmt-agent/Dockerfile

Closes #2515
Dockerfiles have no testing.
Closes #2515
Lint Dockerfiles for potential security vulnerabilities due to incorrect use of shell or other Docker-related errors.
Test by running "make test"

feat(security): Lint Dockerfiles

---

internal/core/command/application/command.go

Close: #3611
Use KindServerError instead of the KindClientError to prevent panic error from the HTTP lib

fix: Fix core-command crashes error

---

cmd/sys-mgmt-agent/Dockerfile

Snyk report High severity issue of Jul 13, 2021

build(deps): update docker in docker image for SMA as called out by Snyk

---

go.mod
internal/core/metadata/application/device.go
internal/core/metadata/application/deviceservice.go
internal/core/metadata/application/provisionwatcher.go
internal/core/metadata/controller/http/device_test.go
internal/core/metadata/controller/http/deviceservice_test.go
internal/core/metadata/controller/http/provisionwatcher_test.go
internal/support/notifications/application/subscription.go
internal/support/notifications/controller/http/subscription_test.go
internal/support/scheduler/application/interval.go
internal/support/scheduler/application/intervalaction.go
internal/support/scheduler/controller/http/interval_test.go
internal/support/scheduler/controller/http/intervalaction_test.go

- Upgrade go-mod-core-contracts to v2.0.1-dev.13
- Fix unit test

build: Upgrade go-mod-core-contracts to v2.0.1-dev.13

---

openapi/v2/core-metadata.yaml
openapi/v2/system-agent.yaml

docs: Update metadata and sma docs

---

ADOPTERS.md
GOVERNANCE.md
OWNERS.md

LF Edge required documentation pages added to the repository (Adopters, Governance and Owners)

docs: added LF Edge required Adopters, Governance and Owners MD pages

---

cmd/core-command/res/configuration.toml
cmd/core-data/res/configuration.toml
cmd/core-metadata/res/configuration.toml
cmd/security-bootstrapper/res-bootstrap-redis/configuration.toml
cmd/security-bootstrapper/res/configuration.toml
cmd/security-secretstore-setup/res-file-token-provider/configuration.toml
cmd/security-secretstore-setup/res/configuration.toml
cmd/support-notifications/res/configuration.toml
cmd/support-scheduler/res/configuration.toml
cmd/sys-mgmt-agent/res/configuration.toml

Mix of single quotes and double quotes in TOML Files
Issue Number: n/a
Replaced single quotes with double quotes in TOML Files
no

refactor: Clean up TOML quotes

---

.github/workflows/codeql-analysis.yml

Fixes #3593
Add configuration files to enable CodeQL static analysis
Closes #3593

feat(security): Add configuration for CodeQL static analysis

---

openapi/v2/system-agent.yaml

docs: fix API path in SMA API document

---

openapi/v2/core-metadata.yaml

fix: Remove operating state from device service

---

cmd/core-command/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/security-bootstrapper/Dockerfile
cmd/security-proxy-setup/Dockerfile
cmd/security-secretstore-setup/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile
cmd/sys-mgmt-agent/Dockerfile

Services built with base Alpine 3.12 image which has CVEs
Services built with base Alpine 3.14 image which has resolved the CVEs

build(security): Upgrade base images to alpine 3.14

---

cmd/core-command/res/configuration.toml

fixes: #3637
not a new feature or code bug - just TOML clean up
no doc to update - just TOML clean up

fix(command): clean out database section from core command

---

cmd/core-command/res/configuration.toml
cmd/core-data/res/configuration.toml
cmd/core-metadata/res/configuration.toml
cmd/support-notifications/res/configuration.toml
cmd/support-scheduler/res/configuration.toml
cmd/sys-mgmt-agent/res/configuration.toml

It was decided the 50000 is too high.
closes #3710
https://github.com/edgexfoundry/edgex-docs/pull/592

perf: Change MaxResultCount setting to 1024

---

internal/core/command/controller/http/command.go

- Run core service and device service
- Test with debug mode to inspect the response code

fix(command): Using the Device Service response code for Get Command

---

internal/pkg/infrastructure/redis/client.go

Closes #3669
Run core services and test the general API is workable.

refactor(all): Remove unused Redis client variables

---

internal/pkg/infrastructure/redis/event.go

Retrieve the eventId from storeKey instead of querying the eventObj to get the eventId.
Closes #3708 
**unit tests not impacted**
**docs not impacted**
1. Run the core-data service and add events
2. Test `delete event by age` and `delete event by deviceName` API

feat(data): Enhance the performance of events deletion

---

.golangci.yml
internal/core/data/messaging/messaging.go
internal/core/metadata/controller/http/deviceprofile_test.go
internal/core/metadata/controller/http/provisionwatcher_test.go
internal/pkg/bootstrap/handlers/database.go
internal/pkg/infrastructure/redis/queries.go
internal/security/config/command/proxy/adduser/command.go
internal/security/kdf/methods.go
internal/security/proxy/service.go
internal/security/secretstore/passwordprovider.go
internal/support/notifications/application/channel/email.go
internal/system/executor/docker.go

See #3565
Ran "make test" suite.  Ran make docker and started framework.

style: Enable gosimple linter and associated recommendations

---

.golangci.yml

See #3565
Per-checkin build tests should be sufficient.
The change here largely duplicate others found by unused and deadcode linters.

style: Fix variable assignments and enable varcheck linter

---

Attribution.txt
go.mod
internal/security/config/command/proxy/jwt/command.go
internal/security/secretstore/kongadminapi.go

Closes #3728
```sh
make docker
#in edgex-compose
cd compose-builder
make run dev
make get-token
```
Total increase in new imports: 0
Does the new import introduce additional import dependencies, if so, how many? 0
Releases/Tags: 17
Contributors: 66
License - what is the license, and is it Apache 2.0 compatible? MIT
Stars/Forks/Watchers: 986/68/14
godoc.org metrics: 170
This is a basic code hygene PR to replace an unmaintained package with a maintained one.

fix(security): Replace abandoned JWT package

---

openapi/v2/core-data.yaml

Update event schema and example to use object value in the Event tags
Closes #3669
**Only update swagger API**
1. Modify the go.mod to replace the core-contracts lib
2. Run core-data 
3. Add event and query event to see the change

docs(data): Update docs to use object value in the Event tags

---

.golangci.yml
internal/security/bootstrapper/command/setupacl/acltokens.go
internal/security/bootstrapper/command/setupacl/command_test.go
internal/security/bootstrapper/command/setupacl/share/constant.go
internal/security/bootstrapper/command/setupacl/stubdata_test.go
internal/security/bootstrapper/command/waitfor/command_test.go
internal/security/bootstrapper/helper/helper.go
internal/security/proxy/const.go
internal/security/proxy/requestor.go
internal/security/proxy/service.go
internal/security/proxy/serviceplugin.go
internal/security/proxy/serviceplugin_test.go
internal/security/secretstore/constants.go
internal/security/secretstore/init.go
internal/security/secretstore/kongadminapi.go
internal/security/secretstore/password_linux_test.go
internal/security/secretstore/password_test.go
internal/support/notifications/application/channel/email.go

See #3565
Basic smoke test -- build software and run in docker.

style: Enable gosec linter and associated recommendations

---

cmd/sys-mgmt-agent/Dockerfile

Closes #3740
make docker; make run dev

fix(security): Bump sys-mgmt-agent base image

---

README.md

Upgrade the ref of Walkthrough from 1.3 to 2.1 docs
Correct the edgex-compose link for downloading docker-compose file
Correct the broken link on LTS Policy
Close https://github.com/edgexfoundry/edgex-go/issues/3795

docs: Clean up README for Jakarta

---

snap/README.md

This PR is closing PR #3806 
- update snap version to 2.1
- update service environment configuration overrides
- update version and links in the rest sections
- change snake-case to nature language for description of
`Service environment configuration overrides`
- update `Security services` section
- update `Installing snapcraft` section
- update Consul's UI's hyperlink
- update two typos
- solve merge conflicts
- add `bash` after "```"
- remove some "$" for consistent
- remove Kong build part
- remove restart edegxfoundry in `Interfaces` section
- add `command`
- update the description of `snapcraft clean`
- change develop mode's installation flag to `--dangerous` for confinement
- change `snap install` command's flag to `--dangerous` for confinement
- update words
Signed-off-by: Mengyi …
```

docs(snap): update snap/README.md

---

openapi/v2/core-metadata.yaml

Also replace spaces with hypens in device name examples
fix #3830
N/A
N/A

docs: Update core-metadata API doc PATCH/PUT examples

---

.github/ISSUE_TEMPLATE/1-bug-report.md
.github/ISSUE_TEMPLATE/2-feature-request.md
.github/ISSUE_TEMPLATE/3-docs-bug.md

docs: update issue templates to indicate required sections

---

cmd/sys-mgmt-agent/Dockerfile

found per synk scan
fix: #3846

fix(sma): update Docker base image in sys mgmt agent Dockerfile

---

openapi/v2/core-command.yaml
openapi/v2/core-data.yaml
openapi/v2/core-metadata.yaml
openapi/v2/support-notifications.yaml
openapi/v2/support-scheduler.yaml
openapi/v2/system-agent.yaml

Update publishing of main branch Open API Documents to be to 2.2.0
Close https://github.com/edgexfoundry/edgex-go/issues/3844
N/A, updating API docs only

docs(all): Upgrade the API Docs version to 2.2.0

---

README.md
bin/test-attribution-txt.sh
cmd/core-command/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/security-bootstrapper/Dockerfile
cmd/security-proxy-setup/Dockerfile
cmd/security-secretstore-setup/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile
cmd/sys-mgmt-agent/Dockerfile
go.mod
snap/local/hooks/go.mod
snap/snapcraft.yaml

Changes related to Go 1.17 and cache optimizations

ci: Go 1.17 related changes

---

go.mod
go.sum

close https://github.com/edgexfoundry/go-mod-messaging/issues/131
<link to docs PR> 
**N/A**
**N/A**

build: Update to latest go-mod-messaging with ZMQ fix

---

go.mod
go.sum
internal/core/metadata/application/device.go
internal/core/metadata/application/notify.go
internal/core/metadata/controller/http/device_test.go

fix #3894 
1. Run metadata from this branch
2. Run device-simple from device-sdk-go
3. try patching(or adding) `Simple-Device01` with invalid protocols, for example:
```
[
{
"requestId": "d3367878-c46b-4263-b0af-1ccac37aab6e",
"device": {
"name": "Simple-Device01",
"adminState": "LOCKED",
"protocols": {
"others": {}
}
}
}
]
```
4. Metadata should return 207 with 500 error:
```
[
{
"requestId": "d3367878-c46b-4263-b0af-1ccac37aab6e", …
```

feat(metadata): invoke validation before adding/updating device

---

internal/core/data/controller/messaging/subscriber.go
internal/core/data/init.go

refactor(data): Move subscriber.go from application to controller

---

go.mod
go.sum
internal/core/metadata/application/notify.go
internal/core/metadata/controller/http/device_test.go

fix #3909 
1. Run core-metadata from this branch
2. run any device-service and then stop them
3. add a new device under that device-service and verify request succeed

fix(metadata): ignore validation result if device service unavailable

---

openapi/v2/core-metadata.yaml

docs(metadata): update metadata swagger API docs for device profile changes

---

cmd/security-spire-config/seed_builtin_entries.sh

feat(security): update the pre-authorized service list for spire server config

---

internal/pkg/infrastructure/redis/queries.go

The original implementation will return nil result set and nil error when count=0.  With such implementation, when query multiple entities and there is no entity in the DB, specify a out-of-range offset param will result in incorrect 200 status code rather than expected 416 status code.  
This commit fixes this issue by moving the check of offset > count with higher precedence over the check of count = 0, so that the APIs can return 416 status code when offset > count && count =0.
fixes #3940 
Signed-off-by: Jude Hung <jude@iotechsys.com> …

fix(all): return 416 code when count is zero and offset > count

---

internal/core/metadata/application/devicecommand.go
internal/core/metadata/controller/http/devicecommand.go
internal/core/metadata/controller/http/devicecommand_test.go
internal/core/metadata/router.go
openapi/v2/core-metadata.yaml

1. run metadata from this branch
2. POST /deviceprofile/deviceCommand, and verify the responses

feat(metadata): Implement Post device command API

---

cmd/core-metadata/res/configuration.toml
internal/core/metadata/application/deviceprofile.go
internal/core/metadata/config/config.go
internal/core/metadata/controller/http/deviceprofile.go
internal/core/metadata/controller/http/deviceprofile_test.go
internal/core/metadata/router.go

addressed in #3919
1. run metadata from this branch
2. verify DELETE `/api/v2/deviceprofile/name/{name}/resource/{resourceName}` is working
3. verify DELETE `/api/v2/deviceprofile/name/{name}/deviceCommand/{commandName}` is working

feat(metadata): implement DELETE device resource, device command API

---

README.md
SECURITY.md

fixes issue 719 in edgex-docs in this repo

fix: replace slack.edgexfoundry.org with edgexfoundry.slack.com

---

.github/workflows/snap.yaml
Jenkinsfile

Signed-off-by: Mengyi <mengyi.wang@canonical.com>

test(snap): add CI workflow, disable Jenkins snap build

---

go.mod
go.sum
internal/core/metadata/application/deviceresource.go
internal/core/metadata/controller/http/deviceresource.go
internal/core/metadata/controller/http/deviceresource_test.go
internal/core/metadata/router.go
openapi/v2/core-metadata.yaml

1. build core-metadata from this branch
2. PATCH /deviceprofile/resource and verify the responses

feat(metadata): Implement PATCH deviceprofile/resource API

---

openapi/v2/core-metadata.yaml

docs(metadata): update metadata Swagger PATCH API responses

---

cmd/core-data/res/configuration.toml
cmd/core-metadata/res/configuration.toml
cmd/security-proxy-setup/res/configuration.toml
cmd/security-spiffe-token-provider/res/configuration.toml
cmd/support-notifications/res/configuration.toml
cmd/support-scheduler/res/configuration.toml
cmd/sys-mgmt-agent/res/configuration.toml

In compose scripts, `make run delayed-start`

feat(security): Add secret store config for delayed start

---

openapi/v2/core-metadata.yaml

docs(metadata): fix Swagger metadata PATCH deviceprofile/resource response

---

snap/snapcraft.yaml

build(snap): Exclude redundant curl files from kuiper

---

.github/dependabot.yml

Adding the [snap's hooks package](https://github.com/edgexfoundry/edgex-go/tree/main/snap/local/hooks) to dependabot in order to get automated PRs for the dependency upgrades.

ci(snap): Add snap go mod to dependabot

---

snap/snapcraft.yaml

build(snap): upgrade to device-virtual v2.2.0 and asc latest/stable

---

snap/local/hooks/cmd/install/install.go
snap/snapcraft.yaml

- device-usb-camera snap
- device-onvif-camera snap

feat(snap): add secretstore token for camera snaps

---

README.md
snap/README.md

docs(snap): improvements to addon-services, env override and badge (Jakarta)

---

CHANGELOG.md

docs: Add snap and security(ekuiper) items to changelog

---

Makefile

Remove golangci-lint and run make lint

chore: Update instructions to get latest linter

---

.github/workflows/codeql-analysis.yml

Theoretically, only affects GitHub scanning, and there is nothing to "test" with this change.

build: Upgrade CodeQL modules, enable addl checkers

---

.gitignore
Makefile
README.md
cmd/core-command/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/security-bootstrapper/Dockerfile
cmd/security-proxy-setup/Dockerfile
cmd/security-secretstore-setup/Dockerfile
cmd/security-spiffe-token-provider/Dockerfile
cmd/security-spire-agent/Dockerfile
cmd/security-spire-config/Dockerfile
cmd/security-spire-server/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile
cmd/sys-mgmt-agent/Dockerfile
go.mod
go.sum
internal/security/bootstrapper/command/setupacl/command_test.go
internal/security/bootstrapper/command/setupacl/stubregistryserver_test.go
internal/security/config/command/proxy/adduser/command_test.go
internal/security/config/command/proxy/deluser/command_test.go
internal/security/config/command/proxy/tls/command_test.go
snap/local/hooks/go.mod
snap/snapcraft.yaml

Fixed issue flag by latest linter
Run the following make commands:
- make tidy
- make build
- make test
- make docker

build: Upgrade to go 1.18 and latest golangci-lint

---

cmd/support-scheduler/res/configuration.toml
internal/support/scheduler/config/config.go

relates to https://github.com/edgexfoundry/edgex-docs/pull/811

fix(scheduler): Remove unused field in scheduler config

---

internal/security/bootstrapper/helper/redis_conf.go
internal/security/bootstrapper/helper/redis_config_test.go

Signed-off-by: Kyle Morton <kylex.f.morton@intel.com>
Closes #4027 

fix: Addressed permission error in redis v7 #4027

---

README.md

docs: update the link address in the document
Signed-off-by: sixhj <sixhj@gmail.com>

docs: update the link address in the document

---

cmd/security-bootstrapper/entrypoint-scripts/consul_wait_install.sh
cmd/security-proxy-setup/res/configuration.toml
internal/security/bootstrapper/command/setupacl/aclpolicies.go
internal/security/bootstrapper/command/setupacl/acltokens.go
internal/security/bootstrapper/command/setupacl/acltokens_test.go
internal/security/bootstrapper/command/setupacl/command.go
internal/security/bootstrapper/command/setupacl/stubregistryserver_test.go
snap/snapcraft.yaml

feat: add management acl token and save token info to file

---

Makefile

build: fix docker build alias typo

---

Attribution.txt
cmd/core-command/res/configuration.toml
cmd/core-data/res/configuration.toml
cmd/core-metadata/res/configuration.toml

Also latest go-mod-messaging brought in more NATS dependencies
New dependencies are from our own go-mod-messaging module. Not new to EdgeX

feat: Add NATS Subject for autoprovisioning streams

---

.blubracket/ignore.yaml

Wait a few days after commit and see if # of findings on https://security.lfx.linuxfoundation.org/ EdgeX dashboard has decreased.

ci: Add blubracket ignore file

---

internal/core/command/controller/messaging/utils.go

fix #4196 
1. Run core-command from this branch
2. Send commandquery request via external MQTT
3. Verified the payload field in response envelope is of `DeviceCoreCommandResponse` or `MultiDeviceCoreCommandsResponse`

fix(command): return response DTO for messaging commandquery

---

internal/pkg/infrastructure/redis/interval.go
internal/pkg/infrastructure/redis/intervalaction.go
internal/support/scheduler/controller/http/intervalaction_test.go

Check interval when adding intervalAction at the infrastructure layer.
Fix #4190
- Run support-shceduler
- Test the POST and PATCH API

fix(scheduler): Check interval when adding intervalAction

---

cmd/core-command/res/configuration.toml
cmd/core-data/res/configuration.toml
cmd/core-metadata/res/configuration.toml
cmd/support-notifications/res/configuration.toml
cmd/support-scheduler/res/configuration.toml
go.mod
go.sum

closes: #374
Signed-off-by: Valina Li <valina.li@intel.com>

feat: add security Consul metrics

---

openapi/v2/core-command.yaml
openapi/v2/core-data.yaml
openapi/v2/core-metadata.yaml
openapi/v2/support-notifications.yaml
openapi/v2/support-scheduler.yaml
openapi/v2/system-agent.yaml

This PR updates the OpenAPI version yaml the next release version 2.4.0

ci: automated version changes for OpenAPI version: [2.4.0]

---

go.mod
go.sum
snap/local/runtime-helpers/bin/setup-consul-acl.sh
snap/local/runtime-helpers/bin/setup-redis-acl.sh
snap/snapcraft.yaml

BREAKING CHANGE: -c/--confdir and -f/--file renamed to -cd/--configDir and -cf/--configFile
closes #4248
https://github.com/edgexfoundry/edgex-docs/pull/916
build core data
run `core-data -h`
verify flags in help have new names
run `core-data --confdir something`
verify error due to --confdir unknown
run `core-data --configDir something`
verify error due to file `something` not found

refactor!: Use latest module with renamed option flags

---

Attribution.txt
internal/security/spiffetokenprovider/init.go

"make test" with new golangci-lint linter.

build: Address linter issues with new golangci-lint linter

---

go.mod
go.sum
internal/core/metadata/controller/http/const_test.go
internal/core/metadata/controller/http/deviceprofile_test.go
internal/core/metadata/controller/http/deviceresource_test.go

build(deps): bump go-mod dependencies and fix unittests

---

snap/README.md

- Remove outdated build instructions
- Improve installation and interface connection instructions
- Update links 

docs(snap): Remove outdated build instructions

---

Makefile

Signed-off-by: Elizabeth J Lee <elizabeth.j.lee@intel.com>
run `make docker` and ensure that core-common-config-bootstrapper is built

fix: update docker target for core common config bootstrapper

---

go.mod
go.sum

Signed-off-by: Elizabeth J Lee <elizabeth.j.lee@intel.com>
tested building docker images and running compose builder

fix: adjust go.mod for new bootstrap version

---

cmd/core-common-config-bootstrapper/res/configuration.yaml

refactor: Tweaks to common device configuration

---

openapi/v2/core-data.yaml

docs: Update Add Event Swagger for new `serviceName` parameter

---

cmd/core-common-config-bootstrapper/res/configuration.yaml

refactor: Add app service default subscribe topics

---

go.mod
go.sum
internal/pkg/application/secret.go
internal/pkg/controller/http/secret_test.go

build(deps)!: Upgrade contracts mod to update /secret DTO

---

go.mod
go.sum
internal/core/data/controller/http/event_test.go
internal/core/data/router.go
openapi/v3/core-data.yaml

BREAKING CHANGE: POST Event RSET endpoint will become /event/{serviceName}/{profileName}/{deviceName}/{sourceName}

feat(data)!: update Add Event REST endpoint

---

cmd/core-command/res/configuration.toml
cmd/core-common-config-bootstrapper/res/configuration.yaml
cmd/support-notifications/res/configuration.toml
go.mod
go.sum
internal/security/spiffetokenprovider/config/config.go
internal/security/spiffetokenprovider/init.go

make test
make notifications
postman: http://localhost:59880/api/v2/secret
view the log with no error

refactor!: Re-work handling of secrets

---

internal/core/data/controller/messaging/subscriber.go

update to align with new internal topics naming

fix(data): update validateEvent topic check

---

go.mod
go.sum

fix: Consume Request API fix in go-mod-messaging

---

cmd/secrets-config/main.go
internal/security/config/bootstraphandler.go
internal/security/config/command/help/command.go
internal/security/config/command/proxy/adduser/command.go
internal/security/config/command/proxy/command.go
internal/security/config/command/proxy/common/common.go
internal/security/config/command/proxy/deluser/command.go
internal/security/config/command/proxy/jwt/command.go
internal/security/config/command/proxy/tls/command.go
internal/security/config/interfaces/command.go
internal/security/config/interfaces/constants.go
internal/security/fileprovider/interface.go
internal/security/fileprovider/mocks/mock.go
internal/security/fileprovider/mocks/mock_test.go
internal/security/fileprovider/tokenconfig_test.go
internal/security/fileprovider/types.go
internal/security/fileprovider/util.go
internal/security/fileprovider/util_test.go
internal/security/secretstore/tokenprovider_linux_test.go
internal/security/secretstore/tokenprovider_test.go
snap/local/helper-go/configure.go
snap/local/helper-go/install.go
snap/local/helper-go/main.go
snap/local/helper-go/options.go

Changes to comments only. No testing required

fix: Typos in Apache-2.0 SPDX headers

---

go.mod
go.sum

build(deps): Bump go-mod-core-contracts

---

internal/security/config/bootstraphandler.go

Closes #4337
See use cases in #4337 for sample test cases to try to verify issue is fixed.

fix: Set exitcode of secrets-config for command execution errors

---

go.mod
go.sum
internal/core/metadata/controller/http/deviceprofile_test.go
openapi/v3/core-metadata.yaml

BREAKING CHANGE:
- added 'optional' field in ResourceProperties
- update data type in ResourceProperties
- update ProtocolProperties to have typed value
related to edgexfoundry/go-mod-core-contracts#592, edgexfoundry/go-mod-core-contracts#770
- [N/A] I have added unit tests for the new feature or bug fix (if not, why?)
- [N/A] I have fully tested (add details below) this the new feature or bug fix (if not, why?)

feat(metadata)!: update metadata unittests and API docs

---

cmd/core-command/res/configuration.toml
cmd/support-notifications/res/configuration.toml
internal/pkg/application/secret.go
internal/security/secretstore/init.go
internal/support/notifications/application/channel/email.go
internal/support/notifications/config/config.go

BREAKING CHANGE: Updated secret path to secret name
make test
make docker

refactor!: Updated secret path to secret name

---

Makefile
cmd/core-command/Dockerfile
cmd/core-common-config-bootstrapper/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/security-bootstrapper/Dockerfile
cmd/security-proxy-auth/Dockerfile
cmd/security-proxy-setup/Dockerfile
cmd/security-secretstore-setup/Dockerfile
cmd/security-spiffe-token-provider/Dockerfile
cmd/security-spire-agent/Dockerfile
cmd/security-spire-config/Dockerfile
cmd/security-spire-server/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile
go.mod
internal/core/metadata/uom/bootstrap.go

run `make docker`
run non-secure edgex stack with ds-virtual with dev images
verify services bootstrap and data is flowing to app-rules-engine
run secure edgex stack with ds-virtual with dev images
verify services bootstrap and data is flowing to app-rules-engine

build: Update to Go 1.20, Alpine 3.17 and linter v1.51.2

---

cmd/core-command/Dockerfile
cmd/core-common-config-bootstrapper/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/security-bootstrapper/Dockerfile
cmd/security-proxy-auth/Dockerfile
cmd/security-proxy-setup/Dockerfile
cmd/security-secretstore-setup/Dockerfile
cmd/security-spiffe-token-provider/Dockerfile
cmd/security-spire-agent/Dockerfile
cmd/security-spire-config/Dockerfile
cmd/security-spire-server/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile

Closes #4151 
run `make docker`

feat(security): add security.txt to docker images (#4407)

---

snap/snapcraft.yaml

refactor(snap): Remove external metadata sourcing

---

cmd/security-proxy-setup/Dockerfile
cmd/security-secretstore-setup/Dockerfile
cmd/security-spire-agent/Dockerfile
cmd/security-spire-config/Dockerfile
cmd/security-spire-server/Dockerfile

closes #4442
run `make docker`

feat: Add Attribution.txt for missing Dockerfiles

---

cmd/core-metadata/Dockerfile
cmd/core-metadata/res/configuration.toml
cmd/core-metadata/res/uom.toml
cmd/core-metadata/res/uom.yaml
internal/core/metadata/uom/bootstrap.go
internal/core/metadata/uom/uom.go
snap/hooks/post-refresh
snap/snapcraft.yaml

It was decided in Minnesota planning that all TOML files would be change to be YAML format.
Close #4441
- Run the service and check the YAML file is loaded
- Run unit test

feat!: Switch UOM file to YAML format

---

openapi/v3/core-metadata.yaml

related to edgexfoundry/go-mod-core-contracts#823
https://github.com/edgexfoundry/edgex-docs/pull/989

docs: Update Value Properties max and min data type from string to number

---

Attribution.txt
go.mod
go.sum
internal/core/common_config/main.go

run `make docker` with this branch
From compose builder run `make run ds-virtual dev`
Verify all service bootstrap succesfully
Verify access via API gateway to core-data /ping
Verify direct access to core-data /ping with token

refactor: Remove use of TOML package

---

Makefile

feat: update golangci-lint to be more verbose and info

---

go.mod
go.sum
internal/core/metadata/application/notify.go
internal/core/metadata/application/provisionwatcher.go
internal/core/metadata/controller/http/provisionwatcher_test.go
internal/pkg/infrastructure/redis/provisionwatcher.go
openapi/v3/core-metadata.yaml

BREAKING CHANGE: Apply provision watcher model changes
Implementation based on the core-contracts PR https://github.com/edgexfoundry/go-mod-core-contracts/pull/820
- Run core service, and device service and enable the discovery
- Send discovery API and check the discovered device is added to the metadata service

feat!: Apply provision watcher model changes

---

cmd/security-spiffe-token-provider/res/configuration.yaml

run `make dspiffetp`
From compose builder:
- run `make gen delayed-start ds-virtual`
- modify the compose file so security-spiffe-token-provider uses local dev image
- run `make up`
- Verify security-spiffe-token-provider bootstraps w/o errors
-

fix: [WIP BUG] Change SPIFFE to Spiffe in security-spiffe-token-provider YAML config

---

cmd/security-spire-config/seed_builtin_entries.sh

refactor: Adjust app service names in Spire seed script

---

internal/core/metadata/application/device.go
internal/core/metadata/controller/http/device_test.go

close #4478
1. Build core metadata image from this branch and run with other services
2. post/patch device with non-existence device service name
```
curl -ki -X POST http://localhost:59881/api/v2/device -d '[
{
"device": {
"name": "test-1",
"adminState": "UNLOCKED",
"operatingState": "UP",
"serviceName": "device-test",
"profileName": "Random-Boolean-Device",
"protocols": {
"other": {}
}
}
}]'
```
3. Verified the status code is 400 inside 207 Multi-Status
```
HTTP/1.1 207 Multi-Status
Content-Type: …
```

fix: Check the device service existence before calling the device validation

---

internal/pkg/bootstrap/handlers/database.go
internal/pkg/db/db.go
internal/pkg/db/redis/client.go

fix: Use Database Timeout setting defined in the configuration

---

go.mod
go.sum
internal/core/command/controller/messaging/internal_test.go

BREAKING CHANGE: all base API version is updated to v3
1. Run EdgeX with this branch
2. Verify base api version is changed to `/api/v3`

feat(all)!: update base API version to v3

---

.github/dependabot.yml

build: Ignore all go-mods except go-mod-bootstrap

---

cmd/core-common-config-bootstrapper/res/configuration.yaml
go.mod
go.sum

[go-mod-bootstrap](https://github.com/edgexfoundry/go-mod-bootstrap/pull/530)

feat: Add GetSecret and RunTimeSecret metrics

---

cmd/security-spiffe-token-provider/README.md
cmd/support-scheduler/res/configuration.yaml
internal/core/command/init.go
internal/core/data/application/event.go
internal/core/data/controller/http/event.go
internal/core/data/main.go
internal/core/metadata/main.go
internal/pkg/bootstrap/handlers/database.go
internal/pkg/controller/http/common.go
internal/pkg/controller/http/secret.go
internal/security/spiffetokenprovider/init.go
internal/support/notifications/config/config.go
internal/support/notifications/main.go
internal/support/scheduler/config/config.go
internal/support/scheduler/init.go
internal/support/scheduler/main.go

fix: Remove all references to v2

---

Attribution.txt
Makefile
cmd/core-command/Dockerfile
cmd/core-common-config-bootstrapper/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/security-bootstrapper/Dockerfile
cmd/security-proxy-auth/Dockerfile
cmd/security-proxy-setup/Dockerfile
cmd/security-secretstore-setup/Dockerfile
cmd/security-spiffe-token-provider/Dockerfile
cmd/security-spire-agent/Dockerfile
cmd/security-spire-config/Dockerfile
cmd/security-spire-server/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile
go.mod

make test
make build
make docker
Verify all are successful

build: Upgrade to go-1.21, Linter1.54.2 and Alpine 3.18

---

go.sum

fix: Run go mod tidy

---

internal/core/data/application/app.go

fix: Remove duplicate definitions

---

cmd/core-command/Dockerfile
cmd/core-common-config-bootstrapper/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/security-bootstrapper/Dockerfile
cmd/security-proxy-auth/Dockerfile
cmd/security-proxy-setup/Dockerfile
cmd/security-secretstore-setup/Dockerfile
cmd/security-spiffe-token-provider/Dockerfile
cmd/security-spire-agent/Dockerfile
cmd/security-spire-config/Dockerfile
cmd/security-spire-server/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile

fix: Address CVE in Alpine base image

---

openapi/v3/README.md
openapi/v3/core-command.yaml
openapi/v3/core-data.yaml
openapi/v3/core-metadata.yaml
openapi/v3/support-notifications.yaml
openapi/v3/support-scheduler.yaml

docs: Update swagger versions to be 3.1.0

---

Makefile
openapi/v3/support-notifications.yaml

and update support-notifications.yaml file for fuzzing test
Closes: #4743
Just run the command `make fuzz-test-support-notifications`, you will observe the fuzzing test result for support-notifications on terminal and the detail result folder support-notifications created in fuzz_test/fuzz_results/

feat: add support-notification fuzzing test

---

cmd/core-common-config-bootstrapper/res/configuration.yaml

feat: Add new StoreForwardQueueSize metric to common App services config

---

internal/core/metadata/application/device.go
internal/core/metadata/application/device_test.go
internal/core/metadata/controller/http/device_test.go

Check the auto events before adding or updating the Device.
Close #4767
Run unit test

feat: Check the auto events before adding or updating the Device

---

go.mod
go.sum
internal/core/metadata/application/device.go
internal/core/metadata/application/device_test.go
internal/core/metadata/controller/http/device_test.go
internal/pkg/infrastructure/redis/device.go
openapi/v3/core-metadata.yaml

refer to edgexfoundry/go-mod-core-contracts#901

feat(metadata): Allow empty profileName in Device

---

cmd/security-spire-agent/Dockerfile
cmd/security-spire-config/Dockerfile
cmd/security-spire-server/Dockerfile
go.mod
go.sum

build: Bump spire version of images

---

openapi/v3/core-command.yaml
openapi/v3/core-data.yaml
openapi/v3/core-keeper.yaml
openapi/v3/core-metadata.yaml
openapi/v3/support-notifications.yaml
openapi/v3/support-scheduler.yaml

docs: Set service version to 3.2.0 in API documents

---

internal/pkg/utils/http.go
internal/support/cronscheduler/application/scheduleactionrecord.go
internal/support/cronscheduler/application/schedulejob.go
internal/support/cronscheduler/container/config.go
internal/support/cronscheduler/container/database.go
internal/support/cronscheduler/controller/http/scheduleactionrecord.go
internal/support/cronscheduler/controller/http/schedulejob.go
internal/support/cronscheduler/init.go
internal/support/cronscheduler/main.go
internal/support/cronscheduler/router.go

This is the second PR of #4834.
- Implement the REST API controller package for Cron Scheduler service
https://github.com/edgexfoundry/edgex-go/pull/4831
- Clone the fork [edgex-go](https://github.com/jackchenjc/edgex-go/tree/issue-4834-2nd) and checkout this branch
- Run the following command at root folder to build local images
```
make docker
```
- Clone this fork [edgex-compose](https://github.com/jackchenjc/edgex-compose/tree/test-cron-scheduler) and checkout  to `test-cron-scheduler` branch
- Head to the compose-builder folder
- Run …

feat: Implement Cron Scheduler Controller Package

---

internal/pkg/correlation/handler.go
internal/support/cronscheduler/application/schedulejob.go
internal/support/cronscheduler/controller/http/scheduleactionrecord.go
internal/support/cronscheduler/controller/http/schedulejob.go
internal/support/cronscheduler/infrastructure/interfaces/SchedulerManager.go
internal/support/cronscheduler/infrastructure/interfaces/mocks/SchedulerManager.go
internal/support/cronscheduler/infrastructure/manager.go

feat: Include Correlation ID in Logs

---

cmd/core-data/res/db/sql/00-utils.sql
cmd/core-data/res/db/sql/01-tables.sql
cmd/security-secretstore-setup/res/configuration.yaml
go.mod
go.sum
internal/pkg/bootstrap/handlers/database.go
internal/pkg/db/postgres/client.go
internal/pkg/db/postgres/utils.go
internal/pkg/infrastructure/postgres/event.go
internal/pkg/infrastructure/postgres/reading.go
internal/pkg/infrastructure/postgres/sql.go

Relates to #4847. Add core-data event related db methods for postgres db client.

feat: Add core-data event related db methods for postgres

---

cmd/support-cron-scheduler/Dockerfile
go.mod
go.sum
internal/support/cronscheduler/application/action/devicecontrol.go
internal/support/cronscheduler/config/config.go
internal/support/cronscheduler/container/config.go
internal/support/cronscheduler/controller/http/schedulerjob_test.go
internal/support/cronscheduler/controller/http/utils_test.go
internal/support/cronscheduler/infrastructure/manager.go
internal/support/cronscheduler/main.go

This is the fourth PR of #4834
- Completed the features of Schedule Job
- Created config package for Cron Schedule Job service
- Added unit tests
- Modified the Dockerfile to add tzdata for supporting timezone in crontab expression

feat: Complete Schedule Job features and Add Unit Tests

---

go.mod
go.sum
internal/pkg/infrastructure/postgres/scheduleactionrecord.go
internal/pkg/infrastructure/postgres/schedulejob.go
internal/pkg/infrastructure/postgres/utils.go
internal/pkg/utils/http.go
internal/support/cronscheduler/application/scheduleactionrecord.go
internal/support/cronscheduler/controller/http/scheduleactionrecord.go
internal/support/cronscheduler/controller/http/scheduleactionrecord_test.go
internal/support/cronscheduler/controller/http/utils_test.go
internal/support/cronscheduler/infrastructure/interfaces/db.go
internal/support/cronscheduler/infrastructure/interfaces/mocks/DBClient.go
internal/support/cronscheduler/infrastructure/manager.go

This is the fifth PR of #4834
- Implemented the schedule action records features for Cron Scheduler service
- Add unit tests

feat: Implement Schedule Action Records for Cron Scheduler

---

go.mod
go.sum
internal/support/cronscheduler/application/schedulejob.go

feat: Add StartTimestamp and EndTimestamp for Cron Scheduler

---

cmd/core-data/Dockerfile
cmd/security-bootstrapper/entrypoint-scripts/postgres_wait_install.sh
cmd/security-bootstrapper/res-bootstrap-postgres/configuration.yaml
cmd/security-secretstore-setup/res/configuration.yaml
internal/pkg/db/postgres/client.go
internal/security/bootstrapper/helper/postgres_script.go
internal/security/bootstrapper/helper/postgres_script_test.go
internal/security/bootstrapper/postgres/handlers/handlers.go
internal/security/secretstore/config/config.go
internal/security/secretstore/init.go

Resolves #4847. Integrate Core Data with Postgres with securiy mode enabled.

feat: Integrate Core Data with Postgres on securiy mode

---

internal/support/cronscheduler/infrastructure/manager.go

fixes #4880
Generate suitable HTTP status code for Cron Scheduler APIs.

fix: Generate suitable HTTP status code

---

openapi/v3/support-cron-scheduler.yaml

fix: Update support-cron-scheduler API document

---

internal/support/cronscheduler/application/schedulejob.go

fix: ScheduleJob should not be triggered with endTimestamp expired

---

internal/support/cronscheduler/controller/http/schedulejob.go
internal/support/cronscheduler/controller/http/schedulejob_test.go

fix: Modify the HTTP status code of TriggerScheduleJobByName API

---

internal/support/cronscheduler/application/schedulejob.go

fix: Fix expired jobs and records should not be triggered and generated

---

go.mod
go.sum
internal/pkg/infrastructure/postgres/schedulejob.go
internal/support/cronscheduler/application/scheduleactionrecord.go
internal/support/cronscheduler/application/schedulejob.go
openapi/v3/support-cron-scheduler.yaml

closes #4897
https://github.com/edgexfoundry/edgex-docs/pull/1373

feat: Automatically Trigger Missed Scheduled Jobs

---

cmd/security-bootstrapper/entrypoint-scripts/postgres_wait_install.sh
internal/security/bootstrapper/helper/postgres_script.go
internal/security/bootstrapper/helper/postgres_script_test.go
internal/security/secretstore/init.go

- Fix the permission denied error in postgres_wait_install script.
- Update the postgres init db script.

fix: Fix the permission denied error in postgres_wait_install script

---

internal/support/cronscheduler/infrastructure/interfaces/SchedulerManager.go
internal/support/cronscheduler/infrastructure/interfaces/mocks/SchedulerManager.go
internal/support/cronscheduler/infrastructure/manager.go
internal/support/cronscheduler/infrastructure/manager_test.go
internal/support/cronscheduler/init.go

fix: Resolved job not found error that occurred after a failed update attempt

---

cmd/core-keeper/res/db/sql/00-utils.sql
cmd/core-keeper/res/db/sql/01-tables.sql
internal/pkg/infrastructure/postgres/consts.go
internal/pkg/infrastructure/postgres/kv.go
internal/pkg/infrastructure/postgres/registry.go
internal/pkg/infrastructure/postgres/sql.go

Resolves #4877. Support Postgres db in Core Keeper.

feat: Support Postgres db in Core Keeper

---

cmd/support-cron-scheduler/res/db/sql/00-utils.sql
cmd/support-cron-scheduler/res/db/sql/01-tables.sql
internal/pkg/infrastructure/postgres/consts.go
internal/pkg/infrastructure/postgres/registry.go
internal/pkg/infrastructure/postgres/scheduleactionrecord.go
internal/pkg/infrastructure/postgres/schedulejob.go
internal/pkg/infrastructure/postgres/sql.go
internal/support/cronscheduler/application/scheduleactionrecord.go

feat: Enhance Support Cron Scheduler persistence layer with PostgreSQL

---

cmd/core-metadata/Dockerfile
cmd/core-metadata/res/db/sql/00-utils.sql
cmd/core-metadata/res/db/sql/01-tables.sql
internal/core/data/application/event_test.go
internal/pkg/common/util.go
internal/pkg/infrastructure/postgres/consts.go
internal/pkg/infrastructure/postgres/device.go
internal/pkg/infrastructure/postgres/device_profile.go
internal/pkg/infrastructure/postgres/device_service.go
internal/pkg/infrastructure/postgres/provisionwatcher.go
internal/pkg/infrastructure/redis/intervalaction.go
internal/pkg/utils/db.go

feat: Add core-metadata device service related db methods for postgres

---

cmd/core-metadata/res/db/sql/01-tables.sql
internal/pkg/infrastructure/postgres/consts.go
internal/pkg/infrastructure/postgres/device_profile.go
internal/pkg/infrastructure/postgres/device_service.go

feat: Add core-metadata device profile related db methods for postgres

---

cmd/support-notifications/Dockerfile
cmd/support-notifications/res/db/sql/00-utils.sql
cmd/support-notifications/res/db/sql/01-tables.sql
internal/pkg/infrastructure/postgres/consts.go
internal/pkg/infrastructure/postgres/device_profile.go
internal/pkg/infrastructure/postgres/device_service.go
internal/pkg/infrastructure/postgres/notification.go
internal/pkg/infrastructure/postgres/scheduleactionrecord.go
internal/pkg/infrastructure/postgres/schedulejob.go
internal/pkg/infrastructure/postgres/sql.go
internal/pkg/infrastructure/postgres/subscription.go
internal/pkg/infrastructure/postgres/transmission.go
internal/pkg/infrastructure/postgres/utils.go

feat: Enhance Support Notifications to support PostgreSQL

---

cmd/security-secretstore-setup/res/configuration.yaml

Changes for https://github.com/edgexfoundry/edgex-compose/issues/463

feat: Update security-secretstore-setup config

---

cmd/security-file-token-provider/res/token-config.json

feat: Add Token Config for support-cron-scheduler

---

go.mod
go.sum
internal/core/data/controller/http/event_test.go

Upgrade core-contracts to v3.2.0-dev.48
Run make test.

build: Upgrade core-contracts to v3.2.0-dev.48

---

go.mod
go.sum

fix: Add validation for update scheduleJob API

---

internal/support/cronscheduler/application/schedulejob.go
internal/support/cronscheduler/infrastructure/manager.go

Arrange schedule job with gocron lib to avoid the following issues.
fixes #4886 
fixex #4933

fix: Arrange schedule job with gocron lib

---

internal/pkg/infrastructure/postgres/event.go

fix: Missing value in core data's readingsPersistedCounter issue

---

Makefile

fix: Revise the flag name and add detailed comments

---

internal/pkg/infrastructure/postgres/notification.go
internal/pkg/infrastructure/postgres/subscription.go

fix: fix subscriptions/notifications query with categories and labels

---

cmd/security-secretstore-setup/res/configuration.yaml

fix: Add the Database related config back to SecretStore Setup

---

Makefile

fix: Make variable usage consistent in Makefile

---

Makefile
README.md
go.mod
go.sum

related to https://github.com/edgexfoundry/go-mod-bootstrap/pull/795
To allow to build services without openziti, add new targte build-noziti and docker-noziti into Makefile. Also revise README.md to include such information.

feat: Add new build-noziti and docker-noziti targets into Makefile

---

internal/core/metadata/application/device.go

fix: Revise response status code of create device API

---

internal/support/scheduler/infrastructure/manager.go

fixes #5048
Fix the out-of-sync issue between the scheduler manager and the database.

fix: Fix the ScheduleJob out-of-sync issue

---

internal/pkg/db/postgres/migration.go

relates to https://github.com/edgexfoundry/edgex-go/issues/5072
fixes typo in comment

feat: fix comment typo

---

internal/pkg/infrastructure/postgres/kv.go

Closes #5081. Modify Get Keeper key query condition.

fix: Modify Get Keeper key query condition

---

go.mod
go.sum
internal/core/data/embed/sql/idempotent/01-tables.sql
internal/pkg/infrastructure/postgres/cache/deviceinfo.go
internal/pkg/infrastructure/postgres/client.go
internal/pkg/infrastructure/postgres/consts.go
internal/pkg/infrastructure/postgres/deviceinfo.go
internal/pkg/infrastructure/postgres/event.go
internal/pkg/infrastructure/postgres/models/deviceinfo.go
internal/pkg/infrastructure/postgres/reading.go
internal/pkg/infrastructure/postgres/sql.go
openapi/core-data.yaml

Optimize Postgres Event Reading schema to reduce disk usage.
Closes #5088 
- Run core services and device-virtual
- Test the event and reading APIs

feat: Optimize Postgres Event Reading schema

---

go.mod
go.sum

build: update to bootstrap 4.0.2

---

.gitignore
.golangci.yml
internal/pkg/utils/restaddress.go

build: pick changes from odessa

---

internal/core/data/embed/consts.go
internal/core/data/embed/schema.go
internal/core/keeper/embed/consts.go
internal/core/keeper/embed/schema.go
internal/core/metadata/embed/consts.go
internal/core/metadata/embed/schema.go
internal/pkg/infrastructure/postgres/consts.go
internal/security/proxyauth/embed/consts.go
internal/security/proxyauth/embed/schema.go
internal/support/notifications/embed/consts.go
internal/support/notifications/embed/schema.go
internal/support/scheduler/embed/consts.go
internal/support/scheduler/embed/schema.go

fixes https://github.com/edgexfoundry/edgex-go/issues/5117
The variable for schema name is defined in multiple places. For example, core_data schema name is defined in https://github.com/edgexfoundry/edgex-go/blob/v4.0.1/internal/pkg/infrastructure/postgres/consts.go#L10 and https://github.com/edgexfoundry/edgex-go/blob/v4.0.1/internal/core/data/embed/schema.go#L10 
This is not ideal when future release needs to update schema name.
This commit refactor the code to use single constant variable for schema name.

refactor: Refactor the code to use single variable for schema name

---

openapi/core-data.yaml
openapi/core-metadata.yaml

Update CoreData API doc and fix format

docs: Update CoreData API doc

---

openapi/core-metadata.yaml

fix: Allow any value by setting additionalProperties: true

---

openapi/core-metadata.yaml

fix: Add missing properties in UpdateDeviceService schema

---

openapi/core-metadata.yaml

- **Fixed schema definition for discoveredDevice**
The original schema incorrectly used `items` under `type: object`, which is only valid for `arrays` according to [OpenAPI spec](https://swagger.io/docs/specification/v3_0/data-models/data-types/?sbsearch=Items#arrays).
Replaced with `allOf` to properly reference the `DiscoveredDevice` schema.
- **Corrected `ProvisionWatchersResponse` and `MultiProvisionWatchersResponse` property name to camelCase**
Confirmed that both `/provisionwatcher/all` and `/provisionwatcher/name/{name}` endpoints return responses with camelCase property names.
Please check if …

docs: Correct schema definition for discoveredDevice

---

openapi/core-keeper.yaml

close #5167 
also remove the metrics API

docs: correct Core Keeper api docs

---

openapi/core-command.yaml

docs: Add missing ObjectReading in Event Readings schema

---

openapi/core-command.yaml

docs: Add missing jsonObject param in GET /device/name/{name}/{command}

---

openapi/core-data.yaml

docs: Correct Readings API schema in document

---

internal/pkg/infrastructure/postgres/device.go
internal/pkg/infrastructure/redis/device.go
internal/security/config/command/proxy/shared/proxyuser.go

1. [go:S117](https://sonarcloud.io/project/issues?impactSeverities=LOW&issueStatuses=OPEN%2CCONFIRMED&id=edgexfoundry_edgex-go&open=AZWEAKgfrhD0GhEEBzJP)
2. [go:S1186](https://sonarcloud.io/project/issues?impactSeverities=HIGH&issueStatuses=OPEN%2CCONFIRMED&id=edgexfoundry_edgex-go&open=AYa3dC_GfmgkCqI0zOLw)

fix: Fix two SonarQube scan failures

---

internal/pkg/utils/crypto/aes.go
internal/pkg/utils/crypto/aes_test.go
internal/security/bootstrapper/helper/postgres_script.go
internal/security/bootstrapper/helper/postgres_script_test.go
internal/security/proxyauth/cryptor.go
internal/security/proxyauth/main.go

fix: #5229 
1. Using the original proxy-auth, add a new key. Then switch to the proxy-auth from this PR and verify that the key information can still be read correctly.
2. Using the proxy-auth from this PR, verify that key write and read operations work properly.

feat: Support secure AES key generation and AES-GCM with CBC fallback

---

openapi/core-data.yaml

Relates to #5255. Modify aggregateFunc query param in Core Data API doc.

fix: Modify aggregateFunc query param in Core Data API doc
