internal/pkg/v2/infrastructure/redis/event.go, internal/pkg/v2/infrastructure/redis/reading.go
The V2 reading id didn't store correctly. Make them store the reading id
with collection prefix in Redis.
=> fix(data): correct the id when storing V2 event

go.mod, internal/core/metadata/v2/controller/http/deviceprofile.go, internal/core/metadata/v2/controller/http/deviceprofile_test.go, internal/core/metadata/v2/io/deviceprofile.go, internal/core/metadata/v2/router.go, internal/pkg/v2/infrastructure/redis/device_profile.go
Fix #2763
Issue Number: #2736
Implement Core Metadata PUT /deviceprofile V2 API according to the API doc
This PR works with go-mod-contracts's PR https://github.com/edgexfoundry/go-mod-core-contracts/issues/326
=> feat(metadata): Implement Metadata PUT /deviceprofile V2 API

go.mod, internal/core/data/init.go
Can not use Redis Streams MesssageBus in secure mode due to lack of password on connection.
Now the DB credentials are used for the Redis Streams MessageBus connection enabling it to work in secure mode.
no
=> fix: Use DB credentials for Redis Streams MesssageBus connection

internal/core/metadata/v2/application/deviceservice.go, internal/core/metadata/v2/controller/http/deviceservice.go, internal/core/metadata/v2/controller/http/deviceservice_test.go, internal/core/metadata/v2/infrastructure/interfaces/db.go, internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go, internal/core/metadata/v2/router.go, internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/device_service.go
Fix #2775
#2775
Implement Core Metadata API for deleting deviceService by name and Id according to the V2 API doc
=> feat(metadata): Implement Metadata delete deviceService V2 API

openapi/v2/core-data.yaml, openapi/v2/core-metadata.yaml
Fix https://github.com/edgexfoundry/edgex-go/issues/2784
core-data: MultiEventsResponse, MultiReadingsResponse
core-metadata: MultiDevicesResponse, MultiDeviceProfilesResponse, MultiDeviceServicesResponse
#2784 
1. Update `MultiReadingsResponse` examples in core-data V2 Swagger file 
2. Change `SimpleReadingResponse` schema name to `MultiSimpleReadingsResponse`
3. Add `MultiDevicesResponse`, `MultiDeviceProfilesResponse` and `MultiDeviceServicesResponsschemas` to core-metadata V2 …
=> docs(all): Add multiple responses schemas to V2 Swagger files

internal/core/metadata/v2/application/deviceservice.go, internal/core/metadata/v2/controller/http/deviceprofile_test.go, internal/core/metadata/v2/controller/http/deviceservice.go, internal/pkg/v2/infrastructure/redis/dbcommands.go, internal/pkg/v2/infrastructure/redis/device_service.go, internal/pkg/v2/infrastructure/redis/queries.go, internal/pkg/v2/utils/http.go, openapi/v2/core-command.yaml, openapi/v2/core-data.yaml, openapi/v2/core-metadata.yaml, openapi/v2/support-logging.yaml, openapi/v2/support-notifications.yaml, openapi/v2/support-scheduler.yaml
#2803 
Based on the original implementation of GET /deviceservice/all, when client
specify an out-of-range offset, query with labels will return out of range
errors(http status=416), but query without labels will return empty
array(http status=200).
This commit make query without labels to also return out of range errors
(http status=416) under such case.
Moreover, Swagger spec indicates that the maximum for limit query string
is 50 records, which is too arbitrary and not flexible enough for clients
to decide their own limit. …
=> fix(metadata): V2 GET /deviceservice/all returns inconsistent response when specifying labels or not

.github/PULL_REQUEST_TEMPLATE.md
This PR fixes the link to Committing.md and adds yes/no checkboxes for the new imports section of the template.
**NA**
**NA**
**NA**
NA
=> fix: PR template broken link, and add yes/no checkboxes for new imports

snap/snapcraft.yaml
Updated the source-tag to 6.0.8 to align with docker-compose redis version.
Using an older version of redis.
Updated the source-tag to 6.0.8 - newer stable release of redis.
Build snap from source.
Ran blackbox tests and all tests passed. Note, you will need to install the latest/edge version of app-service-configurable before running the test suite.
=> fix(snap): update redis to 6.0.8

snap/local/patches/0001-optimize-build-for-pipeline-CI-check.patch
This commit adds a patch which can be applied to
edgex-go's snapcraft.yaml to optimize the build
for the Jenkins pipeline used to build EdgeX. This patch
strips all of the non-edgex go parts from the build,
and when used in conjunction with 'snapcraft prime',
reduces the build time by more than 50%.
NA
NA
NA
Are there any new imports or modules? No
Are …
=> fix(snap): optimize build for jenkins pipeline

internal/core/metadata/v2/application/device.go, internal/core/metadata/v2/controller/http/device.go, internal/core/metadata/v2/controller/http/device_test.go, internal/core/metadata/v2/controller/http/deviceprofile.go, internal/core/metadata/v2/controller/http/deviceprofile_test.go, internal/core/metadata/v2/controller/http/deviceservice.go, internal/core/metadata/v2/controller/http/deviceservice_test.go, internal/core/metadata/v2/infrastructure/interfaces/db.go, internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go, internal/core/metadata/v2/router.go, internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/device.go
Fix #2826
Implement the V2 API for querying all devices by deviceService name, Redis DB should add v2:device:service:name:{serviceName} as new key for searching.
This PR should add deletion code for new Redis key after the [DELETE device API](https://github.com/edgexfoundry/edgex-go/pull/2813) PR merged
=> feat(metadata): Implement GET /device/service/name/{name} V2 API

internal/core/data/v2/application/event.go, internal/core/data/v2/controller/http/event.go, internal/core/data/v2/controller/http/event_test.go, internal/core/data/v2/infrastructure/interfaces/db.go, internal/core/data/v2/infrastructure/interfaces/mocks/DBClient.go, internal/core/data/v2/router.go, internal/core/metadata/v2/application/device.go, internal/core/metadata/v2/controller/http/device.go, internal/core/metadata/v2/controller/http/device_test.go, internal/core/metadata/v2/infrastructure/interfaces/db.go, internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go, internal/core/metadata/v2/router.go, internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/device.go, internal/pkg/v2/infrastructure/redis/event.go, internal/pkg/v2/infrastructure/redis/reading.go, openapi/v2/core-data.yaml
Fix #2842
Implement CoreData GET /event/deice/name/{name} API to query events by offset, limit and device name.
=> feat(data): Implement GET /event/device/name/{name} V2 API

snap/hooks/install, snap/local/runtime-helpers/bin/kong-daemon.sh, snap/local/runtime-helpers/bin/kong-launch.sh, snap/local/runtime-helpers/bin/perl5lib-launch.sh, snap/snapcraft.yaml
NA
NA
NA
Are there any specific instructions or things that should be known prior to reviewing? No
This PR updates the edgexfoundry snap to use the kong debian packages published on bintray vs. building lua, luarocks, kong, and openresty as individual parts (some from source, some downloaded tarballs).
Two other minor changes are included in the PR:
* filter out man pages included in the snap from the …
=> fix(snap): update to use kong deb from bintray

internal/core/metadata/v2/application/device.go, internal/core/metadata/v2/controller/http/device_test.go
Fix #2860
The device PATCH V2 API doesn't check the service and profile whether is exists.
If the serviceName or profileName doesn't exist in the DB, device PATCH V2 API should return 404 in the baseResponse
=>  fix(metadata): device PATCH V2 API should check service and profile

snap/snapcraft.yaml
The Kong Debian package has a symbolic link to an external path, which the review tools in the snap store do not allow. The openresty symlink to /usr/local/openresty/nginx/sbin/nginx needs therefore to be changed to ../nginx/sbin/nginx
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>
NA
NA
NA
No
=> fix(snap): remove external symlink to openresty

internal/core/data/v2/controller/http/event.go, internal/core/metadata/v2/controller/http/device.go, internal/core/metadata/v2/controller/http/deviceprofile.go, internal/core/metadata/v2/controller/http/deviceservice.go
Fix #2870
Golang build failed with 32bits ARCH
Since 32bits ARCH only support 2,147,483,647 as the maximum positive signed integer, so use math.MaxInt32 instead of the math.MaxUint32.
=> fix(metadata): fix V2 API int overflow error on 32bit ARM build

internal/core/metadata/operators/device_service/update.go, internal/core/metadata/operators/device_service/update_test.go, internal/core/metadata/rest_deviceservice.go, internal/core/metadata/rest_deviceservice_test.go, internal/core/metadata/router.go
Fix #2880 
Add service callback for deviceService AdminState Update API
=> feat(metadata): Add service callback for deviceService AdminState Update API

internal/core/data/v2/application/event.go, internal/core/data/v2/application/event_test.go, internal/core/data/v2/controller/http/event.go, internal/core/data/v2/controller/http/event_test.go, internal/core/data/v2/infrastructure/interfaces/db.go, internal/core/data/v2/infrastructure/interfaces/mocks/DBClient.go, internal/core/data/v2/router.go, internal/pkg/v2/infrastructure/redis/event.go, openapi/v2/core-data.yaml
#2837
Implement DELETE /event/device/name/{name} for V2 API. The current V2 API doc still lists DELETE /event/device/{deviceId}; however, as https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/v2/models/event.go#L14 will be updated to DeviceName instead of DeviceId, the V2 API spec shall be updated to reflect this change.
=> feat(data): Implement DELETE /event/device/name/{name} V2 API

.gitignore, cmd/security-file-token-provider/res/token-config.json, internal/security/secretstore/init.go
Fixes #2538
BREAKING CHANGE.  Removes support for monodb in security initialization.
=> feat: Remove security services initialization for mongodb

internal/core/metadata/operators/device_service/update.go
Fix #2991
Since the http.Client fail to send the request and the response body is nil, if we try to close the response body, it will cause invalid address or nil pointer error.
To fix it, just finish the function call when error occurs.
=> fix: Fix nil pointer error when update the unreachable DS adminState

go.mod, internal/core/data/v2/application/event_test.go, internal/core/data/v2/controller/http/const_test.go, internal/core/data/v2/controller/http/event.go, internal/core/data/v2/controller/http/event_test.go, internal/pkg/v2/infrastructure/redis/reading.go, openapi/v2/core-data.yaml
fix #2903 
Per decision made in Ireland planning meeting, Reading DTO/Model of V2 API shall be updated with following changes:
1. change field Name to ResourceName
2. add new field ProfileName
A corresponding PR was merged at edgexfoundry/go-mod-core-contracts#374
This commit revises current V2 API of coredata correspondingly to reflect above changes, and also updates openapi doc.
=> feat(data): Update corresponding V2 API per the recent changes from Reading DTO/Model

internal/core/data/v2/application/reading.go, internal/core/data/v2/controller/http/event.go, internal/core/data/v2/controller/http/reading.go, internal/core/data/v2/controller/http/reading_test.go, internal/core/data/v2/infrastructure/interfaces/db.go, internal/core/data/v2/infrastructure/interfaces/mocks/DBClient.go, internal/core/data/v2/router.go, internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/event.go, internal/pkg/v2/infrastructure/redis/queries.go, openapi/v2/core-data.yaml
fix #2904 
Per https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/default/get_reading_count, implement GET /reading/count V2 API.
This commit also refactor GET /event/count and GET /event/count/device/{deviceName} to reduce duplicate codes.
This commit needs to use github.com/edgexfoundry/go-mod-core-contracts v0.1.117 to build and work properly.
=> feat(data): Implement GET /reading/count V2 API

internal/core/metadata/v2/application/deviceprofile.go, internal/core/metadata/v2/controller/http/deviceprofile.go, internal/core/metadata/v2/controller/http/deviceprofile_test.go, internal/core/metadata/v2/infrastructure/interfaces/db.go, internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go, internal/core/metadata/v2/router.go, internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/device_profile.go
Fix #2915
Implement GET /deviceprofile/manufacturer/{manufacturer} V2 API according to the doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.x#/default/get_deviceprofile_manufacturer__manufacturer_
=> feat(metadata): Implement GET device profiles by manufacturer V2 API

cmd/secrets-config/main.go, cmd/security-proxy-setup/res/configuration.toml
TAF framework is using deprecated egdgex-proxy tool
to create proxy users and is senitive to logging level
in order to determine if user management is successful.
This fix reverts the log level change
as temporary fix for #2922
Permanent fix is that TAF needs to use new utility.
#2922
=> fix: Revert log level change for commit ff93af4

internal/core/metadata/v2/application/device.go, internal/core/metadata/v2/controller/http/device.go, internal/core/metadata/v2/controller/http/device_test.go, internal/core/metadata/v2/infrastructure/interfaces/db.go, internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go, internal/core/metadata/v2/router.go, internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/device.go
Fix #2931
Implement GET  /device/profile/name/{name} V2 API according to the https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-metadata/2.x#/default/get_device_profile_name__name_
=> feat(meta): Implement GET /device/profile/name/{name} V2 API

cmd/security-secrets-setup/start_vault.sh
Change the Vault backend storage configuration from Consul to filesystem so that we can remove Vault dependency on Consul.
The docker-compose file will also need to change to remove the -consul dependency from repo developer-script.
The current edgex-consul healthy check on Vault also need to be remove as that check becomes superfluous.
Closes: #2882
Currently the Vault's backend storage is `Consul` and thus has the dependency on `Consul`. 
To break and remove the direct dependency on …
=> feat(security): Remove Vault dependency on Consul by using file backend

internal/core/data/v2/application/event.go, internal/core/data/v2/application/event_test.go, internal/core/data/v2/controller/http/event.go, internal/core/data/v2/controller/http/event_test.go, internal/core/data/v2/infrastructure/interfaces/db.go, internal/core/data/v2/infrastructure/interfaces/mocks/DBClient.go, internal/core/data/v2/router.go, internal/pkg/v2/infrastructure/redis/event.go, internal/pkg/v2/utils/db.go, openapi/v2/core-data.yaml
fix #2943
Per https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/default/delete_event_age__age_,
implement DELETE /event/age/{age} V2 API.
As this API may delete hugh volume of events/readings, this API is
intentionally implemented to use async way to delete events/readings.
As a result, the return HTTP status code is updated from 200 to 202.
Corresponding API doc is also updated for such change.
=> feat(data): Implement DELETE /event/age/{age} V2 API

snap/snapcraft.yaml
Due to the recent decision to remove use of TLS on a
single device/node, it was also decided to let Kong
generate its own self-signed certificate and get rid
of the EdgeX CA altogether. A PR landed this weekend
which updated some of the default configuration values
in security-secretstore-setup's configuration.toml file
related to TLS configuration. As the snap still contained
overrides for some of these files, installation of the
snap fail when security-secretstore-setup fails to start.
This change removes the configuration overrides related
to Kong TLS configuration from snapcraft.yaml, which then
allows the snap to be installed.
- [NA] Tests for the changes have been added (for …
=> fix(snap): remove kong TLS config overrides

go.mod, internal/core/data/v2/controller/http/event.go, internal/core/data/v2/controller/http/event_test.go, internal/core/data/v2/router.go, openapi/v2/core-data.yaml
fix #2875
Original V2 API defines `GET /event/count/device/{deviceName}` to retrieve the count of events that are associated with the specified device name, and `GET /event/device/name/{name}` to retrieve events that are associated with the specified device name. This two API path should be consistent to avoid user confusion.
This PR makes following changes:
1. Change `GET /event/count/device/{deviceName}` to `GET /event/count/device/name/{name}`
2. Update core-data v2 swagger yaml file with correct paths
3. Add missing VersionResponse …
=> feat(data): Update V2 API path for consistency

internal/core/data/v2/application/event.go
MessageEnvelope doesn't contain the V2 DTO marshaled as JSON and Content Type not set when CoreData V2 Add Event publishes to MessageBus
MessageEnvelope contains V2 DTO marshaled as JSON & Content Type is set to JSON.
=> fix: Properly publish V2 Event DTO to MessageBus as JSON

go.mod, internal/core/metadata/operators/device/notify_test.go, internal/security/config/main.go
core-contract and bootstrap modules have been update to:
- Remote and file logging have been removed
- Factory method signature has changed.
Using latest core-contract and bootstrap
Update single call to Logging Client factory method
=> refactor: Use latest bootstrap for logging client changes

internal/core/data/v2/application/event_test.go, internal/core/data/v2/application/reading.go, internal/core/data/v2/application/reading_test.go, internal/core/data/v2/controller/http/reading.go, internal/core/data/v2/controller/http/reading_test.go, internal/core/data/v2/infrastructure/interfaces/db.go, internal/core/data/v2/infrastructure/interfaces/mocks/DBClient.go, internal/core/data/v2/router.go, internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/event.go, internal/pkg/v2/infrastructure/redis/queries.go, internal/pkg/v2/infrastructure/redis/reading.go, openapi/v2/core-data.yaml
fix #2963 
Per https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/default/get_reading_start__start__end__end_, implement GET /reading/start/{start}/end/{end} V2 API
Also update the swagger yaml file to have ReadingsByTimeRange and EventsByTimeRange to reply http 416 RangeNotSatisfiable when offset is greater than the total count of entries satisfied with time range in the DB.
=> feat(data): Implement GET /reading/start/{start}/end/{end} V2 API

internal/core/data/v2/application/event_test.go, internal/core/data/v2/application/reading.go, internal/core/data/v2/application/reading_test.go, internal/core/data/v2/controller/http/reading.go, internal/core/data/v2/controller/http/reading_test.go, internal/core/data/v2/infrastructure/interfaces/db.go, internal/core/data/v2/infrastructure/interfaces/mocks/DBClient.go, internal/core/data/v2/router.go, internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/reading.go, openapi/v2/core-data.yaml
fix #2967 
Per https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/default/get_reading_resourceName__resourceName_, implement GET /reading/resourcename/{resourcename} V2 API.
Also update swagger yaml file to add 416 response when query range out of bound.
=> feat(data): implement GET /reading/resourcename/{resourcename} V2 API

internal/core/data/v2/application/event.go, internal/core/data/v2/application/event_test.go, internal/core/data/v2/application/reading.go, internal/core/data/v2/application/reading_test.go, internal/core/data/v2/controller/http/event.go, internal/core/data/v2/controller/http/event_test.go, internal/core/data/v2/controller/http/reading.go, internal/core/data/v2/controller/http/reading_test.go, internal/core/data/v2/infrastructure/interfaces/db.go, internal/core/data/v2/infrastructure/interfaces/mocks/DBClient.go, internal/core/data/v2/router.go, internal/pkg/v2/infrastructure/redis/client.go
fix #2961 
Per https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/2.x#/default/get_reading_count_device_name__name_, implement GET /reading/count/device/name/{name} V2 API.
Also change method name from EventCountByDevice to
EventCountByDeviceName for consistency.
=> feat(data): Implement GET /reading/count/device/name/{name} V2 API

cmd/core-command/Dockerfile, cmd/core-metadata/Dockerfile, cmd/security-secretstore-setup/Dockerfile, cmd/security-secretstore-setup/entrypoint.sh, cmd/support-notifications/Dockerfile, cmd/support-scheduler/Dockerfile
Docker containers run as root user.
#2983 
Modified the dockerfiles of various services to create/run as
"edgex_user:edgex_group".
Modified the entrypoint script of security-secretstore-setup to set
the appropriate ownership of the /tmp/edgex/secrets directory that's
mounted to retrieve secrets in various services used throughout.
Removed a security concern from the entrypoint script of
security-secretstore-setup that allowed root level CLI execution access
to anyone that could add parameters via CMD in the dockerfile.
Are there any …
=> feat(security): secure containers run as non-root

cmd/security-secretstore-setup/entrypoint.sh
Since the developer scripts update for non-root user has not yet merged yet the EDGEX_USER and EDGEX_GROUP are never set causing Secret Store Setup to fail before signaling done. This causes Proxy Setup to never run which results in no Kong proxies configured. 
This fix sets the EDGEX_USER and EDGEX_GROUP to a default value when they are not set.
=> fix: Add defaults for User and Group to Secret Store Setup

internal/core/metadata/v2/application/provisionwatcher.go, internal/core/metadata/v2/controller/http/provisionwatcher.go, internal/core/metadata/v2/controller/http/provisionwatcher_test.go, internal/core/metadata/v2/infrastructure/interfaces/db.go, internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go, internal/core/metadata/v2/router.go, internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/provisionwatcher.go, openapi/v2/core-metadata.yaml
fix #3005 
Implement GET API of following routes:
- /provisionwatcher/name/{name}
- /provisionwatcher/all
- /provisionwatcher/service/name/{name}
- /provisionwatcher/profile/name/{name}
Also updates swagger file:
- fix indention error
- remove delete by id route
- add GET PWs by profile name route
=> feat(meta): Implement ProvisionWatcher v2 GET API

snap/hooks/configure, snap/hooks/install, snap/local/patches/0001-optimize-build-for-pipeline-CI-check.patch, snap/snapcraft.yaml
This PR updates the command lines of all the core-*, support-*, and sma services in the snap to use the preferred command-line options for the config provide and registry, as some of these services were still using the legacy command-line options. For most the change was just replacing `--registry` with `-cp -r`.
Also note, this PR also includes three unrelated snaps fixes:
*  cleanup of inconsistent whitespace usage snap hooks
*  address shellcheck warnings in the snap hooks
*  bump the snap epoch to 5 for the Ireland release
**If your build fails** due to your commit message not passing the …
=> fix(snap): cmdline args

cmd/core-data/res/configuration.toml, go.mod, internal/core/data/config/config.go, internal/core/data/v2/application/event.go, internal/core/data/v2/application/event_test.go, internal/core/data/v2/controller/http/event.go, internal/core/data/v2/controller/http/event_test.go, internal/core/data/v2/io/event.go, internal/core/data/v2/router.go, openapi/v2/core-data.yaml
fix #2934 
fix #2995 
Per https://github.com/edgexfoundry/edgex-docs/blob/master/docs_src/design/adr/013-Device-Service-Events-Message-Bus.md, Core data shall publish Events to <TopicPrefix>/<DeviceProfile>/<DeviceName>.
This PR made following changes:
1. Add new property PublishTopicPrefix into MessageQueue configuration.
2. Update Core Data configuration.toml to add PublishTopicPrefix set it to:
PublishTopicPrefix = 'edgex/events' # /<device-profile-name>/<device-name> will be added to this Publish Topic prefix
3. Change V2 Add Event …
=> feat(data): Make Core Data publish events to <TopicPrefix>/<DeviceProfile>/<DeviceName>

snap/local/patches/0001-optimize-build-for-pipeline-CI-check.patch, snap/snapcraft.yaml
This PR fixes an issue with Redis snapshots in the snap. It also updates the snap to the latest 6.0.9 release of Redis.
This PR also contains one unrelated minor change to the device-virtual command-line, which fixes a regression introduced recently when the service command line options in the snap were all updated to use `--cp` and `-r` for the config provider and registry options.
Redis …
=> fix(snap): fix redis persistence/snapshots

internal/core/metadata/v2/application/deviceservice.go, internal/core/metadata/v2/controller/http/deviceservice_test.go
fix 2989
Delete Device Service API doesn't check the associated Device existence.
Delete Device Service API should check the associated Device existence.
If there is any associated Device exists, the Device Service deletion should return error.
=> fix(meta): Delete DS API should check the associated Device existence

internal/core/data/v2/application/event.go
ApiVersion is not set in Event/Readings when published to MessageBus since it is not required to be set in the Add Event Request.
It needs to be set since the App Services use it to determine the version of object received and also needs to be included when the Event/Readings are exported.
ApiVersion is now set in Event/Readings when published to MessageBus
=> fix(core-data): Set ApiVersion on Event/Reading DTOs prior to publishing to MessageBus

internal/core/metadata/v2/application/deviceservice.go, internal/core/metadata/v2/controller/http/deviceservice_test.go, internal/core/metadata/v2/infrastructure/interfaces/db.go, internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go, internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/device_service.go
Refactor update operation to DBClient because deleting and adding to update a record only used for RedisDB.
=> refactor(meta): Refactor device service update operation to DBClient

cmd/security-bootstrapper/Dockerfile
This PR add the ability to build ARM64 version of dockerize binary installation.
Fixes: #3081
currently dockerize only works for amd64 arch. box
Will add support for ARM64 
- [x ] No
- [x ] No
=> feat(security): add build code in Dockerfile for ARM64 of dockerize executable

cmd/security-bootstrapper/Dockerfile
Add CGO_ENABLED=0 flag to make dockerize build statically linked
- [X ] Tests for the changes have been added (for bug fixes / features)
- [ X] No
- [ X] No
=> feat(security): make the built fully statically linked for dockerize

cmd/security-bootstrapper/Dockerfile, cmd/security-bootstrapper/entrypoint-scripts/consul_wait_install.sh, cmd/security-bootstrapper/entrypoint-scripts/kong_wait_install.sh, cmd/security-bootstrapper/entrypoint-scripts/postgres_wait_install.sh, cmd/security-bootstrapper/entrypoint-scripts/proxy_setup_wait_install.sh, cmd/security-bootstrapper/entrypoint-scripts/ready_to_run_wait_install.sh, cmd/security-bootstrapper/entrypoint-scripts/redis_wait_install.sh, cmd/security-bootstrapper/entrypoint-scripts/vault_wait_install.sh, cmd/security-bootstrapper/res/configuration.toml, internal/security/bootstrapper/command/cmd_dispatcher.go, internal/security/bootstrapper/command/cmd_dispatcher_test.go, internal/security/bootstrapper/command/flags_common.go, internal/security/bootstrapper/command/waitfor/command.go, internal/security/bootstrapper/command/waitfor/command_test.go, internal/security/bootstrapper/command/waitfor/uri_flags.go, internal/security/bootstrapper/config/types.go, internal/security/bootstrapper/config/waitFor.go
- New subcommand **waitFor** is added and it replaces the functionality of the former `dockerize`
- Add waitForInfo for the toml configuration (`Timeout` and `RetryInterval`)
- Building related to `dockerize` in Dockerfile is removed
Fixes: #3100
Currently we are using `dockerize` 3rd party lib to do the waiting for other services.
Replacing the `dockerize` with internal implemented `waitFor` as part of …
=> feat(security): Add waitFor subcommand for security-bootstrapper

internal/core/metadata/v2/application/notify.go, internal/core/metadata/v2/application/provisionwatcher.go, internal/core/metadata/v2/controller/http/provisionwatcher.go, internal/core/metadata/v2/controller/http/provisionwatcher_test.go
Close #3090
Add notify functions to invoke Device Service callback for DeviceService change.
=> feat(meta): Invoke Device Service callback for ProvisionWatcher change

go.mod, internal/core/metadata/v2/application/deviceprofile.go, internal/core/metadata/v2/application/deviceservice.go, internal/core/metadata/v2/controller/http/deviceprofile_test.go, internal/core/metadata/v2/controller/http/deviceservice_test.go
Fix #3087
Delete API return 400 when associated object exist
DeviceProfile and DeviceService Delete API should return 409 instead of the 400 when associated object exists
=> fix(meta): Delete API return 409 when associated object exists

internal/support/scheduler/main.go
Support scheduler unable to access DB due to no credentials
Support scheduler now able access DB
=> fix: Support Scheduler V1 DB credentials not used due to V2 DB Handler side effect

snap/local/patches/0001-optimize-build-for-pipeline-CI-check.patch, snap/snapcraft.yaml
The edgexfoundry snap doesn't properly generate redis persistence snapshots.
Snapshots are properly generated.
This fix has already been applied to master. Also as part of this PR, the snap is also updated to use the latest maintenance release of Redis (6.0.10).
=> fix(snap): fix redis snapshots

internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/subscription.go, internal/support/notifications/v2/application/subscription.go, internal/support/notifications/v2/controller/http/subscription.go, internal/support/notifications/v2/controller/http/subscription_test.go, internal/support/notifications/v2/infrastructure/interfaces/db.go, internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go, internal/support/notifications/v2/router.go
Per https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_subscription_all, implemented GET /subscription/all V2 API.
Close #3106
=> feat(notifications): Implement GET /subscription/all V2 API

go.mod, internal/core/metadata/v2/controller/http/deviceprofile_test.go, internal/core/metadata/v2/io/deviceprofile.go, openapi/v2/core-metadata.yaml
Close #3137
Rename PropertyValue's Type field to ValueType and remove the redundant Validate invoke
=> refactor(meta): Rename PropertyValue's Type field to ValueType

internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/subscription.go, internal/support/notifications/v2/application/subscription.go, internal/support/notifications/v2/controller/http/subscription.go, internal/support/notifications/v2/controller/http/subscription_test.go, internal/support/notifications/v2/infrastructure/interfaces/db.go, internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go, internal/support/notifications/v2/router.go
Per [https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_subscription_receiver__receiver_](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_subscription_receiver__receiver_), implemented GET /subscription/receiver/{receiver} V2 API.
Close #3129
=> feat(notifications): Implement GET /subscription/receiver/{receiver} V2 API

internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/subscription.go, internal/support/notifications/v2/application/subscription.go, internal/support/notifications/v2/controller/http/subscription.go, internal/support/notifications/v2/controller/http/subscription_test.go, internal/support/notifications/v2/infrastructure/interfaces/db.go, internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go, internal/support/notifications/v2/router.go
Per https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_subscription_name__name_, implemented GET /subscription/name{name} V2 API.
Close #3135
=> feat(notifications): Implement GET /subscription/name{name} V2 API

internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/subscription.go, internal/support/notifications/v2/application/subscription.go, internal/support/notifications/v2/controller/http/subscription.go, internal/support/notifications/v2/controller/http/subscription_test.go, internal/support/notifications/v2/infrastructure/interfaces/db.go, internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go, internal/support/notifications/v2/router.go
Per [https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/delete_subscription_name__name_](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/delete_subscription_name__name_), implemented DELETE /subscription/name/{name} V2 API.
Close #3140
Putting this PR on hold/draft until after PR #3139 is merged.
=> feat(notifications): Implement DELETE /subscription/name/{name} V2 API

internal/security/bootstrapper/helper/redis_conf.go, internal/security/bootstrapper/helper/redis_config_test.go, internal/security/bootstrapper/redis/Developer-notes.md, internal/security/bootstrapper/redis/configure.go, internal/security/bootstrapper/redis/handlers/handlers.go
- Separate out ACL rule config into a different config file
- Use hashed password in the ACL config file
- Remove requirepass since it is using hashed pwd now
Fixes: #3161
- [x ] Docs have been added / updated (for bug fixes / features)
Currently clear text pwd from Vault can be observed in `redis.conf` file and acl rules are also in the same config file.
Hashed pwd in config file and ACL rule config in a separate …
=> feat(security): Make separate redis ACL conf file and use hashed pwd in config

internal/core/metadata/v2/application/notify.go
apiVersion is now a required field for every request DTOs, use the
factory methods in core-contracts to avoid missing field which leads
to decode(request) failed.
=> fix(meta): use factory methods on request DTOs

internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/client_test.go, internal/pkg/v2/infrastructure/redis/interval.go, internal/support/scheduler/v2/application/interval.go, internal/support/scheduler/v2/controller/http/interval.go, internal/support/scheduler/v2/controller/http/interval_test.go, internal/support/scheduler/v2/infrastructure/interfaces/db.go, internal/support/scheduler/v2/infrastructure/interfaces/mocks/DBClient.go, internal/support/scheduler/v2/router.go
Close #3184
Implement the V2 API according to the swagger doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-scheduler/2.x#/default/get_interval_all
=> feat(scheduler): Implement GET /interval/all V2 API

cmd/core-command/res/configuration.toml, cmd/core-data/res/configuration.toml, cmd/core-metadata/res/configuration.toml, cmd/sys-mgmt-agent/res/configuration.toml, go.mod, internal/core/command/init.go, internal/core/data/init.go, internal/core/metadata/init.go, internal/pkg/bootstrap/handlers/database/database.go, internal/pkg/v2/bootstrap/handlers/database.go, internal/security/bootstrapper/redis/handlers/handlers.go, internal/support/notifications/v2/controller/http/subscription_test.go
Close #3195 
Modify config.Clients to use service key
=> refactor: Modify config.Clients to use service key

cmd/security-secretstore-setup/res/configuration.toml, internal/security/secretstore/config/config.go, internal/security/secretstore/constants.go, internal/security/secretstore/init.go, internal/security/secretstore/secretsengine/enabler.go, internal/security/secretstore/tokencreatable/tokencreatable.go, internal/security/secretstore/tokenfilewriter/tokenfilewriter.go, internal/security/secretstore/tokenfilewriter/tokenfilewriter_test.go, internal/security/secretstore/tokenmaintenance.go
Part of Phase 1 Securing Consul stories: Create a Vault token to configure consul access
Changes in `secretstore-setup`:
- add token file writer implementation for creating and writing Vault's Consul secrets admin token
- add Consul ACL feature flag `"ENABLE_REGISTRY_ACL"`
- add configuration setting for `ConsulSecretAdminTokenPath` for specifying token file location
- refactor TokenMaintenance to share code with token file writer's implementation
Closes: #3155
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: …
=> feat(security): Create a Vault mgmt token for Consul Secrets API Operations

cmd/security-proxy-setup/res/configuration.toml, internal/security/proxy/config/config.go, internal/security/proxy/init.go, internal/security/proxy/service.go, snap/snapcraft.yaml
Empty SecretStore configuration passed to bootstrap so initialization fails when SecretStore is enabled, which is the case for Snap
Configuration now properly passed to bootstrap which allows for the SecretStore to be properly initialized
- [] Yes
=> fix: Enable proper configuration for SecretStore initialization

cmd/security-bootstrapper/Dockerfile, cmd/security-bootstrapper/consul-acl/config_consul_acl.json, cmd/security-bootstrapper/entrypoint-scripts/consul_wait_install.sh, cmd/security-bootstrapper/res/configuration.toml, cmd/security-secretstore-setup/res-file-token-provider/configuration.toml, cmd/security-secretstore-setup/res/configuration.toml, internal/security/bootstrapper/command/cmd_dispatcher.go, internal/security/bootstrapper/command/cmd_dispatcher_test.go, internal/security/bootstrapper/command/flags_common.go, internal/security/bootstrapper/command/setupacl/aclbootstrap.go, internal/security/bootstrapper/command/setupacl/command.go, internal/security/bootstrapper/command/setupacl/command_test.go, internal/security/bootstrapper/command/setupacl/stubdata_test.go, internal/security/bootstrapper/config/config.go, internal/security/bootstrapper/config/types.go, internal/security/bootstrapper/helper/helper.go, internal/security/bootstrapper/interfaces/command.go
This PR is part of Phase 1 to secure Consul.  Main feature added is to enable Consul's ACL and bootstrap ACL. The following are detailed changes:
- Add Consul's ACL configuration file with "allow" policy
- Disable Consul's DNS port
- Add ACL related configuration toml on security-bootstrapper
- Add setupRegistryACL subcommand to security-bootstrapper
- Add checking and retry logic for "non-empty" Consul leader
- Add implementation for setting up Consul's ACL, including bootstrap ACL and configure Consul secrets access for Vault
Closes: #3156
**If your build fails** due to your commit message not passing …
=> feat(security): Implementation to set up Consul ACL

cmd/security-proxy-setup/res/configuration.toml, internal/security/proxy/config/config.go, internal/security/proxy/container/config.go, internal/security/proxy/models/kongParameters.go, internal/security/proxy/service.go, internal/security/proxy/service_test.go, internal/security/proxy/testdata/configuration.toml
Proxy Setup uses repurposed ClientInfo struct for the Route configuration which has become an issue once the standards keys changed to service keys. This is because the key name is also used for the route name
Now Proxy Setup uses existing KongRoute struct that has extra name property for the route name. The Route configuration is properly named `Routes`, no longer `Clients`
- [x ] Yes
BREAKING CHANGE: Names for Route configuration has changed
=> refactor: Rework Proxy Setup to use KongRoute struct for configuration

internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/notification.go, internal/support/notifications/v2/application/notification.go, internal/support/notifications/v2/controller/http/notification.go, internal/support/notifications/v2/controller/http/notification_test.go, internal/support/notifications/v2/infrastructure/interfaces/db.go, internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go, internal/support/notifications/v2/router.go, openapi/v2/support-notifications.yaml
Per https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_notification_status__status_, implemented GET /notification/status/{status} V2 API.
Also revised the Swagger file:
- Added HTTP status code 416 as a possible response to the APIs with query strings `offset` and `limit`.
- Added example responses: 400, 404, 416, 500, AddSubscriptions, UpdateSubscriptions, AddNotifications
- For the APIs used to query multiple data, e.g. /notification/status/{status}, changed the possible response 404 to 400. …
=> feat(notifications): Implement GET /notification/status/{status} V2 API

README.md
Current path is no more available,
I am assuming it has been relocated to this new repo:
https://github.com/edgexfoundry/edgex-compose/
Signed-off-by: Philippe Coval <rzr@users.sf.net>
=> fix: Update docker file location 

internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/notification.go, internal/support/notifications/v2/application/notification.go, internal/support/notifications/v2/controller/http/notification.go, internal/support/notifications/v2/controller/http/notification_test.go, internal/support/notifications/v2/infrastructure/interfaces/db.go, internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go, internal/support/notifications/v2/router.go
Per https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_notification_start__start__end__end_, implemented GET /notification/start/{start}/end/{end} V2 API.
Close #3239
=> feat(notifications): Implement GET /notification/start/{start}/end/{end} V2 API

go.mod, internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/intervalaction.go, internal/support/scheduler/v2/application/interval.go, internal/support/scheduler/v2/application/intervalaction.go, internal/support/scheduler/v2/controller/http/const_test.go, internal/support/scheduler/v2/controller/http/intervalaction.go, internal/support/scheduler/v2/controller/http/intervalaction_test.go, internal/support/scheduler/v2/infrastructure/interfaces/db.go, internal/support/scheduler/v2/infrastructure/interfaces/mocks/DBClient.go, internal/support/scheduler/v2/io/intervalaction.go, internal/support/scheduler/v2/router.go, openapi/v2/support-scheduler.yaml
Close #3187
Implement the V2 API according to the swagger doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-scheduler/2.x#/default/post_intervalaction
=> feat(scheduler): Implement POST /intervalaction V2 API

cmd/security-proxy-setup/res/configuration.toml, internal/security/proxy/service.go
Route configuration map keys are the old random names for the services
Route configuration map keys are now the services' service keys
=> feat: Use service keys for Route configuration keys

snap/local/build-helpers/bin/go-build-helper.sh, snap/local/build-helpers/bin/minimal-snap-build.sh, snap/local/patches/0001-optimize-build-for-pipeline-CI-check.patch, snap/snapcraft.yaml
The snap build downloads prebuilt release tarballs of go 1.15.2 from Google's download site in order to build edgex-go, and the other Go-based parts in the snap.
This change updates the snap build to use the go snap instead of downloading the prebuilt go release tarballs from google's download site. This also means the snap builds are always using the latest go 1.15 stable release.
Are there any specific …
=> fix(snap): use go 1.15.x snap for builds

internal/security/bootstrapper/command/setupacl/acltokens.go, internal/security/bootstrapper/command/setupacl/acltokens_test.go, internal/security/bootstrapper/command/setupacl/command.go, internal/security/bootstrapper/command/setupacl/command_test.go
Part of Securing Consul Phase 1 stories, add new implementation and changes to `security-bootstrapper` setupRegistryACL:
- Add Create agent token logic with using global policy
- Add Agent checking logic to determine whether we should set agent token every time on agent restarting
- Add re-use created agent token logic in the case of re-start and re-set scenarios
- Add set agent token implementation
- Add re-set agent token logic in the case of re-starting and non-persistent token case if needed
Closes: #3157
**If your build fails** due to your commit message not passing the build checks, please review the …
=> feat(security): Implementation for setting up agent token

internal/pkg/correlation/middleware.go
Content-Type not being set in the Context where it is pulled from when setting the Content-Type on the MessageEnevlope.
Now Content-Type is being set in the Context for that set in the  the REST Header when request is first received.
=> fix: Added Content-Type from REST header to Context

snap/local/build-helpers/bin/minimal-snap-build.sh
The yq snap is confined and can only work in the user's home directory.
As the Jenkins pipeline builds the snap outside the homedir, yq is not
able to update the file. This PR changes the script to use the yq binary
from github.
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com>
yq fails to modify snapcraft.yaml and the minimal edgexfoundry snap build fails.
yq is able modify snapcraft.yaml and the minimal edgexfoundry snap build succeeds.
=> ci: update minimal-snap-build.sh script

snap/hooks/install, snap/local/runtime-helpers/bin/setup-consul-acl.sh, snap/local/runtime-helpers/bin/start-consul.sh, snap/snapcraft.yaml
part of securing consul phase 1 in snap build, change details:
- Add token for consul secret engine in snap
- Add env. for ACL enable: ENABLE_REGISTRY_ACL: true
- Add env. for consul secret engine admin token: SECRETSTORE_CONSULSECRETSADMINTOKENPATH
- Add logic for copying the needed configuration toml from security-bootstrapper
- Add consul-bootstrapper one-shot service for setting up Consul's ACL
- Add feature flag logic in start_consul.sh shell script
- Consul-bootstrapper one-shot service to launch using shell script
N/A
Add …
=> build(snap): Snap package build for setup consul acl

cmd/security-bootstrapper/res/configuration.toml, internal/security/bootstrapper/command/setupacl/aclpolicies.go, internal/security/bootstrapper/command/setupacl/aclpolicies_test.go, internal/security/bootstrapper/command/setupacl/aclroles.go, internal/security/bootstrapper/command/setupacl/aclroles_test.go, internal/security/bootstrapper/command/setupacl/acltokens.go, internal/security/bootstrapper/command/setupacl/acltokens_test.go, internal/security/bootstrapper/command/setupacl/command.go, internal/security/bootstrapper/command/setupacl/command_test.go, internal/security/bootstrapper/command/setupacl/stubregistryserver_test.go, internal/security/bootstrapper/config/config.go, internal/security/bootstrapper/config/types.go, internal/security/fileprovider/defaults.go, internal/security/fileprovider/defaults_test.go, internal/security/fileprovider/provider.go, internal/security/fileprovider/provider_test.go
New addition for implementing for Consul's ACL policies creation and roles for Consul tokens generated later on via `go-mod-secret`
- Add logic to check whether the ACL policy is already per-existing before creation of new policy
- Add implementation to create a new ACL policy
- Add implementation to create a role for EdgeX's services via Vault's /consul/roles/* APIs: this sets the stage for creating role-based Consul tokens used by EdgeX services
- Add logic for creating token roles based on EdgeX service keys from configuration file
- Update token-file-provider on Edgex's default policy to add the permission for calling `/consul/creds/"service-key"` endpoint
Closes: #3254, #3160
Please check if your PR fulfills the following …
=> feat(security): Implementation for adding Consul ACL policies, roles

cmd/security-bootstrapper/entrypoint-scripts/consul_wait_install.sh, cmd/security-bootstrapper/entrypoint-scripts/postgres_wait_install.sh, cmd/security-secretstore-setup/Dockerfile, cmd/security-secretstore-setup/entrypoint.sh
'listenTcp' command runs as root everywhere it is used.
'listenTcp' command now runs as non-root everywhere it is used.
=> refactor: Rework entry point scripts to run 'listenTcp' command as non-root

snap/snapcraft.yaml
Kong admin ports 8001(http) and 8444(https) were reachable on all interfaces as
the host was set to 0.0.0.0. Changed to localhost to restrict off-box access.
The Kong admin ports are reachable from an external client.
The Kong admin ports are restricted to localhost
=> fix(snap): secure kong admin ports

go.mod, internal/core/data/v2/application/event_test.go, internal/core/data/v2/application/reading_test.go, internal/core/data/v2/controller/http/event_test.go, internal/pkg/v2/infrastructure/redis/event.go, internal/pkg/v2/infrastructure/redis/reading.go, openapi/v2/core-data.yaml
Close #3270
In March-18-2021 Core WG meeting, we decided to remove created field from Event and Reading
=> feat(data): Remove created field from Event and Reading

internal/pkg/v2/infrastructure/redis/reading.go, internal/pkg/v2/infrastructure/redis/reading_test.go, openapi/v2/core-data.yaml
Close #3286
The Binary Reading conversion hasn't been implemented in the infrastructure layer
Use alias struct to extract ValueType and convert to specified reading
=> feat(data): Implement get Binary Reading from database

openapi/v2/core-command.yaml, openapi/v2/core-data.yaml, openapi/v2/core-metadata.yaml, openapi/v2/support-notifications.yaml, openapi/v2/support-scheduler.yaml, openapi/v2/system-agent.yaml
Close #3312
- Since the RequestId is optional and the user don't need to provide the RequestId for the REST API, so we can remove RequestId from the example of swagger doc.
- And the message can be omitted when it was empty.
=> docs: Remove RequestId from the example of swagger doc

cmd/security-bootstrapper/res/configuration.toml, internal/security/bootstrapper/command/setupacl/aclpolicies.go, internal/security/bootstrapper/command/setupacl/acltokens.go, internal/security/bootstrapper/command/setupacl/command.go, internal/security/bootstrapper/command/setupacl/command_test.go, internal/security/bootstrapper/command/setupacl/share/constant.go, internal/security/bootstrapper/command/setupacl/stubregistryserver_test.go, internal/security/bootstrapper/command/setupacl/tokencleaner/tokencleaner.go, internal/security/bootstrapper/command/setupacl/tokencleaner/tokencleaner_test.go, internal/security/bootstrapper/config/types.go, internal/security/secretstore/tokenfilewriter/tokenfilewriter.go, snap/snapcraft.yaml
changes for `security-bootstrapper` on setupRegitrsyACL
- add logic for deleting consul tokens for the 2nd time or later based on the consul-token files
- add logic for generating consul tokens with go-mod-secret's API
- add logic for re-set up the consul tokens for the 2nd time or later
- add env. override `STAGEGATE_REGISTRY_ACL_TOKENBASEDIR` for snap on consul token base directory
Closes: #3306
N/A, this is new …
=> feat(security): Implementation for generating and storing Consul tokens for EdgeX services

internal/core/metadata/v2/controller/http/deviceservice_test.go
fix by adding test error message when calling mock DbClient
Fix: #3346
unit test failed on using latest go-mod-bootstrap
Fix the broken unit test
- [x ] No
- [x ] No
=> fix: Fix unit test failure when using the latest go-mod-bootstrap v31

internal/support/scheduler/v2/application/intervalaction.go
Fix #3364
Since the intervalName is optional when updating the intervalAction, the API should check whether the intervalName is nil
=> fix(scheduler): PATCH API Check intervalName nil value

Attribution.txt, go.mod, internal/security/proxy/service_test.go
Close #3354
Upgrade the go-mod-bootstrap to v2.0.0-dev.34 and replace use of BurntSushi/toml with pelletier/go-toml
use pelletier/go-toml to be consistent across EdgexFoundry go project, also BurntSushi/toml is unmaintained.
=> refactor: Replace use of BurntSushi/toml with pelletier/go-toml

Attribution.txt, go.mod, internal/core/metadata/v2/application/deviceresource.go, internal/core/metadata/v2/controller/http/deviceresource.go, internal/core/metadata/v2/controller/http/deviceresource_test.go, internal/core/metadata/v2/router.go, openapi/v2/core-metadata.yaml
Close #3229
Implement the GET method to retrieve a Resource by name from specified Profile
GET/deviceresource/profile/{profileName}/resource/{resourceName}
=> feat: Implement API to retrieve Resource by profile and resource name

cmd/support-scheduler/res/configuration.toml
Close #3383
Modify the scheduler config to use V2 API for removing the events
=> feat(scheduler): Use v2 API for default scrub event intervalAction

cmd/security-bootstrapper/consul-acl/config_consul_acl.json, internal/security/bootstrapper/command/setupacl/acltokens.go, internal/security/bootstrapper/command/setupacl/acltokens_test.go, snap/local/runtime-helpers/bin/start-consul.sh
- turn on Consul's "deny" default_policy
- use more restricted policy rules for Consul's agent token than the original global policy rules
Note: After this switch is on, Consul's GUI access like http://localhost:8500/ui
will be automatically locked with authentication required.  Any direct accesses
to Consul require a legit token.
Closes: #3256
Currently the default policy of Consul's server agent is "allow"
Switch …
=> feat(security)!: Switch Consul's default_policy to deny

internal/security/fileprovider/tokenconfig.go, internal/security/secretstore/constants.go, internal/security/secretstore/init.go, internal/security/secretstore/init_test.go
No ability to add known secrets to services which have secret store added via the ADD_SECRETSTORE_TOKENS env var.
Secret Store Setup now has ADD_KNOWN_SECRETS environment variable to specify known secrets to add to the specified services` secret stores.
=> feat(security): Add new environment variable to seed Secret Store with known secrets

cmd/core-data/res/configuration.toml
ZMQ is the default MessageBus
Redis is now the default MessageBus
BREAKING CHANGE: All service receiving Event must now be configured to use Redis as the MessageBus
=> feat: Switch to Redis as the default MessageBus

snap/snapcraft.yaml
Update to kong 2.3.x as this is required to use the new plugin template version 2.1 needed to secure the kong admin API. This change also updates the snap build to use kong's new download site to pull the debian package.
See commit message for details
No change in behavior.
Securing Kong Admin API PR: …
=> fix(snap): update to kong 2.3.3

internal/core/data/v2/application/event.go, internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/device.go, internal/pkg/v2/infrastructure/redis/device_profile.go, internal/pkg/v2/infrastructure/redis/device_service.go, internal/pkg/v2/infrastructure/redis/event.go, internal/pkg/v2/infrastructure/redis/interval.go, internal/pkg/v2/infrastructure/redis/intervalaction.go, internal/pkg/v2/infrastructure/redis/notification.go, internal/pkg/v2/infrastructure/redis/provisionwatcher.go, internal/pkg/v2/infrastructure/redis/queries.go, internal/pkg/v2/infrastructure/redis/reading.go, internal/pkg/v2/infrastructure/redis/subscription.go, internal/pkg/v2/utils/http.go, internal/pkg/v2/utils/http_test.go
Fix: #3409
- Use MaxResultCount to limit the maximum number of returned objects
- Return empty array when limit is zero
=> fix: MaxResultCount limit the maximum number of returned objects

cmd/security-bootstrapper/entrypoint-scripts/kong_wait_install.sh, cmd/security-proxy-setup/res/configuration.toml, cmd/security-secretstore-setup/Dockerfile, cmd/security-secretstore-setup/res/configuration.toml, cmd/security-secretstore-setup/res/kong-admin-config.template.yml, internal/constants.go, internal/security/bootstrapper/helper/helper.go, internal/security/config/command/proxy/adduser/command.go, internal/security/config/command/proxy/adduser/command_test.go, internal/security/config/command/proxy/deluser/command.go, internal/security/config/command/proxy/deluser/command_test.go, internal/security/config/command/proxy/oauth2/command.go, internal/security/config/command/proxy/oauth2/command_test.go, internal/security/config/command/proxy/tls/command.go, internal/security/config/command/proxy/tls/command_test.go, internal/security/proxy/config/config.go, internal/security/proxy/resource_test.go, internal/security/proxy/service.go, internal/security/proxy/service_test.go, internal/security/proxy/testdata/test-jwt, internal/security/secretstore/config/config.go, internal/security/secretstore/init.go, internal/security/secretstore/kongadminapi.go, internal/security/secretstore/kongadminapi_test.go
Kong Admin API is exposed without authentication to the world.
#2537 
Kong Admin API is secured with it's own key that security-proxy-setup uses to securely create the necessary services/routes.
There are some changes to edgex-compose that are necessary to complete this PR.
=> feat(security): Secure kong admin api

cmd/security-bootstrapper/entrypoint-scripts/consul_wait_install.sh, cmd/security-proxy-setup/res/configuration.toml, internal/security/config/command/proxy/adduser/command_test.go, internal/security/config/command/proxy/oauth2/command.go, internal/security/config/interfaces/constants.go, internal/security/proxy/config/config.go, internal/security/proxy/const.go, internal/security/proxy/resource.go, internal/security/proxy/service.go, internal/security/proxy/serviceplugin.go, internal/security/proxy/serviceplugin_test.go, snap/snapcraft.yaml
- Add implementation for enabling request transformer plugin on consul service for Kong's route through proxy-setup
- Fix unit test issues
- Add necessary starting sequence and env. for proxy-setup in snap packaging
no consul service available in Kong
add consul service/route to Kong and enable consul header through kong's request transform plugins on the added consul service.
- [x ] No
- [x ] No
Are there any specific instructions or things that should be known prior …
=> feat(security): Implement consul token header in API Gateway

go.mod, internal/system/agent/v2/application/health.go, internal/system/agent/v2/application/health_test.go, internal/system/agent/v2/controller/http/controller.go, internal/system/agent/v2/router.go, openapi/v2/system-agent.yaml
- separate controller layer and application layer
- the application layer logic is similar to v1
- update health status from boolean true(v1) to string healthy
- update HealthResponse in SwaggerDoc
```
$ curl http://localhost:48090/api/v2/health/edgex-core-data,edgex-core-metadata
{"apiVersion":"v2","statusCode":200,"health":{"edgex-core-data":"healthy","edgex-core-metadata":"healthy"}}
```
There's no mock …
=> feat(sma): implement v2 GET /health/{services} API

internal/pkg/v2/infrastructure/redis/subscription.go
Fix: #3344
fix using the wrong key to update Subscription
=> fix(notifications): fix using the wrong key to update Subscription

Makefile, cmd/core-command/Dockerfile, cmd/core-data/Dockerfile, cmd/core-metadata/Dockerfile, cmd/security-bootstrapper/Dockerfile, cmd/security-proxy-setup/Dockerfile, cmd/security-secretstore-setup/Dockerfile, cmd/support-notifications/Dockerfile, cmd/support-scheduler/Dockerfile, cmd/sys-mgmt-agent/Dockerfile, go.mod, internal/core/command/config/config.go, internal/core/data/config/config.go, internal/core/data/container/messaging.go, internal/core/data/main.go, internal/core/data/messaging/messaging.go, internal/core/data/messaging/messaging_test.go, internal/core/metadata/config/config.go, internal/security/bootstrapper/config/config.go, internal/security/bootstrapper/redis/config/config.go, internal/security/fileprovider/config/config.go, internal/security/proxy/config/config.go, internal/security/secretstore/config/config.go, internal/support/notifications/config/config.go, internal/support/scheduler/config/config.go, internal/system/agent/config/config.go
Secure MessageBus common messaging handler create ZMQ dependency for all service
Core Data has own messaging handler which avoids ZMQ dependecy for all services
- [x ] No
=> fix: Rework Secure MessageBus to remove ZMQ dependency for all services

internal/core/command/v2/application/command.go, internal/core/command/v2/application/command_test.go, openapi/v2/core-command.yaml
Close: #3434
Add a field called parameters to Core Command V2 API. For Get command, it describes the expected readings. For Set command, it describes the parameters in the payload.
=> feat(command): Add parameters field to Core Command V2 API

internal/pkg/v2/infrastructure/redis/notification.go, internal/pkg/v2/infrastructure/redis/queries.go, internal/support/notifications/v2/application/notification.go, internal/support/notifications/v2/controller/http/notification.go, internal/support/notifications/v2/controller/http/notification_test.go, internal/support/notifications/v2/infrastructure/interfaces/db.go, internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go, internal/support/notifications/v2/router.go
Close: #3455
Implement notification cleanup API
- DELETE /cleanup/age/{age}: https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/delete_cleanup_age__age_
- DELETE /cleanup: https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/delete_cleanup
=> feat(notifications): Implement notification cleanup V2 API

internal/pkg/v2/infrastructure/redis/client.go, internal/support/notifications/v2/application/transmission.go, internal/support/notifications/v2/controller/http/transmission.go, internal/support/notifications/v2/controller/http/transmission_test.go, internal/support/notifications/v2/infrastructure/interfaces/db.go, internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go, internal/support/notifications/v2/router.go
Close: #3452
Implement GET /transmission/id/{id} V2 API according to the doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_transmission_id__id_
=> feat(notifications): Implement GET /transmission/id/{id} V2 API

internal/core/command/router.go, internal/core/command/v2/router.go, internal/core/data/router.go, internal/core/data/v2/router.go, internal/core/metadata/router.go, internal/core/metadata/v2/router.go, internal/pkg/correlation/middleware.go, internal/support/notifications/router.go, internal/support/notifications/v2/router.go, internal/support/scheduler/router.go, internal/support/scheduler/v2/router.go, internal/system/agent/router.go, internal/system/agent/v2/router.go
The original LoggingMiddleware would never work because `LoggingClient` wasn't initialized.
https://github.com/edgexfoundry/edgex-go/blob/6b23ec567a86ee52455607061a4fabaca114589a/internal/pkg/correlation/middleware.go#L38-L40
`LoggingClient` is correctly passed into Middleware func as a parameter, now the trace log will correctly shown:
```
level=TRACE ts=2021-05-10T09:30:32.4995448Z app=edgex-core-metadata source=middleware.go:37 X-Correlation-ID=a635250c-d679-429f-a5af-22c41d1e9ad3 …
```
=> refactor: combine and improve http LoggingMiddleware

snap/hooks/install, snap/local/runtime-helpers/bin/kong-daemon.sh, snap/snapcraft.yaml
- Add installation of Kong's Admin plugins template yaml to enable Admin JWT, ACL plugins etc.
- Update the Kong daemon startup shell script to import the plugins into database
- Update the snapcraft yml to integrate the secure Kong's Admin API features
Closes: #3403
kong's admin APIs at 8001 are wide open without authentication and ACLs in snap
Kong's admin APIs are now protected with required JWT authentication with ACLs in snap
- [x ] No
- [x ] No
Are there any specific instructions …
=> build(snap): Enable secure Kong Admin APIs in snap build

cmd/security-bootstrapper/entrypoint-scripts/consul_wait_install.sh, internal/security/secretstore/constants.go, internal/security/secretstore/init.go, snap/local/runtime-helpers/bin/setup-consul-acl.sh, snap/local/runtime-helpers/bin/start-consul.sh, snap/snapcraft.yaml
- feature flag "ENABLE_REGISTRY_ACL" is removed from both edgex-go and snap package building
and so by default Consul will use ACL when it runs in secure mode.
Closes: #3458
Currently there is feature flag `ENABLE_REGISTRY_ACL` in the code.
feature flag removed and ACL is enabled by default when it is running in secure mode.
- [x ] No
- [x ] No
=> feat(security): Remove ENABLE_REGISTRY_ACL feature flag

internal/pkg/v2/infrastructure/redis/client.go, internal/pkg/v2/infrastructure/redis/transmission.go, internal/pkg/v2/utils/http.go, internal/support/notifications/v2/application/transmission.go, internal/support/notifications/v2/controller/http/transmission.go, internal/support/notifications/v2/controller/http/transmission_test.go, internal/support/notifications/v2/infrastructure/interfaces/db.go, internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go, internal/support/notifications/v2/router.go
Close: #3466
Implement GET /transmission/start/{start}/end/{end} V2 API according to the doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/get_transmission_start__start__end__end_
=> feat(notifications): Implement query transmission by time range V2 API

internal/pkg/v2/infrastructure/redis/notification.go, internal/support/notifications/v2/application/notification.go, internal/support/notifications/v2/controller/http/notification.go, internal/support/notifications/v2/controller/http/notification_test.go, internal/support/notifications/v2/infrastructure/interfaces/db.go, internal/support/notifications/v2/infrastructure/interfaces/mocks/DBClient.go, internal/support/notifications/v2/router.go
Close: #3469
Implement DELETE /notifications/age/{age} V2 API according to the doc https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/support-notifications/2.x#/default/delete_notification_age__age_
=> feat(notifications): Implement DELETE /notifications/age/{age} V2 API

go.mod, internal/system/agent/init.go, internal/system/agent/v2/application/const.go, internal/system/agent/v2/application/direct/health.go, internal/system/agent/v2/application/direct/health_test.go, internal/system/agent/v2/application/direct/metrics.go, internal/system/agent/v2/application/executor/executor.go, internal/system/agent/v2/application/executor/metrics.go, internal/system/agent/v2/container/metrics.go, internal/system/agent/v2/controller/http/controller.go, internal/system/agent/v2/interfaces/metrics.go, internal/system/agent/v2/router.go, openapi/v2/system-agent.yaml
- support both `executor` and `direct-service` MetricsMechanism
- reuse Metrics interface with v2 model
- heavily leverage v1 executor code but simplify concurrent logic
response if `MetricsMechanism` is `executor`:
```
{
apiVersion: "v2",
statusCode: 200,
metrics: {
edgex-core-data: {
Success: true,
executor: "docker",
operation: "metrics",
result: {
cpuUsedPercent: 0.07,
memoryUsed: 8642363,
raw: {
block_io: "135kB / 0B",
cpu_perc: "0.07%",
mem_perc: "0.41%",
mem_usage: "8.242MiB / …
```
=> feat(sma): implement v2 GET /metrics/{services} API

openapi/v1/core-command.yaml, openapi/v1/core-data.yaml, openapi/v1/core-metadata.yaml, openapi/v1/support-notifications.yaml, openapi/v1/support-scheduler.yaml, openapi/v1/system-agent.yaml
New port assignments incorrectly applied to V1 Swagger, which got published.
Old port assignments re-applied to V1 Swagger.
=> fix: Revert port changes to V1 Swagger files

cmd/security-proxy-setup/res/configuration.toml
Ports for Device Virtual and Rules Engine in `Proxy Setup` are the old port assignments
Ports for Device Virtual and Rules Engine in `Proxy Setup` are the correct new port assignments
=> fix: Use new ports for device-virtual and rules engine proxy routes

internal/pkg/db/redis/client.go
core service is ready even if DB is still loading, this results in the bootstrap failed in device service (notice the time Redis is ready):
```
$ docker logs edgex-redis
...
1:M 25 May 2021 06:05:43.544 * DB loaded from append only file: 26.494 seconds
1:M 25 May 2021 06:05:43.544 * Ready to accept connections
$ docker logs edgex-core-metadata
...
level=INFO ts=2021-05-25T06:05:26.8633534Z app=core-metadata source=database.go:145 msg="Database connected"
level=INFO …
```
=> fix(all): add PING check after Dial to validate DB is ready

go.mod, internal/system/agent/v2/application/executor/operation.go, internal/system/agent/v2/controller/http/controller.go, internal/system/agent/v2/router.go, openapi/v2/system-agent.yaml
example request body POSTing `/api/v2/operation`:
```
[
{
"requestId": "2f6fe5e2-dd93-478c-a2ba-21642e42a5f5",
"serviceName": "edgex-core-data",
"action": "start"
},
{
"requestId": "998d70a3-7245-4735-b308-ebb9f448fb38",
"serviceName": "edgex-core-command",
"action": "start"
}
]
```
example response:
```
207 Multi-Status
[
{
"requestId": "998d70a3-7245-4735-b308-ebb9f448fb38",
"statusCode": 200
},
{
"requestId": …
```
=> feat(sma): implement v2 POST /operation API

cmd/security-proxy-setup/res/configuration.toml
Route names **not** using service key names
Route for sys-mgmt-agent missing
Route names **now** using service key names
Route for sys-mgmt-agent added
BREAKING CHANGE: API Gateway route names have changed.
=> refactor: Use service key for route names and add missing sys-mgmt-agent

Jenkinsfile
Fix #3517 
Remove 'openapi/v1' from swaggerApiFolders on Jenkinsfile
No.
=> build(all): Remove 'openapi/v1' from swaggerApiFolders in Jenkinsfile

go.mod, internal/pkg/v2/application/secret.go, internal/pkg/v2/controller/http/secret.go, internal/pkg/v2/controller/http/secret_test.go, internal/support/notifications/v2/router.go, openapi/v2/support-notifications.yaml
Close: #3333
Add secret creation API for storing EdgeX service exclusive secret to the Secret Store.
=> feat(notifications): Add secret creation API

cmd/security-secretstore-setup/res/configuration.toml, internal/security/secretstore/config/config.go, internal/security/secretstore/init.go, internal/security/secretstore/secure-messagebus.go, internal/security/secretstore/secure-messagebus_test.go
Kuiper doesn't have secure message bus credentials for Redis MessageBus
When in secure mode and message bus is `redis`, write Kuiper config file with Redis credentials.
=> feat: Configure Kuiper for secure message bus

cmd/core-data/res/configuration.toml
Core data publish and subscribe topics allows it to receive the events that it publishes
Core data publish and subscribe topics not prevent it from receiving the events that it publishes
=> fix: Change publish and subscribe topics so Core doesn't receive its published Events

cmd/security-bootstrapper/entrypoint-scripts/kuiper_wait_install.sh, internal/security/secretstore/certs.go, internal/security/secretstore/init.go, internal/security/secretstore/secure-messagebus.go
When Secret Store Setup is run it regenerates the DB password and since it is already in Vault it isn't used by Redis.
The new password is used for any new services and written to the Kuiper configuration.
password is not regenerated is it already exist in Vault.
=> fix: Don't regenerate DB passwords if already exists & tweaks for Kuiper config

internal/security/proxy/service.go
- servie key for Consul got changed from edgex-core-consul to core-consul and thus we need to change in the code, too
Fix: #3547
Currently the Consul kong route cannot be accessed (forbidden) due to mismatch service key condition.
Fixed the right service key for "core-consul"
- [x ] No
- [x ] No
=> fix: Fix the issue of mismatch Consul service key in proxy-setup

internal/core/data/v2/io/event.go, internal/core/metadata/v2/io/deviceprofile.go, internal/pkg/v2/utils/http.go, internal/pkg/v2/utils/restaddress.go, internal/security/bootstrapper/command/setupacl/aclbootstrap.go, internal/security/bootstrapper/command/setupacl/aclpolicies.go, internal/security/bootstrapper/command/setupacl/aclroles.go, internal/security/bootstrapper/command/setupacl/acltokens.go, internal/security/bootstrapper/command/setupacl/command.go, internal/security/bootstrapper/command/setupacl/command_test.go, internal/security/bootstrapper/command/setupacl/stubregistryserver_test.go, internal/security/bootstrapper/helper/helper.go, internal/security/config/command/proxy/adduser/command.go, internal/security/config/command/proxy/deluser/command.go, internal/security/config/command/proxy/jwt/command.go, internal/security/config/command/proxy/oauth2/command.go, internal/security/config/command/proxy/tls/command.go, internal/security/proxy/requestor.go, internal/security/proxy/service.go, internal/security/proxy/service_test.go, internal/security/proxy/serviceplugin.go, internal/security/proxy/serviceplugin_test.go, internal/security/secretstore/certs.go, internal/security/secretstore/kongadminapi.go, internal/security/secretstore/password.go
Close: #3334
Since the io/ioutil package has been deprecated in Go 1.16, so we should remove the dependency of this package.
https://golang.org/doc/go1.16#ioutil
=> refactor: Remove the io/ioutil usage

internal/pkg/v2/infrastructure/redis/queries.go
Close #3545
- Query with invalid offset range should return 416
- Offset is equal to notification count, it should return 200 and empty list for notifications
=> fix(notifications): Query with invalid offset range should return 416

go.mod, internal/support/scheduler/v2/application/interval.go, internal/support/scheduler/v2/application/scheduler/executor.go, internal/support/scheduler/v2/application/scheduler/executor_test.go, internal/support/scheduler/v2/application/scheduler/manager.go, internal/support/scheduler/v2/application/scheduler/queue_test.go, internal/support/scheduler/v2/controller/http/const_test.go, internal/support/scheduler/v2/controller/http/interval_test.go, openapi/v2/support-scheduler.yaml
Close: #3532
Remove runOnce feature from the scheduler service
=> refactor(scheduler): Remove runOnce feature

cmd/sys-mgmt-executor/main.go, internal/system/agent/v2/application/executor/metrics.go, internal/system/agent/v2/application/executor/operation.go, internal/system/executor/README.md, internal/system/executor/commands.go, internal/system/executor/docker.go, internal/system/executor/docker_test.go, internal/system/executor/metrics.go
Current implementation of sys-mgmt-executor does not properly return error when the docker execution failed. It returns a `system.Result` interface with the success status and errorMessage embedded in. This makes SMA always return 200 even if the execution failed.
```
curl http://localhost:58890/api/v2/system/metrics?services=edgex-core-data,invalid
207
[
{
"statusCode": 200,
"serviceName": "invalid",
"metrics": {
"Success": false,
"errorMessage": "exit status 1",
"executor": "docker",
"operation": "metrics", …
```
=> refactor(sma): refactor sys-mgmt-executor

snap/hooks/install, snap/snapcraft.yaml
This change updates the snap to use go 1.16. Changes include:
* updating build-snap to go 1.16
* pulling consul (1.9.1) from a prebuilt binary release file
* building device-virtual from the master branch
* set device-virtual app adapter to full (required to
provide LD_LIBRARY_PATH and other env vars to app,
needed to find libzmq)
* adding a new device-virtual override for the devices dir
*  updating device-virtual's profiles dir
* using stage-snaps to include app-service-config
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: …
=> fix(snap): go 1.16 update

snap/snapcraft.yaml
1) The Jenkins CI build uses the snap-minimal-build.sh script to create
a minimal version of snapcraft.yaml. As the snap version is now based
directly on the git tag, snapcraft needs to be able to run git. The
minimal snap build doesn't install git as a build package, so the build
fails. This commit fixes that.
To test, run
```
./snap/local/build-helpers/bin/minimal-snap-build.sh
snapcraft prime --use-lxd
```
2) Also, if there are no git tags present, then the version is now set to
0.0.0, instead of the build failing.
To test, run
```
git clone git@github.com:siggiskulason/edgex-go.git --no-tags
cd edgex-go
git checkout fix-snap-minimal-build
snapcraft --use-lxd
```
Signed-off-by: Siggi Skulason <siggi.skulason@canonical.com> …
=> build(snap): fix CI snap-minimal-build issue

snap/local/runtime-helpers/bin/kong-stop.sh, snap/local/runtime-helpers/bin/start-consul.sh, snap/snapcraft.yaml
This PR includes a number of snap runtime updates:
- remove the consul `--client` start option to restrict consul to localhost
- fixes a problem with kong shutdown
- redis --> 6.2.4
- kong --> 2.4.1
- vault --> 1.7.2
- consul --> 1.9.5
=> build(snap): runtime updates

internal/security/config/command/proxy/adduser/command.go, internal/security/config/command/proxy/adduser/command_test.go, internal/security/config/command/proxy/command.go
Deprecates oauth2 proxy auth method
in favor of stronger JWT-based auth method
by removing ability for secrets-config utility
to create OAuth2 users.
security-proxy-setup accidentally broke
OAuth2 functionality by installing a global
JWT auth handler intended to secure admin API
(can't have two global auth handlers because
both auth methods must pass, which is impossible.)
Comment rather than remove code in case
it needs to be added back in Jakarta
stabilization release, otherwise will be
removed permanently in both secrets-config
and proxy-setup.
Closes #3564
**If your build fails** due to your commit message not passing the build checks, please review the guidelines here: …
=> feat(security)!: Deprecate oauth2 auth method

internal/system/agent/application/executor/executor.go, internal/system/agent/application/executor/metrics.go, internal/system/agent/application/executor/operation.go, openapi/v2/system-agent.yaml
For API that relies on executor, user needs to refer to the service by its container name:
```
curl http://localhost:58890/api/v2/system/metrics?services=edgex-core-data,edgex-core-metadata
207
...
```
`edgex-` prefix will be automatically added for default service (those defined in edgex-compose file)
So user can either refer to those services by their service name (e.g. core-data) or container name (e.g. edgex-core-data)
Are there any specific instructions or things that should be known …
=> feat(sma): add 'edgex-' prefix for executor-based API

internal/core/data/application/subscriber.go
Look for a topic with >= 4 segments instead of a fixed length of 5 to
better accomodate configurable base topics for device service
publishing.
Signed-off-by: Alex Ullrich <alexullrich@technotects.com>
Fix #3580 
Only looks for topic containing >= 4 "segments" instead of 5 exactly
=> fix(core-data): Loosen Subscriber Topic Validation

internal/support/notifications/controller/http/subscription.go, internal/support/notifications/controller/http/transmission.go
Building the core services on 32-bit ARM, I got a warning "Constant
4294967295 is bigger than 'int'", which stopped the build (my environment
may be too pedantic). This resolves it.
Signed-off-by: Corey Mutter <corey@friendlyandhelpful.com>
Did not open an issue for this, found it locally.
- [ X ] No
- [ X ] No
I don't know if this is the best fix - maybe it would be better to change the function's prototype to take unsigned int?
New to both EdgeX and …
=> fix(notifications): Remove warning from 32-bit build.

Makefile, README.md
Makefile still contains `run` & `run-docker` targets. ReadMe still refers to these targets
Makefile no longer contains `run` & `run-docker` targets. ReadMe has been update to document alternative way to run EdgeX
=> fix: Remove make run/run-docker and update README

cmd/core-metadata/res/configuration.toml, internal/core/metadata/application/notify.go
Close: #3601
The core-metadata V2 API should send a notification to support-notification after adding or updating the device entity.
=> feat: Send notification after updating device entity

cmd/support-scheduler/res/configuration.toml, internal/support/scheduler/application/interval.go, internal/support/scheduler/application/intervalaction.go, internal/support/scheduler/config/config.go, internal/support/scheduler/init.go
Close: #3642
Interval and IntervalAction should be created as a DTO, and call validate() to ensure the data is valid.
=> feat: Validate Interval and IntervalAction before loading from config

internal/security/kdf/methods.go
Automatic type selection of saltLength constant causes type checking error in numerical comparison.
Closes #3654 
Ensure that the constant is of the same numeric type as Reader.Read() method.
=> fix(security): Mismatched types int and int32

cmd/security-secretstore-setup/Dockerfile
- curl command executable is not used, so it is removed from the Docker file of security service `secretstore-setup`
Fixes: #3656
Unused `curl` binary is included in the Docker image of `secretstore-setup`
`curl` binary is removed from Docker image of `secretstore-setup`
- [x ] No
- [x ] No
=> fix(security): remove unused curl executable from secretstore-setup Dockerfile

openapi/v2/core-metadata.yaml
- fix `labels` misspelled as `lables`
- show `protocols` as an object instead of an array of objects
See issue.
#3672 
Spelling corrected and objects in examples formatted appropriately.
=> docs(meta): fix mistakes in API examples

internal/security/secretstore/secure-messagebus.go, snap/local/hooks/cmd/install/install.go, snap/snapcraft.yaml
This change updates the snap to override the message bus
configuration options of security-secretstore-setup which
are responsible for modifying the kuiper configuration to
work with the secure message bus (redis).
Kuiper is not correctly configured to use the secure message bus (redis) due to the lack of configuration overrides to properly enable.
Are there …
=> fix(snap): add kuiper message-bus config

Attribution.txt, go.mod, internal/core/metadata/controller/http/deviceprofile_test.go, internal/io/reader.go
when add some complex vaules to the attributes of deviceResources in the device profile, error happens. use gopkg.in/yaml.v3 instead of gopkg.in/yaml.v2
Fixes: #3682
Signed-off-by: wangshihui <wangshihui_1985@163.com>
=> fix(meta): device yaml marshal to Json  error

snap/snapcraft.yaml
Closes #3680
API gateway supports "intermediate" level of cipher suites.
- #3680
API gateway supports "modern" cipher suite and TLSv1.3 only.
=> feat(security): Enable modern cipher suite / TLSv1.3 only

cmd/security-proxy-setup/res/configuration.toml, internal/security/proxy/config/config.go, internal/security/proxy/service.go
Current Kong proxy does not return CORS headers to clients.
Closes #1913
New configuration has been added to allow settings of a limited number of CORS headers for the EdgeX routes.
To test, modify `cmd/security-proxy-setup/res/configuration.toml` and set `EnableCORS` to `true`.  Customize other headers as needed.  Rebuild security-proxy-setup docker container (make docker_security_proxy_setup).  Restart framework.
Test with a command like
```
curl -ki -X OPTIONS -H "Origin: …
```
=> feat(security): Feature to enable CORS headers for API gateway

internal/security/config/command/proxy/adduser/command.go, internal/security/config/command/proxy/adduser/command_test.go, internal/security/config/command/proxy/deluser/command.go, internal/security/config/command/proxy/deluser/command_test.go, internal/security/config/command/proxy/tls/command.go, internal/security/config/command/proxy/tls/command_test.go
Closes #3694
Secrets config utility contacts Kong via insecure port.
Interferes with ability to configure Kong remotely.
#3694
Secrets config utility contacts Kong via secure port.
=> fix(security): secrets-config user connect using TLS

snap/README.md, snap/local/hooks/go.mod
This commit adds configure hook support for the new security-file-token-provider `DefaultTokenTTL`
option, which can be used to increase or decrease the default TTL (one hour) assigned to new Vault tokens.
- [NA] Tests for the changes have been added (for bug fixes / features)**
** See #testing for details on how this can be tested.
It's not possible to override the security-file-token-provider's `DefaultTokenTTL` configuration option when using the edgexfoundry snap.
none
The snap configure hook now supports setting this new option.
Are …
=> feat(snap): add vault ttl config support

.golangci.yml, Makefile, internal/core/metadata/controller/http/deviceprofile_test.go, internal/pkg/db/redis/client.go, internal/security/secretstore/tokenprovider_linux_test.go, internal/support/scheduler/application/scheduler/manager.go
Closes #3565
No linting performed as part of automated testing.
#3565
This command enables "make lint" and hooks lint into the "make test" target after unit tests.
The current .golangci.yaml disables many of the default linters so that they can be enabled one-by-one-with appropriate fixes.
Requires that golangci-lint be installed in order to be effective.
If not installed, nothing happens.
=> feat(security): Enable lint hooked to make test + a few trivial fixes

cmd/security-secretstore-setup/res/kong-admin-config.template.yml, internal/security/proxy/models/kongParameters.go, internal/security/proxy/service.go, internal/security/proxy/service_test.go, internal/security/proxy/testdata/configuration.toml
This change moves the JWT auth method from a global setting
to a per-route setting.  This change allows EdgeX end-users
to add custom routes using the Kong admin API that use
alternative auth methods that are not JWT.
Closes #3638
=> fix(security): Move JWT auth method to individual routes

cmd/security-proxy-setup/res/configuration.toml, internal/security/proxy/config/config.go, internal/security/proxy/service.go
Reverts #3678 due to strategy change.  See #1913.
It was decided to move CORS functionality to the
microservice level so that it can be applied both
in the security-enabled as well as security-disabled
states.
This functionality was never implemented in Ireland,
thus implementing and reverting it in Jakarta is
not a breaking change.
@magallardo
=> feat(security): Revert CORS changes for API Gateway

Makefile
Adds the following warning message:
Addresses #3565
WARNING: go linter not installed. To install, run
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.42.1
WARNING: Linting skipped (not on x86_64 or linter not installed)
User is not warned if lint checks are skipped.
#3565
Users will be told how to install the linter.
=> feat(security): Give user instructions on how to install linter

.golangci.yml, internal/pkg/correlation/middleware.go, internal/security/config/bootstraphandler.go, internal/security/proxy/service_test.go
=> style: Enable staticcheck linter and associated recommendations

.golangci.yml, internal/core/command/controller/http/command_test.go, internal/io/reader_test.go, internal/security/config/command/proxy/adduser/command_test.go, internal/security/config/command/proxy/oauth2/command_test.go, internal/security/kdf/methods.go, internal/security/proxy/service_test.go, internal/security/secretstore/tokenprovider_linux_test.go, internal/support/notifications/application/distributioncoordinator.go, internal/support/notifications/application/notification.go, internal/support/notifications/application/send.go
See #3565
make test; make docker;  make run dev in edgex-compose
=> style: Enable errcheck linter and associated recommendations

snap/local/hooks/cmd/install/install.go, snap/local/hooks/go.sum
This PR:
- fixes #3756
- converts the lists to slices for better maintainability
- adds missing service snaps to secret store tokens and known secrets for the following:
- app-rfid-llrp-inventory
- device-gpio
- device-bacnet
- device-grove
- device-uart
- device-rfid-llrp
I have tested by building the snap, performing a fresh install, and checking the following to make sure the 5 new services are added:
Tokens:
```
$ sudo tree /var/snap/edgexfoundry/current/secrets/ 
/var/snap/edgexfoundry/current/secrets/
├── …
```
=> fix(snap): Fix and extend secretStore component lists

cmd/core-metadata/res/configuration.toml, internal/core/metadata/application/notify.go
Set Notifications.PostDeviceChanges to false by default in core-metadata, because support-notifications service is not always up.
Modify the logging level Warn when sending notifications failed.
Close https://github.com/edgexfoundry/edgex-go/issues/3768
https://github.com/edgexfoundry/edgex-docs/pull/617
=> fix(meta): Disable device notification by default

internal/core/metadata/application/provisionwatcher.go, internal/core/metadata/controller/http/provisionwatcher_test.go
The metadata service should check the service and profile before adding to the DB
Closes #3796
* Run core-metadata service
* Verify the API should return error when adding a new ProvisionWatcher with non-existent service and profile
=> fix(meta): Check required service and profile for ProvisionWatcher

snap/local/hooks/go.mod, snap/local/hooks/go.sum
Bump github.com/canonical/edgex-snap-hooks/v2 from v2.0.5 to v2.1.1
See change log: https://github.com/canonical/edgex-snap-hooks/releases
=> build(snap): Bump edgex-snap-hooks to v2.1.1

snap/hooks/pre-refresh
Updating the `release` config value to `jakarta`. 
This config value is read by the checkbox tests, as far as I know.
=> build(snap): update release config value to jakarta

internal/security/secretstore/kongadminapi.go, internal/security/secretstore/kongadminapi_test.go, snap/hooks/post-refresh
This PR contains two commits:
- security-secretstore-setup now creates the kong-admin-jwt file with read+write (owner) permission
- adds a snap post-refresh hook which deletes a stale kong-admin-jwt file with read-only (owner) permissions
- [NA] I have opened a PR for the related docs change (if not, why?)
The easiest way to test this is to:
```
$ sudo snap remove edgexfoundry
$ sudo snap install edgexfoundry --channel=2.0
edgexfoundry (2.0/stable) 2.0.0-2 from Canonical✓ installed
$ sudo ls -l /var/snap/edgexfoundry/current/secrets/security-proxy-setup
-r-------- 1 root root 248 Nov 15 17:10 /var/snap/edgexfoundry/current/secrets/security-proxy-setup/kong-admin-jwt
```
Verify that the file permission now is `-r--------`.
Now …
=> fix(security): update kong admin token file permissions

snap/README.md, snap/local/hooks/cmd/configure/configure.go, snap/local/hooks/cmd/install/install.go, snap/local/runtime-helpers/bin/service-config-overrides.sh, snap/local/runtime-helpers/bin/start-consul.sh, snap/snapcraft.yaml
This PR modifies the way the snap install and configure hooks when the snap in installed in order to ensure that snap configuration provided at install time is processed before services are started. This is working around an issue with snapd where snap configuration at install time is not made available to the snap until the configure hook is called, which is after the services have already been started.
So, this PR disables all of the services in the install hook, and then in the configure hook, the services are started after configuration has been processed.
**Note** - this PR supersedes PR #3791. …
=> fix(snap): defer service startup till after configure hook runs

openapi/v2/support-scheduler.yaml
Update support-scheduler API document to add path field to intervalAction address examples.
fix #3828
N/A
N/A
=> docs: Add path field to support-scheduler intervalAction API example

go.mod, go.sum
BREAKING CHANGE: ZeroMQ no longer supported on native Windows for EdgeX
MessageBus
**N/A for Build PR**
**N/A for Build PR**
=> build: Update to latest go-mod-messaging w/o ZMQ on windows

openapi/v2/core-command.yaml
=> docs: Add 503 response code to core-command API document

internal/security/config/command/proxy/jwt/command.go
This is a minor fix in the jwt package related to the error message returned when failing to read the private key. The correction makes the error message negative, see the diff.
=> fix: correct jwt error message when reading private key

cmd/core-metadata/res/configuration.toml
Fix the typo of notification message from the configuration.toml
Fix #3835
1. Run metadata service with enabled Notifications.PostDeviceChanges
2. Run notification service
3. Run Modbus device service 
4. The metadata service will send a notification with the message 'Metadata notice:  Modbus-TCP-test-device Device creation'
=> fix(meta): Fix the typo of notification message

snap/local/hooks/cmd/configure/configure.go, snap/local/hooks/cmd/configure/main.go, snap/local/hooks/cmd/configure/options.go, snap/local/hooks/go.mod, snap/local/hooks/go.sum, snap/local/runtime-helpers/bin/security-proxy-post-setup.sh, snap/snapcraft.yaml
Fixes #3863, see the issue for details.
~This PR changes the configure hook to skip configuration options of security-proxy in defer-startup mode. To apply those options, the configure hook is called again after security-proxy-setup completes.~
This PR changes the configure hook to skip **runtime** configuration options of security-proxy in **defer-startup** mode. Those config options should be applied after security-proxy-setup completes.
To achieve that:
a) The config option handling function is changed to ignore runtime config options of security-proxy in defer-startup install mode: https://github.com/canonical/edgex-snap-hooks/pull/25
b) The `configure` executable is extended with an `options` subcommand which takes a service name as follows:
```
./configure options …
```
=> fix(snap): Apply proxy's runtime config options after startup

internal/security/secretstore/secure-messagebus.go, snap/local/runtime-helpers/bin/install-setup-kuiper.sh, snap/snapcraft.yaml
This PR is to upgrade kuiper to 1.4.2 
- add `connectionSelector` to re-use EdgeX message bus
- remove unused configure and install scripts 
1. Install
```
snapcraft
snap install edgexfoundry_2.0.1-dev.71_amd64.snap --dangerous
snap set edgexfoundry kuiper=on
snap set edgexfoundry device-virtual=on
```
2. Create stream and sink with `connectionSelector`
```
curl -X POST \
http://localhost:59720/streams \
-d '{
"sql": "create stream edgexAll() WITH (FORMAT=\"JSON\", TYPE=\"edgex\", SHARED=\"true\")"
}'
curl -X POST \ …
```
=> build(snap): upgrade kuiper to 1.4.2

cmd/core-data/res/configuration.toml, cmd/core-metadata/res/configuration.toml, go.mod, go.sum, internal/core/command/application/command.go, internal/core/command/controller/http/command_test.go, internal/core/command/init.go, internal/core/command/main.go, internal/core/data/main.go, internal/core/metadata/application/notify.go, internal/core/metadata/main.go, internal/support/notifications/main.go, internal/support/scheduler/main.go
All core and support services now use new common handler from go-mod-bootstrap which uses registry (if enabled) to obtain the base URL.
This handler only creates the specific Clients for those configured in the [Clients] section.
For services that don't currently uses Clients and don't have any Clients in configuiration, no Clients are created.
closes #3874
This PR is dependent on https://github.com/edgexfoundry/go-mod-bootstrap/pull/305 and is in draft mode until it is merged.
<link to docs …
=> feat: Location of client service obtained from the registry

internal/core/command/init.go
fixes #3884
Start non-secure Edgex stack
Send `curl http://localhost:59882/api/v2/device/name/Random-Binary-Device/Binary`
Verify response is a 500 with `nil DeviceServiceCommandClient returned`
Stop Core Command container
Build and run core command from this branch with no parameters `./core-command`
Send `curl http://localhost:59882/api/v2/device/name/Random-Binary-Device/Binary`
Verify response is a 500 with `failed to send a http request`
This is a result of …
=> fix(core-command): Restore creation of DeviceServiceCommandClient in handler

snap/local/hooks/cmd/install/install.go
This PR adds edgex-ekuiper as an [add-on service](https://docs.edgexfoundry.org/2.2/security/Ch-Configuring-Add-On-Services/) to `secretStoreTokens` and `secretStoreKnownSecrets` (for redisdb) lists.
The Vault token is required for the standalone deployment of eKuiper with snap, where a script queries the Redis credentials after authenticating with Vault. The snap receives the vault token using the `edgex-secretstore-token` content interface or via other means.
=> feat(snap): add secretstore token for edgex-ekuiper snap

snap/snapcraft.yaml
1.4.3 version resolves stream's topic subscription issue: https://github.com/lf-edge/ekuiper/issues/1168
Please follow the test instruction in this [closed issue](https://github.com/lf-edge/ekuiper/issues/1168). The error should not be reproduced anymore.
=> build(snap): upgrade kuiper to 1.4.3

snap/snapcraft.yaml
This upgrade resolves edgexfoundry/device-virtual-go#268
1. Set up edgexfoundry
```
snap install edgexfoundry_2.2.0-dev.38_amd64.snap --devmode
snap set edgexfoundry device-virtual=on
```
2. Modify ASC
```
sudo nano /var/snap/edgexfoundry/current/config/app-service-configurable/res/rules-engine/configuration.toml
LogLevel = "DEBUG"
[Writable.Pipeline]
ExecutionOrder = "FilterByDeviceName, Transform, SetResponseData"
[Writable.Pipeline.Functions] …
```
=> build(snap): upgrade to device-virtual v2.2.0-dev.7 and app-service-configurable latest/beta

internal/core/metadata/application/notify.go
1. run core-metadata from this branch
2. run device-service which is not yet upgraded sdk to v2.2.0-dev.16
3. verify there's no 404 error and device can be successfully added to metadata
=> fix(metadata): add 404 case for not-yet-upgraded device-service

cmd/security-bootstrapper/entrypoint-scripts/proxy_setup_wait_install.sh, cmd/security-proxy-setup/Dockerfile, cmd/security-proxy-setup/entrypoint.sh
The current behavior of security-proxy-setup terminating
on success causes issues for running EdgeX in Kubernetes,
as it is not possible to specify per-container restart policy.
This fix allows users who want to run EdgeX in a Kubernetes pod
to remove awkward workarounds to the current behavior.
Not needed.
To test, `make docker` and then `make run dev` from edgex-compose.
=> fix: security-proxy-setup will not terminate on success

Makefile
Add hardening CGO flags for go binaries
Fixes: #3880
- [X ] I am not introducing a breaking change (if you are, flag in conventional commit message with `BREAKING CHANGE:` describing the break)
- [X ] I am not introducing a new dependency (add notes below if you are)
=> feat(security): Enable security-hardened go binaries for cgo flags

cmd/sys-mgmt-agent/Dockerfile
This is a blind change to address a CVE in the docker base image.  Will find out when TAF regressions run if there is an issue.
=> fix(security): Bump FROM docker version due to CVEs

go.mod, go.sum, internal/core/data/application/event.go, internal/core/data/messaging/messaging.go, internal/core/metadata/application/device.go, internal/core/metadata/application/deviceprofile.go, internal/pkg/bootstrap/handlers/database.go, internal/pkg/infrastructure/redis/event.go, internal/security/config/command/proxy/adduser/command.go, internal/security/config/command/proxy/deluser/command.go, internal/security/config/command/proxy/oauth2/command.go, internal/security/config/command/proxy/tls/command.go, internal/security/fileprovider/provider.go, internal/security/proxy/resource.go, internal/security/proxy/service.go, internal/security/secretstore/certs.go, internal/security/secretstore/password.go, internal/security/secretstore/passwordprovider.go, internal/security/secretstore/tokenmaintenance.go, internal/security/spiffetokenprovider/maketoken.go
=> refactor(all): Use formatted alternative log function instead of fmt.Sprintf

cmd/security-spire-config/seed_builtin_entries.sh
resolves a bug where the -config container enters a crash loop when the framework is restarted,
because of an error when spire server entry already existing
=> fix(security): Fix for spiffe-config crashloop

cmd/core-command/Dockerfile, cmd/core-metadata/Dockerfile, cmd/security-bootstrapper/Dockerfile, cmd/security-proxy-setup/Dockerfile, cmd/security-secretstore-setup/Dockerfile, cmd/security-spiffe-token-provider/Dockerfile, cmd/support-notifications/Dockerfile, cmd/support-scheduler/Dockerfile, cmd/sys-mgmt-agent/Dockerfile
After CGO go build flag is introduced for core services built, several Dockerfiles of core-services are missing some base build packages; hence this fix.
Fixes: #3901 …
=> fix: Add missing packages for local docker builds

Makefile, README.md, cmd/core-command/Dockerfile, cmd/core-metadata/Dockerfile, cmd/security-bootstrapper/Dockerfile, cmd/security-proxy-setup/Dockerfile, cmd/security-secretstore-setup/Dockerfile, cmd/security-spiffe-token-provider/Dockerfile, cmd/support-notifications/Dockerfile, cmd/support-scheduler/Dockerfile, cmd/sys-mgmt-agent/Dockerfile, go.mod, go.sum
- use one INCLUDE_DELAYED_START_BUILD to control make build flag to include/exclude non_delayedstart build tag
- add conditional go build tag for non_delayedstart if those services are not needed
- use go build tag for no_messagebus to avoid CGO for core-services
- update readme for developer notes
Closes: #3952
- [x ] I am not introducing a new …
=> feat(security): Use conditional go build tags for delayed start and no_messagebus

Makefile, README.md, cmd/security-spire-config/seed_builtin_entries.sh
- Add another variable flag for support serivces in makefile
- make support services use the default enabled delayed start in build time
Closes: #3968
run `make …
=> feat: Make support services include spiffe in buildtime from Makefile

internal/core/metadata/application/deviceservice.go, internal/pkg/utils/struct.go, internal/pkg/utils/struct_test.go
fix #3641
1. run metadata from this branch
2. run device-virtual with `DEBUG` log level
3. verify PATCH `/api/v2/deviceprofile` will not trigger DS callback if only updating `lastConnected` field
=> fix(metadata): not trigger DS callback if only lastConnected is updated

cmd/security-spire-config/seed_builtin_entries.sh
app-service-http-export was unable to obtain a secret-store token because the SPIFFE token provided to the service contained app-service-http-export, but the service key for the service is app-http-export.  The inconsistency resulted in the request for a secret store token being denied.
Run docker-compose while enabling delayed start for app-service-http-export
=> fix(security): Workaround for inconsistent app service naming in docker-compose

snap/local/hooks/cmd/configure/configure.go, snap/local/hooks/cmd/configure/main.go, snap/local/hooks/cmd/configure/options.go, snap/local/hooks/go.mod, snap/local/hooks/go.sum, snap/local/runtime-helpers/bin/security-proxy-post-setup.sh
Supersceding #3924
This PR updates the snap to support environment variable injection as part of introducing the following scheme:
```
apps.<app>.<type>.<key>
```
where:
- `<app>` is the name of the app (service, executable)
- `<type>` is the type of option with respect to the app
- `<key>` is key for the option. It could contain a path to set a value inside an object, e.g. `x.y=z` sets `{"x": {"y": "z"}}`.
This change effectively makes options prefixed with `env.` deprecated. Such options will continue to work but be removed as of EdgeX 3.
The reasons for the schema change is as follows:
- The existing options depended on hardcoded mappings from keys to environment variables that was extremely hard to maintain. The new feature allows passing any environment variable dynamically.
- The …
=> feat(snap): Add support for environment variable injection

snap/snapcraft.yaml
1. Install edgex and turn on ekuiper service:
```
snap install edgexfoundry --channel=edge/pr-3996
snap set edgexfoundry device-virtual=on
snap set edgexfoundry kuiper=on
```
2. Create a stream (with SHARED=false) and multiple rules using this same stream
```
edgexfoundry.kuiper-cli create stream stream1 '()WITH(FORMAT="JSON",TYPE="edgex",SHARED="false")'
edgexfoundry.kuiper-cli create rule rule_log '
{
"sql":"SELECT * from stream1",
"actions":[
{
"log":{
}
}
]
}' …
```
=> build(snap): Switch stage kuiper snap's channel to 1/stable

internal/core/data/messaging/messaging.go
=> fix: Remove MessageBus Options data from configuration after client created

CHANGELOG.md
=> docs(all): update Changelog for Kamakura

openapi/v2/core-command.yaml, openapi/v2/core-data.yaml, openapi/v2/core-metadata.yaml, openapi/v2/support-notifications.yaml, openapi/v2/support-scheduler.yaml, openapi/v2/system-agent.yaml
=> docs: Publish swagger to 2.3.0

snap/snapcraft.yaml
Parts 'kuiper' and 'postgres' have some files with same file name, but with different contents
=> build(snap): exclude redundant eKuiper dependencies

internal/core/data/messaging/messaging.go, internal/core/data/messaging/messaging_test.go
close #4021
1. build core-data docker image from this branch and run with edgex security-enabled compose file
2. GET /api/v2/config and verify the response
=> refactor(data): Use deepCopy of messageBusInfo to avoid external adds

snap/local/build-helpers/bin/minimal-snap-build.sh, snap/local/hooks/cmd/configure/configure.go, snap/local/hooks/cmd/configure/options.go, snap/local/hooks/cmd/install/install.go, snap/snapcraft.yaml
This PR removes device-virtual for the following reasons:
- This app is for development/demonstration purposes only and not needed in production. It shouldn’t be shipped by default. It will become [a standalone snap](https://github.com/edgexfoundry/device-virtual-go/pull/287).
- The hardcoded versioning of the source inside the snap makes it hard to keep the edgex-go source compatible with device-virtual source. Upstream takes care of go vendor versioning but not snapcraft parts.
- The build and hooks logic adds avoidable complexity to the core snap. Removing device-virtual reduces edgex snap size from 293M to 283M. …
=> feat(snap): Remove device-virtual

snap/snapcraft.yaml
Cherry picked commit from Kamakura PR:
- #3831
=> build(snap): upgrade device-virtual and app-service-config to 2.1 (Jakarta)

snap/local/hooks/cmd/configure/configure.go, snap/local/hooks/cmd/configure/main.go, snap/local/hooks/cmd/configure/options.go, snap/local/hooks/go.mod, snap/local/hooks/go.sum, snap/local/runtime-helpers/bin/security-proxy-post-setup.sh, snap/snapcraft.yaml
Cherry picked commit from Kamakura PR:
- #3856
---
Fixes https://github.com/edgexfoundry/edgex-go/issues/3863
* fix: add options subcommand to apply partial configuration
* build: bump github.com/canonical/edgex-snap-hooks/v2 to skip runtime config during defer-startup install mode
* feat: apply security-proxy runtime configurations after startup
(cherry picked from commit 3825f82a080d30abbb2fcfe4d8a2f0ca2c9aa8e0)
=> fix(snap): Apply proxy's runtime config options after startup (Jakarta)

cmd/security-spire-agent/Dockerfile, cmd/security-spire-config/Dockerfile, cmd/security-spire-server/Dockerfile
The underlying [Go base image](https://github.com/edgexfoundry/ci-build-images/blob/golang-1.17/Dockerfile#L8-L23) that Jenkins is using to build the Dockerfiles now contains the spire-server and spire-agent binaries. This PR adds a new check into the spire Dockerfile's that first checks to see if the spire-server/agent doesn't exist before compiling the binary. For local builds, nothing will change since the base image is just the base golang image.
amd64 Docker build time ~ 2m, previously ~ 6m
arm64 Docker build time ~ 15m, previously ~ 50m
Fixes: #4024 
Please check if your PR fulfills the …
=> ci: update spire Dockerfile's to allow conditional compilation

internal/core/data/application/event.go
Always returns 202 Accepted immediately
Steps to reproduce:
1. start edgex services by non-security compose file
2. generate around 10000 events
3. delete events by device name or age
4. return 503 HTTP request timeout
Steps to test the fix:
1. build core-data from this branch and run with other edgex services
2. generate around 10000 events
3. delete events by device name or age
4. return 202 Accepted immediately
=> fix(data): fix deleting numerous events HTTP request timeout by goroutines

cmd/core-command/Dockerfile, cmd/core-data/Dockerfile, cmd/core-metadata/Dockerfile, cmd/security-bootstrapper/Dockerfile, cmd/security-proxy-setup/Dockerfile, cmd/security-secretstore-setup/Dockerfile, cmd/security-spiffe-token-provider/Dockerfile, cmd/security-spire-agent/Dockerfile, cmd/security-spire-config/Dockerfile, cmd/security-spire-server/Dockerfile, cmd/support-notifications/Dockerfile, cmd/support-scheduler/Dockerfile, cmd/sys-mgmt-agent/Dockerfile
This PR updates the Alpine Linux mirror from `nl.alpinelinux.org` to `dl-4.alpinelinux.org` due to inconsistency issues in the package index that causes builds to fail.  This new site is officially listed in the mirror list at https://mirrors.alpinelinux.org/#mirror3 while the old one no longer is.
`make docker`
=> chore: Update Alpine download mirror

cmd/security-secretstore-setup/Dockerfile, cmd/security-secretstore-setup/entrypoint.sh
fixes: #3852
Signed-off-by: Valina Li <valina.li@intel.com>
=> fix: security-secretstore-setup volume init semantics

internal/constants.go, internal/security/bootstrapper/command/setupacl/command.go
Closes: #3257
Signed-off-by: Jim Wang (Intel) <yutsung.jim.wang@intel.com>
1. git clone this branch and build security-bootstrapper docker image: `make docker_security_bootstrapper`
2. go to `edgex-compse` repo and use …
=> feat: use different consul service policy rule for service role

internal/security/bootstrapper/command/setupacl/command.go
bug fixes
Fixes: #4109
Signed-off-by: Jim Wang (Intel) <yutsung.jim.wang@intel.com>
1. when using docker-compose please include security-spiffe-token-provider in the edgex-compose builder, i.e.: `make run dev …
=> fix: add missing edgex/security config stem resolution in security-consul-bootstrapper

cmd/sys-mgmt-agent/Dockerfile
I got tired of having to update the Dockerfile for sys-mgmt-agent due to Snyk vulnerabilities in the docker base image.
I have switched to using the alpine base image with the docker-cli and docker-compose installed.
Image size is reduced from 294MB to 135MB, which is a 54% savings.
With the reduced number of dependencies, CVE exposure should be significantly curtailed;
otherwise, we need to update the base image AGAIN.
I spawned edge-ui-go and exercised system maangement …
=> refactor: Switch from docker to alpine base image for sys-mgmt-agent

.dockerignore, Makefile
This PR adds a local docker image as a cache layer when using the make docker* targets. The local cache image uses this [Dockerfile](https://github.com/edgexfoundry/ci-build-images/blob/golang-1.18/Dockerfile) and if the Dockerfile is not available for some reason will fallback to building the image from the `golang:1.18-alpine` image. This local caching layer greatly increases the current local `make docker` speed from ~15m for a clean build down to ~7m. This solution was presented in the last DevOps WG meeting and more information on the change can be seen in the recording [here](https://zoom.us/rec/share/7nAS0u0iQFCPyxPvWK96xPEb1iS0TwLj5zk_csnBIXXua8hW8uPrtWvPQF8a4-Jk.KrPKufpGdX7Gg-SH?startTime=1658419196000).
**If your build …
=> ci: add local cache to optimize local docker builds

cmd/core-metadata/res/configuration.toml, internal/core/metadata/application/device.go, internal/core/metadata/application/device_test.go, internal/core/metadata/config/config.go, internal/core/metadata/main.go
fixes #4117
TBD
Run Non-secure EdgeX Stack from compose builder
```
make run no-secty ds-virtual ds-rest`
```
Stop Core Metadata
In Consul, remove `MessageQueue` configuration for Core Metadata
Using the branch for this PR
Remove `MessageQueue` and `RequireMessageBus` configuration from TOML file
Build Core Metadata docker image locally
Modify generated compose file to switch Core Metadata image to be local image
Restart local Core Metadata image using modified compose file
```
make …
```
=> fix: Add backwards compatability for Device System Events

Makefile
run make with each of the alias targets
Verify the proper target is executed.
=> build: Add convenient alias for each services build and docker target

cmd/core-metadata/res/uom.toml, go.mod, go.sum, internal/core/metadata/controller/http/uom.go, internal/core/metadata/controller/http/uom_test.go, internal/core/metadata/router.go, internal/core/metadata/uom/uom.go, internal/pkg/encoding.go, openapi/v2/core-metadata.yaml
dependent on https://github.com/edgexfoundry/go-mod-core-contracts/pull/756
cbc81fb9b27178ac0d33edb17f9e140940e39377 updated `uom.toml` configuration structure in order to return similar content for json/toml response. 
fix #3957 
1. Run core-metadata from this branch
2. 
```shell
$ curl localhost:59881/api/v2/uom
{
"statusCode": 200,
"uom": {
"source": "reference to source for all UoM if not specified below",
"units": {
"temperature": {
"source": "www.weather.com",
"values": [
"C",
"F",
"K"
]
}, …
```
=> feat(metadata): implement GET Units of Measure API

snap/hooks/post-refresh, snap/hooks/pre-refresh
PR #4119 added the following environment variable:
https://github.com/edgexfoundry/edgex-go/blob/166620d9f56c7df6403b4f88f57b6f2fdd40f3fd/snap/snapcraft.yaml#L278
This makes the edge releases of snap backward incompatible as of v2.3.0-dev.45 because this file doesn't exist when upgrading from an older version. The latest snap beta release which isn't broken is 2.3.0-dev.44 (snap rev 5898/5899). This fix works when upgrading from the latest beta or older.
This PR adds the logic to add the configuration file when upgrading (i.e. using `snap refresh`). …
=> fix(snap): Install Unit of Measure config file on upgrade

Makefile, README.md, cmd/core-command/Dockerfile, cmd/core-command/res/configuration.toml, cmd/core-data/Dockerfile, cmd/core-data/res/configuration.toml, cmd/core-metadata/Dockerfile, cmd/core-metadata/res/configuration.toml, cmd/support-notifications/Dockerfile, cmd/support-scheduler/Dockerfile
Run the following commands and verify each Go build step includes `-tags "include_nats_messaging ...`
```
make build-nats
make docker-nats
```
=> build: Add option to build Core/Support services with NATS Capability

internal/security/secretstore/init.go, internal/security/secretstore/secure-messagebus.go, internal/security/secretstore/secure-messagebus_test.go
Closes: #4147
Signed-off-by: intel <joshua.silverio@intel.com>
Can gen compose file with https://github.com/joshua-silverio/edgex-compose/tree/secure-ekuiper-mqtt
- make gen dev ds-virtual mqtt-bus 
- make up 
- check kuiper container and app rules engine container to see the mqtt-bus connection success and flowing data
- shell in to kuiper container and cat /kuiper/etc/sources/edgex.yaml to confirm usr/pass of mqtt-bus is configured correctly
=> fix(security): add secure mqtt support to eKuiper

cmd/security-spire-config/seed_builtin_entries.sh
Delayed start is not working for support services. Among other problems, for support services,
the service key is support-servicename,
but the service key in docker-compose is just servicename.
Update pre-seeding script to account for this.
Closes #4152
(Update later with related edgex-compose change.)
=> Fix: Delayed start services for support- services fail

internal/core/metadata/application/deviceprofile.go, internal/core/metadata/application/deviceresource.go, internal/core/metadata/controller/http/deviceprofile_test.go, internal/core/metadata/controller/http/deviceresource_test.go
fix #4138
1. Run metadata from this branch with `WRITABLE_UOM_VALIDATION=true` environment variable
2. Verify POST `/api/v2/deviceprofile/resource` API is validating device resource units against `uom.toml` as expected
=> feat(metadata): add UoM validation to POST deviceresource API

snap/snapcraft.yaml
By default, Redis server bind to all available interfaces. The docker containers have additional control over this using the port mappings but this isn't the case when running snaps. This change will replace the default bind configuration for the snaps from all interfaces IPv4/IPv6 to just the loopback interface and IPv4.
```
$ snap install edgexfoundry --edge
edgexfoundry (edge) 2.3.0-dev.61 from Canonical✓ installed
$ sudo lsof -nPi :6379
COMMAND …
```
=> fix(snap): Bind redis server to loopback interface

cmd/core-command/res/configuration.toml, internal/core/command/controller/messaging/external/external.go, internal/core/command/controller/messaging/external/external_test.go
core-command subscribes to 3rd-party command requests and publishes to the appropriate device service via messaging
1. Run core-command from this branch with external MQTT broker and `MESSAGEQUEUE_REQUIRED=true` environment variable
2. Run `PSUBSCRIBE edgex.command.request.*` in `redis` container to subscribe to the forwarded request
3. send command request to `edgex/command/request/<device>/<command>/<method> topic.
For example send following message to …
=> feat(command): command request from external MQTT to internal MessageBus

internal/security/bootstrapper/command/setupacl/aclpolicies.go, internal/security/bootstrapper/command/setupacl/stubregistryserver_test.go
Added a check in getPolicyByName to see whether the policy exists in the policy list before attempting to get the policy. This prevents erroneous or unclear logging.
closes: #4108
Signed-off-by: Rico Chavez-Lopez <rchavezlopez@ucdavis.edu>
- [x ] I have added unit tests for the new feature or bug fix (if not, why?)
<link to docs …
=>  fix: added consul policy list check

snap/hooks/post-refresh
This PR builds on top of #4125 to correctly deploy Unit of Measure config file during an upgrade. 
When we upgrade from a channel that contains an old version with revision number larger than 3900 (for example a recent build of latest/stable), the current [post-refresh](https://github.com/edgexfoundry/edgex-go/blob/a8eb28e71f5ba3ef86e818c168e1634e95121d28/snap/hooks/post-refresh#L19) falsely assumes that the upgrade is from a new version that already has the UOM file. As a result, the UoM file does not get added during the upgrade which leads to the missing UoM file error. …
=> fix(snap): Copy UoM file if not exist during upgrade

cmd/security-bootstrapper/entrypoint-scripts/kong_wait_install.sh
This ensures any missing migration are run and doesn't hurt if there are none. No need to run `kong migrations list`
fixes #4171
Run Kamakura secure stack compose file
Get API Gateway token and verify API Gateway is functional
Stop (down) the services w/o clearing volumes
Run latest WIP secure stack compose file with Kong changed to version 2.8 and `restart: always` commented out.
Verify Kong remains running and the API Gateway is functional using the same token …
=> fix: Always run "kong migrations up"

internal/core/metadata/application/device.go, internal/core/metadata/application/deviceprofile.go, internal/core/metadata/application/deviceservice.go, internal/core/metadata/application/provisionwatcher.go, internal/core/metadata/controller/http/device_test.go, internal/core/metadata/controller/http/deviceprofile_test.go, internal/core/metadata/controller/http/deviceservice_test.go, internal/core/metadata/controller/http/provisionwatcher_test.go, internal/pkg/infrastructure/redis/device.go, internal/pkg/infrastructure/redis/device_profile.go, internal/pkg/infrastructure/redis/device_service.go, internal/pkg/infrastructure/redis/interval.go, internal/pkg/infrastructure/redis/provisionwatcher.go, internal/support/scheduler/application/interval.go, internal/support/scheduler/application/intervalaction.go, internal/support/scheduler/controller/http/intervalaction_test.go
close #4094
1. run core-metadata, support-scheduler, and device-virtual(or device-simple)
2. try the following REST APIs with the given conditions and verify the response
- POST /device (non-existent device service name)
- POST /device (non-existent device profile name)
- PATCH /device (non-existent device service name)
- PATCH /device (non-existent device profile name)
- DELETE /deviceprofile/name/{name} (associated device exists)
- DELETE /deviceprofile/name/{name} …
=> refactor: Move all the db related check to the infrastructure layer

cmd/core-command/res/configuration.toml, internal/core/command/controller/messaging/external.go, internal/core/command/controller/messaging/external_test.go, internal/core/command/controller/messaging/internal.go, internal/core/command/main.go
core-command subscribes to internal command requests and publishes requests to the to the appropriate device service via messaging
fix #4170
1. Run core-command from this branch with `MESSAGEQUEUE_REQUIRED=true` environment variable
2. Send command requests via `redis` container to InternalRequestCommandTopic, for example:
```shell
/data # redis-cli
127.0.0.1:6379> PUBLISH .command.request.Random-Boolean-Device.Bool.get '{"CorrelationID": …
```
=> feat(command): subscribe command request via internal messaging

cmd/core-command/res/configuration.toml, internal/core/command/controller/messaging/external.go, internal/core/command/controller/messaging/internal.go, internal/core/command/controller/messaging/utils.go, internal/core/command/main.go
fix #4176 
1. Run core-command from this branch with `MESSAGEQUEUE_REQUIRED=true` environment variable
2. Send command query request via internal messaging, for example:
```shell
/data # redis-cli
127.0.0.1:6379> PUBLISH .commandquery.request.Random-Boolean-Device '{"CorrelationID": "14a42ea6-c394-41c3-8bcd-a29b9f5e6835", "ApiVersion": "v2", "RequestId": "e6e8a2f4-eb14-4649-9e2b-175247911369", "ContentType": "application/json"}'
(integer) 1
```
3. Verify core-command received …
=> feat(command): command query via internal messaging

cmd/core-command/res/configuration.toml, go.mod, go.sum, internal/core/command/config/config.go, internal/core/command/controller/messaging/external_test.go, internal/core/command/main.go
=> feat(command): refine north-south messaging configuration

snap/local/helper-go/configure.go, snap/local/helper-go/install.go, snap/local/helper-go/main.go, snap/local/helper-go/options.go
This refactoring is to make use of the new [snapctl](https://github.com/canonical/edgex-snap-hooks/tree/main/snapctl) and [log](https://github.com/canonical/edgex-snap-hooks/tree/main/log) packages from the same module.
=> refactor(snap): Use snapctl and log packages

Makefile, cmd/core-command/res/configuration.toml, cmd/core-data/res/configuration.toml, cmd/core-metadata/res/configuration.toml, cmd/support-notifications/res/configuration.toml, cmd/support-scheduler/res/configuration.toml, go.mod, go.sum, internal/core/command/config/config.go, internal/core/command/main.go, internal/core/metadata/config/config.go, internal/core/metadata/main.go, internal/support/notifications/config/config.go, internal/support/notifications/main.go, internal/support/scheduler/config/config.go, internal/support/scheduler/main.go
part of https://github.com/edgexfoundry/go-mod-bootstrap/issues/374
also addresses https://github.com/edgexfoundry/go-mod-bootstrap/issues/379
by using latest go-mod-bootstrap
https://github.com/edgexfoundry/edgex-docs/pull/877
Build docker images from this branch
Use compose builder run `make run dev`
Verify all service bootstrap properly
Verify Core and Support service have the following log messages
```
"SecuritySecretsStored metric registered and will be reported (if enabled)" …
```
=> feat: Enable common security secret service metrics

internal/core/command/controller/messaging/external.go, internal/core/command/controller/messaging/internal.go, internal/core/command/main.go
fix #4194 
1. Run core-command from this branch with `MESSAGEQUEUE_EXTERNAL_ENABLED=true` environment variable
2. Send command request from external MQTT
3. Verified there's no error:
```
level=DEBUG ts=2022-10-12T03:16:28.400503727Z app=core-command source=external.go:88 msg="Received command request from external message queue on topic 'edgex/command/request/Random-Boolean-Device/Bool/get' with 303 bytes"
level=DEBUG ts=2022-10-12T03:16:28.414620847Z app=core-command …
```
=> fix(command): update message queue bootstrap order

internal/core/command/controller/messaging/external.go, internal/core/command/controller/messaging/external_test.go, internal/core/command/controller/messaging/internal.go, internal/core/command/controller/messaging/utils.go
- update external commandQueryHandler function signature
- remove duplicate error message
=> refactor(command): refactor messaging handler

snap/snapcraft.yaml
=> build(snap): Upgrade kong, redis, consul, vault

snap/local/helper-go/configure.go, snap/local/helper-go/const.go, snap/local/helper-go/install.go, snap/local/helper-go/main.go, snap/local/helper-go/options.go
- Switch to use the hooks/env package for snap envs
- Move constants and lists specific to this snap from hooks library to this package
- Refactor service lists to have consistent style
Mostly refactoring. The review could do a side-by-side diff comparison. The snap tests in this PR has good coverage for the affected code. To run the snap test on a pre-built snap locally, run the following from the top level directory of …
=> refactor(snap): environment variable usage and const definitions

snap/local/runtime-helpers/bin/kong-daemon.sh, snap/snapcraft.yaml
Fixes #4221 
Also, bumps to latest stable kong, i.e. 2.8.2.
```
snap install edgexfoundry --channel=latest/stable
snapcraft
snap install <name>.snap --dangerous
snap refresh edgexfoundry --channel=latest/edge/pr-4223
```
=> build(snap): kong migrations up before Kong startup

cmd/security-bootstrapper/entrypoint-scripts/consul_wait_install.sh
removed the wait on vault to be initialized in order to begin starting consul
Closes: #3584
Signed-off-by: Rico Chavez-Lopez <rchavezlopez@ucdavis.edu>
Pull this branch, make docker_base; make docker. In compose-builder, run make dev. Verify in logs that consul and other containers proceed to start up as expected.
=> refactor: removing vault wait from consul start

snap/local/build-helpers/bin/minimal-snap-build.sh, snap/local/helper-go/configure.go, snap/local/helper-go/const.go, snap/local/helper-go/install.go, snap/local/helper-go/options.go, snap/snapcraft.yaml
This PR removes two deprecated apps kuiper and ASC from edgexfoundry snap since version 3.0. They are available as standalone snaps: [edgex-app-service-configurable snap](https://snapcraft.io/edgex-app-service-configurable) and [edegx-ekuiper snap](https://snapcraft.io/edgex-ekuiper).
=> feat(snap)!: Remove deprecated kuiper and ASC apps from edgexfoundry snap

go.mod, go.sum, internal/constants.go, internal/core/command/main.go, internal/core/data/main.go, internal/core/metadata/main.go, internal/security/bootstrapper/command/setupacl/command.go, internal/security/bootstrapper/main.go, internal/security/bootstrapper/mosquitto/configure.go, internal/security/bootstrapper/redis/configure.go, internal/security/config/main.go, internal/security/fileprovider/main.go, internal/security/proxy/main.go, internal/security/secretstore/main.go, internal/security/spiffetokenprovider/main.go, internal/support/notifications/main.go, internal/support/scheduler/main.go, internal/system/agent/main.go
BREAKING CHANGE: Location of service configuration in Consul changed
closes #4242
Note: this PR is dependent on the following PR being merged first.
- https://github.com/edgexfoundry/go-mod-core-contracts/pull/776
- https://github.com/edgexfoundry/go-mod-bootstrap/pull/401
Build and run core/support services with edgex stack running (core/support services stopped)
Verify configuration is pushed to /edgex/3.0/<service-key>
=> refactor!: Use common Config Stem constants for Core Contracts

Attribution.txt
go-mod-configuration should be v3 in attribution.txt as it is used in go.mod as v3
verify this fix with `make test`
=> fix: go mod configuration to v3 in attribution.txt

cmd/core-command/res/configuration.toml, cmd/core-data/res/configuration.toml, cmd/core-metadata/res/configuration.toml, cmd/support-notifications/res/configuration.toml, cmd/support-scheduler/res/configuration.toml, go.mod, go.sum, internal/core/command/config/config.go, internal/core/command/controller/messaging/external.go, internal/core/command/controller/messaging/external_test.go, internal/core/command/controller/messaging/internal.go, internal/core/command/main.go, internal/core/data/application/event.go, internal/core/data/config/config.go, internal/core/data/controller/messaging/subscriber.go, internal/core/data/init.go, internal/core/metadata/application/device.go, internal/core/metadata/application/device_test.go, internal/core/metadata/config/config.go, internal/core/metadata/main.go, internal/security/spiffetokenprovider/config/config.go, internal/support/notifications/config/config.go, internal/support/notifications/main.go, internal/support/scheduler/config/config.go, internal/support/scheduler/main.go, openapi/v2/core-data.yaml
BREAKING CHANGE: MessageQueue renamed to MessageBus and fields changed. See v3 Migration guide.
This PR is dependent on https://github.com/edgexfoundry/go-mod-bootstrap/pull/410 
TBD
Run non-secure Edgex Stack with device virtual and stop all core/support services.
Build core/support services locally
Run core/support services locally with DEBUG log level
Verify core/support services bootstrap properly and connect to the MessageBus
Verify Core Data is receiving events.
=> refactor!: Rework code for refactored MessageBus Configuration

snap/local/runtime-helpers/bin/service-config-overrides.sh, snap/local/runtime-helpers/bin/setup-consul-acl.sh, snap/snapcraft.yaml
The PR https://github.com/edgexfoundry/edgex-go/pull/4071 upgraded the library to generate correct environment files, and updated the env loader script accordingly. However, another env file loader logic was in the consul security bootstrapper script which was left out.
This PR removes the duplicate logic and makes the bootstrapper use the generic env file loader script.
Fixes https://github.com/edgexfoundry/edgex-go/issues/4284
1. Download the snap …
=> fix(snap): source security-bootstrapper config overrides from env file

go.mod, go.sum, internal/core/command/controller/http/command.go, internal/core/command/controller/http/command_test.go, internal/core/command/controller/messaging/external_test.go, internal/core/command/controller/messaging/utils.go, openapi/v2/core-command.yaml
BREAKING CHANGE: ds-pushevent and ds-returnevent to use bool true/false instead of yes/no
related: https://github.com/edgexfoundry/go-mod-core-contracts/pull/782
https://github.com/edgexfoundry/edgex-docs/pull/917 and the core-command Swagger file in this repo
build core-command and device-virtual docker images based on the changes and run docker-compose.yml
The following commands work as expected:
```
curl http://localhost:59882/api/v2/device/name/Random-Boolean-Device/Bool\?ds-pushevent\=true …
```
=> refactor!: Use bool types for command parameters to be more consistent

cmd/core-command/res/configuration.toml, cmd/core-data/res/configuration.toml, cmd/core-metadata/res/configuration.toml, cmd/security-bootstrapper/res-bootstrap-mosquitto/configuration.toml, cmd/security-bootstrapper/res-bootstrap-redis/configuration.toml, cmd/security-spiffe-token-provider/res/configuration.toml, cmd/support-notifications/res/configuration.toml, cmd/support-scheduler/res/configuration.toml, go.mod, go.sum, internal/core/command/config/config.go, internal/core/data/config/config.go, internal/core/metadata/config/config.go, internal/pkg/controller/http/secret_test.go, internal/security/bootstrapper/command/setupacl/command.go, internal/security/bootstrapper/command/setupacl/stubregistryserver_test.go, internal/security/bootstrapper/config/config.go, internal/security/bootstrapper/mosquitto/config/config.go, internal/security/bootstrapper/redis/config/config.go, internal/security/proxy/config/config.go, internal/security/proxy/init.go, internal/security/spiffetokenprovider/config/config.go, internal/security/spiffetokenprovider/init.go, internal/support/notifications/config/config.go, internal/support/scheduler/config/config.go
BREAKING CHANGE: SecretStore config no longer in service configuration file. Changes must be done via use of environment variable overrides of default values
TBD
Run `make docker` from this branch
From compose builder run `make run ds-virtual delayed-start dev`
Verify all core/support services bootstrapped and running properly
Verify Device Virtual bootstrapped and running properly using runtime token provider. Log should contain:
```
level=INFO ts=2023-01-17T20:47:10.1690972Z …
```
=> refactor!: Replace SecretStore service config with default values and overrides

.gitignore, Makefile, cmd/core-common-config-bootstrapper/Dockerfile, cmd/core-common-config-bootstrapper/entrypoint.sh, cmd/core-common-config-bootstrapper/main.go, cmd/core-common-config-bootstrapper/res/configuration.yaml, cmd/security-bootstrapper/res/configuration.toml, cmd/security-file-token-provider/res/token-config.json, internal/core/common_config/README.md, internal/core/common_config/main.go
Signed-off-by: Elizabeth J Lee <elizabeth.j.lee@intel.com>
1. run `make common-config` to ensure the binary builds
3. run in non-secure mode `export EDGEX_SECURITY_SECRET_STORE=false; ./cmd/core-common-config-bootstrapper/core-common-config-bootstrapper`
4. build the docker images `make docker`
5. run in secure mode `export EDGEX_SECURITY_SECRET_STORE=true`
6. use compose builder and run `make run dev`
7. run the core common config bootstrapper from `cmd/core-common-config-bootstrapper` by running `sudo ./core-common-config-bootstrapper`
=> feat: initial core common config bootstrapper and config implementation

cmd/core-command/res/configuration.toml, internal/core/command/config/config.go, internal/core/command/controller/messaging/external.go, internal/core/command/controller/messaging/external_test.go, internal/core/command/controller/messaging/internal.go, internal/core/command/main.go
BREAKING CHANGE:
- MessageBus.Internal renamed to MessageBus and moved to top level.
- MessageBus.External renamed to ExternalMQTT and moved to top level.
closes #4259
1. Run core-command from this branch with external MQTT broker
2. Verify commands via messaging is working correctly
=> refactor(command)!: separate and move MessageBus config to top level

cmd/core-common-config-bootstrapper/Dockerfile, go.mod, go.sum, internal/core/common_config/main.go
Signed-off-by: Elizabeth J Lee <elizabeth.j.lee@intel.com>
1. run `make common-config` to ensure the binary builds
3. run in non-secure mode `export EDGEX_SECURITY_SECRET_STORE=false`
4. run edgex core services from compose builder `make run no-secty`
5. `./core-common-config-bootstrapper -cp=consul.http://localhost:8500 -cf=configuration.yaml`
6. check that the config is loaded into Consul [http://localhost:8500/ui/dc1/kv/edgex/v3/core-common-config-bootstrapper/](http://localhost:8500/ui/dc1/kv/edgex/v3/core-common-config …
=> feat: Push common config to config provider

cmd/core-common-config-bootstrapper/res/configuration.yaml, cmd/core-data/res/configuration.toml, cmd/core-metadata/res/configuration.toml, cmd/security-bootstrapper/res-bootstrap-redis/configuration.toml, cmd/security-bootstrapper/res/configuration.toml, cmd/security-spiffe-token-provider/res/configuration.toml, cmd/support-notifications/res/configuration.toml, cmd/support-scheduler/res/configuration.toml, internal/core/data/config/config.go, internal/core/metadata/config/config.go, internal/pkg/bootstrap/handlers/database.go, internal/pkg/bootstrap/interfaces/database.go, internal/security/bootstrapper/redis/config/config.go, internal/security/bootstrapper/redis/handlers/handlers.go, internal/security/spiffetokenprovider/config/config.go, internal/support/notifications/config/config.go, internal/support/scheduler/config/config.go, openapi/v2/core-data.yaml, openapi/v2/core-metadata.yaml
BREAKING CHANGE: Database configuration for services has changed from a Map to a single instance
closes #4131
TBD
run `make docker` using this branch
run `make run ds-virtual dev` from compose builder from https://github.com/edgexfoundry/edgex-compose/pull/328
Verify all service bootstrap successfully
=> refactor!: Change Database configuration to be single instance

internal/core/metadata/application/device.go, internal/core/metadata/application/notify.go
device service is subscribing device system events and removing REST device callbacks in edgexfoundry/device-sdk-go#1259 The calls to the REST callback can be removed
closes #4235
1. Run metadata from this branch
2. Run device-simple from device-sdk-go and verify device callbacks are working correctl.y
=> feat: remove device callback calls

cmd/security-bootstrapper/res-bootstrap-redis/configuration.toml, internal/security/bootstrapper/helper/redis_conf.go, internal/security/bootstrapper/helper/redis_config_test.go, internal/security/bootstrapper/redis/config/config.go, internal/security/bootstrapper/redis/handlers/handlers.go
Add configuration of maxclients to redis.conf and set it to 1000 as the default value
Closes: #3594
- [x ] I have added unit tests for the new feature or bug fix (if not, why?)
- pull this branch and build docker_security_bootstrapper
- …
=> fix: adjust redis maxclients to 1000 as default value

cmd/core-metadata/res/configuration.toml, internal/core/metadata/config/config.go, internal/core/metadata/main.go
BREAKING CHANGE: Removed the 'Notifications' config and 'Clients.support-notifications' dependency
in EdgeX 3.0, metadata will leverage device system events to replace the original device change notifications
closes #4316
https://github.com/edgexfoundry/edgex-docs/pull/954
=> feat(metadata)!: remove Notifications config

cmd/core-common-config-bootstrapper/res/configuration.yaml
SDK was modified to remove UseMessageBus and REST calls to Core Data to push Events. New Common config is now in sync with SDK.
=> feat: remove UseMessageBus from common config

internal/core/common_config/main.go
=> fix: Add retry when calling HasConfiguration to wait for Consul

internal/core/metadata/application/devicecommand.go, internal/core/metadata/application/deviceprofile.go, internal/core/metadata/application/deviceresource.go, internal/core/metadata/application/notify.go, internal/core/metadata/application/notify_test.go, internal/core/metadata/controller/http/devicecommand_test.go, internal/core/metadata/controller/http/deviceprofile_test.go, internal/core/metadata/controller/http/deviceresource_test.go
publish update device profile system events to device services
related #4273
1. build and run core-metadata with other services
2. create two devices for different device services with the same profile (device-simple and device-virtual in this case)
3. find the correct logs
4. (optional) subscribe the redis messagebus system event topic and receive the correct messages
The logs after updating the device profile
```
level=DEBUG ts=2023-02-13T04:28:03.758651759Z …
```
=> feat: Publish Update Device Profile System Event for Each Device Service

internal/security/bootstrapper/command/setupacl/command_test.go
=> fix: take out parallel running in unit tests to avoid timing issue

internal/core/metadata/application/notify.go, internal/core/metadata/application/provisionwatcher.go
- publish system events for provision watcher add/update/delete
- remove the REST callbacks
close #4329
https://github.com/edgexfoundry/edgex-docs/pull/960
1. build and run core-metadata with other services
2. find the correct logs
3. (optional) subscribe the redis messagebus system event topic and receive the correct messages
- add a provision watcher 
```
level=DEBUG ts=2023-02-13T09:48:21.487595056Z app=core-metadata source=provisionwatcher.go:37 msg="ProvisionWatcher created on DB …
```
=> feat: Implement Provision Watcher System Events

internal/core/metadata/application/deviceservice.go, internal/core/metadata/application/notify.go, internal/core/metadata/controller/http/deviceservice_test.go
- publish system events for device service add/update/delete
- remove the REST callback
close #4328
https://github.com/edgexfoundry/edgex-docs/pull/960
1. build and run core-metadata with other services
2. find the correct logs
3. (optional) subscribe the redis messagebus system event topic and receive the correct messages
- add a device service
```
level=DEBUG ts=2023-02-14T09:40:28.565100915Z app=core-metadata source=deviceservice.go:38 msg="DeviceService created on DB successfully. …
```
=> feat: Implement Device Service System Events

snap/local/helper-go/common.go, snap/local/helper-go/configure.go, snap/local/helper-go/install.go, snap/snapcraft.yaml
A component called "core-common-config-bootstrapper" has been added through PR https://github.com/edgexfoundry/edgex-go/pull/4292, which pushes the common configuration to the Config Provider. This PR adds it into snap packaging.
Additionally, the command-line flags have been updated by this PR to use preferred options for apps.
=> feat(snap): Add core-common-config-bootstrapper

internal/core/data/application/event.go
Previous refactoring missed adding 'core' to event publish topic
=> fix: Add missing 'core' to event publish topic

go.mod, go.sum, internal/core/metadata/controller/http/device_test.go, internal/core/metadata/controller/http/deviceprofile_test.go, internal/core/metadata/controller/http/provisionwatcher_test.go, openapi/v3/core-metadata.yaml
BREAKING CHANGE: Remove Notify field out of Device model/dto
Per https://github.com/edgexfoundry/go-mod-core-contracts/pull/807, the boolean field notify of Device DTO is removed as device creation notification is handled by system event message now.  
Per https://github.com/edgexfoundry/go-mod-core-contracts/pull/803, the ProvisionWatcher DTO is updated with a new Properties field.
This commit updates following material to reflect such changes:
1. update go.mod/go.sum to use go-mod-core-contracts v3.0.0-dev.20
2. update swagger file correspondingly (remove notify field out of Device dto and add properties field into ProvisionWatcher dto)
3. update unit test correspondingly …
=> feat!: Remove Notify field out of Device dto and add Properties field into ProvisionWatcher dto

openapi/v3/core-metadata.yaml
Three `map[string]any` fields are recently added into DTOs:
1. tags field of Device DTO
2. properties field of Device DTO
3. properties field of ProvisionWatcher
The proper way to show `map[string]any` in swagger is like following: 
```
tags:
tag1:
field1: "field1Value"
field2: "field2Value"
tag2:
field3: "field3Value"
field4: "field4Value"
field5: "field5Value"
```
However, #4375 accidentally add extra hyphens like following:
```
tags:
- tag1:
field1: "field1Value"
field2: "field2Value"
- tag2:
field3: "field3Value"
field4: "field4Value"
field5: "field5Value"
```
Those hyphens should be removed for proper map[string] representation. …
=> fix: Remove extra hyphen out of the core-metadata.yaml

.gitignore, Makefile, cmd/security-bootstrapper/res/configuration.toml, cmd/security-proxy-auth/Dockerfile, cmd/security-proxy-auth/entrypoint.sh, cmd/security-proxy-auth/main.go, cmd/security-proxy-auth/res/configuration.toml, internal/security/proxyauth/config/config.go, internal/security/proxyauth/container/config.go, internal/security/proxyauth/init.go, internal/security/proxyauth/main.go
This commit introduces code for the security-proxy-auth microservice. The proxy-auth microservice will be used by the NGINX reverse proxy to perform JWT authentication of inbound requests through the proxy.
This is second in a series of commits to implement the microservice token-based authentication ADR.
* Add the following snippet to add-security.yml to add the proxy-auth service
```
authproxy:
image: edgexfoundry/security-proxy-auth:0.0.0-dev
container_name: edgex-proxy-auth
hostname: edgex-proxy-auth
read_only: true
restart: always
networks:
- edgex-network
ports:
- "127.0.0.1:59842:59842" # FIXME remove localhost mount
entrypoint: ["/bin/sh", "/edgex-init/ready_to_run_wait_install.sh"]
command:
- …
```
=> feat: Create security-proxy-auth microservice (for proxy swapout)

internal/core/command/controller/messaging/external.go, internal/core/command/controller/messaging/internal.go, internal/core/command/controller/messaging/utils.go, internal/core/command/router.go, internal/core/data/application/event.go, internal/core/data/controller/messaging/subscriber.go, internal/core/data/router.go, internal/core/metadata/router.go, internal/pkg/correlation/middleware.go
- Use router.UseEncodedPath() to match the encoded original path to the routes
- Decode the Url path variable before passing to the controller
Close #4371
- Run core service and device service based on the [core-contract](https://github.com/edgexfoundry/go-mod-core-contracts/pull/806) and [device-sdk](https://github.com/edgexfoundry/device-sdk-go/pull/1335) changes.
- Add a profile to the metadata service, the command name and resource name should contain special character like `:`
- Add a device to the metadata service
- …
=> feat: Accept URL escape for device command name and resource name

snap/snapcraft.yaml
Given the current flags, the services (core-metadata, core-command, support-scheduler, support-notifications) don't get registered in Consul and don't produce any errors either.
There appear to be a bug either in the command processing of snapcraft or the EdgeX services. It appear that the `--registry` flag isn't processed at all. This PR is set as a refactoring type because the removed flag values are the defaults and theoretically equivalent. 
Another working solution was to change the order from `--configProvider consul.http://localhost:8500/ --registry` to `--registry --configProvider consul.http://localhost:8500/`. …
=> refactor(snap): Remove explicit config provider addresses

cmd/security-bootstrapper/entrypoint-scripts/nginx_wait_install.sh, cmd/security-proxy-setup/entrypoint.sh
This functionality was dropped in the Kong to NGINX change, and is being restored in order to make it easy to permanently add a custom route that survives "make clean" operations in Docker.
As per existing documentation, use ADD_PROXY_ROUTE on proxy-setup to add custom routes.
Verify changes to /etc/nginx/conf.d/custom-routes.inc and /etc/nginx/templates/custom-routes.inc.template
=> fix(security): Restore ADD_PROXY_ROUTE functionality for docker NGINX

cmd/support-scheduler/res/configuration.toml, internal/pkg/utils/restaddress.go, internal/support/notifications/application/channel/sender.go, internal/support/scheduler/application/intervalaction.go, internal/support/scheduler/application/scheduler/manager.go, internal/support/scheduler/application/scheduler/manager_test.go, internal/support/scheduler/config/config.go, internal/support/scheduler/init.go
The easiest way to test this change is to modify support-scheduler configuration.toml and set the Midnight interval to a period of "5m" (five minutes).  Then make docker (make clean_docker_base docker_base docker), then from edgex-compose/compose-builder run make run dev.   Then do docker logs -f edgex-core-data and wait for the following log message to appear:
```
level=INFO ts=2023-03-08T00:45:00.109776605Z app=core-data source=auth_middleware.go:50 msg="Authorizing incoming call to '/api/v2/event/age/604800000000000' via JWT (Authorization len=467)"
level=INFO ts=2023-03-08T00:45:00.124832092Z app=core-data source=auth_middleware.go:64 msg="Request to '/api/v2/event/age/604800000000000' authorized"
```
If …
=> fix: Add authentication to support-scheduler actions

internal/security/proxyauth/init.go
secuity-proxy-auth was not registering /api/v2/ping endpoint (nor version nor config) common endpoints.  This was causing the service to appear unhealthy in consul, as the snap was starting the service with --registry flag.
Apply https://github.com/edgexfoundry/edgex-compose/pull/350 or run the snap, and verify the service health in consul.
=> fix: Register healthcheck endpoint for security-proxy-auth

go.mod, go.sum, internal/core/command/config/config.go, internal/core/data/config/config.go, internal/core/metadata/config/config.go, internal/security/bootstrapper/config/config.go, internal/security/bootstrapper/mosquitto/config/config.go, internal/security/bootstrapper/redis/config/config.go, internal/security/common/tokenpolicy_test.go, internal/security/fileprovider/config/config.go, internal/security/fileprovider/util_test.go, internal/security/proxyauth/config/config.go, internal/security/secretstore/config/config.go, internal/security/spiffetokenprovider/config/config.go, internal/support/notifications/config/config.go, internal/support/scheduler/config/config.go
Run `make docker` using this branch
Run non-secure EdgeX stack using compose builder `make run no-secty dev`
Verify the logs for all Core/Support services have the following:
```
"listening for private config changes"
"listening for all services common config changes"
```
In Consul change the common config all-service Writable/Telemetry/Interval to `15s`
Verify the logs for all Core/Support service should the Telemetry Interval has changed
```
"Writeable configuration has been updated from the Configuration Provider" …
```
=> feat: Consume watch for common Writable config changes

SECURITY.md, security.txt
Removes obsolete information from SECURITY.md and adds a security.txt for inclusion into docker images and snaps.
References: #4151 
=> feat(security): Update SECURITY.md, add security.txt

internal/security/config/command/proxy/adduser/command.go
Can be tested via get-api-gateway-token.sh in edgex-compose
=> docs(security): Clarify units of jwtTTL

cmd/secrets-config/README.md, internal/security/config/bootstraphandler.go, internal/security/config/command/proxy/adduser/command.go, internal/security/config/command/proxy/deluser/command.go, internal/security/config/command/proxy/tls/command.go, internal/security/config/command/proxy/tls/command_test.go
BREAKING CHANGE: To be consistent with other secrets-config sub-commands, the tls command will now accept camelCase command line arguments.  Also fixes issue with -h option resulting in an error in addition to printing help.
For help, use secrets-config (command) (subcommand) -h
tls subcommand works as usual, with exception of breaking change to argument casing.
=> refactor(security)!: Change to camelCase args for secrets-config proxy tls

cmd/core-command/res/configuration.toml, cmd/core-common-config-bootstrapper/res/configuration.yaml, cmd/core-data/res/configuration.toml, cmd/core-metadata/res/configuration.toml, cmd/security-proxy-auth/res/configuration.toml, cmd/security-spiffe-token-provider/res/configuration.toml, cmd/support-notifications/res/configuration.toml, cmd/support-scheduler/res/configuration.toml, go.mod, go.sum, internal/core/common_config/main.go
closes #4448
TBD
Run non-secure EdgeX stack
Build core-common-config from this branch
Set the following
- export ALL_SERVICES_WRITABLE_TELEMETRY_INTERVAL=50s
- export APP_SERVICES_WRITABLE_TELEMETRY_METRICS_MESSAGESRECEIVED=true
- export DEVICE_SERVICES_WRITABLE_TELEMETRY_METRICS_EVENTSSENT=true
run common config from command line
- `./core-common-config-bootstrapper -cp -cf configuration.yaml -o`
verify consul has the appropriate overridden values
verify logs contain the following:
```
"Variables override of …
```
=> feat: Add env override capability for common configuration

internal/core/command/controller/messaging/external.go, internal/core/command/controller/messaging/utils.go
.(dot) is not escaped by QueryEscape function, check the
commandName is unescapable and use the original escaped
commandName provided by user to build MessageBus topic
1. Run `core-command` from this branch with `EXTERNALMQTT_ENABLED: "true"`
2. Send command request via external command request topic:
```shell
$ docker exec -it mqtt-broker /bin/sh
/ $ mosquitto_pub -t 'edgex/command/request/Simple-Device01/%2Erotation/get' -m "{\"ApiVersion\":\"v2\",\"ContentType\":\"application/json\",\"C …
```
=> fix(command): enable regex for Commands via Messaging

internal/security/config/command/proxy/tls/command.go
See https://docs.edgexfoundry.org/3.0/security/Ch-APIGateway/#using-a-bring-your-own-external-tls-certificate-for-api-gateway
=> fix: Remove forced chown of ngnix tls for snap compatibility

internal/core/metadata/controller/http/uom.go, internal/core/metadata/controller/http/uom_test.go, internal/pkg/encoding.go, openapi/v3/core-metadata.yaml
BREAKING CHANGE: It was decided in Minnesota planning that all TOML files would be change to be YAML format.
Close #4441
- Run unit test
- Test the uom API
```
curl 'http://localhost:59881/api/v2/uom' --header 'Accept: application/x-yaml'
```
=> feat!: Switch UOM API to YAML format

openapi/v3/support-scheduler.yaml
Add AuthMethod to support-schduler API document
Closes #4479
=> docs: Add AuthMethod to support-schduler API document

internal/core/command/controller/messaging/external.go
closes #4505
https://github.com/edgexfoundry/edgex-docs/pull/1017
1. Run `core-command` from this branch with `EXTERNALMQTT_ENABLED: true` and external mqtt broker
2. Send command request via external mqtt request topic:
```shell
$ docker exec -it mqtt-broker /bin/sh
/ $ mosquitto_pub -t 'edgex/command/request/Random-Boolean-Device/Bool/get' -m "{\"ApiVersion\":\"v2\",\"ContentType\":\"application/json\",\"C
orrelationID\":\"14a42ea6-c394-41c3-8bcd-a29b9f5e6835\",\"RequestId\":\"e6e8a2f4-eb14-4649-9e2b-175247911369\"}"
```
3. Subscribe to …
=> fix(command): reset ReceivedTopic for External MQTT response

go.mod, go.sum, internal/core/command/init.go, internal/core/command/router.go, internal/core/data/router.go, internal/core/metadata/router.go, internal/security/proxyauth/init.go, internal/support/notifications/router.go, internal/support/scheduler/application/scheduler/manager.go, internal/support/scheduler/init.go, internal/support/scheduler/router.go
https://github.com/edgexfoundry/edgex-docs/pull/1020
run `make docker` from this branch
run `make run ds-virtual dev` from compose builder
Verify all services bootstrap successfully
attempt to do GET on `http://localhost:59880/api/v2/reading/all`
verify receive auth error
run `make get-token` from compose builder 
Use the token a `Bearer` in attempt to do  GET on `http://localhost:59880/api/v2/reading/all`
Verify good response with many readings.
=> feat: Consume SecretProvider breaking changes

cmd/security-spire-config/seed_builtin_entries.sh
Since the docker service keys change in docker-compose file for support services (support-notifications from notifications and support-scheduler from scheduler),
the tweaks in spire configure script for such behavior is no longer necessary and thus removed it
This should fix part of the problem in issue #4507 
- [x ] I have fully …
=> fix: remove unnecessary service name tweaks for support services

cmd/security-proxy-setup/entrypoint.sh, internal/security/bootstrapper/command/setupacl/command.go, internal/security/config/command/proxy/shared/proxyuser.go, internal/security/fileprovider/tokenconfig.go, internal/security/secretstore/init.go, internal/security/secretstore/vmkencryption.go, snap/local/helper-go/install.go
BREAKING CHANGE: Add EDGEX_ prefix to ADD_SECRETSTORE_TOKENS, ADD_REGISTRY_ACL_ROLES, ADD_KNOWN_SECRETS, and IKM_HOOK variables
https://github.com/edgexfoundry/edgex-docs/pull/1027
=> refactor(security)!: Prefix security related env vars with EDGEX_

cmd/security-spire-agent/Dockerfile, cmd/security-spire-config/Dockerfile, cmd/security-spire-server/Dockerfile, cmd/security-spire-server/server.conf
=> build: update spire

internal/core/data/controller/messaging/subscriber.go, internal/pkg/correlation/middleware.go
BREAKING CHANGE: Use PathUnescape for decoding API path to consist with the change from MQTT topic, the MQTT topic path will encode with url.PathEscape.
Run core services and device service to check whether the event can publish to the message bus.
This modification is based on the issue https://github.com/edgexfoundry/device-sdk-go/issues/1433
=> feat!: Using url.PathUnescape for decoding API path

cmd/core-command/res/configuration.yaml, cmd/core-data/res/configuration.yaml, cmd/core-metadata/res/configuration.yaml, cmd/support-notifications/res/configuration.yaml, cmd/support-scheduler/res/configuration.yaml, go.mod, go.sum, internal/core/command/config/config.go, internal/core/command/main.go, internal/core/data/config/config.go, internal/core/metadata/config/config.go, internal/security/bootstrapper/command/flags_common.go, internal/security/config/command/flags_common.go, internal/security/proxyauth/config/config.go, internal/security/proxyauth/main.go, internal/security/spiffetokenprovider/config/config.go, internal/support/notifications/config/config.go, internal/support/notifications/main.go, internal/support/scheduler/config/config.go, internal/support/scheduler/main.go
Dev Mode is used when running service locally with the other services running in Docker (aka hybrid mode). This causes all the `Host` settings pulled from common configuration to be overridden with the value `localhost`.
https://github.com/edgexfoundry/edgex-docs/pull/1040
run `make docker` using this branch
From latest Compose Builder run ` make run no-secty ds-virtual`
Verify all services have bootstrapped successfully and data is flowing from device virtual to Core Data and App Rules Engine
Verify following GET Command is successful 
``` …
```
=> feat: Consume new -d/--dev Dev Mode command-line flag

cmd/security-spire-config/seed_builtin_entries.sh
[docs PR](https://github.com/edgexfoundry/edgex-docs/pull/1041)
**Testing without setting SPIFFE_CUSTOM_SERVICES**
1. pull the current PR branch
2. build all the edgex-go services `make docker` in edgex-go
3. pull the latest images from edgex-compose compose-builder directory `make pull delayed-start ds-virtual ds-modbus`
4. in edgex-compose compose-builder directory, run `make run dev delayed-start ds-virtual ds-modbus`
5. Wait for all security services to start up. Ensure that edgex-security-spire-config container has run the …
=> feat: Add ability to customize spiffe services

cmd/security-spiffe-token-provider/Dockerfile
go-mod-bootstrap only allows registration of HTTP healtchecks with consul, which will not work for this service, as it requires clients have a client TLS certificate.  In any case, registration is not required for proper functioning of the service
Closes #4531
This service never runs in secure mode and thus embedded CMD is never exercised.
Actually fixed by edgex-compose#375, but this corresponding change is made for conistency.
=> fix: Don't register spiffe token provider service

cmd/security-spire-config/seed_builtin_entries.sh
Also adds a missing service, app-metrics-influxdb
Before this change, "make run delayed-start" would show the following in the spire-config error log:
```
+ echo -n '\'
+ sed -e s/app-service-/app-/
+ service='\'
+ spire-server entry create -socketPath /tmp/edgex/secrets/spiffe/private/api.sock -parentID spiffe://edgexfoundry.org/spire/agent/x509pop/cn/agent0 -dns 'edgex-\' -spiffeID 'spiffe://edgexfoundry.org/service/\' -selector 'docker:label:com.docker.compose.service:\'
Error: path segment characters are limited to letters, numbers, dots, dashes, and underscores
+ echo -n app-external-mqtt-trigger
```
=> fix: Fix multiline break for seed_builtin_entries.sh

snap/local/helper-go/go.mod, snap/local/helper-go/go.sum, snap/local/helper-go/install.go, snap/local/runtime-helpers/bin/source-env-file.sh, snap/snapcraft.yaml
This PR upgrades the snap base from core20 to core22, and also upgrades env file loading logic to incorporate the following fixes:
- https://github.com/canonical/edgex-snap-hooks/pull/83
- https://github.com/canonical/edgex-snap-hooks/pull/82
=> build(snap): Upgrade snap base to core22, upgrade env file loading logic

cmd/security-file-token-provider/res/token-config.json, internal/security/secretstore/init.go, internal/security/spiffetokenprovider/init.go
Closes #4540
security-spiffe-token-provider allows delayed start services to request known secrets. Prior to this commit, it didn't know about the message-bus known secret.  Also is now just a warning to the log if a service requests a nonexistent secret.
Suggested testing instructions:
modify add-runtime-token-config-template.yml and add SECRETSTORE_RUNTIMETOKENPROVIDER_REQUIREDSECRETS: foo,message-bus,redisdb,bar
make run dev delayed-start ds-virtual
docker logs -f edgex-security-spiffe-token-provider
you will notice …
=> fix: Enable delayed-start services to get message-bus credential

internal/pkg/infrastructure/redis/provisionwatcher.go, openapi/v3/core-metadata.yaml
Do not check the empty string profile name for adding the ProvisionWatcher
Run core service and device-simple base on the core-contracts changes and verified the provision watcher API works as expected.
https://github.com/edgexfoundry/go-mod-core-contracts/pull/834
=> feat: Allow Device Profile to be empty string in ProvisionWatcher

.github/workflows/snap.yaml, snap/local/helper-go/common.go, snap/local/helper-go/configure.go, snap/local/helper-go/install.go
Prior to https://github.com/edgexfoundry/edgex-go/issues/4448, it was possible to override configuration coming from the Config Provider via environment variables. This is no longer possible. As a result, the environment variables need to be set before initial startup. This PR changes the services startup to have them disabled and stopped by default, instead of enabled and started. This is to allow changing configurations via environment variables in this Snap (via snap options) when installing the snap manually. 
```bash
snapcraft -v
sudo …
```
=> refactor(snap)!: Disable and stop services by default

internal/pkg/infrastructure/redis/provisionwatcher.go
The service name in Provision Watcher is the base name. It may not exist if each device service(s) are running with the -i/--instance flag
Run device simple with the `-i 1`. 
Verify `Simple-Provision-Watcher` is created even though the device service `device-simple` doesn't exist.
Update the `Simple-Provision-Watcher`
Verify no error.
=> fix: Remove Devices Service exists Check from Add/Update Provision Watcher

internal/support/scheduler/application/scheduler/executor.go, internal/support/scheduler/application/scheduler/executor_test.go
Fixes #4594
As the start and end times of the input remain unchanged, there is no need to modify the docs.
1. Build support-scheduler image from this branch and update the docker compose file which you want to run with to add this prop for `support-scheduler`.
```
volumes:
- /etc/localtime:/etc/localtime:ro
```
2. Run the local support-scheduler image with other services.
3. Modify the LogLevel of support-scheduler to `DEBUG`.
4. Create a new interval with **current time** of your location as start time.
```
curl -X POST http://localhost:59861/api/v3/interval -d '[
{
"apiVersion": "v3",
"interval": {
"interval": "5s",
"name": "test-interval",
"start": "20230621T115000"
}
}
]'
```
5. Checked the logs of …
=> fix: Initialize interval in the local time zone

cmd/security-secretstore-setup/Dockerfile, cmd/security-secretstore-setup/entrypoint.sh
Closes #4570
"make docker" on in this repo.  In edgex-compose, modify add-security.yaml set EDGEX_SECRETS_ROOT to some other value.  Make run dev and verify that the chmod applies to the new directory path, and defaults to /tmp/edgex/secrets if unset.
=> feat: Make secrets base directory configurable

internal/core/metadata/application/device.go, internal/pkg/utils/time.go, internal/pkg/utils/time_test.go, internal/support/scheduler/application/interval.go
Add warn log for interval value from Interval and AutoEvent if the value is less than the suggested value.
Closes #4586.
Invoke the POST interval API with the following command:
```
curl --location 'http://localhost:59861/api/v3/interval' \
--header 'Content-Type: application/json' \
--data '  [ 
{
"apiVersion":"v3",
"interval":{
"name":"test",
"start":"20230707T094508",
"interval":"599us"
}
}
]'
```
The following warning log should be displayed in the support-scheduler log:
```
level=WARN ts=2023-07-05T07:27:29.922821Z …
```
=> fix: Add warn log for create/update interval

internal/core/command/main.go, internal/pkg/bootstrap/handlers/database.go
Closes: #4615
- git clone this PR
- build all services: `make build` 
- make sure your EdgeX stack is running insecure mode from edgex-compose/compose-builder: `make run no-secty`
- and then you would need to stop the service to test from the stack, like for example `docker stop edgex-core-data`
- to see the better error message and handling, you can start with `core-data`: change directory to `cmd/core-data`
- run the core-data in hybrid mode without any common config: `./core-data`, and you should see some better error …
=> feat: use a better error handling logic and messages when run in hybrid mode with no common config

openapi/v3/core-command.yaml
fixing core-command swagger file that has incorrect example and missing PUT parameters
Closes: #4629
following https://github.com/edgexfoundry/edgex-go/pull/4569 test instructions for fuzzing test, you will observe the fuzzing test coverage has increased for core-command after this fix.
=> fix: Fix core-command swagger file

fuzz_test/fuzzing_docker.sh
the FuzzLean test result is inside the FuzzLean folder and that needs to be copied into fuzz_results
Closes: #4636
make docker-fuzz
make fuzz-test-command
You should see "fuzz_test/fuzz_results/core-command/FuzzLean" folder not Test folder
=> fix: report FuzzLean result to fuzz_results folder

internal/core/command/controller/http/command_test.go, internal/pkg/utils/http.go
fixed fuzzing core-command http error 500 when invalid input in body http://localhost:59882/api/v3/device/name/Random-Boolean-Device/Bool
Closes: #4639
make docker-fuzz
make fuzz-test-command
1. after fuzz test is finished, open "/edgex-go/fuzz_test/fuzz_results/core-command/FuzzLean/RestlerResults/experiment113/bug_buckets", you should not see checker_500 error logs.
2. go back to edge-go, run `make test`, everything should pass
or you can verify it on postman:
PUT …
=> fix(security): core-command fuzzing test http error 500

cmd/security-proxy-setup/entrypoint.sh
Closes #4641
Fix crash caused by grep returning nonzero exit code during CORS configuration dump
"make docker" in edgex-go then "make run dev" in edgex-compose/compose-builder
=> fix(security): Fix crash in entrypoint.sh due to exit code

.hadolint.yml, cmd/security-spire-agent/Dockerfile, cmd/security-spire-config/Dockerfile, cmd/security-spire-server/Dockerfile
SPIRE project is now publishing prebuilt containers for linux/amd64 and linux/arm64 on their github project that have statically-linked spire-server and spire-agent components.  Rather than building locally, we can just reference the GHCR containers in a FROM line and directly pull in the binaries, without having to waste time building them.
"make docker" in this repo and "make run dev delayed-start ds-virtual" in edgex-compose/compose-builder and ensure all containers start properly.  This should be tested both on Intel and ARM64 architectures to be valid.
=> build: Pull spire-server and spire-agent from prebuilt containers

internal/core/command/controller/messaging/external.go, internal/core/command/controller/messaging/internal.go, internal/core/command/controller/messaging/internal_test.go, internal/core/command/controller/messaging/utils.go, internal/core/data/application/event.go, internal/core/data/controller/messaging/subscriber.go, internal/core/metadata/application/notify.go, internal/core/metadata/application/notify_test.go
Use escaped for message bus topic
- service name
- profile name
- device name
Close #4053
- Run unit test
- Run core service and device service to verify the API works with special char.
=> feat: Accept Url escape in API path

cmd/core-common-config-bootstrapper/res/configuration.yaml
Old elements were left in-place until all Device/App services got updated with the latest go-mod-bootstrap, which happened with the 3.0 release.
=> refactor: Remove old InsecureSecrets backward compatibility elements

cmd/security-proxy-setup/entrypoint.sh, snap/local/runtime-helpers/bin/security-bootstrapper-nginx
Access-Control-Allow-Credentials must be sent for non-preflight requests as well.  Note that this PR has TAF approval to send extra headers in order to avoid complicated boolean logic in the nginx rules.
TAF team will be testing: https://github.com/edgexfoundry/edgex-go/issues/4648
=> fix(security): Access-Control-Allow-Credentials is all CORS requests

cmd/core-common-config-bootstrapper/res/configuration.yaml
fixes #4684. Add LastConnected metric to device service common config.
=> feat: Add LastConnected metric to device service common config

internal/pkg/infrastructure/redis/notification.go, internal/support/notifications/application/notification.go
Query the latest notification and clean notification by modified date.
Close #4682
Test according to the issue description. https://github.com/edgexfoundry/edgex-go/issues/4682
=> fix: Purge notifications properly

cmd/core-common-config-bootstrapper/res/configuration.yaml
https://github.com/edgexfoundry/edgex-docs/pull/1237
Run non-secure Edgex Stack
View http://localhost:8500/ui/dc1/kv/edgex/v3/core-common-config-bootstrapper/app-services/Writable/Telemetry/Metrics/
Verify `HttpExportErrors` and `MqttExportErrors` are not present
build and run core-common-config-bootstrapper with overwrite flag
```
./core-common-config-bootstrapper -o -cp
```
View http://localhost:8500/ui/dc1/kv/edgex/v3/core-common-config-bootstrapper/app-services/Writable/Telemetry/Metrics/
Verify `HttpExportErrors` and `MqttExportErrors` …
=> feat: Add new export error metrics to App Service common config

Makefile
run `make docker` from this branch
run `make run ds-virtual ds-onvif-camera` from compose builder
verify all service are running as expected
verify access to core/support services via API Gateway
verify UI functions as expected (ie.e core/support endpoints functioning)
=> build: Add ldflags to strip debug info from binaries

go.mod, go.sum, internal/support/notifications/application/channel/sender.go, internal/support/notifications/init.go, openapi/v3/support-notifications.yaml
Closes #4747 
See https://github.com/edgexfoundry/edgex-go/issues/4747#issuecomment-1911312262
~~In draft state due to dependency on [change](https://github.com/edgexfoundry/go-mod-core-contracts/pull/880) in `go-mod-core-contracts`~~
=> feat: allow sending notifications to authenticated EdgeX endpoints

Attribution.txt
=> feat: update attributions

internal/core/metadata/application/device.go, internal/core/metadata/controller/http/device.go, internal/core/metadata/controller/http/device_test.go, openapi/v3/core-metadata.yaml
Fixes #4789. Add new bypassValidation query param to Add/Patch Device API.
=> feat: Add new bypassValidation query param to Add/Patch Device API

go.mod, go.sum, internal/core/metadata/application/deviceprofile.go, internal/core/metadata/controller/http/deviceprofile.go, internal/core/metadata/controller/http/deviceprofile_test.go, internal/core/metadata/router.go, openapi/v3/core-metadata.yaml
The Device Profile sometimes is very large with lots of device resources. Device Profile query may take lots of time and cause request timeout. A new GET /deviceprofile/basicinfo/all API would be helpful for the UI integration
- run core-metadata
- add device profile
- query the API /api/v3/deviceprofile/basicinfo/all
=> feat: Implement Get All DeviceProfile BasicInfo API

cmd/security-secretstore-setup/entrypoint.sh
=> feat: allow rules-engine service to read its token

internal/core/data/controller/messaging/subscriber.go
Please refer the discussion: [Subscribe/Publish Message bus topic - Need understanding on service communications #292](https://github.com/orgs/edgexfoundry/discussions/292) 
Conclusion: no logging for core-data subscription. 
Please note that I'm using a custom Makefile from [edgex-native-build](https://github.com/M0hanrajp/edgex-native-build) (My custom configurations)
* I have gone through [Working in a Hybrid Environment](https://docs.edgexfoundry.org/3.1/getting-started/Ch-GettingStartedHybrid/) and at this time this …
=> feat(core-data): Add message bus subscription log

cmd/support-cron-scheduler/res/db/sql/01-tables.sql, internal/pkg/infrastructure/postgres/schedulejob.go, internal/support/cronscheduler/application/schedulejob.go, internal/support/cronscheduler/infrastructure/manager.go
closes: #4856
- The scheduled job should be stopped if adminState is set to LOCKED
- Modify the timestamp in postgres DB
=> feat: Check AdminState in Cron Scheduler Service

internal/core/metadata/application/device.go, internal/core/metadata/application/device_test.go, internal/core/metadata/controller/http/device_test.go
The current auto event validation in core-metadata doesn't support regular expression, but it is supported by Device SDK. This change allow the regular expression is defined in auto event. Close https://github.com/edgexfoundry/edgex-go/issues/4865
=> fix: EDX-5196 Allow source name in regexp

cmd/core-data/res/db/sql/01-tables.sql, internal/pkg/db/postgres/utils.go, internal/pkg/infrastructure/postgres/consts.go, internal/pkg/infrastructure/postgres/event.go, internal/pkg/infrastructure/postgres/models/reading.go, internal/pkg/infrastructure/postgres/reading.go, internal/pkg/infrastructure/postgres/sql.go
Relates to #4847. Add core-data reading related db client methods for postgres client.
=> feat: Add core-data postgres reading db client methods

cmd/core-common-config-bootstrapper/res/configuration.yaml
The default auto discovery is disabled, but the default discovery is very short (30s).  When the user enables the auto discovery, it would trigger it every 30s by default.  This value doesn't fit the most of use cases.  By modifying it to 0s, the discovery scheduler will be disabled by default.
BREAKING CHANGE: If the user develops a Device Service with the auto
discovery mechanism and enable it, the discovery won't be automatically
triggered every 30s anymore.  Users have to define this
Device_Discovery_Interval: 30s in the Device Service to keep the
original behavior.
Close https://github.com/edgexfoundry/edgex-go/issues/4859 …
=> fix: Disable the default discovery scheduler

Attribution.txt, go.mod, internal/pkg/infrastructure/postgres/scheduleactionrecord.go, internal/pkg/infrastructure/postgres/schedulejob.go, internal/support/cronscheduler/application/scheduleactionrecord.go, internal/support/cronscheduler/application/scheduleactionrecord_test.go, internal/support/cronscheduler/application/schedulejob.go, internal/support/cronscheduler/init.go
This is the sixth PR of #4834
- Load and trigger the existing scheduled jobs from DB
- Calculate and generate the missed schedule action records
- Add missing dependency in Attribution.txt
=> feat: Generate Missed Schedule Action Records

cmd/core-data/res/configuration.yaml, cmd/core-metadata/res/configuration.yaml, cmd/support-notifications/res/configuration.yaml, cmd/support-scheduler/res/configuration.yaml
Relates to #4847. Add more db config in service private config in order to use env variable overwrite to support Postgres in some services.
=> fix: Add more db config in service private configuration

go.mod, go.sum, internal/pkg/infrastructure/postgres/scheduleactionrecord.go, internal/pkg/infrastructure/postgres/schedulejob.go, internal/pkg/infrastructure/postgres/sql.go, internal/support/cronscheduler/application/schedulejob.go, internal/support/cronscheduler/controller/http/schedulejob.go, internal/support/cronscheduler/controller/http/schedulejob_test.go, internal/support/cronscheduler/infrastructure/interfaces/db.go, internal/support/cronscheduler/infrastructure/interfaces/mocks/DBClient.go, openapi/v3/support-cron-scheduler.yaml
This is the eighth PR of #4834
- Support querying scheduleJob by labels
- Remove action id before storing schedule action record into database
The doc has been modified in the same commit.
=> feat: Support Querying ScheduleJob by Labels

internal/support/cronscheduler/application/schedulejob.go, internal/support/cronscheduler/controller/http/schedulejob_test.go
fixes #4883
Fixed the potential crashed issue while updating schedule action. Since there will be new actions being created after job updated, generating new action ID for each actions.
=> fix: Generate new action ID while updating schedule job

internal/pkg/infrastructure/postgres/scheduleactionrecord.go, internal/pkg/infrastructure/postgres/utils.go, internal/support/cronscheduler/application/scheduleactionrecord.go, internal/support/cronscheduler/controller/http/scheduleactionrecord_test.go, internal/support/cronscheduler/infrastructure/interfaces/db.go, internal/support/cronscheduler/infrastructure/interfaces/mocks/DBClient.go
fixes #4889
Fixed the mismatch timezone of start and end time parameters for querying schedule action records.
=> fix: Fix the wrong behavior when querying schedule action records

internal/pkg/bootstrap/handlers/database.go, internal/pkg/infrastructure/postgres/event.go, internal/pkg/infrastructure/postgres/models/reading.go, internal/pkg/infrastructure/postgres/reading.go, internal/pkg/infrastructure/postgres/sql.go
Fixes #4899. Fixes the struct field not found error when query reading in Postgres infra layer methods.
=> fix: Fix the error while query reading with Postgres

cmd/core-keeper/res/db/sql/00-utils.sql, cmd/core-keeper/res/db/sql/01-tables.sql, internal/core/keeper/controller/http/registry.go, internal/pkg/infrastructure/postgres/consts.go, internal/pkg/infrastructure/postgres/registry.go, internal/pkg/infrastructure/postgres/sql.go
Resolves #4877. Add the Keeper registry db methods for Postgres.
=> feat: Add the Keeper registry db methods for Postgres

cmd/core-keeper/Dockerfile, cmd/core-keeper/res/db/sql/01-tables.sql, internal/pkg/infrastructure/postgres/kv.go
Relates to #4877. Return 404 response for Keeper GET key API with Postgres. Copy res/db dir in Keeper Docker file.
=> fix: Return 404 response for Keeper GET key API with Postgres

.golangci.yml, Attribution.txt, Makefile, cmd/core-command/Dockerfile, cmd/core-common-config-bootstrapper/Dockerfile, cmd/core-data/Dockerfile, cmd/core-keeper/Dockerfile, cmd/core-metadata/Dockerfile, cmd/security-bootstrapper/Dockerfile, cmd/security-proxy-auth/Dockerfile, cmd/security-proxy-setup/Dockerfile, cmd/security-secretstore-setup/Dockerfile, cmd/security-spiffe-token-provider/Dockerfile, cmd/security-spire-agent/Dockerfile, cmd/security-spire-config/Dockerfile, cmd/security-spire-server/Dockerfile, cmd/support-cron-scheduler/Dockerfile, cmd/support-notifications/Dockerfile, cmd/support-scheduler/Dockerfile, go.mod, internal/support/cronscheduler/infrastructure/manager.go
Upgrade to go-1.23, Linter1.61.0 and Alpine 3.20
Run make test, make build, make docker commands.
=> build: Upgrade to go-1.23, Linter1.61.0 and Alpine 3.20

cmd/security-proxy-setup/entrypoint.sh, cmd/support-cron-scheduler/res/db/sql/00-utils.sql, cmd/support-cron-scheduler/res/db/sql/01-tables.sql, internal/pkg/infrastructure/postgres/consts.go
Resolves #4930.
- Add /support-cron-scheduler path in API gateway
- Rename support_scheduler schema to support_cron_scheduler
=> fix: Add /support-cron-scheduler path in API gateway

internal/pkg/infrastructure/postgres/scheduleactionrecord.go
The intention here should be to initialize a slice with a capacity of  `len(scheduleActionRecords)`  rather than initializing the length of this slice. 
The online demo: https://go.dev/play/p/q1BcVCmvidW
=> fix: fix slice init length

internal/security/bootstrapper/helper/postgres_script.go, internal/security/bootstrapper/helper/postgres_script_test.go
Resolves #4945. Escape dash in Postgres init db script for schema and username of Security Bootstrapper.
=> fix: Escape dash in Postgres init db script

internal/core/metadata/application/deviceprofile.go, internal/core/metadata/application/deviceservice.go, internal/core/metadata/controller/http/deviceprofile_test.go, internal/core/metadata/controller/http/deviceservice_test.go
=> fix: Delete device profile in use should return 409

go.mod, go.sum, internal/core/data/application/event_test.go, internal/core/data/controller/http/event_test.go, internal/pkg/infrastructure/postgres/reading.go, internal/pkg/infrastructure/redis/reading_test.go
- Test with simple device service
- Run make test
=> feat: Allow store reading as null value

.gitignore, Makefile
closes #4916
Run the following command to build binaries
```
make build
```
And the following command to check `Full RELRO` and `PIE` are enabled
```
checksec --file=./cmd/core-data/core-data
RELRO           STACK CANARY      NX            PIE             RPATH      RUNPATH	Symbols		FORTIFY	Fortified	Fortifiable	FILE
Full RELRO      No canary found   NX enabled    PIE enabled     No RPATH   No RUNPATH   No Symbols	  Yes	2		2		./cmd/core-data/core-data
```
=> feat: Enable ASLR and Full RELRO while building binaries

cmd/support-cron-scheduler/res/configuration.yaml, internal/pkg/infrastructure/postgres/scheduleactionrecord.go, internal/support/cronscheduler/application/scheduleactionrecord.go, internal/support/cronscheduler/application/scheduleactionrecord_test.go, internal/support/cronscheduler/config/config.go, internal/support/cronscheduler/infrastructure/interfaces/db.go, internal/support/cronscheduler/infrastructure/interfaces/mocks/DBClient.go, internal/support/cronscheduler/init.go
closes #4912
https://github.com/edgexfoundry/edgex-docs/pull/1377
=> feat: Schedule action record retention implementation

internal/core/metadata/application/device.go, internal/core/metadata/application/device_test.go, internal/core/metadata/application/provisionwatcher.go, internal/core/metadata/controller/http/provisionwatcher_test.go
=> fix: Check profile existence before adding device/provision watcher

go.mod, go.sum, internal/core/data/controller/http/event_test.go, internal/pkg/infrastructure/postgres/sql.go, internal/pkg/infrastructure/postgres/transmission.go
also upgrade go-mod-core-contracts to latest version
close #4965
=> fix: fix delete transmission by age with Postgres

go.mod, go.sum, internal/core/data/application/event_test.go, internal/core/data/controller/http/event_test.go, internal/pkg/infrastructure/postgres/reading.go, internal/pkg/infrastructure/redis/reading.go, internal/pkg/infrastructure/redis/reading_test.go
- make test
- test with simple DS
=> feat: Using isNull field instead of nil reading value

internal/core/data/application/event.go, internal/core/data/application/reading.go, internal/core/data/controller/http/event_test.go, internal/core/metadata/application/device.go, internal/core/metadata/application/deviceprofile.go, internal/core/metadata/application/deviceservice.go, internal/core/metadata/application/provisionwatcher.go, internal/core/metadata/controller/http/device_test.go, internal/core/metadata/controller/http/deviceprofile_test.go, internal/core/metadata/controller/http/deviceservice_test.go, internal/core/metadata/controller/http/provisionwatcher_test.go, internal/pkg/infrastructure/postgres/device_profile.go, internal/pkg/infrastructure/postgres/reading.go, internal/pkg/utils/count.go, internal/pkg/utils/count_test.go, internal/support/cronscheduler/application/scheduleactionrecord.go, internal/support/cronscheduler/application/schedulejob.go, internal/support/cronscheduler/controller/http/scheduleactionrecord_test.go, internal/support/notifications/application/notification.go, internal/support/notifications/application/subscription.go, internal/support/notifications/application/transmission.go, internal/support/notifications/controller/http/subscription_test.go, openapi/v3/core-metadata.yaml, openapi/v3/support-cron-scheduler.yaml, openapi/v3/support-scheduler.yaml
=> fix: check offset, limit, totalCount before executing query

cmd/core-keeper/res/configuration.yaml
Fixes #4980. Add the Database related config back to Core Keeper.
=> fix: Add the Database related config back to Core Keeper

openapi/core-metadata.yaml
The onChange flag in Device AutoEvent can prevent any non changed values sent out. The onChangeThreshold could provide the advanced feature, and the default value is 0, any changed value that exceeds (>) bounds shall be published.
=> docs: Add onChangeThreshold in Device AutoEvent

internal/support/notifications/application/transmission.go, internal/support/notifications/controller/http/transmission_test.go
=> fix: check offset, limit, totalCount before querying transmissions

go.mod, go.sum, internal/core/keeper/controller/http/kv_test.go
As real implementation of NewMessageClient will require existing MQTT/NATS broker to access to, the unit tests should use Mocking MessageClient to avoid errors.
=> fix: use mocking MessageClient in unit tests

internal/pkg/infrastructure/postgres/reading.go
Allow null reading for Postgres
Run make test, test with core services.
=> feat: Allow null reading for Postgres

cmd/core-keeper/res/db/sql/01-tables.sql, cmd/support-scheduler/res/db/sql/01-tables.sql
Using current time in UTC as default in Postgresql for created and modified time.
Test with core service and support scheduler.
=> fix: Using current time in UTC as default in Postgresql

cmd/core-command/main.go, cmd/core-common-config-bootstrapper/main.go, cmd/core-data/main.go, cmd/core-keeper/main.go, cmd/core-metadata/main.go, cmd/secrets-config/main.go, cmd/security-bootstrapper/main.go, cmd/security-file-token-provider/main.go, cmd/security-proxy-auth/main.go, cmd/security-secretstore-setup/main.go, cmd/security-spiffe-token-provider/main.go, cmd/support-notifications/main.go, cmd/support-scheduler/main.go, internal/core/command/main.go, internal/core/common_config/main.go, internal/core/data/main.go, internal/core/keeper/main.go, internal/core/metadata/main.go, internal/security/bootstrapper/main.go, internal/security/config/main.go, internal/security/fileprovider/main.go, internal/security/proxyauth/main.go, internal/security/secretstore/main.go, internal/security/spiffetokenprovider/main.go, internal/support/notifications/main.go, internal/support/scheduler/main.go
fixes https://github.com/edgexfoundry/edgex-go/issues/5009
There is a user requirement that prefers to combine all core services into a single monolithic service. To easily achieve this based on current code structure, refactor following codes:
1. Change the signature of main function for each core services to allow pass os arguments rather than directly parse `os.Args[1:]`. With this change, the single monolithic service can alter the behavior of each individual internal services by passing different arguments.
2. Remove `os.Exit(0)` by end of a successful run of common_config_bootstrapper. This call is redundant and will force monolithic service to exit directly. …
=> feat: refactor services to build monolithic service easily

internal/security/proxyauth/main.go
=> fix: Use correct service key for security proxy auth

internal/pkg/infrastructure/postgres/event.go, internal/pkg/infrastructure/postgres/reading.go
=> fix: Fix invalid limit issue with PostgreSQL

Attribution.txt, cmd/support-notifications/Dockerfile, go.mod, go.sum, internal/support/notifications/application/channel/container.go, internal/support/notifications/application/channel/mqtt.go, internal/support/notifications/application/channel/sender.go, internal/support/notifications/application/channel/zmq.go, internal/support/notifications/application/send.go, internal/support/notifications/application/subscription.go, internal/support/notifications/application/subscription_test.go, internal/support/notifications/controller/http/subscription_test.go, internal/support/notifications/init.go, openapi/support-notifications.yaml
=> feat: Add MQTT and ZeroMQ channels support to support-notification

cmd/security-secretstore-setup/res/configuration.yaml
=> fix: Remove unused users from the database user creation

cmd/core-data/res/db/sql/01-tables.sql
Using id and origin as the index for TimescaleDB integration.
Since we try to integrate the TimescaleDB as the time series db, we combine `id` and `origin` as the index. 
- replace postgres with timescaleDB
- run SQL to create the hypertable: `SELECT create_hypertable('reding', by_range('origin')); `
- run SQL to set the chunk interval: `SELECT set_chunk_time_interval('reading', 604800000000000);` -- 604800000000000 nanoseconds is for a chunk is 7 days
- check whether the chunk is created `select * from …
=> feat: Update reading table schema

cmd/security-proxy-auth/Dockerfile, go.mod, go.sum
Relates to #5038. Update go-mod-bootstrap version and proxy-auth dockerfile.
=> fix: Upgrade go-mod-bootstrap version

cmd/security-proxy-setup/entrypoint.sh
Relates to #5038. Add the POST /key path to API gateaway from security-proxy-auth.
=> fix: Add the /key path to API gateaway

go.mod, go.sum, internal/core/data/main.go, internal/core/keeper/main.go, internal/core/metadata/main.go, internal/security/proxyauth/main.go, internal/support/notifications/main.go
Fixes #5054. Add svc client handler to some services to fix the panic.
=> fix: Add svc client handler to some services

cmd/security-bootstrapper/entrypoint-scripts/postgres_wait_install.sh, internal/security/bootstrapper/helper/postgres_script.go, internal/security/bootstrapper/helper/postgres_script_test.go, internal/security/bootstrapper/postgres/configure.go, internal/security/bootstrapper/postgres/handlers/handlers.go, internal/security/secretstore/init.go
Resolves #5050. Save postgres superuser password in secretstore.
=> feat: Save postgres superuser password in secretstore

internal/core/data/application/reading.go, internal/core/data/controller/http/reading.go
Query readings without pagination offset to prevent large dataset query and count.
(cherry picked from commit 1a89671151ac64faeeb06f70b556460da8f76616)
Run core service and query reading without offset, the core data will not use SQL count and offset to prevent performance issue.
=> feat: Query readings without pagination offset

cmd/core-data/res/configuration.yaml, internal/core/data/config/config.go, internal/core/data/controller/messaging/system_event.go, internal/core/data/init.go
To purge the redundant events and readings, remove the related events and readings once received the device deletion system event.
fixs #5061
(cherry picked from commit 481bac23ae2783e5fdad02be5b4ce3f7b675fd66)
- enable the EventPurge
- add a device with auto event
- remove the device and check the events and readings should be removed
=> feat: Allow purging events

cmd/core-keeper/res/configuration.yaml, internal/core/data/config/config.go, internal/core/metadata/config/config.go, internal/security/proxyauth/config/config.go, internal/support/notifications/config/config.go
Relates to #5054. Add clients field to service config.
=> fix: Add clients to service config

internal/core/metadata/application/device.go, internal/core/metadata/application/device_test.go, internal/core/metadata/controller/http/device.go, internal/core/metadata/controller/http/device_test.go, internal/core/metadata/infrastructure/interfaces/db.go, internal/core/metadata/infrastructure/interfaces/mocks/DBClient.go, internal/pkg/infrastructure/postgres/consts.go, internal/pkg/infrastructure/postgres/device.go, internal/pkg/infrastructure/redis/client.go, internal/pkg/infrastructure/redis/device.go, openapi/core-metadata.yaml
=> feat(metadata): Add query parameters for device parents/children.

internal/pkg/db/postgres/migration.go
related to https://github.com/edgexfoundry/edgex-go/issues/5072
The orignal initialVersion is specified as 4.0.0, which will cause services with version 4.0.0-dev.XX below the db schema version and fails to initialize the postgreSQL client.
Specify the initialVersion to 4.0.0-dev to avoid this.
1. Add a `VERSION` file with following content in the repository:
```
4.0.0-dev.22
```
2. Build docker images for core-data, core-keeper, core-metadata, support-notifications, support-scheduler, security-proxy-auth:
```
make ddata …
```
=> feat: revise DB schema initialVersion to 4.0.0-dev

cmd/core-data/res/configuration.yaml, internal/core/data/application/reading.go
Update default event retention interval to 168h.
=> feat: Update default event retention duration

go.mod, go.sum, internal/security/common/usermanager.go, internal/security/fileprovider/command/createtoken/command.go, internal/security/fileprovider/command/handlers/init.go, internal/security/fileprovider/tokenprovider/provider.go, internal/security/fileprovider/tokenprovider/provider_test.go, internal/security/secretstore/controller/token.go, internal/security/secretstore/server/handlers/router.go
Relates to #5065. Update create token params while invoking the secretstore-setup regenToken API.
=> fix: Update create token params for regenToken API

internal/core/common_config/main.go, internal/core/common_config/utils.go, internal/core/common_config/utils_test.go
Fixes #5086. Compose env override not works for Common Config.
=> fix: Compose env override not works in Common Config

cmd/security-file-token-provider/res/token-config.json, internal/security/common/usermanager.go
Fixes #5089. Add create token role permission to security-spiffe-token-provider.
=> fix: Add create token role permission to security-spiffe-token-provider

cmd/core-common-config-bootstrapper/res/configuration.yaml, cmd/security-secretstore-setup/res/configuration.yaml
Relates to #5082. Revert EnableNameFieldEscape service config back to false.
=> fix: Revert EnableNameFieldEscape config back to false

internal/core/data/embed/sql/idempotent/01-tables.sql
Since the id is not important to event, remove UNIQUE constraint from event to improve insert speed
=> feat: Optimize Postgres Event schema

.gitignore, vendor/github.com/go-openapi/analysis/internal/debug/debug.go
The original `.gitignore` contain debug, which will ignore `vendor/github.com/go-openapi/analysis/internal/debug/debug.go` and fails the `make test` during build. Update .gitignore to only ignore the debug folder in the top level.
=> build: Update .gitignore and vendor debug pkg

.golangci.yml
Previously golangci-lint run use default timeout 1m, and we may occasionally see timeout exceeding error that fails the build.
This commit add timeout option to 5m for golangci-lint.
=> build: set timeout option for running lint

internal/pkg/utils/restaddress.go
This is to fix an error for support-notifications with followng case: users add a subscription with Rest type channel but doesn't specify shceme will result in empty scheme when sending notifications, thus failing the sending operation.
This fix is to specify default http scheme when scheme is empty.
=> fix: fix error when empty scheme in Rest channel

go.mod
Per https://github.com/dependabot/dependabot-core/issues/11825 and https://github.com/dependabot/dependabot-core/pull/11826 , the dependabot has been updated to use GOTOOLCHAIN=go1.24.1 and it will add toolchain in go mod tidy when the go directive is specified with language version(1.N). As we don't want to the toolchain to be specified with go1.24.1, change the go directive to released version(1.N.P).
=> build: update go.mod with released version

openapi/core-metadata.yaml
The sample for POST new device specifies string for both Port and UnitID, which are incorrect and should be corrected to use numbers.
=> docs: update core-metadata API doc with correct sample

internal/core/data/application/event.go, internal/core/data/controller/http/const.go, internal/core/data/controller/http/event.go, internal/core/data/controller/http/event_test.go, internal/core/data/controller/http/reading.go, openapi/core-data.yaml
fixes https://github.com/edgexfoundry/edgex-go/issues/5134
Query events without total count to prevent large dataset query and count.
Run core service and device service to test the event or reading count.
=> feat: Query events without total count

openapi/core-metadata.yaml
=> fix: added missing retention field on core-metadata API docs

internal/core/command/application/command.go, internal/core/command/application/command_test.go
CoreCommand GET /device/all API check whether device profile is empty, if empty skip the profile query for the specific device.
Close #5163
Run core service and device virtual, and test the API for the device with empty profile name.
=> fix: CoreCommand GET /device/all API check profile is empty

internal/pkg/db/postgres/utils.go
converts a path to the format required for go embed by using '/' as the separator. Close https://github.com/edgexfoundry/edgex-go/issues/5150
See https://github.com/edgexfoundry/edgex-go/pull/5151
=> fix: Windows path in db init sql

internal/core/data/embed/sql/versions/4.1.0-dev/00-tables.sql, internal/pkg/infrastructure/postgres/consts.go, internal/pkg/infrastructure/postgres/deviceinfo.go, internal/pkg/infrastructure/postgres/event.go, internal/pkg/infrastructure/postgres/models/deviceinfo.go, internal/pkg/infrastructure/postgres/reading.go, internal/pkg/infrastructure/postgres/sql.go
CoreData should not return the events when enabling EventPurge and removing device from metadata. This issue occurs when user want to purge large amount of event data.
- Adds mark_deleted field to CoreData deviceInfo table
- Marks deviceInfo as deletable before deleting events adn readings
- Add mark_deleted
Close #5175
- Deploy core service and device-virtual
- Insert million of events readings data
- Remove a device
- Query the event by the deleted device from the DB
- Check whether the related events do not exist
=> fix: Fix event query incorrect return data when enabling EventPurge

internal/core/command/controller/messaging/internal.go
fix: #5152 
1. Deploy core services, device-modbus, and modbus-simulator.
2. Add a Modbus device to core-metadata.
3. Stop modbus-simulator.
4. While the simulator is offline, asynchronously send 100 command requests.
5. Restart modbus-simulator.
6. Verify that `core-command` service is still able to handle command requests once the simulator is back online.
=> fix: Run MessageBus command request processing in goroutines

internal/core/data/application/reading.go, internal/core/data/application/reading_test.go, internal/pkg/cache/device.go
CoreData apply default retention policy to events not coming from auto events
Close #5188
Deploy core service and device-virtual to test the event purge.
=> fix: CoreData apply default retention policy to none autoEvent

internal/pkg/infrastructure/postgres/consts.go, internal/pkg/infrastructure/postgres/deviceinfo.go, internal/pkg/infrastructure/postgres/event.go, internal/pkg/infrastructure/postgres/reading.go, internal/pkg/infrastructure/postgres/scheduleactionrecord.go, internal/pkg/infrastructure/postgres/sql.go
Improve SQL statement by using the namedArgs instead of position namer.
Deploy core service and test with edgex-taf functional test.
=> feat: CoreData improve SQL statement

internal/pkg/infrastructure/postgres/consts.go, internal/pkg/infrastructure/postgres/device.go, internal/pkg/infrastructure/postgres/device_profile.go, internal/pkg/infrastructure/postgres/device_service.go, internal/pkg/infrastructure/postgres/provision_watcher.go, internal/pkg/infrastructure/postgres/sql.go
Improve SQL statement by using the namedArgs instead of position namer.
deploy core-service, device-virtual, device-modbus, device-rest and test with edgex-taf.
=> feat: CoreMetadata improve SQL statement

cmd/core-common-config-bootstrapper/res/configuration.yaml
Relates to #5203. Modify SendChangedReadingsOnly default value to false.
=> fix: Modify SendChangedReadingsOnly default value to false

cmd/core-common-config-bootstrapper/res/configuration.yaml, cmd/core-data/res/configuration.yaml, cmd/core-keeper/res/configuration.yaml, internal/pkg/bootstrap/handlers/database.go, internal/pkg/db/db.go, internal/pkg/db/postgres/client.go
Add Postgres ConnPool Config for user to tune the ConnPool.
This PR is based on the go-mod-bootstrap config changes https://github.com/edgexfoundry/go-mod-bootstrap/pull/892
- Change the config 
- Deploy core service, device service
- Execute the event or reading REST API
- Verify the conn stats by the command
```
docker exec edgex-postgres psql -U postgres -d edgex_db -a -c "select pid, state, query from pg_stat_activity WHERE datname='edgex_db'"
```
=> feat: Add Postgres ConnPool Config

internal/core/common_config/main.go
Add retry logic to wait for core-keeper available, the config bootstrap will retry to send put request to core-keeper if failed.
fix #5236
Deploy services to check the retry logic.
=> fix: Fix common config bootstrap startup failed in no-secty mode

internal/pkg/infrastructure/postgres/reading.go, internal/pkg/infrastructure/postgres/reading_test.go, internal/pkg/infrastructure/postgres/readingagg.go, internal/pkg/infrastructure/postgres/readingagg_test.go
Fixes #5251. Fix the incorrect reading value with trailing zero.
=> fix: Fix the incorrect reading value with trailing zero
