edgexfoundry/edgex-go

.gitignore
cmd/core-command/main.go
cmd/core-data/main.go
cmd/core-metadata/main.go
core/data/init.go

Service cleanup -- restructuring of core-data initialization, including cmd line flag for Consul(Y/N) and Profile (default vs Docker). Also used service name constants in log init message instead of hard-coded strings.

Refactoring core-data

---

.gitignore

current if user build and the project will create some binary and log files we should filter them.
Signed-off-by: vinoyang <vinoyang@tencent.com>

add some ignore items to filter built binary and log files

---

support/notifications-client/client_test.go

hi @drasko and @feclare , I add a test for support notification client because I find this call : 
https://github.com/edgexfoundry/edgex-go/blob/master/support/notifications-client/client.go#L91
will not trigger a real remote request if it run in a new `goroutine`.
Please review this test, I will try to refactor the notification client and this test code. Thanks!

#50 add test for support notifications client

---

.gitignore

The `.DS_Store` always exists in any dir in mac os x as a system hidden file to store the dir's metadata. If we create a new dir in project (and in it's sub dir), it would be created. So we'd better filter it.

add a ignore item to filter mac os x system hidden file

---

cmd/core-command/res/configuration-docker.json

Replacement for PR #38 which was blocked due to sign-off missing.

Fix missing comma (parse error) core/command/config-docker

---

core/domain/enums/admin-state.go
core/domain/enums/admin-state_test.go
core/domain/enums/database.go
core/domain/enums/database_test.go
core/domain/enums/operating-state.go
core/domain/enums/operating-state_test.go

There was a panic if trying to convert to string some invalid values.
Added tests to AdminState and OperatingState
protocol.go is not used anywhere, should be removed
database.go is only used by metadata, should be moved to core/metadata/

Improve core/domain/enums and tests

---

pkg/config/config.go

PR for this issue: https://github.com/edgexfoundry/edgex-go/issues/26

Accept config directory from ENV variable

---

docker/Dockerfile.core-command
docker/Dockerfile.core-data
docker/Dockerfile.core-metadata
docker/Dockerfile.export-client
docker/Dockerfile.export-distro
docker/Dockerfile.support-logging

The default mirrors are not responsive and are
timing out the builds periodically.

Switch mirrors for alpine image apk update

---

pkg/config/config.go
pkg/config/config_test.go

Order of precedence:
1.) Command line
2.) Environment variable
3.) Hard-coded default path
Pertains to isse https://github.com/edgexfoundry/edgex-go/issues/26

Config File Location via Command Line Support

---

cmd/core-metadata/res/configuration-docker.toml

Replace equals sign with colon to correct consul and logging URLs.
Signed-off-by: Justin Scott <justin.a.scott@intel.com>

Fix typos in URLs for core-metadata's docker toml

---

cmd/core-command/main.go
cmd/core-data/main.go
cmd/core-metadata/main.go
cmd/support-logging/main.go
docker/Dockerfile.core-command
docker/Dockerfile.core-data
docker/Dockerfile.core-metadata
docker/Dockerfile.support-logging
pkg/usage/usage.go

1.) Integrated supported cmd line params into docker files for
core-command, core-data, core-metadata, support-logging.
2.) Modified handling of --consul cmds line param. Since it is
effectively a boolean, removed necessity to specify --consul=y
3.) In docker files, configuration-docker.toml cannot be renamed
to configuration.toml or else the file will not be found.
This is due to the --profile cmd line value handling.
Issue https://github.com/edgexfoundry/edgex-go/issues/160

Adding command line params to docker entrypoints

---

docs/configuration/Ch-Configuration.rst

Reference to docker-hub edgex/docker-edgex-core-consul does not exist.
Replaced with edgexfoundry/docker-core-consul.
Signed-off-by: Paul Butler <butler.paul@gmail.com>

repairs typo in repository reference

---

support/consul-client/consul.go

1.) Removed redundant call to obtain DefaultConfig() from consulapi. Empty properties are
populated within the NewClient() call in the exact same manner, so no need for this.
2.) All health checks on a given agent must be uniquely named, so added service name.
Issue https://github.com/edgexfoundry/edgex-go/issues/170

Fixed service health check registration in Consul

---

Makefile

This will help me try out my publish scripts.
The issue this solves happens on the Cavium
build machine and can potentially have several docker
builds happening at one time.  This way I can query for
a specific builds generated docker images in an easy way.

Add GIT_SHA to a docker tag

---

Makefile

It is easier for me to filter on a label
and less error prone.  Additionally, labels are
internal to an image and therefore better suited
in most cases.

Add git_sha label during build of images

---

core/domain/models/command.go

The approach here was to utilize UnmarshalJSON() on the Command domain
model in order to ensure that both Get and Put are initialized. The
bug was caused because the sample request did not have a GET so when
Mongo tried to call Get.String() it panicked due to NIL reference.
I wanted a solution that would NOT entail adding nil checks throughout the code base. We should be able to rely on whether or not a given property is initialized when deserializing.
#223 

Addressing panic from issue #223

---

cmd/core-command/main.go
cmd/core-data/main.go
cmd/core-metadata/main.go
cmd/support-logging/main.go
core/command/const.go
core/data/const.go
core/metadata/const.go
internal/constants.go
support/logging/const.go

Partially related to #173.
This will be used in the work for #182. Some global location holding the keys to services registered in Consul has to be available for all services. Instead of having the URL in a config file, the key will be in Consul and a dependent service has to know what to ask for. In other words, core-data needs to know core-metadata's key without referencing /core/metadata.

Relocated constants for service naming/keys

---

core/data/raml/core-data.raml
core/metadata/raml/core-metadata.raml
core/metadata/rest_deviceservice.go

Please note the addition of a 400 Bad Request response to the metadata
restAddDeviceService() function wherein we are able to validate that
the supplied request is missing information.
#201 

Updated RAML per issue #201

---

export/distro/registrations.go
export/distro/xmpp.go
export/distro/xmpp_test.go
export/registration.go
glide.yaml

cc @janko-isidorovic @drasko and @jpwhitemn 
hi all, 
I have implemented a XMPP export connector and tested it with [hangouts](https://hangouts.google.com/).
there are some statement list below: 
* test code based on the [go-xmpp](https://github.com/mattn/go-xmpp)'s [example code](https://github.com/mattn/go-xmpp/blob/master/_example/example.go)
* there is not a suitable XMPP public server, I have tried to find some servers but there are a few problem, so I used [hangouts](https://hangouts.google.com/), it can be connected with a XMPP protocol.
* someone who want to test it, just fill two config item in `xmpp_test.go` file (I have given the comment) and open a switch variable `testFlag`, more details about XMPP configuration please see [XMPP …

XMPP export connector

---

cmd/export-client/main.go
export/client/clients/database-client.go

Making export-client exit when there no connection to the database

Fix export-client when there is no db connection

---

core/data/clients/memory-database_test.go
core/data/clients/mongo-client.go
core/data/clients/mongo-client_test.go

Added core-data database benchmark for events and readings. This are the results using MemoryDB:
```
BenchmarkMemoryDB/AddReading-4         	 2000000	       932 ns/op
BenchmarkMemoryDB/Readings-4           	1000000000	         2.49 ns/op
BenchmarkMemoryDB/ReadingCount-4       	2000000000	         1.96 ns/op
BenchmarkMemoryDB/ReadingById-4        	   10000	    452221 ns/op
BenchmarkMemoryDB/ReadingsByDevice-4   	   10000	   6302543 ns/op
BenchmarkMemoryDB/AddEvent-4           	  500000	      2478 ns/op
BenchmarkMemoryDB/Events-4             	1000000000	         2.49 ns/op
BenchmarkMemoryDB/EventCount-4         	2000000000	         1.97 ns/op
BenchmarkMemoryDB/EventById-4          	   10000	    445389 ns/op
BenchmarkMemoryDB/EventsForDevice-4    	     300	   5457085 ns/op
```
Using MongoDB: …

Added core-data database benchmark

---

snap/snapcraft.yaml

This upgrades the version of consul that is used in the snap.

snap/snapcraft.yaml: upgrade consul version to v1.2.0

---

snap/snapcraft.yaml

This should fix builds such as https://jenkins.edgexfoundry.org/view/Snap/job/edgex-go-snap-master-stage-snap/5/consoleFull
See specifically:
```
15:41:44 ==> Building Consul - OSes: linux, Architectures: amd64
15:41:44 tput: No value for $TERM and no -T specified
15:41:44 tput: No value for $TERM and no -T specified
15:41:44 tput: No value for $TERM and no -T specified
15:41:44 Using gox for concurrent compilation
15:41:44 tput: No value for $TERM and no -T specified
15:41:45 Number of parallel builds: 3
15:41:45 
15:41:45 -->     linux/amd64: github.com/hashicorp/consul
15:42:13 
15:42:13 1 errors occurred:
15:42:13 --> linux/amd64 error: exit status 2
15:42:13 Stderr: # github.com/hashicorp/consul/vendor/google.golang.org/grpc/encoding/proto
15:42:13 …
```

snap/snapcraft.yaml: upgrade go to v1.10.2

---

core/db/memory/metadata.go
core/db/mongo/metadata.go
core/db/test/db_metadata.go
core/metadata/interfaces/db.go
core/metadata/rest_addressable.go
core/metadata/rest_device.go
core/metadata/rest_deviceprofile.go
core/metadata/rest_devicereport.go
core/metadata/rest_deviceservice.go
core/metadata/rest_provisionwatcher.go
core/metadata/rest_scheduleevent.go

Data base delete methods have been modified in core-metadata in order to work in the same way as in core-data.

Modified delete methods in core-metadata

---

snap/snapcraft.yaml

This is a duplicate of #345 but for california

snap build: use govendor install instead of sync

---

snap/snapcraft.yaml

Use 'govendor init' instead of 'govendor sync'.

[snap] Fix consul build failure

---

core/clients/types/endpoint.go

I observed 200% CPU utilization by core-command and core-data processes.
Profiler showed that culprit is time.Now().After() buzy-loop in
Endpoint.Monitor.
It truly spins for 15 seconds after each "ch" consumption.
Depending on consumption rate it might spin "infinitely"
$ go tool pprof core-command core-command.prof
File: core-command
Type: cpu
Time: Jul 10, 2018 at 3:24pm (PDT)
Duration: 14.52s, Total samples = 28.48s (196.11%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) top10 -cum
Showing nodes accounting for 28430ms, 99.82% of 28480ms total
Dropped 51 nodes (cum <= 142.40ms)
flat  flat%   sum%        cum   cum%
0     0%     0%    21840ms 76.69%  runtime._System /usr/lib/golang/src/runtime/proc.go
20430ms 71.73% 71.73%    20430ms 71.73% …

Use sleep instead of busy-wait

---

snap/snapcraft.yaml

The snap builds many parts from other repositories (eg. consul, config-seed-go, device-virtual). This change updates the non-edgex-go parts to use specify **source-branch: california**.
Note, attempting to build the snap using this PR results in a build failure in core-config-seed-go as the names of the service config directories don't match the names in the master branch of **core-config-seed-go**. See the following issue for the details:
https://github.com/edgexfoundry/core-config-seed-go/issues/22

[snap] Update to use 'california' branches

---

export/client/clients/database-client.go
export/client/clients/memory-database.go
export/client/clients/memory-database_test.go
internal/pkg/db/memory/data.go
internal/pkg/db/test/db_data.go

It was returning null instead of empty array when a registration was never added.

export-client: Fix getting no registrations from memorydb

---

snap/snapcraft.yaml

Fix the core-config-seed-go config paths, as the
changes were only made in the california branch,
and when the snap was updated to use california
branches for the non-edgex-go repos, the build
broke.

[snap] Fix core-config-seed-go install

---

Makefile

Use long git sha to reduce chance of collision

---

cmd/core-data/main.go
internal/core/data/init.go

#458 
Also made change in init.go to explicitly set dbClient to nil if connection fails. Otherwise Init() function may return incorrect success.

Main.go unused function, wrong key, dbClient nil

---

bin/edgex-docker-launch.sh
bin/edgex-launch.sh

Add Support-Notifications to 'make run'. Ensure that the 'make run_docker' command starts the relevant container.
- Per developer testing, here is the relevant snippet from starting the Support Notifications Micro Service outside a container:
`INFO: 2018/08/07 08:03:30 Starting edgex-support-notifications 0.7.0 
INFO: 2018/08/07 08:03:30 This is the Support Notifications Micro Service
INFO: 2018/08/07 08:03:30 Service started in: 22.058701ms
INFO: 2018/08/07 08:03:30 Listening on port: 48060
INFO: 2018/08/07 08:03:30 Service dependencies resolved...
`
- Also per developer testing, here is the relevant snippet from starting the Support Notifications Micro Service _inside_ a container:
`Starting support-notifications
Pulling notifications (edgexfoundry/docker-support-notifications:0.6.0)... …

Add Support-Notifications to 'make run'.

---

docs/api/Ch-APICoreMetadata.rst
docs/api/Ch-ExamplesAPIDemo.rst

Fix documentation links to raml files in their old location. Fixes #462

---

export/client/clients/mongo-client.go
internal/core/data/event.go
internal/core/metadata/rest_device.go
internal/pkg/db/mongo/notifications.go
internal/support/logging/server.go
internal/support/notifications/sending_service.go

Replaced all `time.Now().UnixNano() / int64(time.Millisecond)` by `db.MakeTimestamp()`
As this is a very simple PR, no issue it's created (but will be created if required)

Use db.MakeTimestamp

---

snap/bin/start-edgex.sh
snap/hooks/install
snap/snapcraft.yaml

For 0.6.1 the go version of support-notifications
was added, so update the snap to use it.

[snap] Update to support-notifications-go

---

docs/device/Ch-DeviceServices.rst

The device service documentation page contained a link to a very old version (v3) of the Device Services & SDK requirements document.  This change updates it to the point to the latest version.

[doc] Update SDK reqs link to point to latest (v8)

---

pkg/clients/metadata/schedule.go
pkg/clients/metadata/schedule_test.go
pkg/clients/metadata/scheduleevent.go
pkg/clients/metadata/scheduleevent_test.go

This commit adds public REST clients for Core Metadata's **schedule** and **scheduleevent** endpoints.  These are needed to allow device-sdk-go to query and add both object types.

Add schedule related clients

---

snap/bin/security-start.sh

This should fix issue #509 because the issue there was that we didn't have permissions to go to the directory we came from, likely due to an encrypted home directory, but this should fix this as we will only ever go back to $SNAP_DATA during the popd call.

snap/bin/security-start.sh: go into $SNAP_DATA before doing anything

---

export/distro/format.go
glide.yaml

#514 
Per discussion on the Core and DevOps WG calls these past few weeks, I have added explicit versions to the glide.yaml file. I had to make some decisions while doing this. I used SHAs in the California glide.lock file for reference.
- When a given tag was closely followed by a release, I used the release in the version field.
- When there wasn't a nearby release, I used the tag
- When there was no release at all (such as the XMPP repo) I used the tag
Note that this caused a build error in the export/distro/format.go file but it's very minor, so I fixed that and included it here.
Note that `make prepare` will pull in dependencies not explicitly listed in the glide.yaml so I can't version those. We're relying on the package mgmt of our dependencies in these cases.
Signed-off-by: Trevor …

Adding version information to glide.yaml

---

.gitignore
Makefile
cmd/config-seed/main.go
cmd/config-seed/res/configuration-docker.toml
cmd/config-seed/res/configuration.toml
cmd/config-seed/res/properties/device-bacnet/application.properties
cmd/config-seed/res/properties/device-bacnet;docker/application.properties
cmd/config-seed/res/properties/device-bluetooth/application.properties
cmd/config-seed/res/properties/device-bluetooth;docker/application.properties
cmd/config-seed/res/properties/device-fischertechnik/application.properties
cmd/config-seed/res/properties/device-fischertechnik;docker/application.properties
cmd/config-seed/res/properties/device-modbus/application.properties
cmd/config-seed/res/properties/device-modbus;docker/application.properties
cmd/config-seed/res/properties/device-mqtt/application.properties
cmd/config-seed/res/properties/device-mqtt;docker/application.properties
cmd/config-seed/res/properties/device-snmp/application.properties
cmd/config-seed/res/properties/device-snmp;docker/application.properties
cmd/config-seed/res/properties/device-virtual/application.properties
cmd/config-seed/res/properties/device-virtual;docker/application.properties
cmd/config-seed/res/properties/edgex-support-rulesengine/application.properties
cmd/config-seed/res/properties/edgex-support-rulesengine;docker/application.properties
docker/Dockerfile.config-seed
glide.yaml
internal/constants.go
internal/pkg/usage/usage.go
internal/seed/config/const.go
internal/seed/config/init.go
internal/seed/config/populate.go

#517 
This PR contains work to merge the config-seed service into the edgex-go repo as has been discussed on the Core WG calls. There are several points to note w/r/t this PR:
- The PR looks bigger than it is due to all of the application.properties files that had to be brought over. This is so that we can avoid config file duplication between two repos.
- As described on the calls, the goal was to achieve functional parity with the existing core-config-seed-go service. No functionality for Config V2 has been added yet.
- Today the config-seed is not run unless one wishes to exercise EdgeX via docker containers, so I have not added it to the `make run` command. It IS present in `make build`. You can run the service via
```
cd cmd/config-seed
./config-seed
```
- I have added a docker …

Merge config-seed into edgex-go

---

snap/bin/start-config-seed.sh
snap/snapcraft.yaml

This should fix builds such as https://jenkins.edgexfoundry.org/view/Snap/job/edgex-go-snap-master-stage-snap/64/console which fails with:
```
10:28:01 install: cannot stat './config/core-command/configuration.toml': No such file or directory
```

snap/snapcraft.yaml: fix config file locations in config-seed-go

---

snap/snapcraft.yaml

Note that we only want to do this for the master releases that go to `latest/edge`. We don't want to do this for versioned releases that go into tracks, as with those the versions must be carefully gated.

snapcraft.yaml: use VERSION file to set snap version

---

snap/snapcraft.yaml

* This allows the build to fail immediately if not on amd64 or arm64
* This is also more concise, not requiring an override-build setting
* Is progress towards removing the shell plugin entirely

snapcraft.yaml: simplify mongodb part to use advanced grammar

---

snap/snapcraft.yaml

Allowing access to mongoimport allows easy import of
Blackbox test data required to run blackbox tests.

[snap] Expose mongoimport as an app

---

docs/Dockerfile.build

This fixes #576 by versioning the pip packages used to build the docs. Apparently Sphinx v1.8 breaks on Linux Foundation CI running Python 2.7.5.

docs/Dockerfile.build: specify version for pip packages

---

snap/snapcraft.yaml

No longer necessary with snapd 2.35
This resolves #478.

snapcraft.yaml: remove base64 part

---

snap/snapcraft.yaml

This PR adds a missing COPYRIGHT file for openresty to the snap.

snapcraft.yaml: include COPYRIGHT for openresty

---

internal/core/metadata/rest_addressable.go
internal/core/metadata/rest_deviceprofile.go

This should fix #613.
Is implemented in the same way as it's done with profiles.

Device service is notified when device addressable is updated

---

internal/support/logging/criteria_test.go
internal/support/logging/models/log_entry.go
internal/support/logging/persistence_test.go
internal/support/logging/server.go
internal/support/logging/server_test.go
internal/support/logging/types.go
internal/support/logging/types_test.go
pkg/clients/logging/logger.go
pkg/clients/logging/logger_test.go
pkg/clients/logging/mock-logger.go

Fix #628 
Added the option to set the minimum log level severity. Now by default is INFO, but in another PR we can add the LogLevel configuration parameter, to set this value. 

Added the option to set the minimum log level severity

---

Makefile
internal/support/logging/init.go

#640 
Added content check to verify something received from Consul. If not, force reconnect.
Normalized docker build target name in Makefile
I verified this fix locally as follows:
1.) Stop all Docker containers
2.) Prune all Docker containers `docker container prune`
3.) `make docker_config_seed`
4.) `make docker_support_logging`
5.) cd docker
6.) `docker-compose run logging`
You will see one ERROR line logged followed by successful startup.

Fix improper read from Consul during bootstrap (support-logging)

---

internal/core/data/device.go
internal/core/data/errors/types.go
internal/core/data/event.go
internal/core/data/event_test.go
internal/core/data/reading.go
internal/core/data/reading_test.go
internal/core/data/router.go
internal/core/data/valuedescriptor.go

Related to issue #457 
This pull request attempts to lay the foundational work that will make unit testing this functionality possible and tries to follow the example @tsconn23 used for event.go. Expect a second PR based off this branch very shortly that will add these unit tests.

Refactored reading.go, valuedescriptor.go, and their routing logic in router.go

---

cmd/sys-mgmt-agent/res/configuration.toml
cmd/sys-mgmt-agent/res/docker/configuration.toml
internal/system/agent/init.go
internal/system/agent/services.go

- This PR contains the work done in accordance with: [Issue Number 697](https://github.com/edgexfoundry/edgex-go/issues/697)
- With a view to providing insight into DEV testing, Postman was used with the **following two HTTP GET requests** repeatedly:
**api/v1/metrics:**
- http://localhost:48090/api/v1/metrics/edgex-support-logging,edgex-core-metadata,edgex-support-notifications,edgex-core-data,edgex-core-command,edgex-export-client,edgex-export-distro,edgex-support-scheduler
**api/v1/config:**
- http://localhost:48090/api/v1/config/edgex-support-logging,edgex-core-metadata,edgex-support-notifications,edgex-core-data,edgex-core-command,edgex-export-client,edgex-export-distro,edgex-support-scheduler

Integrate the newly-created GeneralClient into the SMA.

---

api/raml/support-scheduler.raml
cmd/support-scheduler/main.go
internal/core/metadata/const.go
internal/core/metadata/rest_scheduleevent.go
internal/support/scheduler/init.go
internal/support/scheduler/router.go
internal/support/scheduler/schedule.go

Addressing issue with scheduler and core-metadata integration with schedules,scheduleevents, and addressables.  Scheduler will now use core-metadata as the source of truth for schedules and only use it's local configuration scheduler,events when not included in the core-metadata.  Additionally new schedules, events, and addressable unique id's will be generated from core-metadata. 
We currently do not have reactive feedback to the support-scheduler from the metadata client.
For now any changes made to core-metadata which require support-scheduler notification should be accomplished via the /api/v1/flush router call on the support-scheduler.  This will flush the current schedules and reload the entire schedules, events, and addressables …

addressing issue 650 integration with core-metadata

---

snap/snapcraft.yaml

This speeds up the builds and also avoids a problem with maven not finding org.apache.maven.surefire.booter.ForkedBooter and the tests failing.
This should fix builds such as https://jenkins.edgexfoundry.org/view/Snap/job/edgex-go-snap-delhi-stage-snap/1/

snapcraft.yaml: skip tests when building java services

---

internal/seed/config/populate.go

This line isn't really necessary info and is rather debug info.

internal/seed/config/populate.go: turn info line to debug

---

snap/hooks/install
snap/local/bin/start-edgex.sh
snap/snapcraft.yaml

* Update start-edgex.sh to use the new go support-scheduler binary
* Update install hook to also install the support-scheduler config files
Fixes #693

Use go implementation of support-scheduler in snap

---

cmd/support-scheduler/main.go
internal/support/scheduler/init.go
internal/support/scheduler/loader.go
internal/support/scheduler/schedule.go
internal/support/scheduler/servicecheck.go

Addressing the issue with Support Scheduler when during bootstrap it was not waiting for the core-metadata service to be fully up prior to initiating calls to core-metadata.
- Added RetryService functionality to ensure core-metadata is up and running prior to proceeding.
- Removed the schedule, schedule events, and addressable loading functionality from init.go 
- Added schedule, schedule events, and addressable loading functions into new loader.go
- Moved the AddSchedulers() func from the Init.go into Loader.go 

Fixing issue 725 error messages fails to start correctly 

---

internal/system/agent/executor/snap.go
internal/system/agent/init.go
snap/snapcraft.yaml

This is an initial implementation of stopping services using `snapctl` when running inside the snap and must be specified with a configuration.toml OperationsType value of "snap".
Note that currently starting/restarting services doesn't work with this.
To test this:
1. Build the snap from this branch 
```bash
git clone https://github.com/anonymouse64/edgex-go.git
cd edgex-go
git checkout bugfix/sma-snap
snapcraft
```
2. Install the snap (note that this will automatically start the services from the snap, including sys-mgmt-agent):
```bash
sudo snap install --devmode edgexfoundry*.snap
```
3. Verify that `sys-mgmt-agent` is running:
```bash
snap services | grep sys-mgmt-agent
```
4. Issue a stop command to a service that is running (for example `core-command`):
```bash
curl --header …
```

Support stopping services in snap with SMA

---

internal/core/command/init.go
internal/core/data/init.go
internal/core/metadata/init.go
internal/export/client/init.go
internal/export/distro/init.go
internal/support/logging/init.go
internal/support/notifications/init.go
internal/support/scheduler/init.go

#792 
Standardizing on service port check == 0 to determine if service is in race condition with config-seed population in Consul.

Recheck consul connection in case of bootstrap race

---

internal/core/command/init.go
internal/core/data/init.go
internal/core/metadata/init.go
internal/export/client/init.go
internal/export/distro/init.go
internal/support/logging/init.go
internal/support/notifications/init.go
internal/support/scheduler/init.go

#792 (for master branch)
Standardizing on service port check == 0 to determine if service is in race condition with config-seed population in Consul.

Recheck consul connection in case of bootstrap race (master)

---

docs/Dockerfile.build
docs/general/conf.py

This was a change from the california branch that didn't make it into master

Add Google Analytics to generated documentation

---

pkg/models/event.go
pkg/models/event_test.go
pkg/models/reading.go
pkg/models/value-descriptor.go
pkg/models/value-descriptor_test.go

Related with PR #314. Only implemented in core-data.

Omit empty fields in core-data JSONs

---

snap/snapcraft.yaml

Duplicate of #818 but for master
Note that I just cherry picked this for master and didn't also fix the `support-scheduler` jar version because that will be replaced with the go implementation with a followup PR so the version number there doesn't much matter right now.

snapcraft.yaml: don't hard-code version in jar file names

---

snap/hooks/install
snap/local/runtime-helpers/bin/security-start.sh
snap/local/runtime-helpers/config/security-secret-store/vault-config.json.in
snap/snapcraft.yaml

Fixes #623 for Delhi.
This PR does a few things:
* It switches to using the new `vault-worker` and `pkisetup` binaries from security-secret-store for generating certs and loading them into vault, then also uploading them into kong.
* It now correctly checks if the certs have already been generated when re-running and doesn't regenerate them if they already exist
* We also now clear the glide cache before all go build parts that use glide because there's conflicts in the version of packages that `edgex-go`, `security-security-secret-store`, and `security-api-gateway`. This slows down builds somewhat as the packages will have to be fetched clean for each part, but ensures the builds always pass
* The kong routes now correctly present the certificate generated for Kong. 
The main things to …

Update security services for Delhi to use go binaries

---

snap/snapcraft.yaml

This is specifically just to 0.7.1 Delhi dot release.

snapcraft.yaml: upgrade grade to stable

---

internal/pkg/db/redis/metadata.go

Fix for #864 
Fixed GETs on schedule events when using Redis

Fix Issue 864

---

pkg/models/propertyvalue.go

#855 
* Removes default values for data transformation fields when creating a device profile
* Marks json properties as omitempty in the PropertyValue `MarshalJSON()` function.

Don't apply default values to data transformation fields (core-metadata)

---

internal/pkg/db/redis/CONFIGURATION.md

Re Issue #871 
Created Redis configuration doc

Issue #871 Add Redis configuration doc

---

snap/local/runtime-helpers/bin/fork-wrapper.sh
snap/local/runtime-helpers/bin/go-services-wrapper.sh
snap/local/runtime-helpers/bin/security-start.sh
snap/snapcraft.yaml

Fixes https://github.com/edgexfoundry/edgex-go/issues/884
This change is necessary because the daemon-notify interface is not implemented properly and is missing the capabilities "net_admin" and "sys_admin" in AppArmor in order to notify for a different process than the one that `systemd-notify` runs as. 
To remedy this, we instead make all of the daemons that were using systemd-notify into forking daemons, with an additional forking wrapper which immediately forks a process such that systemd can always immediately think that the process has successfully started up. We also need to ensure that the process that is initially forked stays alive for the remainder of the lifetime of the service because that service will be the "main" PID that systemd tracks. So for the go services we need to …

snap/many: replace usage of systemd-notify with forking daemons

---

snap/hooks/configure
snap/hooks/install
snap/snapcraft.yaml

This change adds the following new device services to the snap:
- device-modbus-go
- device-mqtt-go
- device-random
They are all disabled by default, and therefore must be enabled using:
'snap set edgexfoundry `service name`=on'
Enabling device-random will trigger a trio of random signed integer readings to be pushed to Core Data every 5 seconds. 
Enabling device-modbus or device-mqtt will start the respective device service, however no readings will be generated automatically as there are no device profiles configured by default. In order to produce readings from either service, device profiles must be copied to service's configuration directory ($SNAP_DATA/config/service name/res) before starting.
This PR has been tested on Ubuntu 18.04 desktop and on a Dell Gateway 3000 running Ubuntu …

Add new device services

---

internal/export/client/init.go
internal/pkg/startup/endpoint.go

Issue #622 
Root cause analysis has been added to the above issue. This was actually a problem running services with Consul enabled. Docker uses Consul and thereby exposed the problem, but I could also observe the behavior locally by just running everything with the `--consul` flag.

FIX: Client monitor update in milliseconds, not seconds

---

cmd/config-seed/Attribution.txt
cmd/core-command/Attribution.txt
cmd/core-metadata/Attribution.txt
cmd/export-client/Attribution.txt
cmd/export-distro/Attribution.txt
cmd/support-logging/Attribution.txt
cmd/support-notifications/Attribution.txt
cmd/support-scheduler/Attribution.txt
cmd/sys-mgmt-agent/Attribution.txt

Seems I missed `go-toml` in #908.

cmd/many: add go-toml to Attribution.txt files

---

pkg/clients/logging/logger.go

This should fix #913. Also allows to log using only stdout.

Now it's allowed to have an empty logTarget

---

internal/core/command/device.go

#846 
This seems to work as-is for PUT requests, but the check below prevented it from working for other types of requests.

#846 Return HTTP 423 LOCKED when issuing a GET command to a locked device

---

snap/snapcraft.yaml

Also fix a typo: device-mongo should be device-modbus
Note this PR will not build succesfully (and shouldn't be merged) until the following device-* PR's have been merged:
* https://github.com/edgexfoundry/device-mqtt-go/pull/4
* https://github.com/edgexfoundry/device-modbus-go/pull/5
* https://github.com/edgexfoundry/device-random/pull/17
After those get merged, just trigger a rebuild of this with "recheck" and it should be good to go.
I tested this branch by changing the `source-branch` and `source` specs for the parts to my fork and the various bugfix branches and then building from that. The diff can be applied with this patch:
```diff
diff --git a/snap/snapcraft.yaml b/snap/snapcraft.yaml
index 82d0efc..4cf5497 100644
--- a/snap/snapcraft.yaml
+++ b/snap/snapcraft.yaml
@@ -859,9 …
```

snapcraft.yaml: stage Attribution.txt files for device services into snap

---

snap/hooks/install
snap/local/bin/start-edgex.sh
snap/snapcraft.yaml

Duplicate of #716 but for master (i.e. Edinburgh)
* Update start-edgex.sh to use the new go support-scheduler binary
* Update install hook to also install the support-scheduler config files

snapcraft.yaml: use go implementation of support-scheduler (master)

---

internal/core/command/restDevice.go
internal/core/data/device_test.go
internal/core/data/router.go
internal/core/data/valuedescriptor.go
internal/core/data/valuedescriptor_test.go
pkg/clients/request.go

#844, #845
I believe this PR fixes some regressions caused by (or related to) commit: https://github.com/edgexfoundry/edgex-go/commit/40337b3b7d1dcbb47afc1e140e71d89914688f67#diff-2311174e4ebc3d4be67d0cf62dc5e1d2R72 around error handling in the core-command service.
Error codes in this service were being passed up to the rest layer alongside golang errors, and then discarded and 500's written out anyway.  This change causes the rest layer to respect the status codes returned by these functions even when an err value is returned.

#845, #844 Fix error handling in core-command service

---

internal/core/command/restDevice.go

#843
Some core-command APIs shouldn't set the Content-Type header
for an empty response body.
See corresponding blackbox test changes: https://github.com/edgexfoundry/blackbox-testing/pull/117

#843 core-command Content-Type headers

---

internal/core/metadata/rest_deviceprofile.go
internal/pkg/db/db.go
internal/pkg/db/mongo/metadata.go

#841 
Check for empty device profile name in mongo client and
handle the error with a 400 status code.

#841 Check for empty device profile name and return status 400

---

internal/core/metadata/addressable.go
internal/core/metadata/addressable_test.go
internal/core/metadata/interfaces/db.go
internal/core/metadata/interfaces/mocks/DBClient.go
internal/core/metadata/rest_addressable.go
internal/core/metadata/rest_device.go
internal/core/metadata/rest_deviceservice.go
internal/core/metadata/rest_scheduleevent.go
internal/pkg/db/memory/metadata.go
internal/pkg/db/mongo/metadata.go
internal/pkg/db/mongo/models/addressable.go
internal/pkg/db/mongo/models/event.go
internal/pkg/db/mongo/models/reading.go
internal/pkg/db/mongo/models/value_descriptor.go
internal/pkg/db/test/db_metadata.go
internal/support/scheduler/loader.go
pkg/clients/metadata/addressable_test.go
pkg/models/addressable.go
pkg/models/addressable_test.go
pkg/models/baseobject.go

#881 
- GET functions should return values, not populate pointers to types passed as arguments. Side-effect hell.
- Implemented Mongo provider logic, also MemoryDB changes
- Adding fix for issue #932

Decoupling mongo types from metadata/Addressable endpoint

---

internal/pkg/db/mongo/metadata.go

* Updated metadata function signatures so they reference receiver as pointer only if the corresponding function modifies the receiver (in this case, none currently do).

Issue 974 - Update metadata function signatures

---

internal/pkg/db/mongo/metadata.go
internal/pkg/db/mongo/models/event.go
internal/pkg/db/mongo/models/reading.go
internal/pkg/db/test/db_data.go
internal/pkg/db/test/db_metadata.go

#977 
Per the above issue, I've addressed the problems in the mongo/test functions dealing with events and their associated readings (core-data). There remain problems with the metadata relationships between addressable and device services because we are in the middle of refactoring the metadata service. The methodology of these tests will need to be changed to reflect the current implementation
- We have two possible identifiers now (BSON vs UUID) whereas before we only had one.
- We now have contract and provider-specific models whereas before we only had one.
As an example, rather than creating an addressable then saving it, then adding that instance to the parent device service, the approach going forward will be to instantiate the contract object graph as a whole which will then be …

Addressing mongo/test issues w/core-data models

---

internal/core/data/device.go
internal/core/metadata/interfaces/db.go
internal/core/metadata/interfaces/mocks/DBClient.go
internal/core/metadata/rest_addressable.go
internal/core/metadata/rest_device.go
internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/rest_devicereport.go
internal/core/metadata/rest_deviceservice.go
internal/core/metadata/rest_provisionwatcher.go
internal/core/metadata/rest_scheduleevent.go
internal/pkg/db/mongo/device.go
internal/pkg/db/mongo/device_service.go
internal/pkg/db/mongo/metadata.go
internal/pkg/db/mongo/models/addressable.go
internal/pkg/db/mongo/models/command.go
internal/pkg/db/mongo/models/describedobject.go
internal/pkg/db/mongo/models/devicereport.go
internal/pkg/db/mongo/models/deviceservice.go
internal/pkg/db/mongo/models/event.go
internal/pkg/db/mongo/models/id.go
internal/pkg/db/mongo/models/reading.go
internal/pkg/db/mongo/models/service.go
internal/pkg/db/mongo/models/value_descriptor.go
internal/pkg/db/mongo/provision_watcher.go
internal/pkg/db/test/db_metadata.go
pkg/models/deviceservice.go
pkg/models/service.go

Issue 877 - core-metadata DeviceService: Eliminate Mongo Types from Models
* Updated contract to return uuid *string for Id and removed BSON annotations.
* Updated query methods to eliminated references and return result values instead.
* Updated AddDeviceService() to return Id.
* Collapsed common code that translates Id into bson.ObjectId or UUID.
#877

Issue 877 - core-metadata DeviceService: Eliminate Mongo Types from Models

---

internal/pkg/db/mongo/models/command.go

#1019 Guard against a null pointer dereference in internal/pkg/db/mongo/models/command.go

#1019 Fix Import DeviceProfile crash on Commands with empty Put/Get

---

cmd/config-seed/res/properties/go.mod

#1030 
This is a preparatory effort and does not have a material effect on the build since GO111MODULE is not explicitly set. Per the issue above, we need to add this file to get the device-sdk-go module to ignore the config-seed/res/properties directories containing semi-colons. Device-sdk-go is our target first module project.

Added go.mod to config-seed properties folder

---

cmd/support-scheduler/main.go
internal/support/scheduler/schedule.go

Addressed issue in support-scheduler where the intervalAction was not being removed fully from scheduler in memory map references.
This was discovered when executing the black box tests in the intervalAction area. 
Fix:  Removed the intervalAction name reference from in memory helper map.  This map was used in validation to determine if an instance of the intervalAction existed without hitting the queue directly. 
Note: a logging key used in main.go was incorrectly logging data using the wrong key.  That as been fixed as well in main.go.

addressing issue_1060  support scheduler not removing intervalAction in memory references

---

api/raml/core-data.raml
internal/pkg/db/mongo/data.go

Modified query APIs to sort the results based on modified time.
Fix #966.  The queries with a limit were just returning the oldest
results.
This change returns the most recent results for queries with a limit.
The results are sorted by the modified time as this can be more recent
than the created time.
queries affected:
- /event/device/{deviceId}/{limit}:
- /event/{start}/{end}/{limit}:
-  /event/device/{deviceId}/valuedescriptor/{valuedescriptor}/{limit}:
-  /reading/device/{deviceId}/{limit}:
-  /reading/name/{name}/device/{device}/{limit}:
-  /reading/name/{name}/{limit}:
-  /reading/uomlabel/{uomLabel}/{limit}:
-  /reading/label/{label}/{limit}:
-  /reading/type/{type}/{limit}:
-  /reading/{start}/{end}/{limit}:
Possible side effects
1. Performance and scale.  It is recommended to …

Return recent events and readings for Query APIs

---

internal/core/metadata/rest_command.go
internal/pkg/db/mongo/metadata.go

This PR addresses two issues and two issues #986 and #987:
First, the logic for determining if a command was associated with a device profile was broken and would always return that there were no commands associated with a device profile.
Second, the logic for determining whether to update a command was out of sync with the RAML and included an unpublished requirement that the ID of the updated command be different. This has been removed.

Fix issues with commands in device profile service

---

snap/snapcraft.yaml

Duplicate of #905 but for master (thus Edinburgh) and also doesn't include the delhi branch).

snapcraft.yaml: stage Attribution.txt files for dev svcs into snap

---

cmd/export-distro/main.go
internal/core/data/device_test.go
internal/core/data/event.go
internal/core/data/messaging/eventpublisher.go
internal/core/data/messaging/zeromq.go
internal/export/distro/filter.go
internal/export/distro/filter_test.go
internal/export/distro/format.go
internal/export/distro/format_test.go
internal/export/distro/httpsender.go
internal/export/distro/httpsender_test.go
internal/export/distro/influxdb.go
internal/export/distro/mqtt.go
internal/export/distro/registrations.go
internal/export/distro/registrations_test.go
internal/export/distro/types.go
internal/export/distro/xmpp.go
internal/export/distro/zeromq.go
internal/pkg/correlation/models/event.go
pkg/models/event.go

#1089 
Note the following:
* Aliased all imports from `github.com/edgexfoundry/pkg/models` as `contract`
* Introduction of internal/pkg/correlation/model/event.go which wraps the contract event adding a CorrelationID property.
* The above model is sent through the EventPublisher to export-distro
* Export-distro continues to export the regular contract model, as it should, however if exporting via HTTP the correlation-id header is passed to the next endpoint.
* In the case of HTTP export, a log entry is written showing the correlation-id and duration of the call
I have also tested this using a small export client that I've written and I confirmed receipt of the same correlation-id that was generated when the event was ingested by core-data.

Propogating correlation-id through EventPublisher

---

snap/Dockerfile.build
snap/build.sh
snap/entrypoint.sh
snap/snapcraft.yaml

* Adjusts the build scripts + Dockerfile to install snapcraft from the stable snap channel rather than through debian packages. As per the snapcraft maintainers, snapcraft 3.0 will not be backported/SRU'd to xenial, and so to get bugfixes and other features with snapcraft 3.0 we need to start installing from the snap. The trick here used to install it is exactly the same on that upstream snapcraft does, but adapted slightly to work for non-amd64 architectures. 
* Adjusts build scripts to allow for a new "release" job in jenkins (specified by the JOB_NAME jenkins environment variable). This job will specify an env var `SNAP_REVISION` and `SNAP_CHANNEL`, and release that snap revision to that snap channel. This release job is meant to only be manually triggered by users in jenkins. 
* …

Upgrade snapcraft version and refactor build scripts

---

snap/build.sh
snap/snapcraft.yaml

This regex would never match the verbatim "edgex-go-snap-release-snap", so just make it check for that exact job name to trigger a release build in the script
This will unblock https://github.com/edgexfoundry/ci-management/pull/281 as per https://github.com/edgexfoundry/ci-management/pull/281#issuecomment-462889828
Also since now building the snap is broken due to the removal of cassandra 3.11.3 download link, I have fixed that by just updating the URL here, however we should look for a more long term solution than just updating the link everytime they change it. This issue is filed as https://github.com/edgexfoundry/edgex-go/issues/1103

snap/build.sh: fix typo in job name for snap release job

---

snap/snapcraft.yaml

The current architectures key worked with the old snapcraft, but this
is now interpreted as the snap being a multiarch snap.
Currently, if the snap is built it with a recent version of snapcraft it shows up as "edgexfoundry_..._multi.snap", which is wrong.

snapcraft.yaml: fix architectures key

---

cmd/config-seed/Dockerfile
cmd/core-command/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/export-client/Dockerfile
cmd/export-distro/Dockerfile
cmd/support-logging/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile

#1112 
The use of `go mod download` allows Go module dependencies to be downloaded once and then Docker itself will cache the deps for re-use during the various COPY operations. Hoping this will save us quite a build of time in the build pipeline.

Caching go module deps via Docker COPY

---

internal/core/metadata/interfaces/db.go
internal/core/metadata/interfaces/mocks/DBClient.go
internal/core/metadata/rest_command.go
internal/pkg/db/mongo/client_test.go
internal/pkg/db/mongo/metadata.go
internal/pkg/db/test/db_metadata.go
internal/pkg/db/test/db_scheduler.go

This PR fixes several issues in data base test (related with #977).
Anyway, MongoDB test still fails in core-metadata:
```
$ go test -tags mongoRunning
--- FAIL: TestMongoDB (0.20s)
client_test.go:24: This test needs to have a running mongo on localhost
db_metadata.go:684: There should be 1 deviceServices instead of 0
FAIL
exit status 1
FAIL	github.com/edgexfoundry/edgex-go/internal/pkg/db/mongo	0.198s
```
This seems to be a bad implementation in `GetDeviceServicesByAddressableId()` and several similar functions (`GetScheduleEventsByAddressableId()` or `GetDevicesByProfileId()`) 

Fixed issues in core-metadata DB test

---

docs/examples/Ch-ExamplesAddingMQTTDevice.rst
docs/examples/Ch-ExamplesAddingModbusDevice.rst

Fix swapped filenames for device profiles between MQTT and ModBus tutorials. Fixes #1095

Fix modbus/mqtt profile links in docs

---

go.mod
internal/core/data/router.go

#1115 
- Note the actual fix is in go-mod-core-contracts from this PR https://github.com/edgexfoundry/go-mod-core-contracts/pull/9
- Updated go.mod to point to above commit
- Replaced a few occurrences of `StatusServiceUnavailable` with standard `StatusInternalServerError`

404s should be wrapped by ErrServiceClient

---

cmd/config-seed/Dockerfile
cmd/core-command/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/export-client/Dockerfile
cmd/export-distro/Dockerfile
cmd/support-logging/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile

#1124 
NOTE: The `COPY go.sum .` is merely commented out on purpose. Please see my comment on the above issue for the reasoning.

Utilizing golang:1.11-alpine as base Docker image

---

snap/snapcraft.yaml

We need to disable modules when building go itself, otherwise it will try to import the modules from edgex-go first and that will fail during the go part build (note this is before we even try to build edgex-go).
Eventually we would like to have the upstream go remote part handle this, but that is pending more discussion on the forum at https://forum.snapcraft.io/t/go-part-fails-with-go1-11-if-go-mod-exists-in-the-top-level-directory/7546/19
Fixes #1109

Build go with modules off, to allow building go parts with modules

---

internal/core/data/errors/types.go
internal/core/data/valuedescriptor.go
internal/core/data/valuedescriptor_test.go
internal/core/metadata/addressable.go
internal/core/metadata/rest_command.go

This PR fixes #1130 and also:
* Makes update addressable database independent
* Fixed panic error when trying to get commands and max limit is reached
* When trying to add an existing value descriptor, now the error is "duplicate name for value descriptor" instead of "value descriptor still referenced by readings"
And ok, maybe I should create different PR for each of those issues, but at least there is one commit for each one :smiley:

Fix update command and other issues

---

snap/snapcraft.yaml

* Align + remove trailing whitespace
* Use double quotes instead of single quotes for strings
* Remove trailing comma in core-command plugs
* Adjust wording on comment about curl part source spec
* Re-order snapcraft parts to be more logically ordered
* Remove glide part, remove "glide cc" from go parts
* Make go part build after go-build-helper
Tested by building the snap and installing it on Ubuntu 16.04 server and ensuring that all services startup properly.
Closes #1149

cleanup snapcraft.yaml, remove glide part from snap

---

snap/local/runtime-helpers/bin/mongo-worker-wrapper.sh

This prevents us from getting into an infinite loop if mongod is not startable for some reason in the snap.
For example, this could happen if there's another mongod running on the system that makes it unable to listen on the default port number, with this change mongo-worker will at least die after 10 times (or 50 seconds), leading to either an abort of the snap installation (if installing) or explicitly failed services if happening on a snap restart/system reboot.
To test this:
1. Build the snap and install it normally, it should install and have services come up normally.
2. First, listen on mongodb port 27017 with a super simple http server such that mongo-worker will get an invalid response and be unable to initialize mongod:
```bash
RESPONSE="HTTP/1.1 200 OK\r\nConnection: …
```

mongo-worker-wrapper.sh: stop after 10 tries

---

snap/snapcraft.yaml

Duplicate of #1151 but for Delhi.
Closes #1103 for Delhi
Note this is to fix failing edge builds such as https://jenkins.edgexfoundry.org/view/Snap/job/edgex-go-snap-delhi-stage-snap/134/ in the unlikely event we need to do another Delhi release

build cassandra from source in snap for delhi

---

snap/snapcraft.yaml

This will resolve #1103 for edinburgh/master.
Tested by building the snap, installing it and making sure that the security services come up correctly.

build cassandra from source

---

go.mod
internal/pkg/db/mongo/models/deviceprofile.go
internal/pkg/db/mongo/models/value_descriptor.go

Create "floatEncoding" field to "PropertyValue" and "ValueDescriptor"
struct in Mongo db models
fix #1188

Create "floatEncoding" field

---

snap/hooks/configure
snap/hooks/install
snap/hooks/remove
snap/local/runtime-helpers/bin/support-rulesengine-wrapper.sh
snap/snapcraft.yaml

Also remove obsolete remove hook.
To test this, build the snap and install it.
1. Check that support-rulesengine doesn't start by default:
```
snap services edgexfoundry.support-rulesengine | grep disabled | grep inactive
```
2. Check that after starting `support-rulesengine` and `export-client` (which is also disabled by default), support-rulesengine starts up and registers itself with consul:
```
snap set edgexfoundry export-client=on
snap set edgexfoundry support-rulesengine=on
```
You can check the consul status by going to localhost:8500 and seeing that `edgex-support-rulesengine` shows up there.
Closes #552 for Edinburgh (again)

Add support-rulesengine back to the snap

---

bin/edgex-docker-launch.sh
go.mod
internal/core/data/init.go
internal/core/metadata/init.go
internal/core/metadata/rest_command.go
internal/core/metadata/rest_deviceprofile.go
internal/export/client/init.go
internal/pkg/db/db.go
internal/pkg/db/redis/CONFIGURATION.md
internal/pkg/db/redis/README.md
internal/pkg/db/redis/client.go
internal/pkg/db/redis/client_test.go
internal/pkg/db/redis/data.go
internal/pkg/db/redis/device.go
internal/pkg/db/redis/device_profile.go
internal/pkg/db/redis/device_service.go
internal/pkg/db/redis/event.go
internal/pkg/db/redis/export.go
internal/pkg/db/redis/metadata.go
internal/pkg/db/redis/models/db_command.go
internal/pkg/db/redis/models/interval.go
internal/pkg/db/redis/models/interval_action.go
internal/pkg/db/redis/object.go
internal/pkg/db/redis/provision_watcher.go
internal/pkg/db/redis/queries.go
internal/pkg/db/redis/scheduler.go
internal/pkg/db/redis/scripts.go
internal/pkg/db/redis/util.go
internal/support/scheduler/init.go

This brings Redis to Core Data, Core MetaData, Export Client, and Scheduler. The notification service will be merged separately. There is no plan to support the Logger which defaults to using a file.
Please note changes to `metadata/rest_command.go` and `metadata/rest_deviceprofile.go`; there are inconsistencies with how `err == ErrNotFound` and `err == nil` are treated and this is my proposed workaround. At some point we should make a decision on what the right way is and propagate those changes.
There are a few Black Box tests that are failing from what I believe are minor bugs in the tests. I will need to revisit that.

PR for Issue 788 - Redis updated for UUID, contracts, and propagated across services

---

snap/hooks/install

See https://github.com/edgexfoundry/edgex-go/issues/1225#issuecomment-480587494
Closes #1225

snap/hooks/install: don't try to install the configuration-driver.toml

---

cmd/sys-mgmt-agent/res/configuration.toml
internal/system/agent/execution_engine.go
internal/system/agent/init.go
snap/hooks/install
snap/local/runtime-helpers/bin/sys-mgmt-agent-snap-executor.sh
snap/snapcraft.yaml

* Fixes SMA support for using the interfaces defined for each operation 
* Has SMA use consul now that it has support for it
* Add snap specific SMA executor that uses `snapctl` to start/stop/restart services
To test this, build the snap and after installing, run:
```
$ curl --header "Content-Type: application/json" --request POST --data '{"action":"stop","services":["edgex-core-command"]}' localhost:48090/api/v1/operation
Done. Started the requested services.
```
you should then see `core-command` go down is inactive:
```
$ snap services edgexfoundry.core-command
Service                    Startup  Current   Notes
edgexfoundry.core-command  enabled  inactive  -
```
Then start the service with:
```
$ curl --header "Content-Type: application/json" --request POST --data …
```

Fix SMA's ExecutorPath; implement snap-specific executor

---

internal/core/command/device.go
internal/core/command/get.go
internal/core/command/get_test.go
internal/core/command/interfaces.go
internal/core/command/put.go
internal/core/command/put_test.go
internal/core/command/restDevice.go
internal/core/command/types.go
internal/core/command/types_test.go
internal/interface.go

Refactored device.go command execution functionality to allow for easier
testing
Added tests to cover newly added functionality

#1219 Updated core-command to include a correlation ID in the request headers when sending HTTP(s) requests

---

docs/system-management/agent/Ch_SysMgmtAgent.rst

```
- The goal of this PR is to add System Management Agent (SMA) endpoint examples to documentation. 
- To get an appreciation for SMA API calls in action, it is instructive to look at what responses the SMA provides to the caller, for the respective calls.
```
- This PR is per [Issue-1183](https://github.com/edgexfoundry/edgex-go/issues/1183)
`Thus, we consider the following calls that the SMA handles:`
* Metrics of a service
* Configuration of a service
* Start a service
* Stop a service
* Restart a service
* Health check on a service

Add System Management Agent (SMA) endpoint examples to documentation.

---

internal/support/notifications/normal_distribution.go

- Make the critical severity notification asynchronous by making the call to the function distributeAndMark(n) a goroutine and, to indicate this process now being an asynchronous one, logging that the critical severity scheduler has been _triggered_ (instead of _completed_ as we used to do).
- This is to make the response time acceptable, performance-wise: The response time should be less than 200ms.
- This PR is per: [Issue-1187](https://github.com/edgexfoundry/edgex-go/issues/1187)

Make the critical severity notification be an asynchronous one.

---

internal/core/command/device.go
internal/core/command/get.go
internal/core/command/get_test.go
internal/core/command/put.go
internal/core/command/put_test.go

This commit fixes issue #1252
Fixed NewPutCommand function in put.go to use the command.PUT URL rather
than command.GET
Added test to cover the bug which has been fixed in this commit
Cleaned up white-space and empty lines.

Fixed NewPutCommand URL and Body bugs

---

docs/examples/Ch-ExamplesAddingModbusDevice.rst

Change ProfileDir to ProfilesDir for config example

Correct doc typo issue for device-modbus example

---

cmd/sys-mgmt-agent/res/docker/configuration.toml
cmd/sys-mgmt-executor/main.go
internal/system/agent/services.go

- This PR is to enable the Docker-in-Docker solution to to deploy and function properly. For this, we need to pare down logging for the docker-compose reference implementation of the system management executor (aka `sys-mgmt-executor`) because, while the facilities for logging are available to edgex-go services in general, `sys-mgmt-executor` is a standalone, bare-bones executable for which it does not make sense to initialize full-blown logging; instead, we are paring down to lean (built-in golang) logging 👍 
- As part of this, we have moved the field `ExecutorPath` to the top-level in `configuration.toml` (for sys-mgmt-agent docker) so it can be picked up by the runtime.
- The relevant Issue is: [Issue-1266](https://github.com/edgexfoundry/edgex-go/issues/1266)
- Crucially, and …

Pare down logging for the docker-compose reference implementation of sys-mgmt-executor.

---

internal/support/notifications/rest_notification.go

Created field of critical Notification is always 0,
because the field is updated to 0 when marking its status to PROCESSED
fix #1279 

Query Notification before marking PROCESSED

---

internal/core/command/restDevice.go

This commit resolves issue 1285
Updated `restPutDeviceStateByDeviceId` and
`restPutDeviceStateByDeviceName` functions to propegate the underlying
HTTP response code to the caller. Also, updated the HTTP response from
"Internal Server Error(500)" to "Bad Request(400)" when unable to decode
the request body.

Fixed HTTP Response Codes

---

go.mod
internal/pkg/db/mongo/models/deviceprofile.go

Replace Attributes data type with map[string]string in DeviceResource
fix #1289

Use string instead of interface{} in Attributes

---

snap/hooks/install
snap/hooks/post-refresh
snap/hooks/pre-refresh
snap/snapcraft.yaml

This is the first step in resolving #799 (for Delhi).
The crux of the issue is that currently we process configuration files at install time to use snap specific paths such as $SNAP, $SNAP_DATA, $SNAP_COMMON, and use the environment variables for that. However, those environment variables include the revision number of the snap explicitly such as `/var/snap/edgexfoundry/329` for $SNAP_DATA from the stable channel, which is on revision 329. This is an issue when we push an update to the snap, because the configuration files currently wouldn't be changed and so the services would be trying to use files from a previous revision (say 329) when the current revision and actual data is now in (for example) 330. 
We can remedy this by simply using the `current` symlink instead (i.e. …

Specify epoch 0 for Delhi, add post-refresh script to fix config file paths

---

cmd/export-distro/main.go
internal/export/distro/init.go
internal/export/distro/registrations.go

Fix #1307 
In the case where export-client was not running when export-distro was
brought up, distro would get into a loop polling for export-client
connectivity and would ignore a signal to quit from the command line.

Fix Export-Distro Ignoring ^C

---

api/raml/support-notifications.raml
internal/support/notifications/rest_notification.go

Fix #1329
When entities are created in EdgeX the normal practice is to return the
ID of the new record. Previously we were returning the "slug" value
when a notification entry was created, which is something that is provided
by the application creating the notification. Thus it wasn't very
useful. Standardized POST of new notification to return the new ID and
updated the RAML.

Return New Notification ID Instead of Slug

---

internal/support/notifications/rest_subscription.go

Fix [#1313](https://github.com/edgexfoundry/edgex-go/issues/1313)
- Need to use subscription (s), instead of subscription (s2), to properly update subscription per PUT operation.

Use subscription (s), instead of subscription (s2), to properly update subscription per PUT operation.

---

internal/core/data/event.go
internal/core/data/io.go

Fix #1339
It's not feasible to set the bytes for a JSON event when the event is
read into core-data. This is because those bytes won't contain the new
event ID obtained during persistence. Marshal the event at the time of
publication if the Content-Type is application/json.

JSON Event ID Lost When Published to Bus

---

.github/ISSUE_TEMPLATE/1-bug-report.md
.github/ISSUE_TEMPLATE/2-feature-request.md
.github/ISSUE_TEMPLATE/3-docs-bug.md
.github/ISSUE_TEMPLATE/4-security-issue-disclosure.md
.github/ISSUE_TEMPLATE/5-support-request.md

This is a first stab attempt at creating issue templates for assisting a more structured issue list.  When you click "New Issue" you would then be presented with the following:
Each template automatically adds labels as appropriate per issue type. I.e. if you create a "Feature Request" issue, the `enhancement` label will automatically be added. 
Here's an example of each issue type:
Security: https://github.com/rsdmike/edgex-go/issues/64
Docs Bug: https://github.com/rsdmike/edgex-go/issues/63
Feature Request: https://github.com/rsdmike/edgex-go/issues/62
Bug Report: https://github.com/rsdmike/edgex-go/issues/61
Question/Support Request: https://github.com/rsdmike/edgex-go/issues/65
I've started with a pretty strong structure in each category type (adapted from Angular Issue Templates), …

Add Issue Templates for more structure of Github Issues

---

internal/pkg/db/mongo/notifications.go
internal/pkg/db/redis/notifications.go
internal/support/notifications/interfaces/db.go
internal/support/notifications/sending_service.go

Fix #1315
If a notification comes in and transmittal to a subscriber fails, a
retry can occur. In this case, the retry transmission record was being
created with a 0 CreateDate value. This was because dates are managed
at the database provider level and the return value on an ADD operation
is simply the ID of the newly inserted record.  In order to fix this,
I had to add a new function to the DBClient and supporting providers
that would fetch the newly inserted Transmission record so that the
date values could be retained for further opertations.

Transmission resend entries created with 0 CreateDate

---

internal/pkg/db/mongo/notifications.go
internal/pkg/db/redis/notifications.go
internal/support/notifications/interfaces/db.go
internal/support/notifications/rest_transmission.go

Fix #1338 
Change support-notifications transmission endpoints to handle
the limit parameter like every other route in the system.

Update support-notifications transmission endpoints

---

docs/support/logging/Ch-Logging.rst

A formatting issue was preventing the configuration options table from being rendered.

Fix table formatting in Logging docs

---

go.mod
internal/core/data/event.go
internal/export/distro/httpsender.go
internal/export/distro/httpsender_test.go
internal/export/distro/init.go
internal/export/distro/messaging.go
internal/export/distro/mqtt.go
internal/export/distro/registrations.go
internal/export/distro/registrations_test.go
internal/export/distro/types.go
internal/export/distro/xmpp.go
internal/export/distro/zeromq.go

Fix #1217
- For all channels involved in handling of incoming events via bus,
the type has been changed to MessageEnvelope to provide ease of access
to ContentType, Checksum and so-forth
- Added handling of CBOR encoded events. JSON handling continues as
previously defined.
- CBOR events are not processed in any way. The payload is simply sent
out to the relevant subscriber, per decisions in Core WG
- Unit tests have been adjusted and extended to process at least one
CBOR event.
- CBOR events will be sent to the Rules Engine whereupon the RE will
log an error. This does not cause a crash, just a log message on the
RE side. Pending decision from @jpwhitemn as to whether RE should be
filtered from export-distro or possible code change to RE.

Adding CBOR support to export-distro

---

cmd/config-seed/main.go
cmd/core-command/main.go
cmd/core-data/main.go
cmd/core-metadata/main.go
cmd/export-client/main.go
cmd/export-distro/main.go
cmd/support-logging/main.go
cmd/support-notifications/main.go
cmd/support-scheduler/main.go
cmd/sys-mgmt-agent/main.go
go.mod
internal/constants.go
internal/core/command/init.go
internal/core/data/init.go
internal/core/metadata/init.go
internal/export/client/init.go
internal/export/client/server_test.go
internal/export/distro/init.go
internal/seed/config/init.go
internal/seed/config/populate.go
internal/support/logging/init.go
internal/support/logging/types.go
internal/support/notifications/init.go
internal/support/scheduler/init.go
internal/system/agent/init.go
internal/system/agent/services.go

Fix #1345 
In go-mod-core-contracts we have available the following constants (https://github.com/edgexfoundry/go-mod-core-contracts/blob/master/clients/constants.go): 
```
const (
ServiceKeyPrefix                = "edgex-"
ConfigSeedServiceKey            = "edgex-config-seed"
CoreCommandServiceKey           = "edgex-core-command"
CoreDataServiceKey              = "edgex-core-data"
CoreMetaDataServiceKey          = "edgex-core-metadata"
ExportClientServiceKey          = "edgex-export-client"
ExportDistroServiceKey          = "edgex-export-distro"
SupportLoggingServiceKey        = "edgex-support-logging"
SupportNotificationsServiceKey  = "edgex-support-notifications"
SystemManagementAgentServiceKey = "edgex-sys-mgmt-agent"
SupportSchedulerServiceKey      = "edgex-support-scheduler"
)
``` …

Remove duplicate "internal" constants for service keys 

---

docs/support/scheduler/Ch-Scheduling.rst

Fix #1000 
-Inclusion of Interval, and IntervalAction
-Change the verbage of the data definitions for types associated with the Scheduler Service.

Docs -- Remove Schedule and ScheduleEvent types

---

go.mod
internal/export/distro/httpsender.go
internal/export/distro/httpsender_test.go
internal/export/distro/registrations.go

Fix #1366
- For HTTP export, Content-Type header was always JSON even when sending
CBOR content.
- Streamlined context handling to eliminate unneccesary duplication
- Found that for CBOR events, CBOR Content-Type was being sent back to
core-data during MarkPushed operations.
- In HTTP export, added WARN log output for status codes returned other
than 200.

Export-Distro Send Correct HTTP Content-Type for CBOR

---

cmd/support-scheduler/main.go

Fix #1138
Added a guard around the logic which handles logging before an
application has completely bootstrapped. Previous to this commit the
Logging client was being initialized twice and during the second
initialization there would be an error which then lead to nothing being
logged before the application exited with a non-zero status

Fixed logging issue when bootstrapping

---

api/raml/core-metadata.raml
internal/core/metadata/rest_device.go
internal/core/metadata/router.go

Fix #1365 
Send the status data in the body of the request instead of being part of the URL

Core-metadata PUT endpoints for Device Admin/OpState

---

.dockerignore
cmd/config-seed/Dockerfile

This is my proposal to solve #1347 (in contrast with #1348).
Specifically this PR is different in that in order for the config-seed container to support Redis, we just make copies of all the config files that are currently under `/edgex/cmd` at `/edgex/cmd-redis`, then use some simple shell tools (`toml2json`, `jq` and `json2toml`) to modify some of the configuration.toml files in the `cmd-redis` directory with Redis configuration. 
I originally had thought that the increased total file size would be 9 KB, but I measured it as actually 16 KB, which I still think is very minimal. You can measure this by building the config-seed container and getting the size with:
```
$ echo "$(docker image inspect redis-config-seed --format='{{.Size}}') - $(docker image inspect mongo-config-seed …
```

Add redis config files into config-seed container

---

internal/pkg/usage/usage.go

Fix #1302
Needed to update config-seed help message with usage guidelines for all
supported command line flags.

Updating config-seed help message

---

Makefile
bin/edgex-docker-launch.sh

This is linked to [developer-scripts/issues/111](https://github.com/edgexfoundry/developer-scripts/issues/111).
The `Makefile` is refactored so the Docker image tag can be overridden and `bin/edgex-docker-launch.sh` now simplified to completely depend on Docker Compose.

PR for Issue 1299: Redis Enablement for Edinburgh Deployments

---

go.mod

Fix #1380
In preparation for cutting the edinburgh branch, we need to consume
v0.1.0 in the go.mod for all edgex modules
- go-mod-core-contracts
- go-mod-messaging
- go-mod-registry

Update edgex modules to v0.1.0 pre-edinburgh

---

snap/hooks/pre-refresh
snap/snapcraft.yaml

This was missed in PR #1319 since the PR was merged after edinburgh was
branched, but for master now we want fuji as the release.
Also set epoch to 2 for fuji to prevent automatic edinburgh -> fuji
upgrades until we have a migration strategy ready that will use an epoch
of 2* (to read epoch 1 and write epoch 2).

Set snap release metadata to fuji

---

snap/snapcraft.yaml

Fixes #836 for the Fuji version of the snap.
This will need a back-port to Edinburgh branch after #1389 is merged.

Build consul 1.3.1 in the snap

---

snap/hooks/install
snap/local/runtime-helpers/bin/kong-daemon.sh
snap/snapcraft.yaml

* Upgrade to Kong 1.0.3
* Use `kong migrations bootstrap` instead of `kong migrations up`
* Remove lua and luarocks parts and use the bionic ubuntu archive pkgs
lua5.1 and luarocks instead
* Remove kong build dependency on openresty part as they no longer need
to be built after each other
* Build kong inside $SNAPCRAFT_PART_INSTALL
* Upgrade to OpenResty 1.13.6.2 and build with kong's patches
* Replace hard-coded location of nginx in "resty" binary from OpenResty
to use /snap/edgexfoundry/current based path instead of
$SNAPCRAFT_PART_INSTALL
* Fix the nginx and openresty symlinks inside openresty's
$SNAPCRAFT_PART_INSTALL/bin dir to be relative instead of absolute
* Use dpkg --print-architecture instead of uname -m for better
compatibility when cross compiling
* Add layout for …

snap/many: update kong to 1.0.3

---

snap/snapcraft.yaml

The registry arg is now a --key=val style option, where the value is
a custom URL spec with the scheme as the registry type. Since the snap
only works with consul for now, the scheme is just "consul".
Note we have to specify the value as an environment variable because
snapd doesn't allow the ":" character in a app's command spec. See
https://bugs.launchpad.net/snapd/+bug/1827392 for the upstream
bug/feature request to snapd.

snapcraft.yaml: update registry arg for dev svcs

---

cmd/config-seed/Dockerfile
cmd/core-command/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/export-client/Dockerfile
cmd/export-distro/Dockerfile
cmd/support-logging/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile
cmd/sys-mgmt-agent/Dockerfile
snap/snapcraft.yaml

Fix #1401
Upgrade Docker images to use Go 1.12 as a base image
Upgrade snap configuration to Go 1.12.5

Upgrade to Go 1.12

---

snap/snapcraft.yaml

Backport of #1396 to Edinburgh
Note that the snap jobs will fail until #1319 is merged

Build 1.3.1 consul in snap (edinburgh)

---

internal/support/notifications/distribution_coordinator.go

Fix #1420.
Debug print statement in distribution_cordinator.go is a duplicate.
:It is already displayed inside the resend function.

Remove duplicate debug print statement

---

docs/getting-started/Ch-GettingStartedSDK-Go.rst

I found some formatting errors in the document which broke the indentation and list numbering. 
I also fixed two typos and added a missing command to make it easier for developer to copy and paste each command from this document.
Signed-off-by: Alexandre Courouble <acourouble@vmware.com>

Adds missing command and fixes format errors

---

snap/snapcraft.yaml

The upstream configuration.toml default value changed such that this sed expression changing the tokenpath to the correct one for the snap no longer applied, leading to edgexproxy being unable to use the token to load the certificates from vault into Kong for Kong to use when serving HTTPS endpoints.
Fixes: #1458 for Edinburgh, will need a forward port to master as well

Fix security-api-gateway config file

---

internal/core/metadata/operators/addressable/db.go
internal/core/metadata/operators/addressable/get.go
internal/core/metadata/operators/addressable/get_test.go
internal/core/metadata/operators/addressable/mocks/AddressLoader.go
internal/core/metadata/rest_addressable.go
internal/core/metadata/rest_addressable_test.go

Fix #1489
Refactor the `restGetAddressableByPort` REST function handler to use the
operator pattern in efforts to increase unit test coverage.
Update the `restGetAddressableByPort` to use the PortExecutor operator
rather than directly using the DBClient. This will allow for easy
mocking during testing.
Add tests for the newly added PortExecutor operator and all of the
necessary layers needed by the operator.
Add tests for the REST handler `restGetAddressableByPort` to cover the
different situations the function is expected to handle.

Refactor restGetAddressableByPort to use operators

---

internal/core/metadata/operators/addressable/db.go
internal/core/metadata/operators/addressable/get.go
internal/core/metadata/operators/addressable/get_test.go
internal/core/metadata/operators/addressable/mocks/AddressLoader.go
internal/core/metadata/rest_addressable.go
internal/core/metadata/rest_addressable_test.go

Fix #1492
Refactor the restGetAddressableByTopic REST function handler to use the
operator pattern in efforts to increase unit test coverage.
Update the restGetAddressableByTopic to use the TopicExecutor operator
rather than directly using the DBClient. This will allow for easy
mocking during testing.
Add tests for the newly added TopicExecutor operator and all of the
necessary layers needed by the operator.
Add tests for the REST handler restGetAddressableByTopic to cover the
different situations the function is expected to handle.

Refactor restGetAddressableByTopic to use operator

---

go.mod
internal/core/data/event.go

Fix #1509
- Also noticed that if an error were to occur during publishing, our
logging was dropping that from the message. Added error contents to
log output in this case.

Update reference to go-mod-messaging, fix race condition

---

docs/examples/Ch-ExamplesAddingModbusDevice.rst
docs/getting-started/Ch-GettingStartedUsers.rst
docs/quick-start/Ch-QuickStart.rst
docs/security/Ch-APIGateway.rst
docs/security/Ch-SecretStore.rst
docs/walk-through/Ch-WalkthroughRunning.rst

Replace references to the delhi docker-compose file with references to the edinburgh docker-compose file. Fixes #1514

Replace references to the delhi docker-compose with edinburgh

---

snap/snapcraft.yaml

Reopening of #1470 because that PR is stuck with a removed jenkins job that is required and will never be triggered.

Fix security-api-gateway config file + security-api-gateway reorganization

---

internal/core/data/io.go

Fix #1379
When determining whether to treat a message as CBOR or JSON it was
requested that we treat the value of the Content-Type header in a
case insensitive manner.

Handle Content-Type header value as case-insensitive

---

cmd/core-command/res/configuration.toml
cmd/core-command/res/docker/configuration.toml
internal/core/command/device.go
internal/core/command/init.go
internal/core/command/interfaces/db.go
internal/core/metadata/interfaces/db.go
internal/core/metadata/interfaces/mocks/DBClient.go
internal/core/metadata/rest_command.go
internal/core/metadata/router.go
internal/pkg/db/mongo/metadata.go
internal/pkg/db/redis/metadata.go
internal/pkg/db/test/db_metadata.go

- Added direct connection from core-command service to "metadata" database
(should be change in future, core-command is supposed to have its own database)
- Added DBClient interface
- Add new GetCommandByNameAndDeviceId function in the BDClient
- Rewrite all functions that called metadata endpoints for quering commands to use
newly edded DBClient interface
- rename GetCommandByName function to GetCommandsByName (plural)
Fix: https://github.com/edgexfoundry/edgex-go/issues/1274

Add First Steps in Implementing Core-Command Persistent Layer

---

internal/core/metadata/addressable.go
internal/core/metadata/addressable_test.go
internal/core/metadata/operators/addressable/add.go
internal/core/metadata/operators/addressable/add_test.go
internal/core/metadata/operators/addressable/db.go
internal/core/metadata/operators/addressable/get_test.go
internal/core/metadata/operators/addressable/mocks/AddressLoader.go
internal/core/metadata/rest_addressable.go

Fix #1517 
Refactors the AddAddressable logic and adds unit test for that operator and executor.

Unit Test -- Refactored add addressable using operator pattern and added tests.

---

api/raml/core-metadata.raml

core-metadata.raml is consumed by the edgexfoundry/edgex-docs build
pipeline. https://github.com/edgexfoundry/edgex-go/pull/1523 introduced
defects into the raml file that cause the edgex-docs build to fail.

raml file issue causing edgexfoundry/edgex-docs build to fail

---

go.mod

Fix #1560 by removing the direct dependency on Consul and relying on the version used by https://github.com/edgexfoundry/go-mod-registry

Roll back Consul and run go mod tidy.

---

Makefile

For add ARCH to pull node architecture to support both ARM and x86_64 architectures for the RAML verification step.

add ARCH to makefile to pull correct image for RAML verify

---

snap/snapcraft.yaml

Should fix builds such as https://jenkins.edgexfoundry.org/view/Snap/job/edgex-go-snap-master-stage-snap/415/, see:
```
10:44:21 Building security-secret-store 
10:44:21 cd cmd/pkisetup && CGO_ENABLED=0 GO111MODULE=on GOOS=linux go build -a -ldflags="-s -w" -o pkisetup .
10:44:28 cd cmd/vaultworker && CGO_ENABLED=0 GO111MODULE=on GOOS=linux go build -a -o edgex-vault-worker .
10:44:48 install: cannot stat 'pkisetup/pkisetup': No such file or directory
...
10:44:48 Failed to run 'override-build': Exit code was 1.
10:45:17 Build step 'Execute shell' marked build as failure
```

snapcraft.yaml: update sec-secret-store binary locations

---

.sonarcloud.properties

Fix #1553
- Added .sonarcloud.properties file to the root directory. This will
allow the DevOps team to configure auto-scan in SonarCloud so we can
review the output. This may get rolled back if we aren't satisfied.

Adding SonarCloud Config for AutoScan

---

cmd/config-seed/Attribution.txt
cmd/core-command/Attribution.txt
cmd/core-data/Attribution.txt
cmd/core-metadata/Attribution.txt
cmd/export-client/Attribution.txt
cmd/export-distro/Attribution.txt
cmd/security-proxy-setup/Attribution.txt
cmd/security-secrets-setup/Attribution.txt
cmd/support-logging/Attribution.txt
cmd/support-notifications/Attribution.txt
cmd/support-scheduler/Attribution.txt
cmd/sys-mgmt-agent/Attribution.txt
cmd/sys-mgmt-executor/Attribution.txt
go.mod

Fix #1655
- Added entry for github.com/dgrijalva/jwt-go to all
- Removed entries necessitated by previous import of docker by SMA
bitbucket.org/bertimus9/systemstat is still in use

Attribution.txt cleanup for all services

---

Makefile
bin/test-attribution-txt.sh
bin/test-go-mod-tidy.sh

~~Note that CI verify jobs are expected to fail here since the Attribution.txt files need to be updated and go.mod needs to be tidied on master currently.~~ edit: this should now work now that #1665 has been merged and this has been rebased on top of master.
Also note that neither of these changes will change either your vendor directory or go.mod, they both will backup any files that get modified and then restore them afterwards.

Add tests to make test for attribution.txt correctness and go.mod tidiness

---

cmd/security-secrets-setup/Dockerfile
cmd/security-secrets-setup/README.md
cmd/security-secrets-setup/entrypoint.sh

- Remove the execution of security-secrets-setup inside Dockerfile to avoid generating TLS assets on the build time so that docker image does not contain sensitive information 
- Add docker entrypoint shell script to generate TLS assets of Vault/Kong on run-time if not exists yet
With above two it circumvents the issue CWE-318 of CA root private key although the whole process still running on the persistent storage (which should be addressed once features of Pki-Init Go-code are integrated into security-secrets-setup as one: using tmpfs running on the memory, not on the disk).  Nevertheless, with this step 0, it serves the purpose to pave the path to code-refactor security-secrets-setup with Pki-Init (which is much bigger effort) in terms of docker-image aspects.  It also unblocks the …

Fix security-secrets-setup vulnerability issue of sensitive TLS assets on docker image

---

snap/README.md

* Fix markdown link for building on lxd
* Show new --use-lxd option for building with LXD in recent snapcraft
versions
* Add section about setting LXD container environment to build the snap
natively with --destructive-mode in
* Add note about needing to create LXD container manually if building on
non-amd64 machine with snapcraft.

snap/README.md: update LXD section

---

internal/pkg/usage/usage.go

Fixes #1659
Other than occurrences in usage.go, I couldn't find any other usages do anything similar, so makes this a pretty simple change.  Everything compiles and runs just fine.
Signed-off-by: Scott C Sosna <me@scottsosna.dev>

Replace separate Sprintf/Printf with single Printf call

---

internal/core/metadata/operators/device_profile/update.go
internal/core/metadata/operators/device_profile/update_test.go

Fixes #1668
Fixes #1669
Update the `updateDeviceProfile` executor to only update the
DeviceProfile name if it has been provided. Otherwise, use the
pre-existing name.
Add tests to cover situations for updating the DeviceProfile's name.
Removed unused test functions.

Fix update DeviceProfile API handling of name

---

internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/rest_deviceprofile_test.go

Fix #1670
Update the restAddProfileByYaml REST handler to return a '409(Conflict)'
when unable to unmarshal the request body. The reason for this change is
backwards compatibility with EdgeX 1.x. Disregarding backwards
compatibility, the correct response code is '400(Bad Request)'.
Updated unit tests to adhere to the new expectations of the API.

Update restAddProfileByYaml response code

---

internal/core/metadata/operators/addressable/delete.go
internal/core/metadata/operators/addressable/delete_test.go
internal/core/metadata/operators/device_service/db.go
internal/core/metadata/operators/device_service/get.go
internal/core/metadata/operators/device_service/get_test.go
internal/core/metadata/operators/device_service/mocks/DeviceServiceLoader.go
internal/core/metadata/operators/device_service/mocks/DeviceServiceUpdater.go
internal/core/metadata/rest_addressable.go
internal/core/metadata/rest_deviceservice.go
internal/core/metadata/rest_deviceservice_test.go

Fix #1696
While I was working, I also refactored Addressable's delete code to take advantage of the pattern I used in this PR with the GetByAddressable Executor. Instead of having one factory method that takes both an ID and a name, I have two factory methods to reduce the chance that a consumer does the wrong thing. Technically out of scope, but I wanted to catch it while it was on my mind.

Unit test -- Core-Metadata Get Device Service By Name/ Addressable Name

---

internal/core/data/router.go

Fix #1731 
Error from a call to `addNewEvent()` was being ignored in the
handler, causing failures to add Events to be swallowed and
200 OKs to be returned to clients.  This change adds error
handling for the route in accordance with the RAML file at
https://github.com/edgexfoundry/edgex-go/blob/master/api/raml/core-data.raml

Fixes error handling in core-data event/ POST rte

---

go.mod
internal/core/command/device.go
internal/core/data/errors/types.go
internal/core/data/event_test.go
internal/core/data/operators/reading/get_test.go
internal/core/data/operators/value_descriptor/get_test.go
internal/core/data/reading_test.go
internal/core/data/router.go
internal/core/data/valuedescriptor.go
internal/core/data/valuedescriptor_test.go
internal/core/metadata/errors/types.go
internal/core/metadata/operators/device_profile/value_descriptor.go
internal/core/metadata/operators/device_profile/value_descriptor_test.go
internal/core/metadata/rest_addressable.go
internal/core/metadata/rest_command.go
internal/core/metadata/rest_device.go
internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/rest_deviceprofile_test.go
internal/core/metadata/rest_deviceservice.go
internal/support/scheduler/errors/types.go
internal/support/scheduler/interval_test.go
internal/support/scheduler/rest_interval.go
internal/support/scheduler/router.go

Fix #1671
Update constructors, error type checks, and tests to use values rather
than references(pointers) for errors.
Update tests to conform to the changes in the production code.

Standardize error usage

---

internal/pkg/db/redis/data.go
internal/pkg/db/redis/queries.go

Fix #1643
Update the Redis client to return the latest readings when a limit is
applied to the query. This make the Redis client more consistent with
the desired Mongo client results.

Fix Redis' ReadingsByDevice to get latest readings

---

snap/snapcraft.yaml

Needed now since upstream master moves files around which breaks
snapcraft build for edinburgh track.
Fixes issue 1755.

Specify the `edinburgh` branch of mongo-config part

---

cmd/config-seed/Attribution.txt
cmd/config-seed/main.go
cmd/core-command/Attribution.txt
cmd/core-data/Attribution.txt
cmd/core-metadata/Attribution.txt
cmd/export-client/Attribution.txt
cmd/export-distro/Attribution.txt
cmd/security-proxy-setup/Attribution.txt
cmd/security-secrets-setup/Attribution.txt
cmd/security-secretstore-setup/Attribution.txt
cmd/support-logging/Attribution.txt
cmd/support-notifications/Attribution.txt
cmd/support-scheduler/Attribution.txt
cmd/sys-mgmt-agent/Attribution.txt
cmd/sys-mgmt-executor/Attribution.txt
go.mod
internal/constants.go
internal/core/command/init.go
internal/core/data/init.go
internal/core/metadata/init.go
internal/export/client/init.go
internal/export/distro/init.go
internal/seed/config/environment.go
internal/seed/config/environment_test.go
internal/seed/config/populate.go
internal/support/logging/init.go
internal/support/notifications/init.go
internal/support/scheduler/init.go
internal/system/agent/init.go

Fixes #1735 
Adds mechanism for config-seed to read security configuration
environment variables and write them to the registry.
To test, run config-seed command with consul running like this:
`edgex_security_SecretStore="false" edgex_security_nested_Key="value" ./config-seed`
You should end up with two values in the consul KV storage (by default located at http://localhost:8500/ui/dc1/kv/edgex/security/1.0/ if running the consul dev agent locally)
Note: I've had some discussions with @tsconn23 and @michaelestrin and we think it would be good if the "global" security configuration settings were stored in a config file for Geneva, likely in a config-seed/res subdirectory.  This will provide some documentation of what settings are expected/available and sensible defaults.  This change will …

#1735 Populate global security configuration in registry

---

internal/system/agent/services.go

Updated to return error message when --registry flag not set during
service start up.  Expect this code to be further refactored in
follow-on https://github.com/edgexfoundry/edgex-go/issues/1771.
https://github.com/edgexfoundry/edgex-go/issues/1770

SMA /health faults if --registry not set

---

cmd/security-proxy-setup/main.go
internal/pkg/usage/usage.go

Fix #1651 
correct the typo for insecureskipverify in the security-proxy-setup project, and set the default value as false.

fix issue #1651: fixed typo for insecureskipverify; set the default value as false

---

cmd/security-secrets-setup/entrypoint.sh
cmd/security-secrets-setup/main.go
cmd/security-secrets-setup/main_test.go
internal/pkg/config/x509.go
internal/pkg/config/x509_test.go
internal/pkg/usage/usage.go
internal/security/setup/option/constant.go
internal/security/setup/option/generate.go
internal/security/setup/option/generate_test.go
internal/security/setup/option/optionHelpers.go
internal/security/setup/option/pkiOption.go
internal/security/setup/option/pkiOption_test.go
internal/security/setup/option/testdata/res/configuration.toml
internal/security/setup/option/testdata/res/pkisetup-kong.json
internal/security/setup/option/testdata/res/pkisetup-vault.json

To add generate subcommand into security-secrets-setup:
- TLS assets are generated from "scratch" ("working") dir and currently
default to `/edgex/security-secretes-setup/scratch` which is under the path
given by `XDG_RUNTIME_DIR` environment variable
- TLS assets are arranged into several directories based on service names
- TLS assets are deployed into "deployed" dir and is currently default to `/run/edgex/secrets` tmpfs directory
- TLS assets include `CA`, `Vault`, and `Kong` (reverse proxy)
- Sentinel files are generated upon completion of deploy for services
Note: 
The legacy option `-config <configuration_file_dir>` or `-c <configuration_file_dir>` is still available under subcommand `legacy` until phase out in the next phase or release.    Example of usage.: …

Add [generate] subcommand from merging pki-init option generate into security-secrets-setup

---

go.mod
internal/pkg/startup/endpoint.go
internal/system/agent/clients.go
internal/system/agent/clients_test.go
internal/system/agent/direct/metrics.go
internal/system/agent/init.go
internal/system/agent/services.go

GenClients is an unprotected map updated in multiple locations (as a
direct result of an HTTP request) and referenced elsewhere in the SMA.
Access to it should be protected by a mutex.
https://github.com/edgexfoundry/edgex-go/issues/1763

SMA GenClients usage not thread-safe

---

internal/system/agent/router.go
internal/system/agent/services.go

Refactored getHealth(); removed IsKnownServiceKey().
https://github.com/edgexfoundry/edgex-go/issues/1771

SMA Health Check should not be limited to "known" services

---

cmd/sys-mgmt-agent/main.go
internal/system/agent/config.go
internal/system/agent/init.go
internal/system/agent/router.go

Converts system management agent to use the common bootstrap package.
Intentionally reverts global variables eliminated by https://github.com/edgexfoundry/edgex-go/issues/1486
to be consistent with other core service implementations to simplify
intended post-conversion activity to remove global variables from
all core services.
Fixes https://github.com/edgexfoundry/edgex-go/issues/1810

Convert sys-mgmt-agent to use common bootstrap package

---

internal/core/data/router.go

Fix #1816
Please see the issue for detailed repro steps. Using this PR, you can
go through the same steps and you will receive a 400 http status
instead of a 500.
The ErrServiceClient constructor in go-mod-core-contracts was changed
recently to not return a pointer. It appears all references to this
type in edgex-go were corrected accordingly except for this one.

Core-Data/AddEvent - ErrServiceClient no longer a pointer

---

.gitignore
cmd/security-secrets-setup/main.go
cmd/security-secrets-setup/main_test.go
internal/pkg/usage/usage.go
internal/security/setup/option/cache.go
internal/security/setup/option/cache_test.go
internal/security/setup/option/constant.go
internal/security/setup/option/generate.go
internal/security/setup/option/mock_OptionsExecutor_test.go
internal/security/setup/option/optionHelpers.go
internal/security/setup/option/pkiOption.go
internal/security/setup/option/pkiOption_test.go

- Cache directory is defined in environment variable $**PKI_CACHE**, and the default is `/etc/edgex/pki` if not defined
- If cache directory is empty, then TLS assets will be generated and then cached
- TLS assets will be deployed from cache directory into deploy directory which defaults to `run/edgex/secrets` tmpfs directory
- CA private key is always securely erased before cached
Example to run: ``` ./security-secrets-setup -confdir ./res cache ```
Related to: 
- Issue #1635
- Issue #1558 

Add [cache] subcommand from merging pki-init option cache into security-secrets-setup

---

cmd/core-metadata/main.go
internal/core/metadata/config.go
internal/core/metadata/init.go

Converts core-metadata to use the common bootstrap package.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/1802

Convert core-metadata to use common bootstrap package

---

cmd/sys-mgmt-agent/main.go
internal/system/agent/direct/metrics.go
internal/system/agent/init.go
internal/system/agent/router.go
internal/system/agent/services.go

Restores backwards compatibility.
Restores prior behavior of mapping service keys to service names in
configuration to get endpoint data for connecting to external services
to obtain configuration (and health, metrics, etc.).
Fixes: https://github.com/edgexfoundry/edgex-go/issues/1780

SMA Get Configuration Endpoint Without Registry Flag No Longer Returns Configuration

---

internal/core/data/init.go
internal/core/metadata/init.go
internal/pkg/bootstrap/bootstrap.go

Corrects issue when database doesn't connect (but abstraction returns
a non-nil dbClient) for core-data and core-metadata implementations.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/1827

Service Bootstrap Timeout Not Being Honored

---

cmd/export-client/main.go
internal/export/client/config.go
internal/export/client/init.go

Converts export-client to use the common bootstrap package.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/1803

Convert export-client to use common bootstrap package

---

go.mod
internal/system/agent/get_config.go
internal/system/agent/getexecutor.go
internal/system/agent/interfaces/getexecutor.go
internal/system/agent/interfaces/setexecutor.go
internal/system/agent/router.go
internal/system/agent/set_config.go
internal/system/agent/setexecutor.go
internal/system/agent/setexecutor_stub.go
internal/system/agent/setexecutor_test.go

Fix #1432 
- For the `Fuji` release, the SMA will set configuration via Consul if EdgeX has been launched with the "--registry" flag (More details in the related issue).
> Here are some DEV test results:
- When accessing the SMA API (`http://localhost:48090/api/v1/config/edgex-support-notifications,edgex-core-data,edgex-core-command`) with the following body for the PUT operation...
```
{
"key": "Writable.LogLevel",
"value": "INFO"
}
```
...the response obtained is:
```
{
"configuration": {
"edgex-core-command": {
"success": true
},
"edgex-core-data": {
"success": true
},
"edgex-support-notifications": {
"success": true
}
}
}
```
...and it was verified (via `Consul`) that the Registry was updated as expected (for the KVP for the requested services).
- When accessing the SMA API …

Implement the design: SMA Sets Configuration (Writable) Without Restart.

---

internal/security/fileioperformer/interface.go
internal/security/fileioperformer/methods.go
internal/security/fileioperformer/methods_test.go
internal/security/fileioperformer/mocks/mock.go
internal/security/fileioperformer/mocks/mock_test.go

Creates an file I/O abstraction layer that enables
unit testing by mocking file I/O reads and writes
other other file system operations that would
normally be difficult to unit test.
This is part 1 of 6 merges to resolve #1677
Testing instructions: Run "go test" to run init tests.

Creates fileioperformer I/O abstraction layer (part 1 of 6 merges for #1677)

---

internal/security/secretstoreclient/const.go
internal/security/secretstoreclient/interface.go
internal/security/secretstoreclient/mocks/mock.go
internal/security/secretstoreclient/mocks/mock_test.go
internal/security/secretstoreclient/requestor.go
internal/security/secretstoreclient/requestor_test.go
internal/security/secretstoreclient/testdata/test-resp-init.json
internal/security/secretstoreclient/types.go
internal/security/secretstoreclient/types_test.go
internal/security/secretstoreclient/vault.go
internal/security/secretstoreclient/vault_test.go

This is a refactoring of the Vault client originally
found in security-secretstore-setup with re-use and
unit-testability in mind.
The original init and unseal flows have been modified
to remove dependencies on global variables and
hard dependencies on operating system file I/O. 
Additonal methods have been added to create Vault
policies and service tokens.
This is part 3 of 6 merges to resolve #1677
Testing instructions: Run "go test" to run init tests.

Refactor vault client into standalone package with mocks (part 3 of 6 merges for #1677)

---

internal/security/authtokenloader/interface.go
internal/security/authtokenloader/methods.go
internal/security/authtokenloader/methods_test.go
internal/security/authtokenloader/mocks/mock.go
internal/security/authtokenloader/mocks/mock_test.go
internal/security/authtokenloader/types.go

Creates an interface and package that reads a Vault 
token out of a JSON file.  The JSON file can either be
the output of the Vault init command (containing a 
root token) or the output of the token create API
(containing a service token). 
This package is used as a mockable dependency in the
vault client to faciliitate unit testing.
This is part 2 of 6 merges to resolve #1677
Testing instructions: Run "go test" to run init tests.
Preqrequisites:
* https://github.com/edgexfoundry/edgex-go/pull/1788

Creates authtokenreader interface for Vault client token (part 2 of 6 merges for #1677)

---

snap/snapcraft.yaml

Recent snapcraft now understands start-timeout directly, so we don't need to use passthrough anymore.
To test, just build the snap and see that snapcraft doesn't complain about not understanding start-timeout.

snapcraft.yaml: remove passthrough for start-timeout

---

cmd/support-logging/main.go
internal/support/logging/config.go
internal/support/logging/init.go

Converts support-logging to use the common bootstrap package.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/1807

Convert support-logging to use common bootstrap package

---

cmd/support-scheduler/main.go
internal/support/scheduler/config.go
internal/support/scheduler/init.go

Converts support-scheduler to use the common bootstrap package.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/1809

Convert support-scheduler to use common bootstrap package

---

go.mod
internal/system/agent/executor/executor-stub.go
internal/system/agent/executor/executor.go
internal/system/agent/executor/metrics.go
internal/system/agent/executor/operation.go
internal/system/agent/executor/operation_test.go
internal/system/agent/interfaces/executor.go
internal/system/agent/interfaces/operations.go
internal/system/agent/router.go

Adds support for optional parameters on /api/v1/operations endpoint
to be passed along as-is to binary executor implementation.
Depends upon https://github.com/edgexfoundry/go-mod-core-contracts/pull/160.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/770

SMA should support disable/enable parameters for stop/start

---

internal/security/secretstoreclient/messages.go
internal/security/secretstoreclient/testdata/test-resp-init.json
internal/security/secretstoreclient/vault.go

This is a refactoring of SecretStoreClient to move request
processing into a common function. This reduces code duplication
and should increase test coverage slightly as a result.
In the future, additional methods will be added to
SecretStoreClient to enable revokation and regeneration of
the root token and stale per-service service tokens.
This refactoring will eanble those methods to be implemented
in less than 10 lines of code in most cases.
TESTING INSTRUCTIONS:
"go test" in the secretstoreclient folder

Refactor SecretStoreClient to redude code duplication

---

internal/security/fileioperformer/methods_test.go

The fileioperfomer unit tests exercise functionality by attempting
to do file I/O on Unix-style paths, which can cause erroneous
unit test failures on Windows. This change makes these tests
only run on Linux -- other platforms automatically pass.

Resolve spurious unit test failures for fileioperformer in Windows

---

cmd/security-proxy-setup/main.go
cmd/security-proxy-setup/res/configuration.toml
cmd/security-proxy-setup/res/docker/configuration.toml
internal/security/proxy/service.go

Fix #1662
- Modified the security-proxy-setup configuration.toml file(s) docker and local
- Removed the use of the go-mod-core-contracts use of the ServiceList "statically defined"
- Removed the use of the ClientInfo struct and included the new ServiceInfo struct "now featured in the toml config"
- Modified the security/proxy/service.go init func simplifying the KongRoute(s) creational process
- Updated any required helper func(s) as required for the change from ClientInfo to ServiceInfo

Removing dependency for a Device/Service List and use Configuration

---

snap/snapcraft.yaml

Currently, integration within docker-edgex-mongo to access/setup vault isn't done, so we can't enable integration with vault yet for edgex-mongo, so explicitly turn it off (since if we don't specify it edgex-mongo defaults to trying to turn it on). This env var currently controls whether to use the `Credentials`  (with the env var set to `false` or the `SecretStore` section (with the env var missing or set to true) within the specified configuration.toml (we want Credentials which is just hard-coding the credentials inside the configuration.toml file).
This is a temporary measure until full integration is done. 
See also https://github.com/edgexfoundry/edgex-go/issues/1840
Also, the configuration options were changed to match the rest of EdgeX services, so update that too. 
See …

snapcraft.yaml: update docker-edgex-mongo args, add env var to disable security

---

snap/snapcraft.yaml

Executing snapcraft sets snap version for generated snap.
The version is read from VERSION file in root of source tree.
The date and git info is appended to version as previously.

Uses adopt-info with new 'version' part.

---

cmd/support-notifications/main.go
internal/support/notifications/config.go
internal/support/notifications/init.go

Update main.go and init.go to leverage the common bootstrapping functionality available to all services and remove redundant code.

Update support notifications to use common boostrap logic.

---

cmd/support-scheduler/res/configuration.toml
cmd/support-scheduler/res/docker/configuration.toml
internal/support/scheduler/const.go
internal/support/scheduler/interval.go
internal/support/scheduler/schedulecontext.go
internal/support/scheduler/schedulercontext_test.go
internal/support/scheduler/utils.go

Issue #1246  - Adjust Interval frequency so that uses Go standard time format.
Should allow miliseconds, microseconds, as well as nonoseconds.

Changing interval frequency field to use go standard time format

---

cmd/sys-mgmt-agent/toml_test.go
internal/system/agent/clients/general.go
internal/system/agent/clients/general_test.go
internal/system/agent/config/config.go
internal/system/agent/direct/metrics.go
internal/system/agent/getconfig/executor.go
internal/system/agent/init.go
internal/system/agent/setconfig/executor.go

Refactored to remove cyclical references that occur when factory of
metricsImpl is moved from main.go into internal/system/agent.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/1858

System Management Cyclical References

---

cmd/security-secretstore-setup/main.go
internal/pkg/usage/usage.go
internal/security/secretstore/certs_test.go
internal/security/secretstore/config.go
internal/security/secretstoreclient/vault.go

Adds logic to check to see if Vault is currently unsealed and
if not to unseal it.
1. Inside `cmd/security-secretstore-setup/res/configuration.toml`, edit the `[SecretStore]` section for the following fields:
```
server = "localhost"
scheme = "http"
cafilepath = "/Users/jdharms/workspace/edgex-go/cmd/security-secretstore-setup/EdgeXFoundryCA.pem"
certfilepath = "/Users/jdharms/workspace/edgex-go/cmd/security-secretstore-setup/edgex-kong.pem"
keyfilepath = "/Users/jdharms/workspace/edgex-go/cmd/security-secretstore-setup/edgex-kong.priv.key"
tokenfolderpath = "/Users/jdharms/workspace/edgex-go/cmd/security-secretstore-setup"
```
2. Ensure the paths in the previous step point to files on your file system and not mine.  The contents of these files are not important right now; I just used the …

Initialize and Unseal Vault in secretstore-setup init

---

internal/security/secretstoreclient/vault.go
internal/security/secretstoreclient/vault_test.go

The processResponse() internal method takes the response object
and eror object from the previous call to commonRequest().
While processing the error, the code formats an error using
the output error object as a source instead of the input
error object as a source, resulting in a nil access error.
A similar error is made when processing an unexpected response
code: this time a nil error object is always returned.
Unit tests have been added to check regressions.

Fix error handling bug in SecretStoreClient.processResponse

---

internal/core/data/device.go
internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/rest_devicereport.go
internal/core/metadata/rest_provisionwatcher.go
internal/core/metadata/utils.go
internal/support/logging/router.go
internal/support/logging/router_test.go
internal/support/logging/utils.go
internal/support/notifications/rest_notification.go
internal/support/notifications/utils.go

Fix #1582 
- The work in this PR takes care of performing a consistent set of checks across core-services to ensure that the limit (`MaxResultCount`) is not exceeded.

Perform a consistent set of checks across core-services to ensure that the limit is not exceeded.

---

cmd/security-secrets-setup/res/configuration.toml
internal/security/setup/config.go
internal/security/setup/option/cache.go
internal/security/setup/option/cache_test.go
internal/security/setup/option/constant.go
internal/security/setup/option/generate.go
internal/security/setup/option/generate_test.go
internal/security/setup/option/import.go
internal/security/setup/option/import_test.go
internal/security/setup/option/optionHelpers.go
internal/security/setup/option/optionHelpers_test.go
internal/security/setup/option/testdata/res/configuration.toml

user can specify paths for WorkDir, CacheDir, DeployDir and
CertConfigDir in the configuration.toml
CertConfigDir specifies the directory for certificate configuration json
files (fix #1767)
setting specified in environment variables override the configurable
settings
Signed-off-by: Enobong Udoko <enobong.n.udoko@intel.com>

support for configurable settings for security-secrets-setup

---

cmd/core-command/main.go
cmd/core-data/main.go
cmd/core-metadata/main.go
cmd/export-client/main.go
cmd/support-notifications/main.go
cmd/support-scheduler/main.go
internal/core/command/config.go
internal/core/command/init.go
internal/core/data/config.go
internal/core/data/init.go
internal/core/metadata/config.go
internal/core/metadata/init.go
internal/export/client/config.go
internal/export/client/init.go
internal/export/distro/init.go
internal/pkg/bootstrap/container/database.go
internal/pkg/bootstrap/handlers/database/database.go
internal/pkg/bootstrap/interfaces/database.go
internal/pkg/config/types.go
internal/pkg/db/interfaces/db.go
internal/pkg/telemetry/telemetry.go
internal/support/logging/config.go
internal/support/notifications/config.go
internal/support/notifications/init.go
internal/support/scheduler/config.go
internal/support/scheduler/init.go
internal/system/agent/init.go

Extracted dbClient creation from individual service-specific bootstrap
handlers into a common bootstrap handler.  Affected core-command,
core-data, core-metadata, export-client, support-logging,
support-notifications, and support-scheduler.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/1868

Extract dbClient implementations into single common bootstrap handler

---

cmd/core-command/main.go
cmd/core-data/main.go
cmd/core-metadata/main.go
cmd/export-client/main.go
cmd/export-distro/main.go
cmd/support-logging/main.go
cmd/support-notifications/main.go
cmd/support-scheduler/main.go
cmd/sys-mgmt-agent/main.go
internal/pkg/bootstrap/handlers/httpserver/httpserver.go
internal/pkg/bootstrap/handlers/message/message.go
internal/pkg/bootstrap/handlers/secret/secret.go

Affects secret, server, and start_message implementations at
internal/pkg/bootstrap/handlers.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/1880

Refactor to encapsulate common bootstrap handlers in own packages

---

cmd/core-command/res/configuration.toml
cmd/core-command/res/docker/configuration.toml
cmd/core-data/res/configuration.toml
cmd/core-data/res/docker/configuration.toml
cmd/core-metadata/res/configuration.toml
cmd/core-metadata/res/docker/configuration.toml
cmd/export-client/res/configuration.toml
cmd/export-client/res/docker/configuration.toml
cmd/export-distro/res/configuration.toml
cmd/export-distro/res/docker/configuration.toml
cmd/support-logging/res/configuration.toml
cmd/support-logging/res/docker/configuration.toml
cmd/support-notifications/res/configuration.toml
cmd/support-notifications/res/docker/configuration.toml
cmd/support-scheduler/res/configuration.toml
cmd/support-scheduler/res/docker/configuration.toml
cmd/sys-mgmt-agent/res/configuration.toml
cmd/sys-mgmt-agent/res/docker/configuration.toml
go.mod
internal/pkg/bootstrap/container/secret.go
internal/pkg/bootstrap/handlers/secret/secret.go

Fix #1825
Update configuration TOML files to include configurations for
SecretStore which is used to create a SecretClient.

Add SecretStore configurations to TOML files

---

cmd/security-secretstore-setup/main.go
internal/constants.go
internal/security/secretstore/init.go

security-secretsstore-setup is not migrating to common bootstrap
in this release. The config module can panic() while calling
deprecated methods to load the configuration while attempting
to log that configuration.toml cannot be found.
This patch sets the global variable before attempting to call
the deprecated configuration loading functions and then forces
the utility to exit if configuration cannot be loaded.
This is a temporary workaround until the utility can be
migrated to use the common bootstrap.

Fixes #1814 (nil panic while logging missing res/configuration.toml)

---

cmd/core-command/res/docker/configuration.toml
cmd/core-data/res/docker/configuration.toml
cmd/core-metadata/res/docker/configuration.toml
cmd/export-client/res/docker/configuration.toml
cmd/export-distro/res/docker/configuration.toml
cmd/support-logging/res/docker/configuration.toml
cmd/support-notifications/res/docker/configuration.toml
cmd/support-scheduler/res/docker/configuration.toml
cmd/sys-mgmt-agent/res/docker/configuration.toml
internal/core/command/config.go
internal/core/data/config.go
internal/core/metadata/config.go
internal/export/client/config.go
internal/export/distro/config.go
internal/pkg/bootstrap/handlers/secret/secret.go
internal/pkg/bootstrap/interfaces/configuration.go
internal/pkg/config/types.go
internal/support/logging/config.go
internal/support/notifications/config.go
internal/support/scheduler/config.go
internal/system/agent/config/config.go

Fix #1876
Update secret.BootstrapHandler to read the Vault token from a file
specified in the configuration.
Create a new SecretStoreInfo type which encapsulates the SecretConfig
and adds a configuration property for tokenfile information.
Update service specific configurations to use the newly created
SecretStoreInfo rather than SecretConfig so the tokenfile information
can be captured in the struct.

Update secret BootstrapHandler to read token file

---

Makefile

Rename security docker containers:
* docker-edgex-vault -> docker-edgex-secret-store-go
* docker-edgex-proxy-go -> docker-edgex-security-proxy-setup-go
* docker-edgex-vault-worker-go -> docker-edgex-security-secretstore-setup-go
To test, just run `make docker` and observe that all the builds finish. Will require an update to the docker-compose for Fuji in developer-scripts
Fixes #1933

Makefile: rename security docker containers

---

internal/system/agent/router.go

Fix #1932 
- This fix is for the `Edinburgh` branch.

Fix how the POST of invalid data to /api/v1/operation causes the Go runtime to panic.

---

cmd/config-seed/Attribution.txt
cmd/core-command/Attribution.txt
cmd/core-data/Attribution.txt
cmd/core-metadata/Attribution.txt
cmd/export-client/Attribution.txt
cmd/export-distro/Attribution.txt
cmd/security-proxy-setup/Attribution.txt
cmd/security-secrets-setup/Attribution.txt
cmd/security-secretstore-setup/Attribution.txt
cmd/security-secretstore-setup/main.go
cmd/security-secretstore-setup/res/configuration.toml
cmd/security-secretstore-setup/res/docker/configuration.toml
cmd/support-logging/Attribution.txt
cmd/support-notifications/Attribution.txt
cmd/support-scheduler/Attribution.txt
cmd/sys-mgmt-agent/Attribution.txt
cmd/sys-mgmt-executor/Attribution.txt
go.mod
internal/security/secretstore/config.go
internal/security/secretstore/password.go
internal/security/secretstore/password_test.go

Fixes #1676 
This PR implements the functionality to create database/mongodb credentials and store them in Vault during security-secretstore-setup initialization.
There are a few subtleties around this process.
1. The databases to have credentials created are specified in a new section of the security-secretstore-setup config file (for now).  I know that @tingyuz and @michaelestrin have had discussions on other ways to implement this, but they're out of scope for Fuji.
2. For some databases (core-data, for example), a specific service needs access to the credentials as well as the mongo service.  For others (admin, authorization, config, local), only the mongo service needs access.   This separation is handled by having a "service" key in the config section of each database to specify if …

security-secretstore-setup Credential Creation

---

snap/snapcraft.yaml

Also update the name of the license text from that repo.
This was broken by https://github.com/edgexfoundry/support-rulesengine/pull/53

snapcraft.yaml: update rulesengine jar file name

---

snap/snapcraft.yaml

Duplicate of https://github.com/edgexfoundry/edgex-go/pull/1956 for Edinburgh so we can unbreak the builds there.
This one was broken by https://github.com/edgexfoundry/support-rulesengine/pull/54

snapcraft.yaml: update rulesengine jar file name (edinburgh)

---

snap/snapcraft.yaml

Change to project dir root before getting the git rev so that set-version can include the git rev.

Add git rev to snap version

---

internal/core/command/device.go

Fix #1964
* If there are no devices provisioned, Core-Command should return an
empty slice when asked to return all commands in the database. It is
currently returning "null"

Core-Command: List all cmds should return empty slice

---

cmd/security-secretstore-setup/main.go

Security-secretstore-setup opens resp-init.json file in
read-only mode prior to checking if secret store
is initialized.  If the secret store must be initialized,
the code is unable to write the init response to disk.
This fix opens resp-init.json in read/write mode initially,
and during the init+unseal flow, resets the file pointer
prior to unsealing.
Fixes #1968

Fix security-secretstore-setup secret store initialization bug.

---

internal/system/agent/executor/executor-stub.go
internal/system/agent/executor/executor.go
internal/system/agent/executor/metrics.go
internal/system/agent/executor/operation.go
internal/system/agent/executor/operation_test.go
internal/system/agent/interfaces/executor.go
internal/system/agent/interfaces/operations.go
internal/system/agent/router.go
internal/system/executor/README.md

This reverts commit 82e87b26c3ad337de0a3e78cb0efff640788bae8.
See https://github.com/edgexfoundry/edgex-go/issues/1851#issuecomment-543806893
Note that while there is an equivalent PR reverting the go-mod-core-contracts change (see https://github.com/edgexfoundry/go-mod-core-contracts/pull/178), this PR does not depend on that PR since without that revert, we just end up ignoring the Parameters field here. Regardless, we should still remove the Parameters field there too until there's consensus on how to proceed for this feature.
This and https://github.com/edgexfoundry/go-mod-core-contracts/pull/178 will close https://github.com/edgexfoundry/edgex-go/issues/1851

Revert 1847

---

internal/system/agent/executor/operation.go
internal/system/agent/router.go

Fix #1866 
Fix #1856 
- As part of DEV testing, I supplied, in turn, the following incorrect and empty body each in with the request:
1. {"fake":"key"}
2. {}
- As expected, got the expected error message back with the response:
```
"incorrect or malformed body was passed in with request"
```

Add handling for the POST of invalid data to /api/v1/operation.

---

.dockerignore

Fixes #1973
There's no reason to have the .git/ directory in our docker build context,
having it present slows down builds and bloats cached images.

Add .git directory to .dockerignore file

---

.dockerignore
snap/snapcraft.yaml

This reverts commit b8067e79a59edeb59c32d43c4995926d047c226c.
Also manually add whitespace to the snapcraft.yaml folder to trigger the snap jobs in CI to confirm this unbreaks the snap builds.
We will eventually take up issue #1973 after Fuji is out, and we should also discuss in DevOps how to better address this sort of situation where a change outside of the snap/ dir affects the snap build.

Revert "Add .git directory to .dockerignore file (#1974)"

---

cmd/security-secretstore-setup/main.go

Add detailed log entry when error of creating resp-init.json file happens.

log resp-init.json file creation error

---

internal/security/secretstore/password.go
internal/security/secretstore/password_test.go

Fixes #1981
UserPasswordPair should be marshaled into json as
{username, password} instead of {user, password}.

Fix marshaling of secretstore.UserPasswordPair

---

cmd/core-command/res/configuration.toml
cmd/core-command/res/docker/configuration.toml
cmd/security-secretstore-setup/res/configuration.toml
cmd/security-secretstore-setup/res/docker/configuration.toml

Update core-commands' TOML files to use core-metadata's secrets since
core-command uses core-metadata's database for persistence.
Revert changes to security-secretstore-setup which included creating
secrets for core-command. These are not needed since core-command uses
core-metadata's database.

Fix core-command configuration for secrets

---

go.mod
internal/pkg/bootstrap/logging/factory.go

Fixes #1989.
Requires edgexfoundry/go-mod-core-contracts/pull/182 and a release to be cut. Will be taken out of draft status after that happens.

Fix "logTarget cannot be blank" every time on startup

---

cmd/config-seed/res/properties/edgex-support-rulesengine/application.properties
cmd/config-seed/res/properties/edgex-support-rulesengine;docker/application.properties

Rules Engine properties changed so the default is that it now receives messages from new App Service Configurable (rules-engine profile).
closes #1991

feat(config-seed): Change Config Seed rules engine properties for App-Service-Configurable

---

cmd/core-data/main.go
internal/core/data/device.go
internal/core/data/device_test.go
internal/core/data/domain_events.go
internal/core/data/event.go
internal/core/data/event_test.go
internal/core/data/init.go
internal/core/data/reading.go
internal/core/data/reading_test.go
internal/core/data/router.go
internal/core/data/router_test.go
internal/core/data/utils.go
internal/core/data/valuedescriptor.go
internal/core/data/valuedescriptor_test.go

Fix #2024
Update core-data to leverage the dependency injection container(DIC)
during bootstrap and pass a 'LoggingClient' instance down the call stack
to eliminate the need for the 'LoggingClient' global variable.
Update tests to use a DIC when loading REST routes as they will need the
DIC to obtain a reference of the 'LoggingClient'. Also, update any
references to methods/functions which have updated signatures to accept
a 'LoggingClient' as part of changes to the production code.

Remove 'LoggingClient' global usage in core-data

---

bin/edgex-launch.sh
cmd/core-command/res/configuration.toml
cmd/core-data/res/configuration.toml
cmd/core-metadata/res/configuration.toml
cmd/export-client/res/configuration.toml
cmd/security-proxy-setup/res/configuration.toml
cmd/support-logging/res/configuration.toml
cmd/support-notifications/res/configuration.toml
cmd/support-scheduler/res/configuration.toml

See the commit messages for a more thorough explanation, but basically we should be consistent in setting these values for a few reasons, one of which is that it greatly simplifies setting up the security workflow for the snap as a part of my work on #1840
If we don't do this, then I have to either:
- convert the toml file to json to use jq to set these values, then convert back to toml
- use a really nasty sed expression to replace lines with stuff that is really going above the matching lines so that we can insert these keys into the middle of the file
Neither of which I really want to do.
The regression potential here is pretty low since we're simply adding default values (same as for the docker configuration.toml) to config files.
The other change here is changing the default `SNIS` …

many/configuration.toml: set default security key values, fix proxy SNIs

---

cmd/security-proxy-setup/main.go
internal/security/proxy/init.go

Fix nil panic when configuration.toml can't be loaded.
Fixes #1814 
When configuration.toml can't be loaded, the
LoggingClient global variable isn't initialized,
causing main program to panic when it attempts
to log that configuration.toml can't be loaded.
This is a temporary workaround until security-proxy-setup
is migrated to the common bootstrap.

[FUJI BRANCH] Fix nil panic when configuration.toml can't be loaded.

---

cmd/core-command/main.go
internal/core/command/config.go
internal/core/command/const.go
internal/core/command/device.go
internal/core/command/device_test.go
internal/core/command/get.go
internal/core/command/get_test.go
internal/core/command/init.go
internal/core/command/interfaces.go
internal/core/command/put.go
internal/core/command/put_test.go
internal/core/command/restDevice.go
internal/core/command/router.go
internal/core/command/types.go
internal/core/command/types_test.go
internal/pkg/di/container.go

Fix #2013 
Update core-command to leverage the dependency injection container(DIC)
during bootstrap and pass a 'LoggingClient' instance down the call stack
to eliminate the need for the 'LoggingClient' global variable.

Remove 'LoggingClient' global usage in core-command

---

cmd/security-proxy-setup/Dockerfile
cmd/security-secretstore-setup/Dockerfile

We need `/bin/sh` and `curl` in both security-proxy-setup and security-secretstore-setup Docker iamges in order to run our dependency checks in the various dependency checks. 
See usage of this in the developer-scripts PR: https://github.com/edgexfoundry/developer-scripts/pull/172. That PR also contains full testing instructions for everything needed to fix #1710 for Fuji, but to test specifically this PR, all you need to do is build the containers and then start them with the docker-compose from developer-scripts and note that it works as before. I.e. run:
```
$ make docker_security_secretstore_setup docker_security_proxy_setup
```
and observe the containers build successfully. Then apply a patch to developer-scripts repo for the nightly-releases docker-compose.yml file like this: …

security-{proxy,secretstore}-setup/Dockerfile: use alpine to get curl

---

cmd/security-proxy-setup/main.go
internal/security/proxy/init.go

Fix nil panic when configuration.toml can't be loaded.
Fixes #1814 (cherry-pick from fuji branch)
When configuration.toml can't be loaded, the
LoggingClient global variable isn't initialized,
causing main program to panic when it attempts
to log that configuration.toml can't be loaded.
This is a temporary workaround until security-proxy-setup
is migrated to the common bootstrap.
Duplicate of #2054 for master

Fix nil panic when configuration.toml can't be loaded.

---

cmd/core-metadata/main.go
internal/core/metadata/init.go
internal/core/metadata/rest_addressable.go
internal/core/metadata/rest_addressable_test.go
internal/core/metadata/rest_command.go
internal/core/metadata/rest_command_test.go
internal/core/metadata/rest_device.go
internal/core/metadata/rest_device_test.go
internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/rest_deviceprofile_test.go
internal/core/metadata/rest_devicereport.go
internal/core/metadata/rest_deviceservice.go
internal/core/metadata/rest_deviceservice_test.go
internal/core/metadata/rest_provisionwatcher.go
internal/core/metadata/router.go
internal/core/metadata/utils.go

Fix #2018 
- Update core-metadata to leverage the Dependency Injection Container(DIC) during bootstrap and pass a `LoggingClient` instance down the call stack to eliminate the need for the `LoggingClient` global variable.
- Update tests to use a DIC when loading REST routes as they will need the DIC to obtain a reference of the `LoggingClient`.
- Also, update any references to methods/functions which have updated signatures to accept a `LoggingClient` as part of changes to the production code.

Refactor Metadata-related code to remove LoggingClient global variable.

---

internal/security/proxy/certs.go

Fixes #1710  as part of dependency check for security proxy setup bootstrap starting.
Add for-loop of retries until it succeeds.

Fixes issue #1710 for security proxy setup

---

internal/pkg/db/mongo/models/device.go

This is a duplicate of #2083 (which targets the fuji branch)
/pkg/db/mongo/models/device.go's ToContract() method assigned
some values to the named contract.Device in the return value.
This value was overwritten at the end of the method causing these
assignments to be discarded.
This change removes all named return values from the file and
adjusts the methods accordingly.
fixes: #2034

fix: #2034 fixes bug around named return values (edinburgh)

---

internal/pkg/db/redis/queries.go

fix #2064
reference the PR #2073
"RANGE" -> "ZRANGE"
"REVRANGE" -> "ZREVRANGE"

Fix the incorrect Redis command names (fuji)

---

cmd/core-command/res/configuration.toml
cmd/core-command/res/docker/configuration.toml
cmd/core-data/res/configuration.toml
cmd/core-data/res/docker/configuration.toml
cmd/core-metadata/res/configuration.toml
cmd/core-metadata/res/docker/configuration.toml
cmd/export-client/res/configuration.toml
cmd/export-client/res/docker/configuration.toml
cmd/support-logging/res/configuration.toml
cmd/support-logging/res/docker/configuration.toml
cmd/support-notifications/res/configuration.toml
cmd/support-notifications/res/docker/configuration.toml
cmd/support-scheduler/res/configuration.toml
cmd/support-scheduler/res/docker/configuration.toml
go.mod
internal/pkg/bootstrap/handlers/secret/secret.go

Fix #2080
Add configuration properties needed to leverage the retry logic within
the SecretClient. This helps address the issue of temporal coupling,
when security is enabled, between services, and bootstrapping steps by
giving some grace period for dependencies before unsuccessfully
exiting(shutting down) the service.
Update to use the latest version of `go-mod-secrets` which has the retry
logic.

Add configuration for SecretClient retries (master)

---

cmd/core-command/res/configuration.toml
cmd/core-command/res/docker/configuration.toml
cmd/core-data/res/configuration.toml
cmd/core-data/res/docker/configuration.toml
cmd/core-metadata/res/configuration.toml
cmd/core-metadata/res/docker/configuration.toml
cmd/export-client/res/configuration.toml
cmd/export-client/res/docker/configuration.toml
cmd/support-logging/res/configuration.toml
cmd/support-logging/res/docker/configuration.toml
cmd/support-notifications/res/configuration.toml
cmd/support-notifications/res/docker/configuration.toml
cmd/support-scheduler/res/configuration.toml
cmd/support-scheduler/res/docker/configuration.toml
go.mod
internal/pkg/bootstrap/handlers/secret/secret.go

Fix #2080
Add configuration properties needed to leverage the retry logic within
the SecretClient. This helps address the issue of temporal coupling,
when security is enabled, between services, and bootstrapping steps by
giving some grace period for dependencies before unsuccessfully
exiting(shutting down) the service.
Update to use the latest version of `go-mod-secrets` which has the retry
logic.

Add configuration for SecretClient retries (fuji)

---

internal/pkg/db/redis/queries.go

fix #2064
"RANGE" -> "ZRANGE"
"REVRANGE" -> "ZREVRANGE"

Fix the incorrect Redis command names (master)

---

cmd/core-command/res/configuration.toml
cmd/core-command/res/docker/configuration.toml
cmd/core-data/res/configuration.toml
cmd/core-data/res/docker/configuration.toml
cmd/core-metadata/res/configuration.toml
cmd/core-metadata/res/docker/configuration.toml
cmd/export-client/res/configuration.toml
cmd/export-client/res/docker/configuration.toml
cmd/support-logging/res/configuration.toml
cmd/support-logging/res/docker/configuration.toml
cmd/support-notifications/res/configuration.toml
cmd/support-notifications/res/docker/configuration.toml
cmd/support-scheduler/res/configuration.toml
cmd/support-scheduler/res/docker/configuration.toml
go.mod
snap/snapcraft.yaml

This is in concert with a change to go-mod-secrets to do the parsing in go-mod-secrets.
Note that this can't be merged until after https://github.com/edgexfoundry/go-mod-secrets/pull/38 is merged. I need to push a commit here changing the go.mod to use the updated version of go-mod-secrets after the go-mod-secrets PR is merged and the merge job runs tagging the repo with a new release. 
To test this, I suggest building all of the docker containers here and then testing this alongside my outstanding developer-scripts PR here: https://github.com/edgexfoundry/developer-scripts/pull/175 which with https://github.com/edgexfoundry/docker-edgex-consul/pull/7 and https://github.com/edgexfoundry/docker-edgex-mongo/pull/67 will make edgex-mongo fully deterministic and ordered after it's …

many/configuration.toml: use time.Duration string for RetryWaitPeriod

---

snap/snapcraft.yaml

This is a user command for running security-proxy-setup to create tokens, etc.
The home and removable-media plugs are for reading config files outside of the snap's writable area.
To test, build the snap and run:
```
$ edgexfoundry.security-proxy-setup-cmd --help
Usage: /snap/edgexfoundry/x1/bin/security-proxy-setup [options]
Server Options:
-p, --profile <name>              Indicate configuration profile other than default
-r, --registry                    Indicates service should use Registry
--insecureSkipVerify=true/false   Indicates if skipping the server side SSL cert verification, similar to -k of curl
--init=true/false                 Indicates if security service should be initialized
--reset=true/false                Indicate if security service should be reset to initialization …
```

snapcraft.yaml: add security-proxy-setup-cmd

---

cmd/support-notifications/Dockerfile

- This PR addresses: #2041 
- This fix is for the `Fuji` branch, and was made possible by invaluable assist from @tsconn23, and also @michaelestrin, and @AnthonyMBonafide 👍

Fix support-notifications was failing to send email for critical notification.

---

cmd/support-notifications/Dockerfile

- This PR addresses: #2041 
- This fix is for the `master` branch, and was made possible by invaluable assist from @tsconn23, and also @michaelestrin, and @AnthonyMBonafide 👍

Fix (on master branch) how support-notifications was failing to send email for critical notification

---

cmd/config-seed/Dockerfile

Fixes #2108 in Fuji.
Verification steps:
1. Create a local docker image for `config-seed`.
2. Build a container using that image.
3. Edit http://github.com/edgexfoundry/developer-scripts/blob/master/releases/nightly-build/compose-files/docker-compose-nexus-redis-no-secty.yml so that your local container is pulled instead of the remote Nexus image. This will be on line 70.
4. Allow the build to run and proceed.
5. Ensure core-command has not died.
6. After the containers are running, inspect Consul at http://localhost:8500/ui/
7. Navigate to the core-command configuration, and visually inspect that Redis is set as the default provider.

(fuji) Fixed bug with using Redis for core-command in Docker.

---

internal/pkg/db/redis/data.go
internal/pkg/db/redis/event.go
internal/pkg/db/redis/queries.go

#2076 in Fuji.
Verification steps:
Start Redis. Start core-data with Redis configured as the DB.
First, flush your Redis database with this redis-cli command:
`redis-cli FLUSHALL`
Run the following cURL command:
```
curl -X POST \
http://localhost:48080/api/v1/event \
-H 'Accept: */*' \
-H 'Accept-Encoding: gzip, deflate' \
-H 'Cache-Control: no-cache' \
-H 'Connection: keep-alive' \
-H 'Content-Length: 230' \
-H 'Content-Type: application/json' \
-H 'Host: localhost:48080' \
-H 'cache-control: no-cache' \
-d '{  
"origin":1471806386919,
"device":"cartachometer",
"readings":[  
{  
"origin":1471806386919,
"device":"cartachometer",
"name":"luminousIntensity",
"value":"40"
}
]
}'
```
Copy the UUID returned by the request. Run this additional cURL command to delete the event:
```
curl -X …
```

(fuji) Delete event func for Redis misses the deletion of pushed and device collection

---

snap/hooks/configure
snap/hooks/install
snap/snapcraft.yaml

Add the app-service-configurable service to the snap so that it can be used with the rules-engine profile in place of the export services for Fuji when a user wants to use support-rulesengine.
To test this, build the snap and then install it. Then:
```
$ snap services edgexfoundry.app-service-configurable
Service                                Startup   Current   Notes
edgexfoundry.app-service-configurable  disabled  inactive  -
```
```
$ snap set edgexfoundry support-rulesengine=on
$ snap services edgexfoundry.app-service-configurable
Service                                Startup  Current  Notes
```
```
edgexfoundry.app-service-configurable  enabled  active   -
$ snap logs edgexfoundry.app-service-configurable 
2019-11-12T16:52:52Z edgexfoundry.app-service-configurable[14568]: …
```

Add app-service-config with rules-engine profile to the snap

---

internal/core/metadata/operators/device/update.go
internal/core/metadata/operators/device/update_test.go

Fix #2119
Update the HTTP method from POST to PUT when invoking a callback for
a device service when a device has been updated.

Fix update device functionality to correct method

---

internal/security/secretstore/certs.go
internal/security/secretstore/certs_test.go
internal/security/secretstore/init.go
internal/security/secretstore/password.go
internal/security/secretstore/password_test.go
internal/security/secretstore/requester.go

Fixes: https://github.com/edgexfoundry/edgex-go/issues/2127
Dependency on (includes work from) https://github.com/edgexfoundry/edgex-go/pull/2126. That PR must be reviewed and merged prior to this one.

security-secretstore-setup: refactor to remove LoggingClient global variable

---

go.mod
internal/pkg/endpoint/endpoint.go

Alternate Endpointer contract implementation that encapsulates go routine and stream creation and avoids exposing recently added Fetch() method.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/2099

Endpointer Clean Up

---

snap/snapcraft.yaml

This PR switches to using Kong 1.3, which requires re-adding back the lua and luarocks parts since the versions of those in the ubuntu bionic archives are too old to build Kong 1.3. Additionally, to build Kong 1.3 we also have to add a new Lua module to OpenResty, lua-kong-nginx-module.
Since MongoDB 4.2 links against libssl 1.1, and MongoDB 3.4 links against libssl 1.0, we need to make that change in sync with changing Kong because Kong 1.0 cannot link against libssl 1.1, but Kong 1.3 can link against libssl 1.1. I think that Kong and company can be built to link against libssl 1.0, but that is not the default so I didn't want to add extra work for myself to first upgrade Kong to 1.3 using libssl 1.0, only to switch to libssl 1.1 immediately afterwards when upgrading MongoDB. Thus these …

snapcraft.yaml: upgrade Kong to 1.3.0, upgrade MongoDB to 4.2

---

snap/snapcraft.yaml

This avoids https://github.com/edgexfoundry/edgex-go/issues/2138 because we are
able to make directories as needed in /tmp, where we are unable to create
the root directory of $XDG_RUNTIME_DIR of /run/user/0 due to one or both of
these snapd bugs:
- https://bugs.launchpad.net/snap-confine/+bug/1620442
- https://bugs.launchpad.net/snappy/+bug/1656340
Signed-off-by: Ian Johnson <ian.johnson@canonical.com>
Fixes #2138 for Fuji
To test this, you need to build the snap and install it in strict mode with `--dangerous` because installing with devmode will not trigger the denial. Attempting to install in strict mode without this patch will fail as in the referenced issue. Specifically do this on a Linux machine after [installing snapd](https://snapcraft.io/docs/installing-snapd):
If you are …

Specify XDG_RUNTIME_DIR as /tmp for security-secrets-setup in the snap

---

snap/snapcraft.yaml

Duplicate of https://github.com/edgexfoundry/edgex-go/pull/2139 but for master.

Specify XDG_RUNTIME_DIR as /tmp for security-secrets-setup in the snap (master)

---

internal/core/data/event.go
internal/core/data/event_test.go
internal/core/data/init.go
internal/core/data/reading.go
internal/core/data/reading_test.go
internal/core/data/router.go
internal/core/data/router_test.go
internal/core/data/valuedescriptor.go
internal/core/data/valuedescriptor_test.go

Fix #2025
Remove dbClient global variable from the core-data service/package(s)
and update the routers to get the dbClient from th DI container and pass
it to the necessary REST handlers. Also, update any functions/methods
which were referring to the dbClient global variable to rather accept an
instance of the DBClient interface.
Update tests to conform to the changes to the production code.

Remove dbClient global variable from core-data

---

Makefile
cmd/security-secrets-setup/Dockerfile
cmd/security-secrets-setup/entrypoint.sh
cmd/security-secrets-setup/start_vault.sh
cmd/security-secretstore-setup/Dockerfile
cmd/security-secretstore-setup/entrypoint.sh

This PR attempts to address issues #1716.  There are a couple steps to accomplish that:
1. Split the docker image file from inhering the Vault
2. Update the newly generated TLS paths (Related PRs: https://github.com/edgexfoundry/docker-edgex-mongo/pull/71, )
3. Update the consul checking scripts (Related PR: https://github.com/edgexfoundry/docker-edgex-consul/pull/10)
The focus of this PR is on the **step 1**.
The original customized edgex-vault docker image is broken into two separate images:
the official Vault docker image from HashiCorp and the `security-secrets-setup` docker image
- add customized docker entrypoint script for starting vault
- use sentinel files for readiness check of TLS cert of vault because vault image does not have curl command available
- prepare cross-mount …

Split customized vault into two docker images- part 1

---

snap/hooks/configure
snap/hooks/install
snap/snapcraft.yaml

Duplicate of #2116 for Geneva/master.
Unclear what we want to do long term with this, but since we don't have a new replacement rules engine yet and the export services are supposed to be dropped sometime this cycle, let's just make sure that master is in the same state as Fuji w/respect to using rules-engine.
Also note that this builds from master app-service-configurable rather than the tagged 1.0 release of that repo since we want master to be rolling.

Add app-service-config with rules-engine profile to the snap (master)

---

internal/support/scheduler/schedule.go
internal/support/scheduler/utils.go

QueueClient receiver and corresponding factory method moved to
schedule.go where the QueueClient method implementation lives.  Removed
unused currentQueueClient global.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/2154

Scheduler: Remove QueueClient global and refactor its code

---

internal/support/scheduler/container/queue.go
internal/support/scheduler/init.go
internal/support/scheduler/interval.go
internal/support/scheduler/interval_action.go
internal/support/scheduler/interval_action_test.go
internal/support/scheduler/interval_test.go
internal/support/scheduler/loader.go
internal/support/scheduler/rest_interval.go
internal/support/scheduler/rest_interval_test.go
internal/support/scheduler/rest_intervalaction.go
internal/support/scheduler/rest_intervalaction_test.go
internal/support/scheduler/router.go

Fixes #2037.
Requires merge from #2176 first.
To verify, run the unit and blackbox tests.

Scheduler: Remove scClient global variable

---

cmd/security-proxy-setup/main.go
cmd/security-secrets-setup/main.go
cmd/security-secretstore-setup/main.go
go.mod
internal/constants.go

Refactoring to move security service keys from edgex-go to go-mod-core contracts.
Fixes #2174
Merge blocked by https://github.com/edgexfoundry/go-mod-core-contracts/pull/185

Refactoring to move security service keys from edgex-go to go-mod-core contracts.

---

snap/snapcraft.yaml

Change from /run/edgex/secrets to /tmp/edgex/secrets

Update the default TLS path to /tmp instead of /run for snap

---

internal/core/command/router.go
internal/support/scheduler/router.go

Part of #2074 
To verify, run the unit tests and the `ping` and `resource` black box tests for `core-command`. Scheduler does not have a ping or resource BB test; hit those endpoints manually. 

Removed unused request parameters from scheduler and command.

---

internal/core/metadata/container/coredata.go
internal/core/metadata/init.go
internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/rest_deviceprofile_test.go
internal/core/metadata/router.go

Fix #2022 
- As with the PR for the prior issue (#2021), a handful of blackbox failures are also present in `master` when I ran them; these failures are not related to the changes made per this (current) PR.

Refactor metadata to remove the vdc (i.e. ValueDescriptorClient) global variable.

---

internal/pkg/db/redis/data.go
internal/pkg/db/redis/event.go

Fix #2143
Update the deleteEvent function to perform an extra lookup for the
checksum value associated with the event to be deleted and remove the
lingering data. The additional lookup is necessary since there are three
different types of Events(correlation,contract,and redisEvent) being
used within the Redis implementation of the DBClient and the one being
used for common lookups(contract) does not have the checksum information
so it is lost during serialization. The approach is the most direct and
non-invasive solution. Other attempts to clean-up and reduce the
divergence of the types being used resulted in unrelated Blackbox test
failures.

Fix orphaned event checksum data for Redis

---

cmd/security-secretstore-setup/main.go
internal/pkg/usage/usage.go
internal/security/secretstore/init.go

init is not being used in security-secretstore-setup so remove it from the codebase. This is to address #2077 
Signed-off-by: Tingyu Zeng <Tingyu.Zeng@rsa.com>

fix issue 2077: init flag not being used in security-secretstore-setup

---

internal/pkg/db/redis/queries.go

The issue where Redis events were not being deleted correctly. 
The nil object will cause the reading unmarshal error "unexpected end of JSON input", so check every object and then return the result.
Fix #2187

Fix event deleting func with redis DB.

---

internal/core/command/init.go
internal/core/data/init.go
internal/core/metadata/init.go
internal/export/client/init.go
internal/export/distro/init.go
internal/pkg/bootstrap/bootstrap.go
internal/pkg/bootstrap/configuration/registry.go
internal/pkg/bootstrap/handlers/database/database.go
internal/pkg/bootstrap/handlers/httpserver/httpserver.go
internal/pkg/bootstrap/handlers/message/message.go
internal/pkg/bootstrap/handlers/secret/secret.go
internal/pkg/bootstrap/interfaces/handler.go
internal/pkg/telemetry/telemetry.go
internal/security/proxy/init.go
internal/security/secrets/init.go
internal/security/secretstore/init.go
internal/support/logging/init.go
internal/support/scheduler/init.go
internal/system/agent/init.go

Moved context to be first parameter in function/method calls; ensure
named ctx.  See https://golang.org/pkg/context/
Fixes: https://github.com/edgexfoundry/edgex-go/issues/2195

Refactor Bootstrap context.Context usage to be idomatic

---

internal/core/data/container/events.go
internal/core/data/device_test.go
internal/core/data/domain_events.go
internal/core/data/event.go
internal/core/data/event_test.go
internal/core/data/init.go
internal/core/data/router.go

Fix #2026
Remove the global variable chEvent and instead use the DI container to
pass the reference to the channel to different parts of the system.
Update function arguments to accept either publishing or consuming Go
channels so that the intent of the function is clear and also to avoid
errors at compile time.
Update tests to work with the new function signatures.

Remove chEvent global variable from core-data

---

Makefile
cmd/security-file-token-provider/Attribution.txt
cmd/security-file-token-provider/README.md
cmd/security-file-token-provider/main.go
cmd/security-file-token-provider/res/configuration.toml
cmd/security-file-token-provider/res/docker/configuration.toml
internal/pkg/usage/usage.go
internal/security/fileprovider/config/config.go
internal/security/fileprovider/container/config.go
internal/security/fileprovider/init.go
internal/security/fileprovider/interface.go
internal/security/fileprovider/provider.go

This is the main program bootstrap skeleton for
cmd/security-file-token-provider as documented in
edgex-docs/security/token-file-provider.1.rst

Implement cmd/security-file-token-provider scaffolding

---

cmd/core-command/main.go
cmd/security-file-token-provider/main.go
cmd/security-proxy-setup/main.go
cmd/security-secrets-setup/main.go
cmd/security-secretstore-setup/main.go
cmd/support-notifications/main.go
cmd/support-scheduler/main.go
cmd/sys-mgmt-agent/main.go

Removed redundant definition of ConfigurationInterfaceName in
dependency injection container instantiation in each core
service's main.go.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/2206

Remove Unnecessary DIC definition in service's main.go

---

cmd/security-secretstore-setup/entrypoint.sh

This PR is to remove the invalid or no-longer existing flag, `--init`, for `security-secretstore-setup` (aka vault-worker).
The init flag was removed from PR #2188 but this place from the entrypoint script was omitted at that time so the bug is was introduced.
Fixes issue #2213

Fix bug #2213: invalid init flag for vault-worker

---

internal/core/data/container/messaging.go
internal/core/data/event.go
internal/core/data/event_test.go
internal/core/data/init.go
internal/core/data/router.go

Fix #2027
Remove the msgClient global variable in favor of using the DI container
for passing around an instance during bootstrap. Update functions which
were referring to the global variable to instead accept an instance as
function arguments.
Update tests to work with the changes to the production code.

Remove msgClient global variable for core-data

---

internal/support/logging/container/persistence.go
internal/support/logging/init.go
internal/support/logging/interfaces/persistence.go
internal/support/logging/router.go

dbClient -> persistenceClient; interfaces.Logger -> interfaces.Persistence
From https://github.com/edgexfoundry/edgex-go/pull/2204#discussion_r355002100
Fixes: https://github.com/edgexfoundry/edgex-go/issues/2211
Dependency on #2071

support-logging -- update variable/interface naming for consistency

---

internal/security/secretstoreclient/const.go
internal/security/secretstoreclient/interface.go
internal/security/secretstoreclient/messages.go
internal/security/secretstoreclient/mocks/mock.go
internal/security/secretstoreclient/mocks/mock_test.go
internal/security/secretstoreclient/roottoken.go
internal/security/secretstoreclient/roottoken_test.go
internal/security/secretstoreclient/vault.go
internal/security/secretstoreclient/vault_test.go

Add a number of API calls to the SecretStoreClient
that will be needed to implement Geneva release
security features. These calls support revokation
of previously issued tokens, revokation of the root
token, and generation of new root tokens from
the Vault master key.

Add API calls to SecretStoreClient needed for future PRs

---

internal/core/command/router.go
internal/core/data/router.go
internal/core/metadata/router.go
internal/export/client/router.go
internal/export/distro/router.go
internal/support/logging/router.go
internal/support/notifications/router.go
internal/support/notifications/utils.go
internal/support/scheduler/router.go
internal/system/agent/router.go

Removed unused request parameters from controller functions.  Cleaned
up formatting. Cleaned up io.WriteString() usage; now consistently
using w.Write(). Explicitly ignoring errors from w.Write() and
r.Body.Close().  Folded metrics, configuration, and ping controller
functions into routing definition closures (except for export
services which are being archived before Geneva release).
Fixes: https://github.com/edgexfoundry/edgex-go/issues/2074

Remove unused request parameter from controller functions

---

internal/system/agent/concurrent/concurrent.go
internal/system/agent/direct/metrics.go
internal/system/agent/executor/executor-stub.go
internal/system/agent/executor/metrics.go
internal/system/agent/executor/metrics_test.go
internal/system/agent/executor/operation.go
internal/system/agent/executor/operation_test.go
internal/system/agent/getconfig/executor.go
internal/system/agent/getconfig/get.go
internal/system/agent/interfaces/config.go
internal/system/agent/interfaces/operations.go
internal/system/agent/router.go

Implemented concurrent calls to individual services/external
executor to obtain metrics.  Updated context.Context parameter
passing to be idiomatic (i.e. first parameter).
Fixes: https://github.com/edgexfoundry/edgex-go/issues/2008

Gather System Management Metrics Asynchronously

---

internal/pkg/endpoint/endpoint.go

Fixes: https://github.com/edgexfoundry/edgex-go/issues/2238

Endpoint.Monitor missing "for" loop

---

internal/security/secretstore/init.go
internal/security/secretstore/tokenprovider.go
internal/security/secretstore/tokenprovider_linux_test.go
internal/security/secretstore/tokenprovider_test.go

Remove platform dependencies from TokenProvider unit tests.
Fixes #2233.
Remove platform dependencies (assumption of /bin/false, /bin/true,
and /bin/echo) from the unit tests by injecting a dependency
that abstracts the concrete implementation of os.exec and os.Cmd.

Remove platform dependencies from TokenProvider unit tests.

---

internal/core/data/container/metadata.go
internal/core/data/device.go
internal/core/data/domain_events.go
internal/core/data/event.go
internal/core/data/event_test.go
internal/core/data/init.go
internal/core/data/reading.go
internal/core/data/reading_test.go
internal/core/data/router.go
internal/core/data/valuedescriptor.go
internal/core/data/valuedescriptor_test.go

Fix #2028
Remove the global variable mdc(metadata client), and instead use the DI
container to create and pass an instance to functions/methods which need
it.
Update function/method signatures to accept the metadata client as a
parameter.
Update tests to work with changes to the production code.

Remove global variable mdc from core data

---

cmd/security-secretstore-setup/README.md

Fix #1776 
- Note that, with recent release, the command line parameters for `secretstore-setup` have been updated. The latest supported command line parameters have been updated per the section `securitySecretStoreSetupUsageStr` in [usage.go](https://github.com/edgexfoundry/edgex-go/blob/master/internal/pkg/usage/usage.go):
- Also, the link to fuji compose file has been updated.

Add README to security-secretstore-setup service.

---

README.md

Observed issue was:
```
docker-compose --version
docker-compose version 1.21.0, build unknown
ERROR:
Can't find a suitable configuration file in this directory or any
parent. Are you in the right directory?
Supported filenames: docker-compose.yml, docker-compose.yaml
```
Change-Id: Ia750efa6da96509e2e095ae8f76f094b2b01bde6
Forwarded: https://github.com/edgexfoundry/edgex-go/pull/2261
Signed-off-by: Philippe Coval <rzr@users.sf.net>

doc: Save to docker-compose.yml

---

cmd/security-proxy-setup/res/docker/configuration.toml
internal/security/proxy/certs.go

Add dependency on auth token loader so that it can read service
tokens or root tokens interchangably.  Configure docker version of
configuration.toml to use per-service token.
Fixes #1930 

Enable edgex-proxy to use per-service token instead of root token.

---

cmd/security-secretstore-setup/entrypoint.sh
cmd/security-secretstore-setup/res-file-token-provider/docker/configuration.toml
cmd/security-secretstore-setup/res/docker/configuration.toml
internal/security/fileprovider/init.go
internal/security/fileprovider/main.go
internal/security/secretstore/certs.go
internal/security/secretstore/certs_test.go
internal/security/secretstore/constants.go
internal/security/secretstore/init.go
internal/security/secretstore/password.go
internal/security/secretstore/password_test.go
internal/security/secretstore/tokenmaintenance.go
internal/security/secretstore/tokenmaintenance_test.go
internal/security/secretstoreclient/types.go

This commit modifies the back-half of the Vault init/unseal
flow so that the Vault key shares are used to generate a
transient root token when is then used for the remainder
of processing.  The transient root token is used to create
an admin token with the necessary privilege to run
security-file-token-provider with a non-root token.
Moreover, the transient token is also used for seeding
of database passwords and Kong TLS certificates.
Additionally, upon every startup, the existing admin/
service tokens from the previous run are revoked and
replaced with new ones.  The container entrypoint
script is changed to busy-wait at the end of its execution
so that tokens are not inadvertently revoked and replaced
should the container restart as happens during
blackbox testing.
This commit also …

Deprivilege token provider and revoke old tokens on startup.

---

go.mod
internal/security/fileprovider/init.go
internal/security/fileprovider/provider.go
internal/security/fileprovider/provider_test.go
internal/security/fileprovider/tokenconfig.go
internal/security/fileprovider/tokenconfig_test.go
internal/security/proxy/certs.go
internal/security/secretstore/init.go
internal/security/secretstoreclient/requestor.go
internal/security/secretstoreclient/roottoken.go
internal/security/secretstoreclient/roottoken_test.go
internal/security/secretstoreclient/vault.go
internal/security/secretstoreclient/vault_test.go

Fix #2235
Update the versions of go-mod-secrets and go-mod-bootstrap
Update references to 'authtokenloader' and 'fileioperformer' since they
have been moved from go-mod-bootstrap to go-mod-secrets in the versions
now being utilized.

Update go-mod-secrets and go-mod-bootstrap

---

cmd/security-secretstore-setup/res/docker/configuration.toml
internal/security/secretstore/init.go
internal/security/secretstore/init_test.go
internal/security/secretstoreclient/interface.go
internal/security/secretstoreclient/messages.go
internal/security/secretstoreclient/mocks/mock.go
internal/security/secretstoreclient/mocks/mock_test.go
internal/security/secretstoreclient/roottoken.go
internal/security/secretstoreclient/roottoken_test.go
internal/security/secretstoreclient/vault.go
internal/security/secretstoreclient/vault_test.go

Changes revokeroottokens setting in docker configuration
from false to true and expunges the root token from
resp-init.json when revokeroottokens==true.
To facilitate this change, it is necessary to filter
the Vault /sys/init response so that the root_token
field can be removed.  Minor changes have been made
to SecretStoreClient such that all file IO is done
in secretstore-setup and the SecretStoreClient interfaces
data data structures instead of reader/writer interfaces.
Fixes #1929 

Implement Vault root token revokation

---

cmd/security-secretstore-setup/res/docker/configuration.toml

Root token needs to be temporarily disabled until the following
services are fixed to use non-root tokens:
- edgex-mongo
- edgex-support-logging
- edgex-core-data
- edgex-support-notifications
- edgex-core-metadata
- edgex-core-command
- edgex-support-scheduler
Related issue: #2318 

Turn off root token revokation temporarily until other services updated.

---

api/openapi/v2/core-command.yaml
api/openapi/v2/core-data.yaml
api/openapi/v2/core-metadata.yaml
api/openapi/v2/support-logging.yaml
api/openapi/v2/support-notifications.yaml
api/openapi/v2/support-scheduler.yaml

Remove ErrorEnvelope (batch endpoint DTO -- wraps use-case DTO).
Add ErrorResponse (use-case DTO).
Add ErrorResponse to all relevant use-case-request paths.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/2323

Update OpenAPI Docs for V2 API -- Generic Errors

---

api/openapi/v2/core-command.yaml
api/openapi/v2/core-data.yaml
api/openapi/v2/core-metadata.yaml
api/openapi/v2/support-logging.yaml
api/openapi/v2/support-notifications.yaml
api/openapi/v2/support-scheduler.yaml

Support for /ping, /metrics, /version, and /config endpoints is currently
specified for the HTTP GET method. That method is cachable. These are not
resource retrievals that should be cached; they are commands. Update to
specify support via the HTTP POST method.
Add a corresponding request DTO for each of these endpoints.
Update to support single and array of use-case requests and responses 
for these endpoints.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/2321

Update OpenAPI Docs for V2 API -- Ping, Metrics, Version, Configuration

---

cmd/sys-mgmt-agent/res/configuration.toml
cmd/sys-mgmt-agent/res/docker/configuration.toml

- Fix the issue related to the SMA operation "restart" (via Blackbox scripts). Details in [Issue-372](https://github.com/edgexfoundry/blackbox-testing/issues/372)

Update the configuration.toml for sys-mgmt-agent to increase the default value for the http.Server timeout..

---

cmd/security-secretstore-setup/res/configuration.toml
cmd/security-secretstore-setup/res/docker/configuration.toml

change the names of properties in configuration.toml of security-secretstore-setup project from all lower cases to upper case of first letter so that they are consistent with others in edgex-go project
fix #1762

Fix the issue of all lower-case spellings of properties in configuration.toml

---

cmd/sys-mgmt-agent/res/configuration.toml
cmd/sys-mgmt-agent/res/docker/configuration.toml

Fix the issue related to the SMA operation "restart" (as tested by Blackbox scripts) wherein the said operation fails on `ARM64 builds` (but continues to pass on `UBUNTU builds` and not an issue there). Further details in [Issue-384](https://github.com/edgexfoundry/blackbox-testing/issues/384).

Increase http.Server timeout value to make allowance for the ARM64 build.

---

snap/hooks/install
snap/local/parts/drop-user/Makefile
snap/local/parts/drop-user/drop.c
snap/local/runtime-helpers/bin/gosu-snap_daemon.sh
snap/snapcraft.yaml

The gosu commnand doesn't support libnss-extrausers
as used on Ubuntu Core, so the snap install fails
on an Ubuntu Core system when gosu is used to start
postgres.
This commit replaces gosu with a local C part which is
now used to run postgres and its applications as the
'snap_daemon' user.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/2356
Issue Number:

snap: replace gosu with local drop-user cmd

---

snap/snapcraft.yaml

A recent change to device-sdk-go introduced new command-line
changes which break the device services (-random, and -virtual)
included by default in the snap. Both of these device services
were being built from the fuji branch instead of from a source
tag, which also contributed to this breakage. This commit updates
the command-line arguments for both, and also sets a git-tag to
be used for both instead of the fuji branch.
Fixes: https://github.com/edgexfoundry/edgex-go/issues/2366
_- [ ] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide_
The commit doesn't follow the guidelines because the given wiki page doesn't include any …

snapcraft.yaml: fix builtin fuji device services

---

Jenkinsfile

This fixes string interpolation in Groovy and allows for the proper environment variables to be read.

fix issues with wrong quotes in Jenkinsfile

---

Jenkinsfile

Looking at the old JJB job, the REPO_ROOT was just actually set to the WORKSPACE path:
https://github.com/edgexfoundry/ci-management/blob/master/jjb/edgex-templates-go.yaml#L20
https://github.com/edgexfoundry/ci-management/blob/master/jjb/edgex-go/edgex-go.yaml#L14
Those are the same paths. Jenkins exposes an environment variable called `$WORKSPACE` to the build so I updated `REPO_ROOT` to match the `$WORKSPACE` when calling build step and the tests passed.
The reason I have to move the REPO_ROOT out of the `env` section is because of the way that the underlying edgeXGeneric pipeline parses environment variables and the fact that $WORKSPACE is not available until the main build node is allocated.
Please check if your PR fulfills the …

REPO_ROOT needs to be set to the WORKSPACE location

---

README.md
cmd/config-seed/Dockerfile
cmd/core-command/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/security-proxy-setup/Dockerfile
cmd/security-secrets-setup/Dockerfile
cmd/security-secretstore-setup/Dockerfile
cmd/support-logging/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile
cmd/sys-mgmt-agent/Dockerfile
go.mod

Fix #2341 
- After making the updates to the Dockerfiles, as well as to go.mod, I built the Docker images and made sure the Docker containers are launched properly. Also did a sanity check by hitting the `ping` endpoint each of all services for the correct response.

Update Core/Security/Support/SMA Service Dockerfiles for Go 1.13.

---

internal/security/secrets/helper/helper_test.go

Fixes #2379, supersedes #2387. Please see conversation there for context.
I was not able to reproduce the bug running the test locally, but I believe there is a race condition present and the file will not always be left hanging. Regardless, @bnevis-i was correct in the last PR, we are relying on the deferred call to `os.RemoveAll` happening after the file has been closed by the writer. With this PR, we should now always close the file, *and then* delete all files in the directory.
Cleared up linter warnings.

File created by TestGetCertConfigValid is removed from repo and always deleted

---

internal/support/notifications/rest_notification.go
internal/support/notifications/rest_notification_test.go

- This PR will address https://github.com/edgexfoundry/edgex-go/issues/2328.
- Functionally tested this by creating a _NORMAL_ notification and confirming that it is now processed immediately. Then proceeded to creating a _CRITICAL_ notification and confirming that it is also processed immediately. 
- In addition (per the ask to [revise the docs content accordingly](https://github.com/edgexfoundry/edgex-go/issues/2328#issuecomment-581975741)), a PR has been created (https://github.com/edgexfoundry/edgex-docs/pull/88) in the `edgex-docs` repo, similar to how this has been done in the past (for e.g. per https://github.com/edgexfoundry/edgex-docs/pull/63).

Send notifications of any severity when they are received.

---

go.mod

Due to the defect described in edgexfoundry/go-mod-secrets#49, and the recent fix of that issue in go-mod-bootstrap version 0.0.21, we need to update the go-mod-bootstrap version in go.mod to version v0.0.21 to resolve the token-lookup issue when bootstrap handler is called from all core-services.
Related issues:
- edgexfoundry/blackbox-testing#398
- edgexfoundry/go-mod-secrets#49
- edgexfoundry/go-mod-bootstrap#52
Closes: #2406
All core services failed to start as token-lookup failure 403, when it is running in secure mode.
Issue Number: #2406 
With the fix in version 0.0.21 of go-mod-bootstrap, all core services will start ok. …

Update go.mod to use go-mod-bootstrap v0.0.21 to resolve token-lookup issue

---

internal/pkg/db/redis/queries.go

Fixes #2374
Fixes #2394 
Issue Number: #2374
A unique temporary key is generated every time `getObjectsByValuesSorted` is invoked, and the result of `ZINTERSTORE` is stored in a cache set indexed to that key. This set is deleted at the end of every call to the function.
To verify:
1. Start core-data. Start redis. Start some method of inspection on your Redis DB. I use a program called `redis-browser.` Clear your database with `redis-cli FLUSHDB`.
2. Make the following request to core-data:
```
curl --location --request POST 'http://localhost:48080/api/v1/reading' \
--header 'Content-Type: application/json' \
--data-raw '{ …
```

getObjectsByValueSorted in Redis: removed indeterminism and fixed sorting issue

---

internal/pkg/db/redis/notifications.go

Fixes #2414
Currently attempting to delete a Notification which doesn't exist by ID will result in a 200 response code.
Issue Number:
#2414 
Attempting to delete a Notification which doesn't exist will result in a 404 response.

delete notification by id should return 404 if doesn't exist

---

go.mod
internal/pkg/db/mongo/models/reading.go

Persist ValueType, MediaType, FloatEncoding Properties on Readings.
Fixes #2425.  Redis DB Client implementation uses `json.Marshal()`
to store Readings, so no change is required.
To verify functionality, run against a local database (both mongo
and redis) and use the following curl command:
```curl --location --request POST 'http://localhost:48080/api/v1/reading' \
--header 'Content-Type: application/json' \
--data-raw '{
"name": "foo",
"value": "3.14159",
"mediaType": "some type",
"floatEncoding": "ieee16.4",
"valueType": "Float64"
}'
```
Then GET on the same url and ensure the three new fields are
there as expected.
The fields on …

Persist new properties on Readings

---

api/openapi/v1/core-metadata.yaml
internal/core/metadata/rest_provisionwatcher.go

Currently, provision watchers do not match the Swagger API, and that API behaves in strange ways, such as returning a status of Internal Server Error when Not Found would be more appropriate (`GetProvisionWatcherByIdentifier`).
Issue Number: Fixes #2410
The API now behaves as a reasonable user would expect.
Black box tests need to be updated. I will push changes for those shortly.

Provision Watcher REST API Audit: Read Endpoints

---

Makefile

config-seed is no longer building due to upstream python issue;
this is preventig merge requests to edgex-go to fix other issues.
Temporarily disable config-seed building util fix is available
or until config-seed is permanently removed.
Issue Number: #2236
No longer build config-seed in order to enable PR merges to continue.
Continue to use pre-built config-seed until config-seed end of life is executed.

fix[workaround]: Disable build of config-seed due to python issue

---

cmd/support-notifications/res/docker/configuration.toml
go.mod

Fixes #2433
Upgrade to latest go-mod-bootstrap to fix issue with deserializing username
and password from consul configuration.  Add missing password to support-
notifications.
Blackbox tests are failing for non-security testing because mongodb was changed to require authentication and the bootstrapping framework due to a bug in 3rd party open source is unable to pull the username and password from .toml configuration that has been reflected into consul into the database credentials.  Thus no service can authenticate to the database, bombing the test suite.
Issue Number: #2433
Username and password retrieval is fixed.
See testing …

fix: Blackbox testing failures for docker-compose-nexus-mongo-no-secty.yml

---

api/openapi/v2/core-command.yaml
api/openapi/v2/core-metadata.yaml

This implements the changes in go-mod-core-contracts #64 and #189
It also removes the Responses from Commands, as these are not used
Signed-off-by: Iain Anderson <iain@iotechsys.com>
- [ x ] Docs have been added / updated (for bug fixes / features)
- [ x ] Documentation content changes
Issue Number:
- [ x ] Yes
The Device Profile structure is modified. Services which deal with device profiles (eg core-command, core-metadata, device services) will need to be updated

Simplify Device Profile in v2 API specification

---

internal/core/metadata/errors/types.go
internal/core/metadata/rest_provisionwatcher.go
internal/pkg/errorconcept/provision_watcher.go

Currently, the provision watcher update code will never correctly detect duplicate entries and throws the wrong errors.
Issue Number: Fixes #2411
The update code correctly detects duplicate entries and throws the correct status codes.
Additional blackbox tests are needed; provision watcher error coverage is very poor.

Provision Watcher REST API Audit: Update Endpoint

---

internal/security/fileprovider/provider.go
internal/security/fileprovider/provider_test.go
internal/security/fileprovider/tokenconfig.go
internal/security/fileprovider/tokenconfig_test.go

- security-file-token-provider now can take the environment variable,
ADD_SECRETSTORE_TOKENS that takes a comma-separated list of additional service keys
for which to create tokens.
- The tokens create with the default token parameters and policies.
- Unit tests refactored to reduce some duplicate codes
Fix: #2266
The current security-token-file-provider can only take the pre-configured services from the TOML configuration file and it is asked for adding additional service token on the fly from the environment variable.
Issue Number: #2266 
With this PR, the additional Vault tokens can be created via the environment variable …

Implementation for adding addtional Vault tokens from the environment variable

---

cmd/core-command/res/configuration.toml
internal/core/command/init.go
internal/core/command/rest_device.go
internal/core/metadata/init.go

A race occurs during bootstrap external client initialization between the bootstrap handler and the bootstrap registry component. If the external client is initialized JIT, the registry variable will no longer contain valid data. On subsequent calls, the registry variable is updated and execution proceeds as normal.
Issue Number: Fixes #2421 
The external client is initialized before the bootstrap update code and the race does not occur.
To verify:
Repro the bug on master:
Run (in order) consul, redis, config-seed, core-data, core-metadata, core-command. Ensure the core services are configured for consul usage and not local configuration. Make the following curl command: `curl …

Race condition when initializing external clients using bootstrap

---

internal/core/metadata/rest_provisionwatcher.go
internal/pkg/db/mongo/metadata.go
internal/pkg/db/mongo/models/provisionwatcher.go
internal/pkg/errorconcept/provision_watcher.go

#1723  PR Checklist
This PR attempts to address an issue where if an object presented to the Mongo metadata driver for update did not have an ID (but was a valid object in the database) instead of automatically performing a lookup by ID, the driver would generate a new ID and then throw an error because no updated could be performed on the new ID.
Issue Number: Fixes #2464
This has been corrected, and now when no ID is present on the update request, the driver will first do a lookup by name to attempt to match the update request to an existing object.
To verify, run the metadata blackbox tests using Mongo.

Handling empty IDs in the Mongo metadata driver

---

cmd/security-proxy-setup/res/configuration.toml
internal/security/proxy/testdata/configuration.toml

All other services use that have it use [Clients.CoreData] not [Clients.Coredata]
Case matters... Our global override uses Clients_CoreData
Changed it to Clients.CoreData everywhere.
Fixes: https://github.com/edgexfoundry/blackbox-testing/issues/424
Currently, the configuration toml file uses the case-sensitive service name, Coredata.  It is supposed to use CoreData.
Issue Number: https://github.com/edgexfoundry/blackbox-testing/issues/424
Change the service name of core data to be CoreData

Fix Blackbox Testing issue #424

---

go.mod
internal/core/data/init.go

Core data fails to publish to MQTT MessageBus due to not being connected.
Issue Number: #2466 
Core data successfully publishes to MQTT MessageBus.

fix: Add call to Message Bus Connect()

---

internal/security/proxy/service.go
internal/security/proxy/service_test.go

`security-proxy-setup service` now can take an environment variable, `ADD_PROXY_ROUTE`,
that takes a comma-separated list of paired additional service name and URL for which to create Kong routes.
The paired spec. is given like the following:
**\<ServiceName\>.\<RouteURL\>**
where ServiceName is the name of service which requests to create Kong route
and RouteURL is the full qualified URL for the service. eg.: http://edgex-app-service-rules:59807
So for a single service the value would be: "app-service-rules.http://edgex-app-service-rules:59807"
This service info is used to add the service to the routes for Kong.
Fixes: #2473
The …

Implement ability to add additional Kong routes

---

cmd/core-command/res/configuration.toml
cmd/core-data/res/configuration.toml
cmd/core-metadata/res/configuration.toml
cmd/security-proxy-setup/res/configuration.toml
cmd/security-secrets-setup/res/configuration.toml
cmd/security-secretstore-setup/res/configuration.toml
cmd/support-logging/res/configuration.toml
cmd/support-notifications/res/configuration.toml
cmd/support-scheduler/res/configuration.toml
cmd/sys-mgmt-agent/res/configuration.toml
go.mod

Fix #2479
- [ X] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [X ] Other... Please describe:
Configuration changes to enable logging to only write to `StdOut` by default.
Issue Number: 2479
Services will no longer write to a file by default. The absence of an explicitly specified log file path will cause the logger to just write to `StdOut`.
- [ X] No

Set Empty LogFile Path for All Services

---

snap/hooks/install
snap/snapcraft.yaml

- [x ] The commit message follows our guidelines: https://wiki.edgexfoundry.org/display/FA/Contributor%27s+Guide
- [updates to README to follow in a subsequent PR] Docs have been added / updated (for bug fixes / features)
I've verified that all of the services (including security services which are enabled by default) all come up with no errors logged. I've also verified that device-virtual if enabled, comes up, loads it's device profiles, devices, and auto-events and starts generating events and readings as expected.
This PR resolves issue: #2051 
No
With the recent change to remove config-seed, it is no longer …

snap: use per-service env overrides

---

cmd/core-command/Attribution.txt
cmd/core-data/Attribution.txt
cmd/core-metadata/Attribution.txt
cmd/security-file-token-provider/Attribution.txt
cmd/security-proxy-setup/Attribution.txt
cmd/security-secrets-setup/Attribution.txt
cmd/security-secretstore-setup/Attribution.txt
cmd/support-logging/Attribution.txt
cmd/support-notifications/Attribution.txt
cmd/support-scheduler/Attribution.txt
cmd/sys-mgmt-agent/Attribution.txt
cmd/sys-mgmt-executor/Attribution.txt
go.mod
internal/core/data/io.go

Fixes #2439.
Replaces ugorji/go with fxamacker/cbor and updates
dependencies and Attribution.txt files.
Ensures calls to read cbor buffers are wrapped in
a LimitReader of reasonable size before exhausting.
This PR contains the parts of #2481 that still need to be carried over, and is scoped to only CBOR related changes.
Issue Number:
#2439
Purely refactoring, no change in behavior.

Swap ugorji/go with fxamacker/cbor library

---

internal/core/command/device.go
internal/core/command/device_test.go
internal/core/command/errors/types.go
internal/core/command/get.go
internal/core/command/get_test.go
internal/core/command/interfaces.go
internal/core/command/put.go
internal/core/command/put_test.go
internal/core/command/restDevice_test.go
internal/core/command/rest_device.go
internal/core/command/router.go
internal/core/command/test_utils.go
internal/core/command/types.go
internal/core/command/types_test.go
internal/core/command/utils.go

- This is the second (thought first in sequence of being reviewed) of two `PR`s that will address https://github.com/edgexfoundry/edgex-go/issues/2272 ("Response of issueDeviceCommand is not providing CBOR Content-Type header"). 
- The second `PR` (in `device-sdk-go`) was previously submitted, with [details on sequencing here](https://github.com/edgexfoundry/device-sdk-go/pull/464#issuecomment-598815862).
- `Blackbox Integration tests` were run, to validate the updates per this `PR` (Results are provided in the comment below).
- The set of steps used for testing are provided in the comment below.
- Immediately after submitting this `PR`, on realizing that we would be better served by marking this as a `Draft PR`, I sought to reclassify this as a `Draft PR`, but don't see an option to do …

Fix core-command response when handling a CBOR result.

---

internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/rest_deviceprofile_test.go
internal/core/metadata/router.go

Fix #2429 
Core metadata service doesn’t create the value descriptor by uploading device profile when EnableValueDescriptorManagement=true and it only works by post the profile in JSON format
Issue Number: #2429 
Core metadata service should create the value descriptor by uploading the device profile when EnableValueDescriptorManagement is true.
In this commit, Add the missing logic to restAddProfileByYaml and restAddProfileByYamlRaw function.

Create value descriptor when adding the device profile in YAML format

---

internal/core/command/rest_device.go

This fixes the following issue: https://github.com/edgexfoundry/blackbox-testing/issues/434
- Essentially, added back in a missing line in `func restGetCommandsByDeviceName()` for setting the ContentType. This was missed during one of the several refactorings which were done in the recent past. 
- It applies to the function restGetCommandsByDeviceName(), and the missing line (`w.Header().Set(clients.ContentType, clients.ContentTypeJSON)`) has been reinstated. Note that since the execution of a core-command is effectively a pass-through, a JSON result can be passed back to the caller as a string.
- Ran the blackbox tests, which passed. Here's the individual command, which resulted in the expected response body and `application/json` for `Content-Type`, which addresses the issue reported …

Fix issue (Content-Type-related) reported by Blackbox Testing .

---

cmd/core-command/Attribution.txt
cmd/core-data/Attribution.txt
cmd/core-metadata/Attribution.txt
cmd/security-file-token-provider/Attribution.txt
cmd/security-proxy-setup/Attribution.txt
cmd/security-secrets-setup/Attribution.txt
cmd/security-secretstore-setup/Attribution.txt
cmd/support-logging/Attribution.txt
cmd/support-notifications/Attribution.txt
cmd/support-scheduler/Attribution.txt
cmd/sys-mgmt-agent/Attribution.txt
cmd/sys-mgmt-executor/Attribution.txt
go.mod

Update go-mod-messaging version to allow the usage of the RedisStreams functionality. This is an opt in feature and not a default. 
EdgeX Go is using an older version of go-mod-messaging which does not have RedisStreams functionality
Issue Number: #2508
Using a newer version which provides RedisStreams functionality 
No
A new issue was created to consolidate the Redis libraries used to just one across EdgeX. See #2509 for more details.

Update version of go-mod-messaging

---

Makefile

Signed-off-by: Lisa Rashidi-Ranjbar <lisa.a.rashidi-ranjbar@intel.com>
Current build on Jenkins errors out because of these extra images. This happens after pushing the images that aren't malformed.
https://jenkins.edgexfoundry.org/blue/organizations/jenkins/edgexfoundry%2Fedgex-go/detail/master/62/pipeline
Issue Number: N/A
This is reverting a change that caused this behavior. The nexus repository is filled in on push so there is no reason to build the extra images and cause errors. See:
https://github.com/edgexfoundry/ci-management/blob/master/shell/edgexfoundry-go-docker-push.sh#L32-L52## 
Does this PR introduce a breaking change?

Remove extra docker image tags that become malformed in the push

---

internal/pkg/db/redis/client.go

Signed-off-by: André Srinivasan <andre@redislabs.com>
The Redis client is not honoring `EDGEX_SECURITY_SECRET_STORE` and attempting to authenticate to the database even if security is disabled.
Issue Number: #2516 
Don't attempt to authenticate if `EDGEX_SECURITY_SECRET_STORE == false`

Check EDGEX_SECURITY_SECRET_STORE before sending Redis password

---

api/openapi/v2/system-agent.yaml
bin/edgex-docker-launch.sh
internal/pkg/bootstrap/handlers/database/database.go
internal/pkg/db/db.go
internal/pkg/db/mongo/client.go
internal/pkg/db/mongo/client_test.go
internal/pkg/db/mongo/models/addressable.go
internal/pkg/db/mongo/models/channel.go
internal/pkg/db/mongo/models/command.go
internal/pkg/db/mongo/models/device.go
internal/pkg/db/mongo/models/deviceprofile.go
internal/pkg/db/mongo/models/devicereport.go
internal/pkg/db/mongo/models/deviceservice.go
internal/pkg/db/mongo/models/event.go
internal/pkg/db/mongo/models/interval.go
internal/pkg/db/mongo/models/interval_action.go
internal/pkg/db/mongo/models/notification.go
internal/pkg/db/mongo/models/provisionwatcher.go
internal/pkg/db/mongo/models/reading.go
internal/pkg/db/mongo/models/subscription.go
internal/pkg/db/mongo/models/transmission.go
internal/pkg/db/mongo/models/value_descriptor.go

Mongo functionality is not marked as deprecated.
Issue Number: #2478
Mongo functionaltiy is marked as deprecated in GoDocs according to the Go standard for deprecating code. This will aid in persuading future developers from using or updating the code which is expected to be removed. Also we can leverage a linter to identify any deprecated code to aid in removing the code in the future.
No
Along with updated or added GoDoc comments, I updated a few example references to Mongo. Those are examples in the OpenAPI spec and have no impact on functionality.

Deprecate Mongo Functionality

---

snap/snapcraft.yaml

After this PR was merged to device-virtual-go: https://github.com/edgexfoundry/device-virtual-go/pull/96/files the daily snap builds have been [broken](https://jenkins.edgexfoundry.org/job/edgexfoundry/job/cd-management/job/edgex-go-daily-snap/). This PR updates the path to Attribution.txt should fix the issue.
Issue Number:

bugfix: update Attribution.txt path after changes to device-virtual-go

---

cmd/security-secrets-setup/entrypoint.sh

Signed-off-by: André Srinivasan <andre@redislabs.com>
Issue Number: #2542 
Old Redis password file is removed when secrets are initialized
This is dependent on [developer-scripts #274](https://github.com/edgexfoundry/developer-scripts/pull/274)

Remove old password file

---

internal/pkg/db/redis/client.go

Redis lazy connection cause unrecoverable error since occur outside bootstrap retry loop
Issue Number:  #2545
Test Redis connection during bootstrap so failures trigger retry

fix: Add Redis connection test during client creation so error will trigger retry

---

go.mod
internal/core/data/interfaces/db.go
internal/pkg/db/interfaces/db.go
internal/pkg/db/redis/client.go
internal/pkg/db/redis/client_integration_test.go
internal/pkg/db/redis/data.go
internal/pkg/db/test/db_data.go
internal/pkg/db/test/db_metadata.go
internal/pkg/db/test/db_notifications.go

The Redis implementation of the DBClient persists the `BinaryValue` data within a reading.
Issue Number: #2527 
1. The Redis implementation of the DBClient does not persists the `BinaryValue` data within a reading.
1. A integration test for Redis has been added to verify the changes
1. Existing integration tests have been fixed to compile and run correctly.
These changes are non-breaking because this was the original intent of the system which was implemented correctly for Mongo and overlooked for Redis
To verify, create a `Reading` with a `BinaryValue` and ensure:
1. Issuing a GET for the `Reading` results in a response with an empty `BinaryValue`
1. Use the Redis CLI to ensure the …

Fix Reading Redis Binary Payload Persistence

---

snap/hooks/install
snap/local/runtime-helpers/config/security-secret-store/vault-config.hcl.in
snap/snapcraft.yaml

Issue Number: #2547 
Also see related issue: #2495 
The new behavior is that PKI setup (aka security-secrets-setup) in the snap is now aligned with the docker deployment of Geneva, and the intermediate files in `$SNAP_DATA/pki/EdgeXFoundryCA` are no longer present.  See the issue for more details.
```
$ export SNAP_DATA=/var/snap/edgexfoundry/current
espy@sumo$ sudo tree $SNAP_DATA/secrets/ -P "*.pem|*.crt|*.key" --prune
/var/snap/edgexfoundry/current/secrets/
├── ca
│   └── ca.pem
├── edgex-kong
│   ├── ca.pem
│   ├── server.crt
│   └── server.key
└── edgex-vault
├── ca.pem
├── server.crt
└── server.key
3 directories, 7 files
```
Specifically, **ca.pem** (the root CA) and the TLS …

snap: update security-secrets-setup config

---

cmd/core-data/res/configuration.toml

Unable to use env overrides for the optional MQTT values
Issue Number: 2563
Now able to use env overrides for the optional MQTT values

feat: Add default MQTT optional MessageQueue values to enable env overrides

---

cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/support-logging/Dockerfile
cmd/support-notifications/Dockerfile
cmd/sys-mgmt-agent/Dockerfile

closes #2572
Signed-off-by: Mike <michael.johanson@intel.com>
Issue Number: #2572 
Ports are accurately represented in Dockerfiles

fix: accurately represent default port w/ EXPOSE in dockerfiles

---

internal/pkg/db/redis/data.go

PR Checklist
Reading IDs not set when Event is pushed onto the Message Bus
Issue Number: #2569
Reading IDs available when Event is pushed onto the Message Bus

fix: Added setting the Reading ID in the Events collection.

---

go.mod

Env overrides with blank values such as Service_Host="" were ignored.
Issue Number: #2576
Updated to use v0.0.32 of go-mod-bootstrap
Env overrides with blank values now work.

fix: fix: Allow overrides that have empty/blank value

---

go.mod

ListenAndServe was lock to specific adapter for the specified hostname
Issue Number:  #2578
ListenAndServe now not using hostname so available on any of the host system's adapters

fix: Don't use hostname for webserver ListenAndServe

---

snap/snapcraft.yaml

This commit updates the source tags for app-service-configurable and device-virtual to the latest stable.
- app-service-configurable: 1.2.0
- device-virtual: 1.2.1
This PR updates the tags used by the snap for app-service-configurable and device-virtual to the latest versions released as part of the Geneva 1.2.1 release.

snap: update app-service-cfg and device-virtual tags

---

Makefile

No tagging of locally build images for the nexus registry.
Issue Number: #2592
Locally built images now have addition tag for nexus registry
No
No

build: Added addingal tagging of docker images with nexus registry.

---

internal/core/metadata/operators/device_profile/value_descriptor.go
internal/core/metadata/operators/device_profile/value_descriptor_test.go
internal/core/metadata/rest_deviceprofile_test.go

Fix #2584 
PR Checklist
Update device profile by ID will throw the item not found error
Issue Number: 2584
API query the device profile by id and name to prevent item not found error.

fix: Get deviceProfile by ID when updating the deviceProfile and valuedescriptor

---

internal/pkg/db/redis/data.go

In /internal/pkg/db/redis/data.go, the func EventsForDeviceLimit should call getObjectsByRevRange to retrieve the entries for keys in the reverse sorted set order.
fix #2604 
Issue Number: #2604 
This API [/v1/event/device/{deviceId}/{limit}](https://app.swaggerhub.com/apis-docs/EdgeXFoundry1/core-data/1.2.0#/default/get_v1_event_device__deviceId___limit_) now will return last(newest) $n records

fix: Query event API w/ limit always returns first $n records (redis)

---

internal/core/data/event.go
internal/pkg/db/redis/data.go

Fix by using the db creation time on message queue for Event.
closes #2602
Signed-off-by: Lindsey Cheng <beckysocute@gmail.com>
The created timestamp of Event/Reading is zero on the message queue (can be seen on the app services pushed via 0MQ or message bus).
Issue Number: #2602 
The created timestamp of Event/Reading value should be the same as the created field saved in the database on the message queue, which is the entry creation timestamp in the database.
No.

fix: Created timestamp is 0 on message queue

---

snap/README.md
snap/hooks/configure
snap/hooks/install
snap/snapcraft.yaml

Mongo was announced as deprecated in the Geneva (1.2.0)
release, and removed as part of the Hanoi release (1.3.0).
Fixes: https://github.com/edgexfoundry/edgex-go/issues/2612
- [**NA**] Tests for the changes have been added (for bug fixes / features)
- [**NA**] Docs have been added / updated (for bug fixes / features)
- [**NA**] `make test` has completed successfully
EdgeX has supported Mongodb as one of it's data persistence options since the first release. Redis support was added in the Fuji release and became the default database provider in the Geneva release. Mongo was declared deprecated in the Geneva release and slated for removal as …

snap: remove mongod

---

internal/security/proxy/service.go
internal/security/proxy/service_test.go

The PR from #2474 introduces an enhancement that users could add
additional Kong routes via environment variable ADD_PROXY_ROUTE.
The value of ADD_PROXY_ROUTE takes a comma-separated list of one or
more (at least one) paired additional service name and URL for which
to create proxy Kong routes. The paired specification is in the format
of {RoutePrefix}.{TargetRouteURL}. There is a bug here: if
{TargetRouteURL} contains dot characters, e.g. an IP address, the
route parsing logic will break, as the code simply use
`routePair := strings.Split(route, ".")`
to parse the route. To avoid this potential issue, the code should
consider to only spilt {RoutePrefix}.{TargetRouteURL} into 2 substrings
with the very first dot: `routePair := strings.SplitN(route, ".", 2)`
Signed-off-by: Jude Hung …

fix: ADD_PROXY_ROUTE fails if URL contains dot

---

cmd/core-command/res/configuration.toml
cmd/core-data/res/configuration.toml
cmd/core-metadata/res/configuration.toml
cmd/support-logging/res/configuration.toml
cmd/support-notifications/res/configuration.toml
cmd/support-scheduler/res/configuration.toml
cmd/sys-mgmt-agent/res/configuration.toml
go.mod

- Updated to latest go-mod-bootstrap v0.0.36
- Added Service.ServerBindAddr setting to config files for all edgex-go microservices
fix: #2624 
Before go-mo-bootstrap v0.0.36, the ListenAndServe IP address defaults to binding to an all-interface listener value of 0.0.0.0
Issue Number: #2624 
Added a Service.`ServerBindAddr` configurable value to config file to reflect this change: https://github.com/edgexfoundry/go-mod-bootstrap/pull/84
The default value of `ServerBindAddr` of each service is blank, so the Service.`Host` value is now the ListenAndServe IP address. However, it allows env override to set a specific value as needed for …

feat: Add config setting for value used for ListenAndServe

---

snap/local/patches/0001-Go-mod-bootstrap-fix.patch
snap/snapcraft.yaml

Use previous version of bootstrap due to the 0.0.0.0 'bug',
which causes edgex services to listen on all interfaces instead
of localhost when run in the snap (or natively).
Fixes: https://github.com/edgexfoundry/device-sdk-go/issues/456
Issue Number: 456 (https://github.com/edgexfoundry/device-sdk-go/issues/456)
Services are listening to the correct address instead of 0.0.0.0.
The existing dependency (referenced in go.mod) go-mod-bootstrap contains a bug. To resolve this issue is by referencing the previous version of the go-mod-bootstrap dependency.
Please review the patch file and snapcraft.yaml.

snap: revert to go-mod-bootstrap v0.0.32

---

cmd/security-file-token-provider/res/token-config.json
internal/security/secretread/types.go
internal/security/secretstore/init.go

This reverts commit 87b21bebefd6aee52e42130607210e5adb257784.
Revert previous breaking change as discussed EdgeX archtiecture meeting 2020-07-20.
Issue Number:
#2538

Revert "chore: Remove security services initialization for mongodb"

---

Jenkinsfile

This PR is being created to update the Jenkinsfile in preperation for https://github.com/edgexfoundry/edgex-go/pull/2644.
It contains the following changes:
- Remove raml_verify from `testScript`
- Disable `publishSwaggerDocs` (until PR-2644 is merged)
- Update `swaggerApiFolders` paths to match PR-2644
Issue Number:

build: update Jenkinsfile to test 'testScript'

---

internal/core/metadata/errors/types.go
internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/rest_deviceprofile_test.go
internal/pkg/errorconcept/device_profile.go
openapi/v1/core-metadata.yaml

Fix #2596 
YAML DeviceProfile uploading API doesn't validate the content.
Issue Number: #2596
Invoke Validate function when uploading yaml format DeviceProfile to prevent uploading invalid DeviceProfile.
Since deviceProfile.Validate() not validate the nested object, so create another function to validate that.

fix: Invoke Validate function when adding yaml DeviceProfile

---

api/openapi/v1/core-metadata.yaml
internal/core/metadata/errors/types.go
internal/core/metadata/rest_deviceprofile.go
internal/core/metadata/rest_deviceprofile_test.go
internal/pkg/errorconcept/device_profile.go

Fix #2655 
(cherry picked from commit 9098740bb9c39ad5ae1b6b14d814f8ae0a19a439)
YAML DeviceProfile uploading API doesn't validate the content.
Issue Number: #2655 
Refactor deviceProfile adding func to use same validation logic for JSON and YAML format DeviceProfile.

[Geneva] fix(metadata): Refactor deviceProfile JSON and YAML POST API

---

internal/support/scheduler/schedule.go

Code was incorrectly using `string()` to convert int to readable string. 
Issue Number: #2662
Code now correctly uses Itoa() to convert the int to a readable string.
no

fix: Use Itoa() instead of string() for int conversion

---

internal/pkg/db/redis/event.go
internal/pkg/v2/infrastructure/redis/event.go

New Tags property on V1 & V2 models not persisted to Redis DB
Issue Number: #2668
New Tags property on V1 & V2 models is now persisted to Redis DB
no

feat: Add persisting of new Tags property on V1 & V2 Event models for Redis

---

snap/local/patches/0002-lua-resty-openssl-fix.patch
snap/snapcraft.yaml

Without this patch, Kong's spec for lua-resty-openssl is overriden by lua-resty-acme, causing the latest version (0.6.4-1) to get installed, which causes the service to fail to start.
Issue Number:
NA
no
no

fix (snap): use version 0.6.3 of lua-resty-openssl

---

Dockerfile.build
Jenkinsfile
README.md
bin/test-attribution-txt.sh
cmd/core-command/Dockerfile
cmd/core-data/Dockerfile
cmd/core-metadata/Dockerfile
cmd/security-proxy-setup/Dockerfile
cmd/security-secrets-setup/Dockerfile
cmd/security-secretstore-setup/Dockerfile
cmd/support-logging/Dockerfile
cmd/support-notifications/Dockerfile
cmd/support-scheduler/Dockerfile
cmd/sys-mgmt-agent/Dockerfile
go.mod
snap/local/build-helpers/bin/go-build-helper.sh
snap/snapcraft.yaml

Updated Dockerfile.build, go.mod, README.md, snapcraft.yml to Go 1.15 or patch 1.15.2 where applicable.  Removed reference in Jenkinsfile to allow devops CI/CD default to apply
Signed-off-by: Jim White <jpwhite_mn@yahoo.com>
also ran `make docker` and `snapcraft --debug`
n/a
Issue Number: #2680  
n/a
none
Removed go lang reference in Jenkinsbuild.  This will now default to what devops has defaulted in CI/CD.

build: fix#2680 - update GoLang in all places to Go 1.15.2

---

snap/README.md
snap/hooks/configure
snap/hooks/install
snap/hooks/pre-refresh
snap/snapcraft.yaml

Remove deprecated support-logging service from snap.
- [NA] `make test` has completed successfully
Up til this point, it's not been possible to update from one major/minor version of EdgeX due to the use of sequential epochs in snapcraft.yaml. This policy may be changed with the Hanoi. If so, when someone attempts to refresh from the geneva snap and they have support-logging enabled, the refresh/update should fail to install with an appropriate error message (**note**, this has not been implemented in this PR). This is similar to what would happen if someone were to …

fix(snap): remove support-logging

---

internal/core/data/v2/application/device.go
internal/pkg/v2/infrastructure/redis/client.go

The dbclient variable initialization was removed accidentally.
Issue Number: Fix https://github.com/edgexfoundry/edgex-go/issues/2693
Add the dbclient variable initialization back to fix the nil pointer panic.

Fix (core-data): add back dbclient variable init

---

go.mod
internal/core/data/v2/application/event.go
internal/core/data/v2/controller/http/event_test.go
internal/pkg/v2/infrastructure/redis/event.go

Event ID will be generated before storing into the database
Issue Number: Fix https://github.com/edgexfoundry/edgex-go/issues/2684
In V2 API, Event ID has to be UUID and pre-populated.
Adopt the latest go-mod-contracts to include this validation.
Modify the related unit test to verify this feature.
Remove the UUID assignment before storing into the database.
Remove checksum and correlation id from Event model.

feat(core-data): Event ID has to be pre-populated

---

internal/support/notifications/sending_service.go
internal/support/notifications/sending_service_test.go

Use ContentType defined on notification on HTTP header for HTTP channel
and MIME header for SMTP channel.  Also add chunking with newlines for
long SMTP messages.
Signed-off-by: Alex Ullrich <alexullrich@technotects.com>
Not sure if a bug per se but current implementation disregards the content type set on the notification, and also runs into problems sending long SMTP messages
Issue Number: #2682 
Includes content type specified on the notification in the HTTP header for REST transmission, and in the MIME header for SMTP transmission.  Also introduces chunking of SMTP payloads for messages longer than 1000 characters.
No
I mentioned ability to specify character set and general sending …

feat(support-notifications): use notification content type

---

cmd/security-secretstore-setup/res/configuration.toml
go.mod
internal/security/secretstore/credentialgenerator.go
internal/security/secretstore/credentialgenerator_test.go
internal/security/secretstore/execrunner-mock_test.go
internal/security/secretstore/execrunner.go
internal/security/secretstore/init.go
internal/security/secretstore/password.go
internal/security/secretstore/password_linux_test.go
internal/security/secretstore/password_test.go
internal/security/secretstore/passwordprovider.go
internal/security/secretstore/passwordprovider_test.go
internal/security/secretstore/tokenprovider.go
internal/security/secretstore/tokenprovider_linux_test.go
internal/security/secretstore/tokenprovider_test.go
internal/security/secretstoreclient/types.go

Remove dependency on GoKey for password generator;
if not specified, the built-in password generator
does the equivalent of "openssl rand -base64 33"
which generates a base64 encoded random string
of 264 random bits.
Otherwise, the code looks for a PasswordProvider
in configuration that points to an executable,
and PasswordProviderArgs that specify the
arguments to that executable.  The code then
launches that exectuable, trims the trailing
newline, and uses the result as a password.
Current functionality uses Vault root token and database name to feed into GoKey password generator.  The GoKey password generator was never fully vetted …

feat: Implement pluggable password generator

---

internal/core/data/v2/controller/http/event.go
internal/pkg/v2/utils/http.go

Write the http header before setting the correct content type.
Issue Number: Fix https://github.com/edgexfoundry/edgex-go/issues/2718
Create an utils package for the future V2 API implementation.
Create WriteHttpHeader helper function to set up header for http controllers.
Set content-type before calling `w.WtiteHeader()`

fix(data):add content-type before writing header

---

internal/core/data/v2/controller/http/event.go
internal/pkg/v2/infrastructure/redis/event.go

Issue Number: Fix https://github.com/edgexfoundry/edgex-go/issues/2738
If the query error is errors.KindEntityDoesNotExist, the error log
should not be printed out because it is not a real error.
In the infrastructure layer, if the event doesn't exist when adding, the
error should not be returned.

Fix(data):query event doesn't print error message

---

go.mod
internal/core/metadata/v2/controller/http/deviceprofile.go
internal/core/metadata/v2/controller/http/deviceprofile_test.go
internal/pkg/v2/infrastructure/redis/dbcommands.go
internal/pkg/v2/infrastructure/redis/device_profile.go

Fix #2736
Issue Number: #2736 
Add a check in the infrastructure layer to check whether the device profile Id
exists.  If it exists, the API should return 409 conflict.

fix(metadata): Device profile post returns 409 if id exists

---

internal/support/notifications/sending_service.go
internal/support/notifications/sending_service_test.go

Using only RCPT calls to resolve recipient leads to empty to: fields in some email clients, and seems like it may cause some destination hosts to reject messages.
Signed-off-by: Alex Ullrich <alexullrich@technotects.com>
Issue Number:
#2757 
Write sender and to addresses into SMTP message header

fix(notifications): include From/To in SMTP header

---

internal/core/metadata/v2/application/deviceservice.go
internal/core/metadata/v2/controller/http/deviceservice.go
internal/core/metadata/v2/controller/http/deviceservice_test.go
internal/core/metadata/v2/infrastructure/interfaces/db.go
internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go
internal/core/metadata/v2/io/deviceservice.go
internal/core/metadata/v2/router.go
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/device_service.go

Implement Core Metadata POST /deviceservice V2 API according to the API doc
Fix #2728
Signed-off-by: Jude Hung <jude@iotechsys.com>
Issue Number:#2728
Implement Core Metadata POST /deviceservice V2 API according to the API doc
No

feat(metadata): Implement Core Metadata POST /deviceservice V2 API

---

internal/core/metadata/v2/application/deviceprofile.go
internal/core/metadata/v2/controller/http/deviceprofile.go
internal/core/metadata/v2/controller/http/deviceprofile_test.go
internal/core/metadata/v2/infrastructure/interfaces/db.go
internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go
internal/core/metadata/v2/router.go
internal/pkg/v2/infrastructure/redis/client.go

Fix #2729
Issue Number: #2729
Implement Core Metadata GET /deviceprofile/name/{name} V2 API according to the API doc
This PR is base on the following PRs:
https://github.com/edgexfoundry/edgex-go/pull/2701
https://github.com/edgexfoundry/go-mod-core-contracts/pull/311
https://github.com/edgexfoundry/edgex-go/pull/2722

feat(metadata): Implement Metadata GET /deviceprofile/name/{name} V2 API

---

go.mod
internal/core/metadata/v2/application/deviceprofile.go
internal/core/metadata/v2/controller/http/deviceprofile.go
internal/core/metadata/v2/controller/http/deviceprofile_test.go
internal/core/metadata/v2/infrastructure/interfaces/db.go
internal/core/metadata/v2/infrastructure/interfaces/mocks/DBClient.go
internal/core/metadata/v2/router.go
internal/pkg/v2/infrastructure/redis/client.go
internal/pkg/v2/infrastructure/redis/device_profile.go

Fix #2752
Issue Number: #2752
Implement Core Metadata V2 API for deleting device profile by name and id according to the API doc
This PR works with https://github.com/edgexfoundry/go-mod-core-contracts/pull/323

feat(metadata): Implement Metadata V2 API for deleting device profile
